import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentSouthAsia {

    private static let cuisine_india = Cuisine(
        id: "india",
        regionID: "south-asia",
        country: "India",
        adjective: "Indian",
        tagline: "A dozen kitchens under one flag, argued over grain by grain.",
        summary: "India is not one kitchen but a few dozen, divided by grain, fat and the local sour thing. Wheat and mustard oil in the north, rice and coconut in the south, tamarind and sesame between them. Spices are toasted and ground per dish rather than shaken from one jar, and most tables balance a starch, a wet dish and something pickled.",
        staples: ["rice", "wheat", "lentils", "ghee", "yogurt", "tamarind"],
        techniques: ["tempering whole spices in hot fat", "slow braising in yogurt", "fermenting batters overnight"],
        flavourBase: "Whole spices bloomed in hot fat, then a sour note from tamarind, yogurt or lime.",
        stampInk: "ochre",
        stampShape: "arch",
        stampMotif: "wheel")

    private static let cuisine_srilanka = Cuisine(
        id: "srilanka",
        regionID: "south-asia",
        country: "Sri Lanka",
        adjective: "Sri Lankan",
        tagline: "An island that measures everything against coconut.",
        summary: "Sri Lankan cooking runs on coconut in three forms: milk, oil and grated flesh. Curry powder here is roasted almost black for meat and left pale for vegetables, and sourness comes from goraka or lime rather than tamarind alone. A meal is built as one starch surrounded by many small dishes, each cooked separately and mixed by hand on the plate.",
        staples: ["rice", "coconut", "chili", "curry leaves", "goraka", "pandan"],
        techniques: ["tempering in coconut oil", "roasting curry powder dark", "steaming rice flour"],
        flavourBase: "Coconut milk set against roasted chili and the sour resin of goraka.",
        stampInk: "teal",
        stampShape: "scallop",
        stampMotif: "wave")

    private static let cuisine_nepal = Cuisine(
        id: "nepal",
        regionID: "south-asia",
        country: "Nepal",
        adjective: "Nepali",
        tagline: "Mountain food built for long walks and short summers.",
        summary: "Nepali food is shaped by altitude. Rice and lentils hold the middle hills, buckwheat and millet climb above them, and the Kathmandu Valley keeps its own Newar repertoire of buffalo, beaten rice and fermented greens. Seasoning is restrained next to India: timur pepper, cumin, garlic and a sour pickle to cut through, with ghee or mustard oil doing the rest.",
        staples: ["rice", "lentils", "millet", "buffalo", "mustard oil", "fermented greens"],
        techniques: ["steaming filled dough", "fermenting greens into gundruk", "grilling over wood coals"],
        flavourBase: "Timur pepper, cumin and garlic in mustard oil, with a fermented sour behind it.",
        stampInk: "crimson",
        stampShape: "shield",
        stampMotif: "mountain")

    static let cuisines: [Cuisine] = [cuisine_india, cuisine_srilanka, cuisine_nepal]

    private static let dishes_india: [Dish] = [
        Dish(id: "india-dosa", cuisineID: "india",
             name: "Masala Dosa", nativeName: "ಮಸಾಲೆ ದೋಸೆ",
             summary: "A batter of rice and urad dal is left to ferment overnight, then spread thin on a hot griddle until it crisps into lace at the edges. Karnataka gave it the potato filling, softened with mustard seed and turmeric, and the tiffin rooms of Bengaluru and Udupi turned it into a morning institution.",
             tasteNote: "Shattering crisp at the rim, soft where it wraps the potato, with a mild sour tang from the fermented batter and a warm turmeric finish.",
             eaten: "Breakfast or late afternoon, torn by hand and dipped in coconut chutney and a bowl of sambar.",
             ingredients: ["rice batter", "urad dal", "potato", "mustard seed", "curry leaves", "turmeric"],
             tags: ["breakfast", "street", "vegetarian"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 2, herbal: 1, rich: 2),
             palette: "ochre"),
        Dish(id: "india-jhol", cuisineID: "india",
             name: "Macher Jhol", nativeName: "মাছের ঝোল",
             summary: "Bengal's everyday fish curry is deliberately thin, a turmeric and ginger broth rather than a heavy gravy. Rohu or hilsa is salted, briefly fried in mustard oil, then simmered with potato and a pinch of panch phoron. The point is not richness but a light, sharp liquid that rice can absorb without going greasy.",
             tasteNote: "Thin and clean on the tongue, pungent with mustard oil, gently hot from green chili, with soft potato and flaking fish underneath.",
             eaten: "Lunch at home, spooned over rice and mixed with the fingers, usually after a first course of dal.",
             ingredients: ["river fish", "mustard oil", "turmeric", "potato", "green chili", "panch phoron"],
             tags: ["home", "seafood", "soup"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 2, herbal: 1, rich: 1),
             palette: "saffron"),
        Dish(id: "india-litti", cuisineID: "india",
             name: "Litti Chokha", nativeName: "लिट्टी चोखा",
             summary: "Bihar's field food: wheat dough balls stuffed with roasted gram flour, ajwain and pickle masala, then baked in embers until blistered black. They are cracked open, drowned in ghee, and eaten with chokha, a mash of fire roasted eggplant, tomato and potato beaten together with raw mustard oil and green chili.",
             tasteNote: "Dry, smoky crust giving way to a crumbly savory center, cut by the sharp mustard bite and soft smokiness of the eggplant mash.",
             eaten: "Eaten hot with the hands, at roadside coal stalls or as a winter dinner, with raw onion.",
             ingredients: ["wheat dough", "roasted gram flour", "eggplant", "tomato", "ghee", "mustard oil"],
             tags: ["home", "street", "vegetarian", "grilled"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 2, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "india-dhokla", cuisineID: "india",
             name: "Khaman Dhokla", nativeName: "ખમણ ઢોકળા",
             summary: "Gujarat steams its snacks rather than frying them. A batter of ground gram is left to sour or quickly leavened, poured into trays and steamed into a spongy yellow cake, then cut into squares and finished with a tempering of mustard seed and curry leaf plus a sugar water bath that keeps every square damp.",
             tasteNote: "Light and springy, almost weightless, faintly sour and sweet at once, with popping mustard seed and a clean lemon edge at the end.",
             eaten: "Mid morning or teatime, eaten from a plate with a small spoon, with green chutney alongside.",
             ingredients: ["gram flour", "yogurt", "mustard seed", "curry leaves", "green chili", "lemon"],
             tags: ["snack", "vegetarian", "fermented"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 1, herbal: 1, rich: 0),
             palette: "cream"),
        Dish(id: "india-roganjosh", cuisineID: "india",
             name: "Rogan Josh", nativeName: "روگن جوش",
             summary: "Kashmiri lamb braised slowly in yogurt with dried Kashmiri chili, fennel and dried ginger, and no onion or garlic at all in the Pandit version. The red comes from ratanjot root and mild chili rather than heat. It anchors the wazwan, the long banquet cooked by a team of wazas for weddings.",
             tasteNote: "Meat that slides off the bone into a glossy red sauce, warm with fennel and ginger, tangy from yogurt, more perfume than fire.",
             eaten: "Served at feasts from a shared copper tramis, eaten with rice using the right hand.",
             ingredients: ["lamb", "yogurt", "kashmiri chili", "fennel powder", "dried ginger", "ratanjot"],
             tags: ["feast", "braised"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 3),
             palette: "crimson"),
        Dish(id: "india-puranpoli", cuisineID: "india",
             name: "Puran Poli", nativeName: "पुरणपोळी",
             summary: "Maharashtra's festival flatbread, made in quantity for Holi and Ganesh Chaturthi. Split chana dal is cooked with jaggery until it stiffens into puran, mashed smooth with cardamom and nutmeg, then sealed inside wheat dough and rolled out thin enough to see the filling through. It is griddled dry and only then brushed with ghee.",
             tasteNote: "Soft and slightly chewy, the filling grainy and deeply caramel sweet, cardamom rising late, ghee smoothing everything into one warm mouthful.",
             eaten: "Eaten at midday festival meals, torn by hand, often with a spoonful of warm milk or ghee.",
             ingredients: ["chana dal", "jaggery", "wheat flour", "cardamom", "nutmeg", "ghee"],
             tags: ["sweet", "feast", "vegetarian"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 1, herbal: 1, rich: 3),
             palette: "amber"),
        Dish(id: "india-panipuri", cuisineID: "india",
             name: "Pani Puri", nativeName: "पानी पूरी",
             summary: "A hollow semolina sphere the size of a walnut, punched open at the top, packed with potato, chickpea and tamarind, then dunked in cold mint and cumin water and handed over immediately. The whole thing exists in a five second window, which is why the vendor makes them one at a time and watches you eat.",
             tasteNote: "Crack, then a rush of cold sour water, mint and roasted cumin, soft spiced potato behind it, heat arriving last.",
             eaten: "Standing at a street cart, one at a time in a single mouthful, from a leaf bowl.",
             ingredients: ["semolina puris", "tamarind water", "mint", "roasted cumin", "potato", "chickpeas"],
             tags: ["street", "snack", "vegetarian", "chili"],
             profile: Taste(heat: 2, sour: 3, sweet: 1, savour: 2, herbal: 3, rich: 0),
             palette: "herb"),
        Dish(id: "india-jadoh", cuisineID: "india",
             name: "Jadoh", nativeName: "Ja Doh",
             summary: "Khasi cooking in Meghalaya leans on pork, ginger and black sesame rather than the spice masalas of the plains. Jadoh is short grain rice simmered in pork stock with turmeric and pieces of belly and offal until every grain is stained rust brown. Roadside jadoh stalls in Shillong sell it from morning until the pot runs out.",
             tasteNote: "Soft, faintly sticky rice carrying pork fat and ginger, mildly salty rather than spiced, with a warm iron note from the offal.",
             eaten: "A working breakfast or lunch, served on a plate with dohjem sausage and a fierce chili paste.",
             ingredients: ["short grain rice", "pork belly", "ginger", "turmeric", "black pepper", "onion"],
             tags: ["rice", "street", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "rust"),
    ]

    private static let dishes_srilanka: [Dish] = [
        Dish(id: "srilanka-ricecurry", cuisineID: "srilanka",
             name: "Rice and Curry", nativeName: "බත් සහ ව්‍යංජන",
             summary: "The national meal is a plate of rice ringed by five or six curries, each cooked apart and seasoned differently: a dhal in coconut milk, a fried fish, a bitter gourd, a green leaf, a sambol. Nothing is stirred together in the pot. The eater builds each mouthful by hand, adjusting the ratio as they go.",
             tasteNote: "Every spoonful lands differently: creamy dhal, sharp coconut sambol, bitter gourd, and rice absorbing all of it into something warm and steady.",
             eaten: "The main midday meal, mixed and eaten with the right hand, at home or a rice shop.",
             ingredients: ["red rice", "dhal", "coconut milk", "curry leaves", "chili", "maldive fish"],
             tags: ["home", "rice", "chili"],
             profile: Taste(heat: 3, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "saffron"),
        Dish(id: "srilanka-hoppers", cuisineID: "srilanka",
             name: "Egg Hopper", nativeName: "බිත්තර ආප්ප",
             summary: "Fermented rice flour batter thinned with coconut milk is swirled up the sides of a small round pan so it sets into a bowl, crisp and lacy at the rim, spongy at the base. An egg cracked into the middle cooks in the residual heat. Hopper pans come out at dusk, when the stalls fire up for the evening.",
             tasteNote: "Brittle edges snap, the center stays soft and slightly sour, the yolk running into it, salt and chili sambol cutting the coconut.",
             eaten: "Bought at evening street stalls, folded and eaten by hand with lunu miris onion sambol.",
             ingredients: ["rice flour", "coconut milk", "yeast", "egg", "black pepper", "onion sambol"],
             tags: ["street", "breakfast", "fermented"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 2, herbal: 0, rich: 2),
             palette: "amber"),
        Dish(id: "srilanka-kottu", cuisineID: "srilanka",
             name: "Kottu Roti", nativeName: "කොත්තු රොටි",
             summary: "Godamba roti is chopped on a hot steel plate with egg, vegetables, curry and whatever meat is going, worked with two blunt cleavers until it becomes a coarse hash. The clatter is the advertisement, audible down the street. It began as a way to use up yesterday's roti and became the country's late night staple.",
             tasteNote: "Chewy shreds of bread with crisp scorched bits, egg binding it, leek and chili sharp, gravy soaking the bottom of the pile.",
             eaten: "Late at night from a street kitchen, eaten with a fork off paper, with extra curry gravy.",
             ingredients: ["godamba roti", "egg", "leeks", "carrot", "chili", "curry gravy"],
             tags: ["street", "fried", "chili"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "srilanka-lamprais", cuisineID: "srilanka",
             name: "Lamprais", nativeName: "ලම්ප්‍රයිස්",
             summary: "A Dutch Burgher invention from the colonial kitchens of Colombo: rice cooked in stock, a three meat curry, fried ash plantain, a blachan of dried shrimp and two frikkadel meatballs, all folded into a banana leaf and baked so the leaf perfumes everything inside. It is assembled by hand and sold by the packet.",
             tasteNote: "Steam and banana leaf first, then stock rich rice, sweet fried plantain, salty shrimp paste and a soft meatball, each bite different.",
             eaten: "Opened at the table from its leaf, eaten with a fork at lunch or carried to work.",
             ingredients: ["short grain rice", "mixed meat curry", "ash plantain", "shrimp blachan", "frikkadel", "banana leaf"],
             tags: ["feast", "rice", "braised"],
             profile: Taste(heat: 2, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "ochre"),
        Dish(id: "srilanka-ambulthiyal", cuisineID: "srilanka",
             name: "Ambul Thiyal", nativeName: "ඇඹුල් තියල්",
             summary: "A southern fishing coast preservation method turned into a dish. Tuna cubes are cooked almost dry with goraka, the sun dried fruit of Garcinia, plus black pepper and pandan, until the pieces blacken and firm up. With no coconut milk and very little water, it keeps for days in a covered clay pot without cooling.",
             tasteNote: "Dense, almost meaty fish, intensely sour and black peppery, salt heavy, with no sauce to soften the edges.",
             eaten: "One or two pieces per person alongside rice and milder curries, at lunch, eaten by hand.",
             ingredients: ["tuna", "goraka", "black pepper", "pandan leaf", "garlic", "curry leaves"],
             tags: ["seafood", "home", "braised"],
             profile: Taste(heat: 2, sour: 3, sweet: 0, savour: 3, herbal: 1, rich: 1),
             palette: "char"),
        Dish(id: "srilanka-stringhoppers", cuisineID: "srilanka",
             name: "String Hoppers", nativeName: "ඉඳිආප්ප",
             summary: "Rice flour dough is pressed through a fine sieve into flat nests and steamed in stacked trays, so each disc is a tangle of thin white threads. They come out neutral on purpose, a vehicle for dhal, coconut sambol and a thin fish or potato curry poured over the top at the table.",
             tasteNote: "Soft, faintly chewy threads with almost no flavour of their own, taking on coconut, chili and whatever curry is poured over.",
             eaten: "Breakfast or dinner, five or six nests per plate, broken up and mixed by hand.",
             ingredients: ["red rice flour", "water", "salt", "coconut sambol", "dhal curry", "curry leaves"],
             tags: ["breakfast", "vegetarian", "noodle"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 2, herbal: 1, rich: 1),
             palette: "cream"),
        Dish(id: "srilanka-kiribath", cuisineID: "srilanka",
             name: "Kiribath", nativeName: "කිරිබත්",
             summary: "Rice boiled and then finished in thick coconut milk until it sets firm enough to cut, pressed flat and sliced into diamonds. It marks beginnings: the first of the month, Sinhala and Tamil New Year, a birthday, a new house. Plain by design, so the sharp onion and chili of lunu miris beside it does the work.",
             tasteNote: "Dense and creamy, barely salted, mildly sweet from coconut, then scorching heat the moment the chili sambol touches it.",
             eaten: "Eaten by hand in the morning on festival days, with lunu miris or a spoon of jaggery.",
             ingredients: ["short grain rice", "thick coconut milk", "salt", "red onion", "dried chili", "lime"],
             tags: ["feast", "rice", "vegetarian", "breakfast"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 1, herbal: 0, rich: 3),
             palette: "cream"),
        Dish(id: "srilanka-watalappan", cuisineID: "srilanka",
             name: "Watalappan", nativeName: "වටලප්පන්",
             summary: "A steamed custard brought by Malay settlers, built on kithul jaggery rather than white sugar, with coconut milk standing in for cream and eggs doing the setting. Cardamom, clove and nutmeg are ground in fresh. It appears at wedding tables and holiday meals, turned out dark brown and studded with cashew.",
             tasteNote: "Silky and dense, closer to caramel than vanilla, with smoky palm sugar, warm spice and toasted cashew on top.",
             eaten: "Served cold in small bowls at the end of a festival meal, eaten with a teaspoon.",
             ingredients: ["kithul jaggery", "coconut milk", "eggs", "cardamom", "clove", "cashew"],
             tags: ["sweet", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 2, rich: 3),
             palette: "umber"),
    ]

    private static let dishes_nepal: [Dish] = [
        Dish(id: "nepal-dalbhat", cuisineID: "nepal",
             name: "Dal Bhat Tarkari", nativeName: "दाल भात तरकारी",
             summary: "Not a recipe so much as the shape of the Nepali day: rice, a soupy lentil dal poured over it, a seasonal vegetable curry, pickle and greens. It is eaten twice, late morning and evening, and refills are expected. The dal changes with the household, the tarkari with whatever the season has produced.",
             tasteNote: "Mild and steady: loose warm dal, plain rice, a turmeric vegetable, then a jolt of sour chili pickle to reset the mouth.",
             eaten: "Twice a day at home, mixed with the right hand from a steel plate, seconds always offered.",
             ingredients: ["rice", "black lentils", "potato", "cauliflower", "turmeric", "mustard greens"],
             tags: ["home", "rice", "vegetarian"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 2, herbal: 1, rich: 1),
             palette: "saffron"),
        Dish(id: "nepal-momo", cuisineID: "nepal",
             name: "Momo", nativeName: "मोमो",
             summary: "Thin wheat wrappers pleated around minced buffalo, onion and coriander, steamed in stacked aluminium baskets. Nepal took the dumpling from Tibetan traders and added its own achar, a ground tomato and sesame sauce with dried chili, which is really what people queue for. Kathmandu argues about achar recipes more than about fillings.",
             tasteNote: "Slippery skin, hot juice released on the first bite, meat sweet with onion, then the achar bringing sesame, sour tomato and burn.",
             eaten: "Ten to a plate as an afternoon snack, picked up by hand and dropped in achar.",
             ingredients: ["wheat flour", "minced buffalo", "onion", "coriander", "tomato", "sesame seeds"],
             tags: ["dumpling", "street", "snack"],
             profile: Taste(heat: 2, sour: 2, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "crimson"),
        Dish(id: "nepal-sekuwa", cuisineID: "nepal",
             name: "Sekuwa", nativeName: "सेकुवा",
             summary: "Roadside grilling from the eastern hills: goat or pork marinated in timur pepper, ginger, garlic and mustard oil, threaded on sticks and cooked over wood coals rather than gas, which is the whole argument. Bhaktapur and the Dharan highway are both known for it. The fat is left on so it drips and flares.",
             tasteNote: "Charred outside, chewy and juicy within, a numbing citrus tingle from timur, smoke and mustard oil sitting on the salt.",
             eaten: "Eaten off the skewer at roadside grills in the evening, with beaten rice and raw onion.",
             ingredients: ["goat meat", "timur pepper", "ginger", "garlic", "mustard oil", "turmeric"],
             tags: ["grilled", "street", "snack"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 2, rich: 3),
             palette: "char"),
        Dish(id: "nepal-chatamari", cuisineID: "nepal",
             name: "Chatamari", nativeName: "चतामरी",
             summary: "A Newar rice flour crepe cooked on a flat pan, sometimes plain, more often topped with minced buffalo, egg and spring onion before the base sets. It belongs to the Kathmandu Valley's feast calendar and is cooked to order in Newari kitchens, thin, soft and never folded. Outsiders call it Nepali pizza, which annoys people.",
             tasteNote: "Soft, slightly chewy base with a lacy underside, mild rice sweetness under salty meat and a runny egg holding it together.",
             eaten: "Cut into wedges and shared at Newari feasts and small valley eateries, eaten with the hands.",
             ingredients: ["rice flour", "minced buffalo", "egg", "spring onion", "ginger", "cumin"],
             tags: ["feast", "snack", "bread"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "ochre"),
        Dish(id: "nepal-selroti", cuisineID: "nepal",
             name: "Sel Roti", nativeName: "सेलरोटी",
             summary: "A ring of fermented rice batter, sweetened lightly and poured in a circle straight into hot ghee, where it puffs into something between a doughnut and a bread. Households make it in quantity for Tihar and Dashain, and it keeps for days, which is why it travels to relatives across the hills.",
             tasteNote: "Crisp shell, dense springy crumb, mildly sweet with a faint sour edge from the batter, cardamom and ghee in the finish.",
             eaten: "Broken and eaten by hand on festival mornings, with yogurt, potato curry or plain tea.",
             ingredients: ["rice flour", "sugar", "ghee", "cardamom", "banana", "milk"],
             tags: ["sweet", "feast", "fried", "vegetarian"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 0, herbal: 1, rich: 3),
             palette: "amber"),
        Dish(id: "nepal-gundruk", cuisineID: "nepal",
             name: "Gundruk ko Jhol", nativeName: "गुन्द्रुक को झोल",
             summary: "Mustard and radish leaves are wilted, packed airtight and left to sour for weeks, then dried into gundruk, the hill answer to a winter without vegetables. The soup version simmers it with potato, soybean, tomato and chili into a thin sour broth. Every house has a jar, and the smell of it cooking carries.",
             tasteNote: "Sharply sour and faintly funky, thin in the mouth, with chewy leaf, soft potato and a clean chili heat at the back.",
             eaten: "Ladled beside rice or dhindo at home, especially in winter, eaten with a spoon or by hand.",
             ingredients: ["gundruk", "potato", "soybeans", "tomato", "dried chili", "garlic"],
             tags: ["fermented", "vegetarian", "soup", "home"],
             profile: Taste(heat: 2, sour: 3, sweet: 0, savour: 2, herbal: 1, rich: 0),
             palette: "herb"),
        Dish(id: "nepal-dhindo", cuisineID: "nepal",
             name: "Dhindo", nativeName: "ढिँडो",
             summary: "Millet or buckwheat flour stirred into boiling water with a wooden paddle until it thickens into a stiff, glossy mass that stands up on its own. It was the lean season food of the hills and has since become a point of pride, served in mountain lodges as the thing people ate before rice reached the villages.",
             tasteNote: "Thick and slightly sticky, nutty and almost plain on its own, which is the point, since the curry and pickle carry the flavour.",
             eaten: "Pinched off in lumps with the fingers, barely chewed, dipped into gundruk soup or curry.",
             ingredients: ["millet flour", "buckwheat flour", "water", "ghee", "salt", "gundruk"],
             tags: ["home", "vegetarian"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 1, herbal: 0, rich: 1),
             palette: "umber"),
        Dish(id: "nepal-jujudhau", cuisineID: "nepal",
             name: "Juju Dhau", nativeName: "जुजु धौ",
             summary: "Bhaktapur's king of curds, buffalo milk boiled down with a little sugar, spice and cream, then set in unglazed clay pots that wick moisture out overnight and leave it thick enough to hold a spoon upright. The pot is part of the method rather than packaging, and the curd is never sold in anything else.",
             tasteNote: "Thick and almost fudgy, faintly sweet, with a cool tang and a trace of cardamom, cleaner than any cream.",
             eaten: "Eaten straight from the clay pot with a spoon, at festivals, weddings or as an afternoon stop.",
             ingredients: ["buffalo milk", "sugar", "cardamom", "cloves", "cream", "yogurt culture"],
             tags: ["sweet", "dairy", "feast"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 0, herbal: 1, rich: 3),
             palette: "cream"),
    ]

    static let dishes: [Dish] = dishes_india + dishes_srilanka + dishes_nepal
}
