import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentMedEurope {

    private static let cuisine_italy = Cuisine(
        id: "italy",
        regionID: "med-europe",
        country: "Italy",
        adjective: "Italian",
        tagline: "Few things on the plate, each one arguing for itself.",
        summary: "Italian cooking is regional before it is national, and it defends the ingredient rather than transforming it. A Ligurian cook and a Sicilian cook share almost nothing but the instinct to keep the plate short: three or four things, in season, handled lightly. Technique exists to get out of the way. Much of what the world calls Italian food was invented by people cooking around scarcity.",
        staples: ["wheat", "olive oil", "tomato", "cheese", "pork", "anchovy"],
        techniques: ["slow braising in a pot", "baking in a wood oven", "hand-rolling egg pasta"],
        flavourBase: "Olive oil, garlic and tomato, with cured pork and aged cheese for depth.",
        stampInk: "crimson",
        stampShape: "arch",
        stampMotif: "grain")

    private static let cuisine_france = Cuisine(
        id: "france",
        regionID: "med-europe",
        country: "France",
        adjective: "French",
        tagline: "A written grammar of stock, butter and patience.",
        summary: "French cooking is a system: stocks, sauces and a written grammar that lets a cook in Lille and a cook in Nice work from the same logic. Underneath the technique sits farm produce and a stubborn regionalism, so the same discipline yields buttery Normandy one week and olive oil and pepper the next. Precision is the point, not luxury.",
        staples: ["butter", "wheat", "cream", "cheese", "pork", "shallot"],
        techniques: ["slow braising in a cocotte", "reducing stock into sauce", "baking under a crust"],
        flavourBase: "Butter, shallot and stock, sharpened with mustard, wine vinegar and herbs.",
        stampInk: "indigo",
        stampShape: "shield",
        stampMotif: "pot")

    private static let cuisine_spain = Cuisine(
        id: "spain",
        regionID: "med-europe",
        country: "Spain",
        adjective: "Spanish",
        tagline: "Small plates, long tables, and salt from two seas.",
        summary: "Spain cooks around the table rather than the plate. Small dishes arrive to be shared, meals run late, and the calendar still decides what appears: beans and pork in the wet north, tomatoes and cold soups in the dry south, rice where there is water for it. Olive oil, pimenton and cured pork carry flavor across every one of those climates.",
        staples: ["olive oil", "garlic", "pimenton", "cured pork", "rice", "beans"],
        techniques: ["frying in olive oil", "slow simmering in a clay pot", "grilling over vine wood"],
        flavourBase: "Olive oil, garlic and pimenton, lifted with sherry vinegar.",
        stampInk: "ochre",
        stampShape: "scallop",
        stampMotif: "sun")

    static let cuisines: [Cuisine] = [cuisine_italy, cuisine_france, cuisine_spain]

    private static let dishes_italy: [Dish] = [
        Dish(id: "italy-cacioepepe", cuisineID: "italy",
             name: "Cacio e Pepe", nativeName: "Cacio e pepe",
             summary: "A Roman trattoria staple built from three things a shepherd could carry: dry pasta, aged pecorino and black pepper. The sauce is an emulsion, not a recipe, made by working starchy cooking water into grated cheese until it turns glossy. It breaks easily, which is why Romans argue about it more than they argue about carbonara.",
             tasteNote: "Slippery, clinging strands with a slight chew, then sharp salted sheep's milk, and pepper that builds heat and resin at the back of the throat.",
             eaten: "Eaten with a fork at lunch, first course in a Roman trattoria, before a small meat plate.",
             ingredients: ["tonnarelli pasta", "pecorino romano", "black peppercorns", "pasta water"],
             tags: ["noodle", "home", "vegetarian"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 2),
             palette: "cream"),
        Dish(id: "italy-tortellini", cuisineID: "italy",
             name: "Tortellini in Brodo", nativeName: "Tortellini in brodo",
             summary: "Bologna and Modena have argued for centuries over who folds these correctly, and both agree they belong in broth rather than sauce. The filling is pork loin, mortadella, prosciutto and parmesan; the broth is capon, simmered slowly and skimmed clear. It is the Christmas lunch opener across Emilia, and the count per bowl is a matter of pride.",
             tasteNote: "Thin golden broth, clean and deeply savory, then soft pasta giving way to a warm, faintly nutmegged pork filling.",
             eaten: "Spooned from a deep bowl at Christmas lunch, with grated parmesan offered separately at the table.",
             ingredients: ["egg pasta", "pork loin", "mortadella", "prosciutto", "parmigiano reggiano", "capon broth"],
             tags: ["dumpling", "soup", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "italy-bistecca", cuisineID: "italy",
             name: "Bistecca alla Fiorentina", nativeName: "Bistecca alla fiorentina",
             summary: "Cut from Chianina cattle, this is a thick T-bone grilled over oak or vine embers and served rare by rule, not preference. Tuscan butchers sell it by weight and it is meant for a table of several people. Salt goes on after the sear; anything else, including sauce, is treated locally as an insult.",
             tasteNote: "Charred crust that cracks salt, then cool red beef inside, mineral and bloody, with fat softening the finish.",
             eaten: "Carved on a board and shared between three or four, with white beans and olive oil alongside.",
             ingredients: ["chianina t-bone", "coarse salt", "olive oil", "rosemary"],
             tags: ["grilled", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "char"),
        Dish(id: "italy-pizzamargherita", cuisineID: "italy",
             name: "Pizza Margherita", nativeName: "Pizza margherita",
             summary: "Naples turned flatbread into a trade. A wet, slack dough rests for a day, is stretched by hand and cooked in ninety seconds against the floor of a wood oven. The tomato, mozzarella and basil version dates to the late nineteenth century and was named for a visiting queen, though the city had been eating it plainer already.",
             tasteNote: "Soft, blistered edge with a wet center, bright acid tomato, milky mozzarella and the green snap of torn basil.",
             eaten: "Served whole and uncut, folded into quarters by hand, or wrapped as a portafoglio and eaten walking.",
             ingredients: ["wheat dough", "san marzano tomatoes", "fior di latte", "basil", "olive oil"],
             tags: ["street", "bread", "vegetarian"],
             profile: Taste(heat: 0, sour: 2, sweet: 1, savour: 2, herbal: 2, rich: 2),
             palette: "crimson"),
        Dish(id: "italy-arancine", cuisineID: "italy",
             name: "Arancine", nativeName: "Arancine di riso",
             summary: "Sicilian rice fritters that likely descend from Arab-era rice cookery, stuffed with meat ragu and peas or with ham and mozzarella, then breaded and fried. Palermo makes them round and calls them arancine; Catania shapes them into cones after Mount Etna and says arancini. Every bar counter on the island keeps a tray warm from morning on.",
             tasteNote: "Crackling crumb shell, then dense saffron rice, and a molten savory center of ragu with stringy melted cheese.",
             eaten: "Bought from a bar counter in paper, eaten standing at any hour, often as a whole meal.",
             ingredients: ["risotto rice", "saffron", "meat ragu", "peas", "caciocavallo", "breadcrumbs"],
             tags: ["street", "fried", "rice", "snack"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 3, herbal: 0, rich: 3),
             palette: "ochre"),
        Dish(id: "italy-bagnacauda", cuisineID: "italy",
             name: "Bagna Cauda", nativeName: "Bagna càuda",
             summary: "A Piedmontese winter ritual more than a dish. Garlic, salted anchovies and olive oil are cooked down slowly into a pungent warm sauce, kept over a flame in an earthenware pot while everyone at the table dips raw and roasted vegetables into it. It belongs to the hills of the Langhe and Monferrato, and to long evenings after the harvest.",
             tasteNote: "Sharp raw crunch first, then a heavy oily hit of garlic and salted fish, softening into something almost sweet.",
             eaten: "Shared from one communal pot over a burner, vegetables dipped by hand, on cold autumn evenings.",
             ingredients: ["salted anchovies", "garlic", "olive oil", "cardoons", "sweet peppers"],
             tags: ["home", "feast"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 0, rich: 3),
             palette: "umber"),
        Dish(id: "italy-culurgiones", cuisineID: "italy",
             name: "Culurgiones", nativeName: "Culurgionis d'Ogliastra",
             summary: "From the Ogliastra hills of eastern Sardinia, these are pasta parcels filled with potato, sharp pecorino and mint, closed by hand in a pleat that looks like a wheat ear. The stitch takes practice and was traditionally taught between women in a household. Shepherd food in origin, they were once made for the November feast days.",
             tasteNote: "Springy pasta, then a soft potato filling that is salty and grassy at once, mint cutting the sheep cheese.",
             eaten: "Served on a plate with simple tomato sauce and grated pecorino, as a family Sunday first course.",
             ingredients: ["semolina dough", "potato", "pecorino sardo", "mint", "garlic", "tomato sauce"],
             tags: ["dumpling", "home", "vegetarian"],
             profile: Taste(heat: 0, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "herb"),
        Dish(id: "italy-tiramisu", cuisineID: "italy",
             name: "Tiramisu", nativeName: "Tiramisù",
             summary: "The youngest classic in the Italian canon, most credibly traced to a restaurant in Treviso in the 1970s, with Friuli claiming a rival origin. Savoiardi biscuits are dipped in strong coffee and layered with mascarpone whipped into egg and sugar, then dusted with bitter cocoa. No baking, no oven, and it must rest cold before it is cut.",
             tasteNote: "Cold and loose on the spoon, coffee-soaked sponge under thick sweet cream, finishing dry and bitter with cocoa.",
             eaten: "Scooped cold with a spoon after dinner, or mid-afternoon with coffee, in a small dish.",
             ingredients: ["savoiardi biscuits", "mascarpone", "eggs", "espresso", "sugar", "cocoa powder"],
             tags: ["sweet", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 3),
             palette: "umber"),
    ]

    private static let dishes_france: [Dish] = [
        Dish(id: "france-bouillabaisse", cuisineID: "france",
             name: "Bouillabaisse", nativeName: "Bouillabaisse",
             summary: "Marseille fishermen made this from the rockfish nobody would buy, boiled hard with fennel, saffron and orange peel. The broth and the fish are served in two stages, the broth first with rouille and toasted bread. A 1980 charter tried to fix which species belong in it, which tells you how seriously the city takes the question.",
             tasteNote: "Deep orange broth, saline and heavy with saffron and fennel, then firm white fish falling apart under the spoon.",
             eaten: "Broth served first in a deep bowl, fish carved after, with garlic rouille spread on bread.",
             ingredients: ["rockfish", "saffron", "fennel", "orange peel", "garlic rouille", "olive oil"],
             tags: ["seafood", "soup", "feast"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "saffron"),
        Dish(id: "france-choucroute", cuisineID: "france",
             name: "Choucroute Garnie", nativeName: "Choucroute garnie",
             summary: "Alsace sits on a border and eats like it. Cabbage is salted and fermented through autumn, then slowly cooked with lard, juniper and Riesling, and buried under smoked pork, ham hock and several sausages. It is a cold-weather platter for a full table, and no Alsatian household considers a small one worth making.",
             tasteNote: "Sour, soft cabbage with a wine edge, then salty smoked pork and fat, juniper and pepper running through it.",
             eaten: "Brought out on one large platter for a winter Sunday table, with boiled potatoes and mustard.",
             ingredients: ["fermented cabbage", "smoked pork belly", "ham hock", "strasbourg sausage", "juniper berries", "potatoes"],
             tags: ["fermented", "feast", "braised"],
             profile: Taste(heat: 0, sour: 3, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "cream"),
        Dish(id: "france-bourguignon", cuisineID: "france",
             name: "Boeuf Bourguignon", nativeName: "Bœuf bourguignon",
             summary: "Burgundian peasant cooking that got promoted. Tough working cattle needed hours of slow heat, and the region's red wine did the tenderizing, with bacon, onions and mushrooms added late. Escoffier wrote it down and it left the farmhouse for the restaurant, but the method has not changed: brown hard, then leave it alone in a low oven.",
             tasteNote: "Beef that gives way without chewing, in a dark glossy sauce that is winey and slightly sweet, deeply meaty.",
             eaten: "Ladled from the pot at a family dinner, with bread or potatoes to catch the sauce.",
             ingredients: ["beef chuck", "red wine", "smoked bacon", "pearl onions", "button mushrooms", "carrots"],
             tags: ["braised", "home"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "france-galette", cuisineID: "france",
             name: "Galette Complete", nativeName: "Galette complète",
             summary: "Brittany could not grow much wheat, so it grew buckwheat, and the dark savory crepe came out of that. A thin batter of buckwheat flour and water is spread on a flat griddle, topped with ham, grated cheese and an egg, then folded into a square with the yolk showing.",
             tasteNote: "Lacy crisp edges over a soft pliable center, earthy and slightly bitter buckwheat against salty ham and runny yolk.",
             eaten: "Eaten with knife and fork in a creperie, any time from lunch to late evening.",
             ingredients: ["buckwheat flour", "ham", "gruyere", "egg", "salted butter"],
             tags: ["street", "home", "bread"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 2),
             palette: "ochre"),
        Dish(id: "france-piperade", cuisineID: "france",
             name: "Piperade", nativeName: "Piperada",
             summary: "The Basque country grows a mild red pepper at Espelette and a long green one, and this is what it does with them. Peppers, onion and tomato are stewed down in fat until they collapse, then beaten egg is stirred through until barely set. Farmhouse cooking, made in quantity when the peppers come in.",
             tasteNote: "Soft and loose, almost spoonable, sweet cooked pepper and tomato with a slow warm chili prickle and creamy egg.",
             eaten: "Eaten straight from the pan at lunch with bread, sometimes with a slice of Bayonne ham.",
             ingredients: ["green peppers", "tomatoes", "onion", "eggs", "espelette pepper", "olive oil"],
             tags: ["home", "vegetarian", "chili"],
             profile: Taste(heat: 2, sour: 1, sweet: 2, savour: 2, herbal: 1, rich: 1),
             palette: "crimson"),
        Dish(id: "france-quenelles", cuisineID: "france",
             name: "Quenelles de Brochet", nativeName: "Quenelles de brochet sauce Nantua",
             summary: "Lyon's answer to a bony river fish. Pike flesh is pounded with choux paste and butter into a pale dumpling, poached, then baked under a crayfish sauce from the lakes near Nantua. The quenelle swells in the oven and collapses if you wait. It is the classic order in a bouchon, and older than most of them.",
             tasteNote: "Almost weightless and mousse-like, dissolving on the tongue, under a pink shellfish sauce that is buttery and sweetly saline.",
             eaten: "Served hot from the oven in a bouchon at dinner, with rice or plain bread.",
             ingredients: ["pike flesh", "choux paste", "butter", "crayfish", "cream", "egg"],
             tags: ["seafood", "dumpling"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 2, herbal: 0, rich: 3),
             palette: "blush"),
        Dish(id: "france-tartiflette", cuisineID: "france",
             name: "Tartiflette", nativeName: "Tartiflette",
             summary: "Younger than it looks. Savoyard villages had long baked potatoes with cheese, but this exact version was pushed in the 1980s by the Reblochon producers' union to sell more of their cheese, and it worked. Potatoes, lardons and onion go under a halved wheel of Reblochon and bake until the rind blisters.",
             tasteNote: "Heavy and molten, soft potato under stretchy washed-rind cheese that is nutty and faintly barnyard, with salty bacon through it.",
             eaten: "Scooped from the baking dish after a day in the mountains, with green salad and pickles.",
             ingredients: ["potatoes", "reblochon", "smoked lardons", "onion", "cream"],
             tags: ["home", "dairy"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "amber"),
        Dish(id: "france-canele", cuisineID: "france",
             name: "Canele de Bordeaux", nativeName: "Cannelé bordelais",
             summary: "A small fluted cake from Bordeaux with a black caramelized shell and a custard center, baked in copper molds lined with beeswax. The batter is loose, closer to crepe batter than dough, and rests overnight. Convent kitchens near the port are usually credited, using egg yolks left over from the wine trade's fining process.",
             tasteNote: "A thin bitter-sweet crust that shatters, then a dense wobbling custard inside, warm with vanilla, rum and caramel.",
             eaten: "Bought by the half-dozen from a pastry shop, eaten in the afternoon with coffee, standing.",
             ingredients: ["milk", "egg yolks", "sugar", "flour", "vanilla", "beeswax"],
             tags: ["sweet", "snack"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 2),
             palette: "char"),
    ]

    private static let dishes_spain: [Dish] = [
        Dish(id: "spain-paella", cuisineID: "spain",
             name: "Paella Valenciana", nativeName: "Paella valenciana",
             summary: "The rice dish of the Albufera wetlands south of Valencia, cooked outdoors over orange wood in a wide shallow pan. The original is field food: rabbit, chicken, flat green beans, garrofo beans and snails, never seafood, which Valencians will explain at length. The rice must end dry and separate, with a toasted crust stuck to the pan.",
             tasteNote: "Dry separate grains carrying saffron and wood smoke, tender rabbit, and a chewy scorched layer scraped from the bottom.",
             eaten: "Eaten straight from the pan with wooden spoons at a long Sunday lunch outdoors.",
             ingredients: ["bomba rice", "rabbit", "chicken", "flat green beans", "saffron", "rosemary"],
             tags: ["rice", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "saffron"),
        Dish(id: "spain-gazpacho", cuisineID: "spain",
             name: "Gazpacho Andaluz", nativeName: "Gazpacho andaluz",
             summary: "Before tomatoes reached Spain this was bread, garlic, oil and vinegar pounded in a mortar, a way for Andalusian field workers to survive the heat. Tomato and pepper joined later and turned it red. It is drunk cold through the summer, and the bread is still in there, doing the work of thickening.",
             tasteNote: "Cold and smooth with a faint grain of bread, sharply acidic from vinegar, then raw garlic and green pepper.",
             eaten: "Drunk from a glass or spooned from a bowl at midday in summer, with diced vegetables.",
             ingredients: ["ripe tomatoes", "cucumber", "green pepper", "stale bread", "sherry vinegar", "olive oil"],
             tags: ["home", "vegetarian", "soup"],
             profile: Taste(heat: 0, sour: 3, sweet: 1, savour: 1, herbal: 1, rich: 1),
             palette: "crimson"),
        Dish(id: "spain-pulpo", cuisineID: "spain",
             name: "Pulpo a Feira", nativeName: "Polbo á feira",
             summary: "Galician fair food, cooked by women called pulpeiras who travel between village festivals with copper cauldrons. The octopus is dipped three times into boiling water to keep the skin on, then boiled, cut with scissors into coins and thrown onto a wooden plate with oil, coarse salt and pimenton. Inland Galicia eats more of it than the coast.",
             tasteNote: "Tender with a slight springy resistance, clean sea salt, then smoky sweet paprika and grassy olive oil coating the tongue.",
             eaten: "Eaten standing at a festival stall with toothpicks, off a wooden plate, with boiled potatoes.",
             ingredients: ["octopus", "pimenton", "coarse sea salt", "olive oil", "potatoes"],
             tags: ["seafood", "street", "snack"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 1),
             palette: "rust"),
        Dish(id: "spain-tortilla", cuisineID: "spain",
             name: "Tortilla Espanola", nativeName: "Tortilla de patatas",
             summary: "Potato and egg, slowly confited in olive oil and set into a thick cake, flipped on a plate halfway through. It appeared in Spain around the early nineteenth century as cheap filling food and never left. The only real question is whether the middle should still run, which divides the country more reliably than politics.",
             tasteNote: "Soft and heavy, potato almost creamy, egg barely set in the middle, sweet from long-cooked onion and olive oil.",
             eaten: "Cut into wedges at room temperature, eaten as a tapa, in a sandwich, or for supper.",
             ingredients: ["potatoes", "eggs", "onion", "olive oil", "salt"],
             tags: ["home", "vegetarian", "snack"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 2, herbal: 0, rich: 2),
             palette: "ochre"),
        Dish(id: "spain-fabada", cuisineID: "spain",
             name: "Fabada Asturiana", nativeName: "Fabada asturiana",
             summary: "Asturias is wet, green and cold, and this is what it eats. Large flat fabes beans are soaked overnight and simmered gently with smoked chorizo, morcilla and salt-cured pork shoulder until the broth thickens by itself. Nothing is stirred hard, because the beans must stay whole. One bowl usually ends the day's eating.",
             tasteNote: "Beans that collapse to butter in the mouth, in a thick smoky broth, heavy with paprika and cured pork fat.",
             eaten: "Served in a deep bowl as a midday winter main, with bread and nothing much after.",
             ingredients: ["fabes beans", "chorizo", "morcilla", "cured pork shoulder", "pimenton", "saffron"],
             tags: ["braised", "home", "feast"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "umber"),
        Dish(id: "spain-calcots", cuisineID: "spain",
             name: "Calcots amb Romesco", nativeName: "Calçots amb romesco",
             summary: "A Catalan winter ritual around a specific onion, grown so the stem stays long and white. The calcots are burned black over vine cuttings, wrapped in newspaper to steam, then peeled at the table and dropped into a nut and pepper sauce. It happens outdoors between January and April, and everyone wears a bib.",
             tasteNote: "Slippery and very sweet inside the charred skin, smoky, then a thick sauce of almond, dried pepper and vinegar.",
             eaten: "Pulled by hand from the newspaper, dipped, and lowered into the mouth at an outdoor spring gathering.",
             ingredients: ["calcot onions", "almonds", "hazelnuts", "nyora peppers", "tomato", "sherry vinegar"],
             tags: ["grilled", "feast", "vegetarian"],
             profile: Taste(heat: 1, sour: 2, sweet: 3, savour: 2, herbal: 0, rich: 2),
             palette: "char"),
        Dish(id: "spain-gilda", cuisineID: "spain",
             name: "Gilda", nativeName: "Gilda",
             summary: "The first pintxo, invented in a San Sebastian bar in the 1940s and named after the Rita Hayworth film, because regulars called it green, salty and a little racy. Three things on a stick: a salted anchovy, pickled guindilla peppers and a manzanilla olive. Nothing is cooked, and the order of assembly is argued over.",
             tasteNote: "One sharp mouthful: vinegar and brine first, then oily anchovy salt, a mild grassy chili burn, and bitter olive.",
             eaten: "Taken off a bar counter in one bite before dinner, standing, usually two or three at once.",
             ingredients: ["salted anchovy", "guindilla peppers", "manzanilla olive", "olive oil"],
             tags: ["snack", "street", "raw"],
             profile: Taste(heat: 1, sour: 3, sweet: 0, savour: 3, herbal: 0, rich: 1),
             palette: "jade"),
        Dish(id: "spain-churros", cuisineID: "spain",
             name: "Churros con Chocolate", nativeName: "Churros con chocolate",
             summary: "Simple flour-and-water dough piped through a star nozzle into hot oil, so it fries fast and stays hollow. Spain drinks its chocolate thick enough to stand a churro in, a habit that goes back to the first cacao arriving from the Americas. Churrerias open before dawn and do their best trade on Sunday mornings.",
             tasteNote: "Crisp ridged shell, steam and soft dough inside, barely sweet on its own until the bitter thick chocolate coats it.",
             eaten: "Dipped into a cup of hot chocolate at breakfast or very late, standing at a churreria.",
             ingredients: ["flour", "water", "salt", "frying oil", "dark chocolate", "milk"],
             tags: ["sweet", "street", "breakfast", "fried"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 2),
             palette: "char"),
    ]

    static let dishes: [Dish] = dishes_italy + dishes_france + dishes_spain
}
