import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentEastAsia {

    private static let cuisine_japan = Cuisine(
        id: "japan",
        regionID: "east-asia",
        country: "Japan",
        adjective: "Japanese",
        tagline: "Season first, salt second, and nothing added that is not needed.",
        summary: "Japanese cooking works by subtraction. A cook chooses one ingredient at its best moment, then does as little as possible to it, letting dashi carry salt and smoke underneath so the vegetable or the fish still tastes like itself. Season dictates the menu, the plate is chosen to suit the food, and restraint is treated as a skill rather than a limitation.",
        staples: ["rice", "dashi", "soy", "miso", "seaweed"],
        techniques: ["simmering in dashi", "grilling over charcoal", "steaming in a lidded cup"],
        flavourBase: "Dashi, soy and mirin, with salt and smoke arriving before sweetness.",
        stampInk: "indigo",
        stampShape: "circle",
        stampMotif: "wave")

    private static let cuisine_korea = Cuisine(
        id: "korea",
        regionID: "east-asia",
        country: "Korea",
        adjective: "Korean",
        tagline: "Fermented depth, chili warmth, and a table covered in small dishes.",
        summary: "Korean food is built around the jar. Cabbage, soybeans and chilies are salted and left to time, and the sour, deep results season everything that follows. A meal arrives all at once as a spread of small dishes around rice, so the eater balances each bite themselves. Heat here is warming rather than punishing, and it usually comes with garlic and sesame close behind.",
        staples: ["rice", "gochujang", "sesame oil", "garlic", "soybean paste", "cabbage"],
        techniques: ["fermenting in crocks", "grilling at the table", "simmering in earthenware"],
        flavourBase: "Chili, garlic and fermented soybean, rounded out with sesame and a little sugar.",
        stampInk: "crimson",
        stampShape: "shield",
        stampMotif: "mountain")

    private static let cuisine_china = Cuisine(
        id: "china",
        regionID: "east-asia",
        country: "China",
        adjective: "Chinese",
        tagline: "Wok heat, balance, and texture treated as a flavor of its own.",
        summary: "China is less one kitchen than eight or more, argued over by region. What holds them together is a shared grammar: control of heat in the wok, a working balance of salt, sweet, sour and aroma, and the idea that texture matters as much as flavor. Sichuan reaches for numbing pepper, Guangdong for steam and clean broth, and the north builds on wheat.",
        staples: ["rice", "wheat", "soy sauce", "ginger", "scallions", "vinegar"],
        techniques: ["stir frying over high heat", "steaming in bamboo", "red braising"],
        flavourBase: "Soy, ginger and rice vinegar, with chili and peppercorn where the west of the country begins.",
        stampInk: "rust",
        stampShape: "scallop",
        stampMotif: "knot")

    static let cuisines: [Cuisine] = [cuisine_japan, cuisine_korea, cuisine_china]

    private static let dishes_japan: [Dish] = [
        Dish(id: "japan-shoyu-ramen", cuisineID: "japan",
             name: "Shoyu Ramen", nativeName: "醤油ラーメン",
             summary: "Ramen came to Japan from Chinese noodle shops and was rebuilt city by city until every region claimed its own version. The shoyu style is the Tokyo answer: a clear soy seasoning base sitting under a bird and pork broth. It is a working person's meal, fast, cheap and endlessly argued about.",
             tasteNote: "Springy noodles with a slight snap, then a clean salty broth carrying roasted meat and scallion, finishing lighter than it looks.",
             eaten: "Slurped fast at a counter with chopsticks and a spoon, often late at night, alone.",
             ingredients: ["wheat noodles", "soy tare", "chicken and pork broth", "chashu pork", "nori", "menma"],
             tags: ["noodle", "soup", "street"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "japan-nigiri", cuisineID: "japan",
             name: "Nigirizushi", nativeName: "握り寿司",
             summary: "Sushi began as a preservation trick, fish packed in fermenting rice, and only became fast food in nineteenth century Edo when cooks started pressing a slice over a seasoned rice pillow to sell from carts. The vinegar in the rice is the point; the fish is chosen and cut, not cooked.",
             tasteNote: "Cool yielding fish against rice still warm from the hand, faintly sweet and sharp with vinegar, a clean saline finish.",
             eaten: "Eaten in one bite, fish side down into soy, by hand or chopsticks, at the counter.",
             ingredients: ["sushi rice", "rice vinegar", "tuna and sea bream", "wasabi", "nori"],
             tags: ["raw", "seafood", "rice"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 2, herbal: 0, rich: 1),
             palette: "cream"),
        Dish(id: "japan-okonomiyaki", cuisineID: "japan",
             name: "Okonomiyaki", nativeName: "お好み焼き",
             summary: "The name means grilled how you like it, and the dish is a postwar answer to scarce rice: shredded cabbage bound with a thin flour and dashi batter, cooked flat on a hot steel plate. Osaka mixes everything together, Hiroshima stacks it in layers over noodles and defends the difference loudly.",
             tasteNote: "Soft and steamy inside with crisp browned edges, sweet brown sauce and mayonnaise over cabbage, smoky from bonito flakes.",
             eaten: "Cut with a small spatula straight off the griddle at the table, shared, usually in the evening.",
             ingredients: ["cabbage", "flour and dashi batter", "pork belly", "okonomiyaki sauce", "bonito flakes", "egg"],
             tags: ["street", "grilled", "snack"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 3, herbal: 0, rich: 2),
             palette: "umber"),
        Dish(id: "japan-chawanmushi", cuisineID: "japan",
             name: "Chawanmushi", nativeName: "茶碗蒸し",
             summary: "A savory custard steamed in the same lidded cup it is served in, and one of the few Japanese dishes eaten with a spoon. Dashi and egg are whisked in careful proportion, then held just below a boil so the surface stays smooth. Small treasures hide underneath: a shrimp, a mushroom, a gingko nut.",
             tasteNote: "Barely set, closer to warm silk than to egg, gently salty with dashi, and quiet enough to taste the mushroom.",
             eaten: "Served warm in its own cup with a small spoon, early in a meal or beside rice.",
             ingredients: ["egg", "dashi", "shrimp", "shiitake mushroom", "gingko nuts", "mitsuba"],
             tags: ["home", "seafood"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 2, herbal: 1, rich: 1),
             palette: "cream"),
        Dish(id: "japan-ozoni", cuisineID: "japan",
             name: "Ozoni", nativeName: "お雑煮",
             summary: "The first thing eaten on New Year's morning, and the one dish where families argue about their own grandmother's version. Kanto keeps a clear broth with square toasted mochi, Kansai uses white miso and round cakes. Whatever the region, the pounded rice cake at the center is the point of the year.",
             tasteNote: "Thin clear broth, mild and salty, then the mochi turns stretchy and gluey between the teeth, with sharp citrus peel at the end.",
             eaten: "Eaten on New Year's morning from a lacquer bowl with chopsticks, slowly, before anything else.",
             ingredients: ["mochi rice cakes", "dashi", "chicken", "komatsuna greens", "yuzu peel"],
             tags: ["feast", "soup", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 2, herbal: 1, rich: 1),
             palette: "jade"),
        Dish(id: "japan-nasu-dengaku", cuisineID: "japan",
             name: "Nasu Dengaku", nativeName: "茄子田楽",
             summary: "Dengaku is an old temple technique: skewer something, coat it in sweetened miso, hold it near the fire until the paste blisters. Eggplant took the method over because it collapses into cream under heat while the glaze stays firm. Buddhist kitchens kept it meatless and the rest of the country kept it anyway.",
             tasteNote: "Spoon soft flesh under a dark sticky glaze, sweet first and then deeply salty, with a faint bitterness from the skin.",
             eaten: "Served hot as a side with rice and chopsticks, one half per person, at dinner.",
             ingredients: ["japanese eggplant", "red miso", "mirin", "sugar", "sesame seeds"],
             tags: ["vegetarian", "grilled", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 3, herbal: 0, rich: 1),
             palette: "plum"),
        Dish(id: "japan-oyakodon", cuisineID: "japan",
             name: "Oyakodon", nativeName: "親子丼",
             summary: "Parent and child in a bowl, which is a blunt way of naming chicken and egg together over rice. The chicken simmers in dashi, soy and mirin in a small shallow pan, then beaten egg is poured in and pulled off the heat while still loose, so it sets on the rice.",
             tasteNote: "Loose custardy egg running into rice, sweet soy soaking downward, tender chicken and soft onion, comforting rather than complicated.",
             eaten: "A weekday lunch, eaten fast from the bowl with chopsticks, pickles and clear soup alongside.",
             ingredients: ["rice", "chicken thigh", "egg", "onion", "dashi", "soy and mirin"],
             tags: ["rice", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 3, herbal: 0, rich: 2),
             palette: "saffron"),
        Dish(id: "japan-warabimochi", cuisineID: "japan",
             name: "Warabimochi", nativeName: "わらび餅",
             summary: "Not really mochi at all, but a jelly set from bracken starch, cut into wobbling cubes and buried in roasted soybean flour. Kyoto sells it in summer from carts and old shops, chilled, because the texture only works cold. Real bracken starch is scarce now, so most versions cut it with tapioca.",
             tasteNote: "Cold, slippery and barely holding its shape, almost no sweetness of its own until the nutty flour and dark syrup arrive.",
             eaten: "A cold summer sweet, picked up with a toothpick or small fork, with green tea.",
             ingredients: ["bracken starch", "sugar", "kinako soybean flour", "kuromitsu syrup", "water"],
             tags: ["sweet", "snack", "vegetarian"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 0, herbal: 0, rich: 1),
             palette: "ochre"),
    ]

    private static let dishes_korea: [Dish] = [
        Dish(id: "korea-kimchi", cuisineID: "korea",
             name: "Baechu Kimchi", nativeName: "배추김치",
             summary: "Every Korean household once made this in late autumn, in a single collective weekend called kimjang, salting whole cabbages and packing them with chili, garlic and salted seafood before burying the jars. Fermentation does the rest through winter. Younger kimchi is crisp and fresh, older kimchi turns sour and goes into stews and pancakes.",
             tasteNote: "Crunching wet cabbage stem, then sour salt, garlic and a slow chili warmth that keeps building after you swallow.",
             eaten: "On the table at every meal in a small dish, picked up with chopsticks between bites of rice.",
             ingredients: ["napa cabbage", "gochugaru chili flakes", "garlic", "salted shrimp", "korean radish"],
             tags: ["fermented", "home", "chili"],
             profile: Taste(heat: 2, sour: 3, sweet: 0, savour: 3, herbal: 1, rich: 0),
             palette: "crimson"),
        Dish(id: "korea-bibimbap", cuisineID: "korea",
             name: "Bibimbap", nativeName: "비빔밥",
             summary: "The name simply means mixed rice, and the dish began as a way to clear leftover seasoned vegetables into one bowl. Each namul is cooked separately so it keeps its own character, then arranged in wedges over rice with chili paste and an egg. The eater destroys the arrangement immediately, which is the point.",
             tasteNote: "Warm rice against cool crisp vegetables, sesame oil through everything, sweet chili heat, and a soft yolk pulling it together.",
             eaten: "Stirred hard with a spoon until uniform, then eaten from the bowl with soup on the side.",
             ingredients: ["short grain rice", "spinach and bean sprouts", "carrot and zucchini", "gochujang", "fried egg", "sesame oil"],
             tags: ["rice", "home", "chili"],
             profile: Taste(heat: 2, sour: 1, sweet: 1, savour: 3, herbal: 1, rich: 1),
             palette: "jade"),
        Dish(id: "korea-bulgogi", cuisineID: "korea",
             name: "Bulgogi", nativeName: "불고기",
             summary: "Fire meat, and the direct descendant of a grilling tradition that goes back to skewered beef in the Goguryeo period. Thin slices sit in soy, pear juice, garlic and sesame until the sugars in the fruit soften them, then they cook in seconds over a domed grill plate.",
             tasteNote: "Tender to the point of falling apart, sweet and salty with caramelized edges, sesame and garlic underneath, juices pooling.",
             eaten: "Cooked at the table, wrapped in lettuce with rice and soybean paste, shared among a crowd.",
             ingredients: ["thin sliced beef", "soy sauce", "asian pear", "garlic", "sesame oil", "scallions"],
             tags: ["grilled", "feast", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "korea-samgyetang", cuisineID: "korea",
             name: "Samgyetang", nativeName: "삼계탕",
             summary: "A whole young chicken stuffed with sticky rice, ginseng and jujube, then simmered until the bird gives way. Koreans eat it on the hottest days of summer, on the logic that heat should be met with heat rather than avoided. It arrives boiling in a stone pot with salt and pepper on the side.",
             tasteNote: "Mild milky broth with almost no salt until you add it, meat sliding off bone, rice gone soft and porridge like.",
             eaten: "One pot per person, eaten scalding hot at midsummer lunch with spoon, chopsticks and coarse salt.",
             ingredients: ["young chicken", "glutinous rice", "ginseng root", "jujube", "garlic", "scallions"],
             tags: ["feast", "soup", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 2, herbal: 3, rich: 2),
             palette: "cream"),
        Dish(id: "korea-kongguksu", cuisineID: "korea",
             name: "Kongguksu", nativeName: "콩국수",
             summary: "Soybeans are boiled, skinned and ground into a cold unseasoned milk, and noodles are dropped straight into it. There is no broth, no stock and often no salt until the eater adds it. A summer dish from the southern provinces, plain on purpose, and one of the few Korean noodles with no chili anywhere near it.",
             tasteNote: "Thick chalky cold soy milk clinging to chewy wheat noodles, nutty and faintly sweet, waking up the moment salt hits.",
             eaten: "A hot weather lunch, eaten cold with chopsticks and a spoon, salt and cucumber added yourself.",
             ingredients: ["soybeans", "wheat noodles", "cucumber", "sesame seeds", "ice"],
             tags: ["noodle", "vegetarian", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 1, herbal: 0, rich: 2),
             palette: "cream"),
        Dish(id: "korea-hotteok", cuisineID: "korea",
             name: "Hotteok", nativeName: "호떡",
             summary: "Chinese traders brought a filled wheat flatbread to Korean ports in the late nineteenth century and Korea sweetened it. Dough is pressed onto a griddle, flattened with a metal disc, and the brown sugar inside melts into syrup. Winter markets sell it folded into a paper cup because it leaks.",
             tasteNote: "Crisp fried outside, chewy bread beneath, then molten cinnamon sugar and crushed nuts that run everywhere on the first bite.",
             eaten: "Bought from a street cart in winter, eaten standing from a paper cup, carefully.",
             ingredients: ["wheat and glutinous flour", "brown sugar", "cinnamon", "peanuts", "yeast"],
             tags: ["street", "sweet", "snack"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 2),
             palette: "ochre"),
        Dish(id: "korea-pajeon", cuisineID: "korea",
             name: "Haemul Pajeon", nativeName: "해물파전",
             summary: "A batter pancake built around whole scallions rather than dotted with them, with squid and clams pushed in before it sets. Busan claims the best version. Koreans associate it with rainy days, partly because the sound of batter hitting oil is said to resemble rain on a roof.",
             tasteNote: "Lacy crisp edges giving way to a soft eggy middle, sweet cooked scallion, chewy squid, sharp soy and vinegar dip.",
             eaten: "Torn apart with chopsticks and shared on a rainy afternoon, dipped in soy and vinegar.",
             ingredients: ["wheat batter", "scallions", "squid", "clams", "egg", "soy vinegar dip"],
             tags: ["fried", "seafood", "snack"],
             profile: Taste(heat: 1, sour: 1, sweet: 1, savour: 2, herbal: 1, rich: 2),
             palette: "saffron"),
        Dish(id: "korea-tteokbokki", cuisineID: "korea",
             name: "Tteokbokki", nativeName: "떡볶이",
             summary: "The palace original was soy seasoned and mild; the version everyone knows was invented in a Sindang market stall in the 1950s when a vendor dropped rice cakes into chili sauce. Cylinders of pressed rice simmer in gochujang until the sauce clings. It became the standard after school food of an entire country.",
             tasteNote: "Dense chewy cylinders that resist the teeth, coated in a thick sweet chili sauce with a burn that arrives late.",
             eaten: "Eaten standing at a market stall from a paper cup with a wooden skewer, afternoon snack.",
             ingredients: ["garaetteok rice cakes", "gochujang", "fish cakes", "sugar", "scallions", "anchovy stock"],
             tags: ["street", "snack", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 3, savour: 2, herbal: 0, rich: 1),
             palette: "crimson"),
    ]

    private static let dishes_china: [Dish] = [
        Dish(id: "china-xiaolongbao", cuisineID: "china",
             name: "Xiaolongbao", nativeName: "小籠包",
             summary: "Shanghai's contribution to the dumpling argument: jellied stock is folded into the pork filling, and steaming melts it back into soup inside the wrapper. The skin has to be thin enough to see through and strong enough to lift. Nanxiang bakers standardized the pleat count, and people still count them.",
             tasteNote: "A thin slippery skin, then hot savory broth flooding out, then dense seasoned pork, cut by sharp black vinegar and ginger.",
             eaten: "Lifted from the steamer by the pleat, bitten open on a spoon, morning tea with vinegar.",
             ingredients: ["wheat wrappers", "pork", "aspic stock", "ginger", "black vinegar"],
             tags: ["dumpling", "snack", "street"],
             profile: Taste(heat: 0, sour: 2, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "cream"),
        Dish(id: "china-mapo-doufu", cuisineID: "china",
             name: "Mapo Doufu", nativeName: "麻婆豆腐",
             summary: "Named for a pockmarked old woman who ran a Chengdu noodle shop in the 1860s and cooked tofu for porters passing her door. The dish is the clearest statement of Sichuan's ma la: numbing peppercorn against chili heat, held in a glossy sauce thick enough to stand a spoon.",
             tasteNote: "Silky tofu cubes that barely hold together, fierce chili heat, then a buzzing tingle on the lips that will not stop.",
             eaten: "Spooned over white rice at a family dinner, one shared dish among several on the table.",
             ingredients: ["silken tofu", "ground pork", "doubanjiang", "sichuan peppercorn", "chili oil", "scallions"],
             tags: ["home", "chili", "braised"],
             profile: Taste(heat: 3, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "crimson"),
        Dish(id: "china-peking-duck", cuisineID: "china",
             name: "Peking Duck", nativeName: "北京烤鴨",
             summary: "An imperial kitchen dish refined over centuries: air is pumped under the skin, the bird is scalded, coated in maltose and hung to dry for a day before it meets a fruitwood fire. The skin is the whole ambition. A carver works it at the table into counted slices, and the carcass goes back for soup.",
             tasteNote: "Glass thin skin shattering into rendered fat, then mild dark meat, sweet fermented sauce and the clean bite of raw scallion.",
             eaten: "Rolled into thin pancakes with scallion and sauce, built by hand, at a long celebratory dinner.",
             ingredients: ["whole duck", "maltose glaze", "thin pancakes", "sweet bean sauce", "scallions", "cucumber"],
             tags: ["feast", "grilled"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 3, herbal: 0, rich: 3),
             palette: "rust"),
        Dish(id: "china-zhou", cuisineID: "china",
             name: "Zhou", nativeName: "粥",
             summary: "Rice cooked far past the point of holding its shape, stirred until the grains dissolve into their own starch. Every province has a version, from plain white breakfast rice to Cantonese pots simmered with pork bone and dried scallop. It is what China eats first thing in the morning, and what it eats when nothing else appeals.",
             tasteNote: "Loose and warm, sliding rather than chewing, barely seasoned until soy and pickles go in, then salty and quietly savory.",
             eaten: "Breakfast, eaten with a flat spoon alongside fried dough sticks and salted vegetables.",
             ingredients: ["short grain rice", "pork bone stock", "ginger", "scallions", "fried dough sticks"],
             tags: ["breakfast", "home", "rice"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 1, herbal: 0, rich: 1),
             palette: "cream"),
        Dish(id: "china-hongshaorou", cuisineID: "china",
             name: "Hong Shao Rou", nativeName: "紅燒肉",
             summary: "Red braised pork belly, made by caramelizing sugar in oil until it turns the color of dark tea, then letting cubes of belly cook down in it with soy, wine and spice until the fat turns translucent. Hunan and Shanghai both claim it, seasoning it differently, and both versions take hours.",
             tasteNote: "Fat that melts before you can chew it, lean meat falling into threads, deep sweet soy and a sticky lacquered coating.",
             eaten: "Served in a small pot with plain rice to cut it, at family dinners and holidays.",
             ingredients: ["pork belly", "rock sugar", "dark soy sauce", "shaoxing wine", "star anise", "ginger"],
             tags: ["braised", "home", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "china-dandanmian", cuisineID: "china",
             name: "Dan Dan Mian", nativeName: "擔擔麵",
             summary: "Chengdu street vendors once carried the whole operation on a shoulder pole, noodles at one end and sauce at the other, which is where the name comes from. The original is a small portion with almost no broth, just chili oil, preserved vegetable and sesame waiting at the bottom of the bowl to be stirred up.",
             tasteNote: "Thin wheat noodles slick with chili oil and sesame paste, salty preserved greens, crunchy pork bits, numbing heat building steadily.",
             eaten: "A small bowl eaten fast with chopsticks at a street stall, stirred hard before the first bite.",
             ingredients: ["wheat noodles", "chili oil", "sesame paste", "ya cai preserved greens", "minced pork", "sichuan peppercorn"],
             tags: ["noodle", "street", "chili"],
             profile: Taste(heat: 3, sour: 1, sweet: 0, savour: 3, herbal: 0, rich: 2),
             palette: "rust"),
        Dish(id: "china-ganbian-sijidou", cuisineID: "china",
             name: "Ganbian Sijidou", nativeName: "乾煸四季豆",
             summary: "Dry frying is a Sichuan method with no sauce and no liquid: green beans go into hot oil until the skins blister and wrinkle and the water inside is driven off. What remains is concentrated. Preserved mustard stem and dried chili go in at the end, so the beans stay the loudest thing on the plate.",
             tasteNote: "Blistered wrinkled skins with a snap underneath, intensely beany, salty from preserved greens, a dry smoky chili heat.",
             eaten: "A shared plate at dinner, eaten with chopsticks and rice, one bean at a time.",
             ingredients: ["green beans", "ya cai preserved greens", "dried chilies", "garlic", "sichuan peppercorn"],
             tags: ["vegetarian", "fried", "home"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 1),
             palette: "herb"),
        Dish(id: "china-tangyuan", cuisineID: "china",
             name: "Tangyuan", nativeName: "湯圓",
             summary: "Glutinous rice flour balls filled with black sesame or peanut paste, floated in a thin sweet ginger or osmanthus soup. They are eaten at the Lantern Festival that closes the new year and at winter solstice, because the round shape and the word for reunion sound close enough to matter.",
             tasteNote: "Stretchy chewy skin giving way to hot dark sesame paste, sweet and slightly oily, in a thin barely sweet broth.",
             eaten: "Eaten with a spoon from a shallow bowl at festival evenings, two or three at a time.",
             ingredients: ["glutinous rice flour", "black sesame paste", "sugar", "ginger", "osmanthus"],
             tags: ["sweet", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "blush"),
    ]

    static let dishes: [Dish] = dishes_japan + dishes_korea + dishes_china
}
