import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentNorthEurope {

    private static let cuisine_poland = Cuisine(
        id: "poland",
        regionID: "north-europe",
        country: "Poland",
        adjective: "Polish",
        tagline: "Sour, smoked and slow, from a country that learned to store the year.",
        summary: "Polish cooking runs on preservation and patience: cabbage soured in barrels, rye left to ferment, meat smoked for the months when nothing grows. The seasoning is quiet, built on dill, marjoram, caraway and sour cream rather than heat. Sunday means one long-simmered pot and a stack of dumplings, and almost every table keeps something pickled within reach.",
        staples: ["rye", "cabbage", "potato", "pork", "sour cream", "dill"],
        techniques: ["souring in brine", "long braising", "smoking over wood"],
        flavourBase: "Sour cream, dill and marjoram over pork fat, with sauerkraut sharpening everything.",
        stampInk: "crimson",
        stampShape: "shield",
        stampMotif: "grain")

    private static let cuisine_sweden = Cuisine(
        id: "sweden",
        regionID: "north-europe",
        country: "Sweden",
        adjective: "Swedish",
        tagline: "Preserved for the dark, sweetened for the light.",
        summary: "Swedish cooking was built for a short summer and a long dark, which is why so much of it is cured, smoked, pickled or preserved in sugar. The palate leans on dill, allspice, cardamom and vinegar, and sweet is allowed to sit beside salt without apology. Coffee and a bun are a fixed institution, not an indulgence.",
        staples: ["potato", "rye", "dill", "cream", "herring", "lingonberry"],
        techniques: ["curing with salt and sugar", "slow simmering", "smoking over alder"],
        flavourBase: "Dill, allspice and vinegar against butter, with berry acidity closing the plate.",
        stampInk: "indigo",
        stampShape: "circle",
        stampMotif: "fish")

    private static let cuisine_hungary = Cuisine(
        id: "hungary",
        regionID: "north-europe",
        country: "Hungary",
        adjective: "Hungarian",
        tagline: "Paprika, fat and onion, worked until they turn red.",
        summary: "Hungarian kitchens are organized around three things: pork fat, onions cooked down slowly, and paprika stirred in off the heat so it never scorches. Almost every savory dish begins that way, then splits into soup, stew or a pan of vegetables. Sour cream cools what paprika warms, and the Great Plain's cattle and river fish still set the menu.",
        staples: ["paprika", "onion", "lard", "sour cream", "pork", "wheat"],
        techniques: ["stewing down onions", "frying in lard", "open-kettle cooking"],
        flavourBase: "Sweet paprika bloomed in fat over onion, cooled by sour cream.",
        stampInk: "rust",
        stampShape: "arch",
        stampMotif: "flame")

    static let cuisines: [Cuisine] = [cuisine_poland, cuisine_sweden, cuisine_hungary]

    private static let dishes_poland: [Dish] = [
        Dish(id: "poland-pierogi-ruskie", cuisineID: "poland",
             name: "Pierogi Ruskie", nativeName: "Pierogi ruskie",
             summary: "Despite the name, these belong to the old Polish-Ruthenian borderlands rather than Russia. Soft wheat dough is filled with potato and farmer's cheese, boiled, then usually finished in butter with onion until the edges catch. They are the dumpling a Polish cook makes when feeding a crowd cheaply, and the one most argued about at family tables.",
             tasteNote: "Slippery, tender dough giving way to a soft salty-sour filling, with sweet fried onion and butter carrying the finish.",
             eaten: "Eaten with a fork at home, six or eight to a plate, with sour cream on the side.",
             ingredients: ["wheat dough", "potato", "farmer's cheese", "onion", "butter"],
             tags: ["dumpling", "vegetarian", "home"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 2, herbal: 1, rich: 2),
             palette: "cream"),
        Dish(id: "poland-bigos", cuisineID: "poland",
             name: "Bigos", nativeName: "Bigos",
             summary: "Hunter's stew, though the hunt is optional. Sauerkraut and fresh cabbage are cooked for hours with whatever meat the house has: pork shoulder, kielbasa, a smoked rib, sometimes prunes and dried mushrooms. It is deliberately made in quantity days ahead, because every reheating deepens it, and it travels from Christmas through the whole cold season.",
             tasteNote: "Soft shreds of cabbage, deeply sour and smoky, with fat-rich meat, a hint of prune sweetness and a long peppery finish.",
             eaten: "Ladled hot from the pot with dark rye bread, at Christmas, after a hunt, or on any winter evening.",
             ingredients: ["sauerkraut", "white cabbage", "pork shoulder", "kielbasa", "dried mushrooms", "prunes"],
             tags: ["braised", "fermented", "feast"],
             profile: Taste(heat: 0, sour: 3, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "poland-zurek", cuisineID: "poland",
             name: "Zurek", nativeName: "Żurek",
             summary: "Soured rye flour and water are left to ferment for days, and that liquid, the zakwas, is the whole point. Thinned with smoked meat stock and white sausage, it becomes a soup with a sharp, almost yogurt-like backbone. Traditionally the first thing eaten on Easter morning, often poured into a hollowed loaf of bread.",
             tasteNote: "Thick and cloudy, tart the way buttermilk is tart, with smoked sausage fat, garlic and marjoram rounding the sourness out.",
             eaten: "Spooned at Easter breakfast, sometimes served inside a bread bowl, with halved boiled egg on top.",
             ingredients: ["rye sourdough starter", "white sausage", "smoked bacon", "boiled egg", "marjoram", "garlic"],
             tags: ["soup", "fermented", "feast"],
             profile: Taste(heat: 0, sour: 3, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "cream"),
        Dish(id: "poland-zapiekanka", cuisineID: "poland",
             name: "Zapiekanka", nativeName: "Zapiekanka",
             summary: "A product of the 1970s, when a halved baguette, mushrooms and cheese were what a state-run snack bar could reliably supply. It is toasted open-faced until the cheese browns, then striped with ketchup. Krakow's round Plac Nowy kiosks turned it into a late-night institution, and the toppings have multiplied ever since.",
             tasteNote: "Crisp-edged bread under molten, slightly rubbery cheese, earthy mushroom beneath, and a sweet-sharp ketchup line cutting through it all.",
             eaten: "Bought from a kiosk window after midnight, wrapped in paper, eaten standing with both hands.",
             ingredients: ["baguette", "button mushrooms", "grated cheese", "onion", "ketchup", "chives"],
             tags: ["street", "bread", "snack"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 3, herbal: 0, rich: 2),
             palette: "amber"),
        Dish(id: "poland-schabowy", cuisineID: "poland",
             name: "Kotlet Schabowy", nativeName: "Kotlet schabowy",
             summary: "The Sunday cutlet: pork loin pounded thin, dragged through flour, egg and breadcrumbs, then fried in enough fat to float. It arrived from Vienna in the nineteenth century and never left, becoming the dish by which a Polish home cook is quietly judged. Potatoes and shredded cabbage salad are not optional.",
             tasteNote: "A dry, crackling crust breaking onto thin, mild pork, with fried butter richness and lemon lifting the last bites.",
             eaten: "Served for Sunday dinner with boiled potatoes, dill and a mound of shredded cabbage salad.",
             ingredients: ["pork loin", "breadcrumbs", "egg", "flour", "lard", "lemon"],
             tags: ["fried", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 2, herbal: 0, rich: 3),
             palette: "ochre"),
        Dish(id: "poland-paczki", cuisineID: "poland",
             name: "Paczki", nativeName: "Pączki",
             summary: "Rich yeast dough, heavy with egg yolks and butter, is fried until a pale ring shows around its middle, the sign of a properly risen paczek. The classic filling is rose petal jam, though plum is common. On Fat Thursday before Lent, bakeries sell them by the million and queues run down the street.",
             tasteNote: "Light and springy rather than heavy, faintly eggy, with a floral jam center and a brittle sugar glaze cracking on top.",
             eaten: "Bought warm by the box on Fat Thursday and eaten by hand with coffee.",
             ingredients: ["yeast dough", "egg yolks", "butter", "rose petal jam", "sugar glaze", "candied orange"],
             tags: ["sweet", "fried", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 2),
             palette: "blush"),
        Dish(id: "poland-sledz", cuisineID: "poland",
             name: "Sledz w Smietanie", nativeName: "Śledź w śmietanie",
             summary: "Baltic herring, salted at sea and soaked back down at home, then dressed in sour cream with raw onion and apple. Cheap protein for centuries of fast days, it survives as the small cold plate that opens a Polish celebration, set out beside bread while the hot food is still on the stove.",
             tasteNote: "Silky, firm fillets, salty and faintly oily, cooled by thick cream, with sharp onion and sweet apple breaking through.",
             eaten: "A cold starter with rye bread, served before the main courses at name days and Christmas Eve.",
             ingredients: ["salted herring", "sour cream", "onion", "apple", "black pepper", "dill"],
             tags: ["seafood", "snack", "home"],
             profile: Taste(heat: 0, sour: 2, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "cream"),
        Dish(id: "poland-oscypek", cuisineID: "poland",
             name: "Oscypek", nativeName: "Oscypek",
             summary: "Up in the Tatra highlands, shepherds press salted sheep's milk curd into carved spindle molds, brine it, then smoke it over pine in the hut rafters. The result is a hard, ridged, straw-colored cheese with protected status. Grilled over coals until it blisters and served with cranberry preserve, it is what you eat walking through Zakopane.",
             tasteNote: "Squeaky and dense at first, then softening to a smoky, salty chew, with tart cranberry cutting the fat.",
             eaten: "Grilled at a mountain stall and eaten hot off a wooden board, with cranberry jam.",
             ingredients: ["sheep's milk", "rennet", "brine", "pine smoke", "cranberry preserve"],
             tags: ["grilled", "street", "dairy"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 3, herbal: 0, rich: 2),
             palette: "saffron"),
    ]

    private static let dishes_sweden: [Dish] = [
        Dish(id: "sweden-kottbullar", cuisineID: "sweden",
             name: "Swedish Meatballs", nativeName: "Köttbullar med gräddsås",
             summary: "Small meatballs of beef and pork bound with milk-soaked breadcrumbs and grated onion, fried in butter and served in a cream gravy built from the same pan. The lingonberry beside them is not a garnish but a corrective, its acidity the reason the plate does not collapse into richness. Everyday food and Sunday food alike.",
             tasteNote: "Soft, almost springy inside, browned outside, in a mild peppery cream sauce with sharp red berries cutting each bite.",
             eaten: "Eaten with fork and knife at home, with boiled potatoes, lingonberry jam and pickled cucumber.",
             ingredients: ["ground beef", "ground pork", "breadcrumbs", "cream", "lingonberry", "allspice"],
             tags: ["home", "fried", "dairy"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 3, herbal: 0, rich: 3),
             palette: "cream"),
        Dish(id: "sweden-gravlax", cuisineID: "sweden",
             name: "Gravlax", nativeName: "Gravad lax",
             summary: "Before refrigeration, salmon was buried, gravad, in sand with salt to ferment through the season. The modern version keeps the name and drops the burial: fillets are packed in salt, sugar and dill for two days under a weight, which firms the flesh without any heat. Nothing is cooked, and nothing needs to be.",
             tasteNote: "Silken, faintly translucent slices, sweet and salty in equal measure, with dill and a mustard sauce that finishes sharp.",
             eaten: "Sliced thin onto a board for Midsummer and Christmas tables, with dark bread and mustard sauce.",
             ingredients: ["salmon fillet", "coarse salt", "sugar", "dill", "white pepper", "mustard sauce"],
             tags: ["raw", "seafood", "feast"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 3, herbal: 3, rich: 2),
             palette: "blush"),
        Dish(id: "sweden-skagen", cuisineID: "sweden",
             name: "Toast Skagen", nativeName: "Toast Skagen",
             summary: "Invented in the 1950s by restaurateur Tore Wretman and named for a Danish fishing town, this is small cold-water shrimp folded into mayonnaise and dill, piled onto bread fried in butter. It became the standard Swedish first course, formal enough for a restaurant and simple enough that any host can produce it.",
             tasteNote: "Crisp buttery toast under a cool, creamy heap of sweet shrimp, with dill, lemon and salty roe popping through.",
             eaten: "A starter before dinner, eaten with knife and fork, often topped with a spoon of roe.",
             ingredients: ["cold-water shrimp", "mayonnaise", "dill", "white bread", "lemon", "bleak roe"],
             tags: ["seafood", "snack", "feast"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 3, herbal: 2, rich: 3),
             palette: "cream"),
        Dish(id: "sweden-artsoppa", cuisineID: "sweden",
             name: "Yellow Pea Soup", nativeName: "Ärtsoppa med fläsk",
             summary: "Yellow peas soaked overnight and simmered with a piece of salted pork until they break down into something between soup and porridge. The Thursday habit is old, reportedly a leftover of pre-Reformation fasting rhythms, and the Swedish armed forces still serve it on that day, followed by thin pancakes.",
             tasteNote: "Thick and mealy, mildly sweet from the peas, salty with pork, and lifted by a stripe of hot mustard.",
             eaten: "Served on Thursdays in a deep bowl with mustard, followed by pancakes and jam.",
             ingredients: ["yellow peas", "salted pork", "onion", "thyme", "marjoram", "mustard"],
             tags: ["soup", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 2, rich: 2),
             palette: "saffron"),
        Dish(id: "sweden-raggmunk", cuisineID: "sweden",
             name: "Raggmunk", nativeName: "Raggmunk",
             summary: "Grated raw potato is stirred into a thin batter of flour, egg and milk, then fried in butter until the starch sets into lace at the edges. The name suggests a shaggy doughnut. It is thrift food from the potato century, and the salt pork and lingonberry alongside are what turn it into dinner.",
             tasteNote: "Crisp brown lace giving onto a soft potato center, buttery and plain, sharpened by tart berries and salty pork.",
             eaten: "A weekday dinner, eaten straight from the skillet with fried pork strips and lingonberry jam.",
             ingredients: ["potato", "flour", "milk", "egg", "butter", "salt pork"],
             tags: ["fried", "home"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 2, herbal: 0, rich: 3),
             palette: "ochre"),
        Dish(id: "sweden-kanelbullar", cuisineID: "sweden",
             name: "Cinnamon Buns", nativeName: "Kanelbullar",
             summary: "Cardamom-scented dough rolled around butter, sugar and cinnamon, cut, twisted or coiled, then baked and finished with pearl sugar. They exist because fika exists: the fixed pause for coffee that structures a Swedish working day. October fourth is officially their day, which tells you how seriously the habit is taken.",
             tasteNote: "Soft and pull-apart, warm with cardamom, buttery cinnamon in the spiral, and crunchy sugar pearls on the crust.",
             eaten: "Eaten by hand at fika, mid-morning or afternoon, with strong coffee, at home or in an office.",
             ingredients: ["wheat flour", "cardamom", "butter", "cinnamon", "pearl sugar", "milk"],
             tags: ["sweet", "vegetarian", "snack"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "sweden-vasterbottenspaj", cuisineID: "sweden",
             name: "Vasterbotten Cheese Pie", nativeName: "Västerbottensostpaj",
             summary: "A short pastry shell filled with egg, cream and grated Vasterbotten, a hard cow's milk cheese made in only one dairy in the north. The pie is the fixed partner to the August crayfish party, cut in wedges and passed around outdoors while the light goes. Sharp cheese, plain pastry, nothing else needed.",
             tasteNote: "Crumbly pastry under a set, custardy filling, intensely salty and nutty from the cheese, with a long savory finish.",
             eaten: "Cut in wedges at the August crayfish party, eaten warm outdoors with dill and cold shrimp.",
             ingredients: ["short pastry", "vasterbotten cheese", "eggs", "cream", "butter", "dill"],
             tags: ["vegetarian", "dairy", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "cream"),
        Dish(id: "sweden-pitepalt", cuisineID: "sweden",
             name: "Pitepalt", nativeName: "Pitepalt",
             summary: "From Pitea in the far north: raw grated potato and barley flour worked into heavy grey dumplings around a nugget of salt pork, then simmered slowly so they hold together. Cold-country food built for a full day of physical work. Leftovers are sliced and fried the next morning, which many people prefer.",
             tasteNote: "Dense and gluey in a way that is the point, mild and starchy, with salty pork fat at the center and butter over the top.",
             eaten: "A winter main course, eaten with butter, lingonberry jam and sometimes a glass of cold milk.",
             ingredients: ["grated potato", "barley flour", "salt pork", "butter", "lingonberry"],
             tags: ["dumpling", "home"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 2, herbal: 0, rich: 2),
             palette: "umber"),
    ]

    private static let dishes_hungary: [Dish] = [
        Dish(id: "hungary-gulyas", cuisineID: "hungary",
             name: "Goulash Soup", nativeName: "Gulyásleves",
             summary: "Cattle herders on the Great Plain cooked this in a kettle over open fire, which is why it is a soup and not the thick stew the word became abroad. Beef, onion, paprika, potato and carrot, with tiny pinched csipetke noodles dropped in near the end. Thin enough to drink, substantial enough to be the meal.",
             tasteNote: "A clear red broth, sweet with onion and paprika, tender beef and soft potato, warm rather than sharply hot.",
             eaten: "Ladled from a kettle at midday, with white bread and a dish of hot paprika paste alongside.",
             ingredients: ["beef shin", "onion", "sweet paprika", "potato", "carrot", "caraway"],
             tags: ["soup", "home", "feast"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "rust"),
        Dish(id: "hungary-porkolt", cuisineID: "hungary",
             name: "Porkolt", nativeName: "Pörkölt",
             summary: "The base dish of the whole cuisine: onions cooked in pork fat until they collapse, paprika stirred off the heat, then meat and almost no liquid, left to give up its own. Beef, pork, chicken or veal all work. Add sour cream and it becomes paprikas; thin it out and it drifts toward goulash soup.",
             tasteNote: "Thick and glossy, deeply savory, with slow onion sweetness, a gentle paprika warmth and beef that pulls apart under the fork.",
             eaten: "A home main course served with small egg dumplings or bread, eaten with a fork any evening.",
             ingredients: ["beef chuck", "onion", "lard", "sweet paprika", "tomato", "green pepper"],
             tags: ["braised", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 0, rich: 3),
             palette: "umber"),
        Dish(id: "hungary-halaszle", cuisineID: "hungary",
             name: "Fisherman's Soup", nativeName: "Halászlé",
             summary: "River fishermen's soup from the Danube and Tisza, built by cooking small bony fish down to a stock, straining it, then poaching carp fillets in that intensely red liquid. Szeged and Baja argue about the correct method, one with pasta in the bowl and one without. It is the Christmas Eve dish in much of the country.",
             tasteNote: "A thin, glowing broth with real paprika bite, clean sweet carp, and a fatty depth from the fish it was built on.",
             eaten: "Served on Christmas Eve from a kettle bowl, with white bread and sometimes noodles underneath.",
             ingredients: ["carp", "small river fish", "onion", "hot paprika", "green pepper", "tomato"],
             tags: ["soup", "seafood", "feast"],
             profile: Taste(heat: 3, sour: 0, sweet: 1, savour: 3, herbal: 0, rich: 2),
             palette: "crimson"),
        Dish(id: "hungary-langos", cuisineID: "hungary",
             name: "Langos", nativeName: "Lángos",
             summary: "Originally baked at the mouth of the bread oven while it heated, hence the name, from lang, flame. Now the dough is stretched by hand and deep fried into a blistered disc, rubbed with garlic, then covered in sour cream and grated cheese. It belongs to markets, thermal baths and Lake Balaton in August.",
             tasteNote: "Chewy and greasy in the good way, blistered and crisp at the rim, cool sour cream against hot garlicky dough.",
             eaten: "Handed over on a paper plate at a market or lakeside stall, eaten folded, standing up.",
             ingredients: ["wheat dough", "potato", "garlic", "sour cream", "grated cheese", "sunflower oil"],
             tags: ["street", "fried", "vegetarian"],
             profile: Taste(heat: 0, sour: 2, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "cream"),
        Dish(id: "hungary-toltott-kaposzta", cuisineID: "hungary",
             name: "Stuffed Cabbage", nativeName: "Töltött káposzta",
             summary: "Sour cabbage leaves wrapped around ground pork and rice, then buried in shredded sauerkraut with smoked ribs and stewed until everything tastes of everything else. It is a Christmas and wedding dish, made in a pot large enough to last several days, and like bigos next door it improves each time it is reheated.",
             tasteNote: "Tender sour leaves around soft, fatty pork and rice, smoky beneath, with sour cream calming the sharp finish.",
             eaten: "Two rolls per plate at Christmas or a wedding, with sour cream and a slice of white bread.",
             ingredients: ["sour cabbage leaves", "ground pork", "rice", "smoked ribs", "sweet paprika", "sour cream"],
             tags: ["feast", "braised", "fermented"],
             profile: Taste(heat: 1, sour: 3, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "umber"),
        Dish(id: "hungary-lecso", cuisineID: "hungary",
             name: "Lecso", nativeName: "Lecsó",
             summary: "High summer, when the pointed white peppers and tomatoes come in together and cost almost nothing. They are stewed down with onion and paprika until they slump into a loose, sweet mass. Eggs stirred through or sausage added turns it into a meal; on its own it is a side, a spread, and a way of storing August.",
             tasteNote: "Soft, silky peppers and collapsed tomato, sweet and slightly smoky, with an oily sheen and a mild paprika hum.",
             eaten: "Cooked in a pan on a summer stove and eaten with fresh bread, often with eggs stirred in.",
             ingredients: ["white wax peppers", "tomato", "onion", "sunflower oil", "sweet paprika", "egg"],
             tags: ["vegetarian", "home", "braised"],
             profile: Taste(heat: 1, sour: 1, sweet: 2, savour: 2, herbal: 0, rich: 2),
             palette: "rust"),
        Dish(id: "hungary-turos-csusza", cuisineID: "hungary",
             name: "Turos Csusza", nativeName: "Túrós csusza",
             summary: "Wide flat noodles tossed with fresh curd cheese, sour cream and crisped pork cracklings, then browned briefly. Sweet and savory sit in the same bowl, which unsettles visitors and bothers no Hungarian. It comes from the same peasant logic as the country's other flour-and-dairy dishes: cheap, filling, and finished in a single pan.",
             tasteNote: "Slippery noodles under cool grainy curd, salty crackling crunch on top, tangy cream and a faint milky sweetness.",
             eaten: "A main course at lunch, eaten with a spoon, sometimes dusted with sugar instead of cracklings.",
             ingredients: ["flat egg noodles", "curd cheese", "sour cream", "pork cracklings", "salt"],
             tags: ["noodle", "home", "dairy"],
             profile: Taste(heat: 0, sour: 2, sweet: 1, savour: 2, herbal: 0, rich: 3),
             palette: "cream"),
        Dish(id: "hungary-dobos", cuisineID: "hungary",
             name: "Dobos Torte", nativeName: "Dobos torta",
             summary: "Jozsef Dobos presented this in 1885: five thin sponge layers with chocolate buttercream between them, sealed under a sheet of hard caramel that was there to keep the cake from drying out on the road. He kept the recipe private for years, then handed it to the pastry guild. The top still cracks under a fork.",
             tasteNote: "Brittle caramel shattering into dense buttercream and dry, fine sponge, with bittersweet chocolate settling over a long burnt-sugar finish.",
             eaten: "A slice with black coffee in an afternoon coffee house, or at a birthday table.",
             ingredients: ["sponge layers", "chocolate buttercream", "butter", "eggs", "caramel", "hazelnut"],
             tags: ["sweet", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 3),
             palette: "char"),
    ]

    static let dishes: [Dish] = dishes_poland + dishes_sweden + dishes_hungary
}
