import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentSoutheastAsia {

    private static let cuisine_thailand = Cuisine(
        id: "thailand",
        regionID: "southeast-asia",
        country: "Thailand",
        adjective: "Thai",
        tagline: "Four tastes argued into balance, then adjusted again at the table.",
        summary: "Thai cooking is built on balance held in tension: hot, sour, salty and sweet pushed against each other in a single mouthful. Fish sauce, lime and chili do the heavy work, while pounding in a stone mortar releases what chopping cannot. Regions differ sharply, from the coconut-rich south to the bitter, fermented north.",
        staples: ["rice", "fish sauce", "coconut milk", "chili", "lime", "galangal"],
        techniques: ["pounding in a stone mortar", "wok frying over high flame", "steaming in banana leaf"],
        flavourBase: "Fish sauce, lime and chili, held against palm sugar until nothing dominates.",
        stampInk: "ochre",
        stampShape: "arch",
        stampMotif: "flame")

    private static let cuisine_vietnam = Cuisine(
        id: "vietnam",
        regionID: "southeast-asia",
        country: "Vietnam",
        adjective: "Vietnamese",
        tagline: "Clear broths, raw herbs, and nothing finished before it reaches you.",
        summary: "Vietnamese kitchens lean on freshness rather than fat. Broths are simmered long and skimmed clear, then met at the table by raw herbs, lettuce and lime that each eater adds by hand. French bread and coffee were absorbed and rebuilt to local taste. Fish sauce carries the salt, and almost nothing arrives already seasoned to its end.",
        staples: ["rice", "fish sauce", "fresh herbs", "rice noodles", "lime"],
        techniques: ["simmering broth clear", "charcoal grilling", "rolling in rice paper"],
        flavourBase: "Nuoc cham: fish sauce, lime, sugar and chili, loosened with water.",
        stampInk: "teal",
        stampShape: "oval",
        stampMotif: "leaf")

    private static let cuisine_indonesia = Cuisine(
        id: "indonesia",
        regionID: "southeast-asia",
        country: "Indonesia",
        adjective: "Indonesian",
        tagline: "Coconut, chili and palm sugar across a thousand island kitchens.",
        summary: "Seventeen thousand islands do not share one kitchen, but they share a pantry: coconut, chili, palm sugar, tamarind and a ground spice paste called bumbu that starts nearly every pot. Cooking is slow where it needs to be, letting coconut milk break down into oil and crust. Sweet, salty and hot sit very close together.",
        staples: ["rice", "coconut milk", "chili", "palm sugar", "shrimp paste", "tamarind"],
        techniques: ["grinding bumbu spice paste", "reducing slowly in coconut milk", "grilling over coconut husk"],
        flavourBase: "Bumbu paste, coconut and palm sugar, with sambal sharpening the edges.",
        stampInk: "rust",
        stampShape: "scallop",
        stampMotif: "wave")

    static let cuisines: [Cuisine] = [cuisine_thailand, cuisine_vietnam, cuisine_indonesia]

    private static let dishes_thailand: [Dish] = [
        Dish(id: "thailand-padthai", cuisineID: "thailand",
             name: "Pad Thai", nativeName: "ผัดไทย",
             summary: "A wok noodle dish promoted in the 1930s and 40s as national food, when the government pushed rice noodles to save whole grain rice and give the country a dish of its own. Tamarind, palm sugar and fish sauce make the sauce; everything else is negotiable.",
             tasteNote: "Soft, springy noodles with a faint chew, sour tamarind and palm sugar up front, peanut grit and a dry, salty finish.",
             eaten: "Eaten with fork and spoon from a street cart plate, lime and chili flakes added yourself.",
             ingredients: ["rice noodles", "tamarind paste", "palm sugar", "fish sauce", "dried shrimp", "crushed peanuts"],
             tags: ["street", "noodle", "fried"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 3, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "thailand-tomyum", cuisineID: "thailand",
             name: "Tom Yum Goong", nativeName: "ต้มยำกุ้ง",
             summary: "Central Thailand's argument for sourness as a structure rather than an accent. Lemongrass, galangal and kaffir lime leaf are bruised and dropped in whole, meant to be pushed aside instead of eaten. The clear version is older; the cloudy one thickened with evaporated milk came later and now outsells it.",
             tasteNote: "Thin, scalding broth that hits sour and hot at once, prawn sweetness underneath, and a long citrus-oil burn that keeps going.",
             eaten: "Ladled into small bowls beside shared rice at lunch, spoon only, alongside several other dishes.",
             ingredients: ["prawns", "lemongrass", "galangal", "kaffir lime leaves", "bird's eye chili", "fish sauce"],
             tags: ["soup", "seafood", "chili"],
             profile: Taste(heat: 3, sour: 3, sweet: 1, savour: 3, herbal: 3, rich: 1),
             palette: "crimson"),
        Dish(id: "thailand-somtam", cuisineID: "thailand",
             name: "Som Tam", nativeName: "ส้มตำ",
             summary: "Green papaya shredded into threads and bruised in a clay mortar with garlic, chili, lime and fish sauce. It came west from Isan and Laos with migrant workers and became the country's default hot-weather food. The pounding is the cooking; nothing here ever meets heat.",
             tasteNote: "Crisp wet shreds that stay crunchy, sharp lime and raw garlic, salt from dried shrimp, and chili that arrives late and stays.",
             eaten: "Torn sticky rice in hand, shared with grilled chicken, usually late morning or as an afternoon snack.",
             ingredients: ["green papaya", "lime", "bird's eye chili", "fish sauce", "dried shrimp", "long beans"],
             tags: ["street", "raw", "chili"],
             profile: Taste(heat: 3, sour: 3, sweet: 1, savour: 3, herbal: 1, rich: 0),
             palette: "herb"),
        Dish(id: "thailand-massaman", cuisineID: "thailand",
             name: "Massaman Curry", nativeName: "แกงมัสมั่น",
             summary: "Persian and Indian traders left cardamom, cinnamon and cloves in the southern ports, and Thai cooks folded them into a coconut curry unlike any other here. It is slow, mild and slightly sweet, closer to a braise than a curry, and it turns up at weddings and holidays.",
             tasteNote: "Thick and heavy, potatoes collapsing, warm dry spice riding over coconut fat, gentle sweetness, only the faintest heat at the back.",
             eaten: "Spooned over rice at a family table, often at celebrations, eaten slowly with a spoon.",
             ingredients: ["beef shin", "coconut milk", "massaman paste", "potatoes", "tamarind", "roasted peanuts"],
             tags: ["braised", "feast", "rice"],
             profile: Taste(heat: 1, sour: 1, sweet: 2, savour: 3, herbal: 1, rich: 3),
             palette: "rust"),
        Dish(id: "thailand-khaosoi", cuisineID: "thailand",
             name: "Khao Soi", nativeName: "ข้าวซอย",
             summary: "Chiang Mai's coconut curry noodle, carried down old caravan routes by Yunnanese Muslim traders. Soft egg noodles sit in the bowl and a tangle of the same noodles is fried crisp and dropped on top, so the texture keeps changing as you work through it.",
             tasteNote: "Silky curry broth with turmeric warmth, soft noodles below and shattering fried ones above, pickled mustard cutting the coconut fat.",
             eaten: "A lunch bowl in the north, eaten with chopsticks and spoon, lime and shallots on the side.",
             ingredients: ["egg noodles", "coconut milk", "khao soi curry paste", "chicken", "pickled mustard greens", "shallots"],
             tags: ["noodle", "soup", "street"],
             profile: Taste(heat: 2, sour: 1, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "saffron"),
        Dish(id: "thailand-mooping", cuisineID: "thailand",
             name: "Moo Ping", nativeName: "หมูปิ้ง",
             summary: "Pork shoulder marinated overnight in coconut milk, garlic root and white pepper, then threaded onto bamboo and grilled over coals at dawn. Sold outside markets and school gates, it is breakfast for anyone heading to work, handed over in a plastic bag with sticky rice.",
             tasteNote: "Charred edges giving way to soft fatty pork, sweet and salty at once, coconut and pepper trailing behind the smoke.",
             eaten: "Bought hot off the grill in the morning, eaten straight from the stick while walking.",
             ingredients: ["pork shoulder", "coconut milk", "garlic", "white pepper", "palm sugar", "light soy"],
             tags: ["street", "grilled", "breakfast"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "thailand-hormok", cuisineID: "thailand",
             name: "Hor Mok", nativeName: "ห่อหมก",
             summary: "A steamed curry custard, not a curry at all in texture. Fish is folded with red curry paste, coconut cream and egg, then set inside a pinned banana leaf cup until it holds like a soft mousse. Older cooks judge each other on whether it wobbles correctly.",
             tasteNote: "Loose and trembling, spooned rather than cut, coconut sweetness ahead of a slow chili warmth, with basil and lime leaf behind.",
             eaten: "Opened at the table from its leaf cup with a spoon, part of a shared rice meal.",
             ingredients: ["white fish", "red curry paste", "coconut cream", "egg", "kaffir lime leaves", "thai basil"],
             tags: ["seafood", "feast", "home"],
             profile: Taste(heat: 2, sour: 0, sweet: 1, savour: 3, herbal: 2, rich: 3),
             palette: "ochre"),
        Dish(id: "thailand-mangosticky", cuisineID: "thailand",
             name: "Mango Sticky Rice", nativeName: "ข้าวเหนียวมะม่วง",
             summary: "Sticky rice is steamed, then soaked warm in salted coconut cream so it stops being plain starch and turns into something closer to a pudding. It arrives with ripe mango only during the short season when the fruit is worth eating, which is most of the point.",
             tasteNote: "Warm chewy grains against cold soft fruit, coconut salt against mango sugar, thick and clean rather than heavy.",
             eaten: "A late afternoon sweet eaten with a spoon, sold in season from carts and market stalls.",
             ingredients: ["glutinous rice", "coconut cream", "palm sugar", "salt", "ripe mango", "mung beans"],
             tags: ["sweet", "street", "vegetarian"],
             profile: Taste(heat: 0, sour: 1, sweet: 3, savour: 1, herbal: 0, rich: 2),
             palette: "cream"),
    ]

    private static let dishes_vietnam: [Dish] = [
        Dish(id: "vietnam-pho", cuisineID: "vietnam",
             name: "Pho Bo", nativeName: "Phở bò",
             summary: "Northern in origin, born around Hanoi in the early twentieth century, when French demand for beef left bones that local cooks could use. Charred ginger and onion, star anise and cassia go into water for hours. The test of a good bowl is whether the broth stays clear.",
             tasteNote: "Clean hot broth with sweet spice underneath, slippery flat noodles, thin beef turning grey as it cooks in the bowl.",
             eaten: "A breakfast bowl eaten with chopsticks and spoon, herbs and lime added by hand at the table.",
             ingredients: ["beef bones", "rice noodles", "star anise", "cassia bark", "fish sauce", "spring onion"],
             tags: ["noodle", "soup", "breakfast"],
             profile: Taste(heat: 0, sour: 1, sweet: 1, savour: 3, herbal: 2, rich: 2),
             palette: "umber"),
        Dish(id: "vietnam-banhmi", cuisineID: "vietnam",
             name: "Banh Mi", nativeName: "Bánh mì",
             summary: "The colonial baguette was rebuilt with rice flour, so the crust shatters and the crumb stays light enough to compress in one hand. Pate and mayonnaise stayed from the French side; pickled carrot, cilantro and chili came from the Vietnamese one. Fillings change by city and by cart.",
             tasteNote: "Crackling crust, soft interior, cool sharp pickle against warm fatty pate, cilantro cutting through, chili arriving at the end.",
             eaten: "Handed over in paper and eaten while walking, most often in the morning or mid afternoon.",
             ingredients: ["rice flour baguette", "pork pate", "cold cuts", "pickled daikon and carrot", "cilantro", "chili"],
             tags: ["street", "bread", "snack"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 3, herbal: 2, rich: 2),
             palette: "cream"),
        Dish(id: "vietnam-buncha", cuisineID: "vietnam",
             name: "Bun Cha", nativeName: "Bún chả",
             summary: "Hanoi's lunch: pork patties and belly slices grilled over charcoal, then dropped into a warm bowl of diluted fish sauce with green papaya floating in it. Noodles and herbs sit dry on the side and you move them across yourself, dipping rather than pouring.",
             tasteNote: "Smoky pork fat loosening into a thin sweet-salty dip, cold noodles, raw herbs, and a soft sourness under everything.",
             eaten: "Lunch only, at low plastic tables, dipping noodles and herbs into the bowl with chopsticks.",
             ingredients: ["pork belly", "ground pork", "fish sauce", "rice vinegar", "green papaya", "rice vermicelli"],
             tags: ["grilled", "noodle", "street"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 3, herbal: 3, rich: 2),
             palette: "amber"),
        Dish(id: "vietnam-goicuon", cuisineID: "vietnam",
             name: "Goi Cuon", nativeName: "Gỏi cuốn",
             summary: "Rice paper softened in water and rolled around poached pork, shrimp, noodles and whole lettuce leaves, with nothing cooked at the moment of assembly. It is often built at the table by whoever is eating. The roll is deliberately plain; the peanut and hoisin sauce carries it.",
             tasteNote: "Cool and slippery, mild sweet shrimp and soft noodle, herbs sharpening each bite, thick nutty sauce doing the seasoning.",
             eaten: "Dipped whole into peanut sauce and eaten by hand, usually as a light shared starter.",
             ingredients: ["rice paper", "poached shrimp", "pork belly", "rice vermicelli", "mint and perilla", "peanut sauce"],
             tags: ["raw", "snack", "seafood"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 2, herbal: 3, rich: 1),
             palette: "jade"),
        Dish(id: "vietnam-comtam", cuisineID: "vietnam",
             name: "Com Tam", nativeName: "Cơm tấm",
             summary: "Built on broken rice, the fractured grains once sold cheap because millers counted them as rejects. Saigon workers ate them under a grilled pork chop, and the dish stayed even after the rice stopped being a bargain. Shredded pork skin and a steamed egg loaf usually come alongside.",
             tasteNote: "Small dry grains that stay separate, charred sweet pork edges, salty scallion oil, and thin sharp fish sauce over everything.",
             eaten: "A single plate meal with fork and spoon, eaten at any hour, with pickles and a bowl of broth.",
             ingredients: ["broken rice", "grilled pork chop", "scallion oil", "shredded pork skin", "nuoc cham", "pickled vegetables"],
             tags: ["rice", "grilled", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 3, herbal: 1, rich: 2),
             palette: "ochre"),
        Dish(id: "vietnam-banhxeo", cuisineID: "vietnam",
             name: "Banh Xeo", nativeName: "Bánh xèo",
             summary: "A rice flour and turmeric batter poured into a screaming hot pan so it sets thin and lacy, then folded over pork, shrimp and bean sprouts. The name comes from the hiss it makes going in. Southern cooks make them huge; in the center they stay small.",
             tasteNote: "Brittle golden edges, soft steamy center, sweet shrimp and crunchy sprouts, all of it wrapped in cool leaves before it reaches you.",
             eaten: "Torn apart, wrapped in mustard leaf and herbs, dipped in nuoc cham, shared at dinner.",
             ingredients: ["rice flour", "turmeric", "coconut milk", "pork belly", "shrimp", "bean sprouts"],
             tags: ["fried", "street", "seafood"],
             profile: Taste(heat: 1, sour: 1, sweet: 1, savour: 2, herbal: 3, rich: 2),
             palette: "saffron"),
        Dish(id: "vietnam-dauhu", cuisineID: "vietnam",
             name: "Tofu in Tomato Sauce", nativeName: "Đậu hũ sốt cà chua",
             summary: "One of the plainest things on a Vietnamese home table and one of the most common. Fried tofu cubes are simmered briefly in tomato with scallion and seasoned with a little fish sauce, or with salt and soy in Buddhist households. It exists to be eaten with rice.",
             tasteNote: "Spongy fried skin soaking up thin sweet tomato, soft custardy inside, mild and salty with almost no heat.",
             eaten: "One of three or four dishes at a family dinner, spooned over rice from a shared bowl.",
             ingredients: ["firm tofu", "ripe tomatoes", "scallion", "garlic", "soy sauce", "white pepper"],
             tags: ["home", "vegetarian", "fried"],
             profile: Taste(heat: 0, sour: 2, sweet: 1, savour: 2, herbal: 1, rich: 1),
             palette: "rust"),
        Dish(id: "vietnam-chetroinuoc", cuisineID: "vietnam",
             name: "Che Troi Nuoc", nativeName: "Chè trôi nước",
             summary: "Glutinous rice balls filled with sweetened mung bean, floated in ginger syrup and finished with coconut cream. They are made for Tet Han Thuc and other family occasions, when the round shape and the floating are read as a wish for things to settle and go smoothly.",
             tasteNote: "Chewy elastic skin that pulls, soft sweet bean center, hot ginger syrup thinning into coconut across the tongue.",
             eaten: "Served warm in a small glass with a spoon, at festivals and after family meals.",
             ingredients: ["glutinous rice flour", "mung beans", "fresh ginger", "palm sugar", "coconut cream", "sesame seeds"],
             tags: ["sweet", "feast", "vegetarian"],
             profile: Taste(heat: 1, sour: 0, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "blush"),
    ]

    private static let dishes_indonesia: [Dish] = [
        Dish(id: "indonesia-nasigoreng", cuisineID: "indonesia",
             name: "Nasi Goreng", nativeName: "Nasi goreng",
             summary: "Yesterday's rice fried hard in a wok with sweet soy and chili paste, originally a way to use cold rice before refrigeration and before the heat turned it sour. Carts push it through neighborhoods at night, announced by a metal spoon tapped against the side of a pan.",
             tasteNote: "Dry separate grains carrying smoke and caramelized sweet soy, salty shrimp paste underneath, a runny egg yolk softening all of it.",
             eaten: "Late at night from a street cart or first thing at breakfast, with prawn crackers.",
             ingredients: ["day-old rice", "kecap manis", "shallots", "garlic", "shrimp paste", "bird's eye chili"],
             tags: ["street", "rice", "fried"],
             profile: Taste(heat: 2, sour: 0, sweet: 2, savour: 3, herbal: 0, rich: 2),
             palette: "umber"),
        Dish(id: "indonesia-rendang", cuisineID: "indonesia",
             name: "Rendang", nativeName: "Rendang",
             summary: "Minangkabau cooking taken to its conclusion: beef simmered in coconut milk and spice paste for hours until the liquid goes, the coconut oil separates, and the meat fries in whatever is left. Dry rendang keeps for weeks without cooling, which is exactly why it travelled so far.",
             tasteNote: "Dense dark shreds that fall apart under a fork, deep toasted coconut and galangal, slow building heat, oily and intensely savory.",
             eaten: "Served at weddings and Lebaran with rice, taken in small amounts because it is strong.",
             ingredients: ["beef chuck", "coconut milk", "galangal", "lemongrass", "dried chilies", "turmeric leaf"],
             tags: ["braised", "feast", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 1, savour: 3, herbal: 2, rich: 3),
             palette: "char"),
        Dish(id: "indonesia-sateayam", cuisineID: "indonesia",
             name: "Sate Ayam", nativeName: "Sate ayam",
             summary: "Skewered chicken grilled over coconut husk charcoal and buried in peanut sauce thinned with sweet soy. Java made it ordinary, traders from the Arab and Indian routes probably brought the idea of meat on sticks, and every region since has argued about the sauce.",
             tasteNote: "Smoky charred edges, soft chicken, thick sweet peanut sauce clinging to it, lime and raw shallot lifting the last bites.",
             eaten: "Ten sticks to a portion with pressed rice cakes, eaten with fingers at an evening grill.",
             ingredients: ["chicken thigh", "peanuts", "kecap manis", "candlenut", "lime", "shallots"],
             tags: ["grilled", "street", "snack"],
             profile: Taste(heat: 1, sour: 1, sweet: 3, savour: 3, herbal: 0, rich: 2),
             palette: "rust"),
        Dish(id: "indonesia-gadogado", cuisineID: "indonesia",
             name: "Gado-Gado", nativeName: "Gado-gado",
             summary: "Blanched vegetables, tofu, tempeh and egg under a thick peanut sauce ground in a stone mortar. The name means roughly mix-mix. It reads as a salad but nothing in it stays raw for long, and the sauce is the actual dish; the rest is structure to hold it.",
             tasteNote: "Warm soft vegetables and firm tofu under a heavy nut sauce, sweet then salty, crackers snapping on top.",
             eaten: "A lunch plate eaten with a spoon, the sauce poured over just before it reaches the table.",
             ingredients: ["long beans", "cabbage", "bean sprouts", "tempeh", "boiled egg", "peanut sauce"],
             tags: ["vegetarian", "home", "snack"],
             profile: Taste(heat: 1, sour: 1, sweet: 2, savour: 2, herbal: 0, rich: 3),
             palette: "herb"),
        Dish(id: "indonesia-sotoayam", cuisineID: "indonesia",
             name: "Soto Ayam", nativeName: "Soto ayam",
             summary: "A turmeric chicken broth found in dozens of local versions across Java and beyond, each town insisting on its own. The base is aromatic rather than heavy, and the bowl gets assembled from parts kept separate until serving: noodles, shredded chicken, egg, fried shallots, a wedge of lime.",
             tasteNote: "Clear yellow broth, warm with turmeric and lemongrass, thin glass noodles slipping past, fried shallot sweetness on top, lime sharpening the end.",
             eaten: "Breakfast or a light lunch, spoon and fork, with rice and sambal set alongside.",
             ingredients: ["chicken", "turmeric", "lemongrass", "glass noodles", "fried shallots", "lime"],
             tags: ["soup", "breakfast", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 3, herbal: 2, rich: 1),
             palette: "saffron"),
        Dish(id: "indonesia-tumpeng", cuisineID: "indonesia",
             name: "Nasi Tumpeng", nativeName: "Nasi tumpeng",
             summary: "A cone of turmeric coconut rice standing on a round tray, ringed by side dishes and built for birthdays, house moves and thanksgivings. The cone points up because it once stood for a mountain. Whoever is being honored cuts the tip and hands it to someone they respect.",
             tasteNote: "Fragrant coconut rice, faintly sweet and salty, eaten against fried chicken, spiced tempeh and hot sambal all at once.",
             eaten: "Cut at the table on a leaf-lined tray and shared by hand at family celebrations.",
             ingredients: ["rice", "coconut milk", "turmeric", "pandan leaf", "lemongrass", "fried shallots"],
             tags: ["feast", "rice", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 2, herbal: 2, rich: 2),
             palette: "ochre"),
        Dish(id: "indonesia-klepon", cuisineID: "indonesia",
             name: "Klepon", nativeName: "Klepon",
             summary: "Green rice flour balls colored with pandan, each hiding a lump of palm sugar that liquefies in the steamer. They are rolled in grated coconut and eaten at room temperature. The point is the moment they burst, which is why nobody bites one in half.",
             tasteNote: "Soft chewy skin, dry coconut on the outside, then hot dark sugar releasing all at once and coating the mouth.",
             eaten: "Bought by the box from morning markets, eaten whole with fingers as a mid-morning snack.",
             ingredients: ["glutinous rice flour", "pandan", "palm sugar", "grated coconut", "salt", "tapioca starch"],
             tags: ["sweet", "snack", "vegetarian"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 1, herbal: 1, rich: 1),
             palette: "jade"),
        Dish(id: "indonesia-pempek", cuisineID: "indonesia",
             name: "Pempek", nativeName: "Pempek",
             summary: "Palembang's fish and sago cakes, boiled first and then fried, served in a black vinegar and palm sugar sauce called cuko that is aggressively sour. The sago gives them a dense bounce that surprises anyone expecting a soft fish cake. Common across South Sumatra, rare anywhere else.",
             tasteNote: "Springy, almost rubbery bite inside a crisp fried shell, then a thin sour-sweet sauce that stings with chili and garlic.",
             eaten: "Cut up in a bowl with the sauce poured over, eaten with a fork in the afternoon.",
             ingredients: ["spanish mackerel", "sago flour", "palm sugar", "tamarind", "garlic", "bird's eye chili"],
             tags: ["fried", "seafood", "street"],
             profile: Taste(heat: 2, sour: 3, sweet: 2, savour: 3, herbal: 0, rich: 2),
             palette: "amber"),
    ]

    static let dishes: [Dish] = dishes_thailand + dishes_vietnam + dishes_indonesia
}
