import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesAfrica {

    private static let recipes_morocco: [Recipe] = [
        Recipe(dishID: "morocco-lamb-tagine", serves: 4, prepMinutes: 20, cookMinutes: 150, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "boneless lamb shoulder, cut into 2-inch chunks"),
                   RecipeIngredient(amount: "2", item: "yellow onions, thinly sliced"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "ground ginger"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "1/2 tsp", item: "turmeric"),
                   RecipeIngredient(amount: "a pinch", item: "saffron threads (or 1/4 tsp more turmeric)"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "1 cup", item: "pitted prunes"),
                   RecipeIngredient(amount: "2 tbsp", item: "honey"),
                   RecipeIngredient(amount: "1/2 cup", item: "toasted slivered almonds"),
                   RecipeIngredient(amount: "2 cups", item: "water"),
               ],
               steps: [
                   "Toss the lamb with the ginger, cinnamon, turmeric, saffron, salt, and pepper in a bowl until every piece is coated in the rust-colored spice paste.",
                   "Warm the olive oil in a Dutch oven over medium heat and soften half the sliced onions for 5 minutes, then nestle the lamb on top in one layer.",
                   "Scatter the remaining onions over the meat, pour in the water, and bring to a bare simmer. Cover and cook over low heat for 2 hours, turning the lamb once.",
                   "While the lamb cooks, simmer the prunes in a small pan with the honey, a ladle of the braising liquid, and a pinch of cinnamon for 15 minutes, until glossy and swollen.",
                   "Uncover the pot for the last 20 minutes so the sauce reduces until it coats a spoon; the onions should have melted into it completely.",
                   "Check the lamb with a fork; it should pull apart with no resistance. Taste the sauce and adjust the salt.",
                   "Pile the lamb onto a warm platter, spoon the honeyed prunes and their syrup over the top, and finish with the toasted almonds. Serve with crusty bread, not utensils.",
               ],
               note: "The onions must cook down to an invisible silk that thickens the sauce; if you can still see onion slices at the end, keep simmering uncovered.",
               shortcut: "A 3.5-quart slow cooker on low for 7 hours works; you lose the reduced, sticky sauce, so simmer the liquid down in a pan before serving."),
        Recipe(dishID: "morocco-couscous", serves: 6, prepMinutes: 30, cookMinutes: 60, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "couscous"),
                   RecipeIngredient(amount: "1 can (15 oz)", item: "chickpeas, drained"),
                   RecipeIngredient(amount: "1 lb", item: "butternut squash, peeled and cut into big wedges"),
                   RecipeIngredient(amount: "3", item: "carrots, halved lengthwise"),
                   RecipeIngredient(amount: "2", item: "turnips, quartered"),
                   RecipeIngredient(amount: "2", item: "zucchini, cut into thick batons"),
                   RecipeIngredient(amount: "1/4", item: "green cabbage, in two wedges"),
                   RecipeIngredient(amount: "1", item: "yellow onion, quartered"),
                   RecipeIngredient(amount: "2", item: "tomatoes, quartered"),
                   RecipeIngredient(amount: "a pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "1 tsp", item: "ground ginger"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
               ],
               steps: [
                   "Put the onion, tomatoes, olive oil, saffron, ginger, salt, and 8 cups of water in a large pot. Bring to a boil and simmer 15 minutes to make the broth.",
                   "Add the carrots, turnips, and cabbage to the broth and simmer 15 minutes; they cook longest because they go in firmest.",
                   "Add the squash, zucchini, and chickpeas and simmer another 20 minutes, until a knife slides into every vegetable without pressure but nothing is collapsing.",
                   "Meanwhile put the couscous in a wide bowl, stir in 2 cups of hot broth ladled from the pot, cover, and let it swell for 10 minutes.",
                   "Rake the couscous with a fork, rub in the butter with your fingertips until no lumps remain, and season with a little salt.",
                   "Taste the broth; it should be golden and gently savory. Add salt until it tastes like something you would sip on its own.",
                   "Mound the couscous on a wide platter, make a well, arrange the vegetables in the well, and ladle broth generously over everything. Pass extra broth at the table.",
               ],
               note: "The broth is the dish; vegetables and grain are only as good as the saffron liquid you pour over them at the end, so season it fearlessly.",
               shortcut: "Instant couscous soaked in broth skips traditional triple steaming; the grains are slightly less fluffy but the difference disappears under a ladle of broth."),
        Recipe(dishID: "morocco-harira", serves: 6, prepMinutes: 20, cookMinutes: 60, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3/4 cup", item: "brown or green lentils"),
                   RecipeIngredient(amount: "1 can (15 oz)", item: "chickpeas, drained"),
                   RecipeIngredient(amount: "1 can (28 oz)", item: "crushed tomatoes"),
                   RecipeIngredient(amount: "1", item: "yellow onion, finely chopped"),
                   RecipeIngredient(amount: "2 stalks", item: "celery with leaves, finely chopped"),
                   RecipeIngredient(amount: "1 cup", item: "chopped fresh cilantro"),
                   RecipeIngredient(amount: "1/2 cup", item: "chopped fresh parsley"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1 tsp", item: "ground ginger"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "3 tbsp", item: "all-purpose flour"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "lemon, in wedges"),
               ],
               steps: [
                   "Warm the olive oil in a soup pot over medium heat and cook the onion and celery with the ginger, cinnamon, and salt until soft and fragrant, about 8 minutes.",
                   "Stir in the tomato paste and cook 2 minutes until it darkens a shade, then add the crushed tomatoes and half the cilantro and parsley.",
                   "Add the lentils and 8 cups of water, bring to a boil, then simmer uncovered for 35 minutes, until the lentils are fully tender.",
                   "Add the chickpeas and simmer 10 more minutes so they take on the broth's flavor.",
                   "Whisk the flour into 1 cup of cold water until smooth, then pour it into the soup in a thin stream, stirring constantly.",
                   "Simmer 10 minutes more, stirring often, until the soup turns silky and coats the back of the spoon; it should pour like heavy cream, not porridge.",
                   "Stir in the remaining herbs, taste for salt, and serve hot with lemon wedges and, if you want the full sunset table, dates on the side.",
               ],
               note: "The flour slurry is what makes harira harira; add it slowly while stirring or you get dumplings, and let it cook out so no raw-flour taste remains.",
               shortcut: "Skip the slurry and blend two ladles of the finished soup instead; the texture is close, though you lose the classic velvety sheen."),
        Recipe(dishID: "morocco-bastilla", serves: 6, prepMinutes: 50, cookMinutes: 75, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "phyllo dough, thawed (stands in for warqa)"),
                   RecipeIngredient(amount: "2 lb", item: "boneless chicken thighs"),
                   RecipeIngredient(amount: "2", item: "yellow onions, grated"),
                   RecipeIngredient(amount: "4", item: "eggs, beaten"),
                   RecipeIngredient(amount: "2 tsp", item: "ground cinnamon, plus more for dusting"),
                   RecipeIngredient(amount: "1 tsp", item: "ground ginger"),
                   RecipeIngredient(amount: "a pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "1/2 cup", item: "chopped cilantro and parsley"),
                   RecipeIngredient(amount: "10 tbsp", item: "butter, melted"),
                   RecipeIngredient(amount: "1 cup", item: "sliced almonds"),
                   RecipeIngredient(amount: "3 tbsp", item: "powdered sugar, plus more for dusting"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Simmer the chicken with the onions, 1 teaspoon cinnamon, ginger, saffron, salt, 2 tablespoons butter, and 1 cup water, covered, for 35 minutes, until the meat shreds easily. Lift out the chicken and shred it.",
                   "Boil the cooking liquid hard until only about a cup remains, lower the heat, and stir in the beaten eggs and herbs. Cook gently, stirring, until the mixture sets into soft, wet curds.",
                   "Toast the almonds in a dry skillet until golden, then crush them roughly and mix with the powdered sugar and remaining teaspoon of cinnamon.",
                   "Brush a 10-inch round pan with butter. Layer in 6 phyllo sheets, buttering each, letting the edges hang over the sides like petals.",
                   "Spread the egg mixture over the base, then the shredded chicken, then the sweet almonds. Fold the overhanging phyllo over the top and cap with 4 more buttered sheets, tucking the edges under.",
                   "Bake at 375°F for 35 to 40 minutes, until deep golden and crisp; a skewer through the center should come out hot.",
                   "Slide onto a platter, dust generously with powdered sugar, and draw a lattice over it with pinches of cinnamon. Cut at the table and eat while the pastry still shatters.",
               ],
               note: "Reduce the braising liquid until almost sticky before adding the eggs; a wet filling turns the bottom crust to paper mache within minutes of baking.",
               shortcut: "Rotisserie chicken saves the braise; simmer the onions and spices in 1 cup of stock first so the filling still tastes like Morocco, not the deli counter."),
        Recipe(dishID: "morocco-msemen", serves: 4, prepMinutes: 45, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/2 cup", item: "fine semolina, plus more for sprinkling"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "about 1 cup", item: "warm water"),
                   RecipeIngredient(amount: "6 tbsp", item: "butter, melted"),
                   RecipeIngredient(amount: "1/4 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "1/2 cup", item: "honey, for serving"),
               ],
               steps: [
                   "Mix the flour, semolina, salt, and sugar, then add warm water a splash at a time until you have a soft, smooth dough. Knead 10 minutes until it stretches without tearing.",
                   "Divide into 8 balls, coat them in oil, and rest 15 minutes; the rest is what lets you stretch them paper thin later.",
                   "Oil your counter and hands. Flatten one ball and stretch it outward from the center until it is a near-transparent sheet, patching any small tears without worry.",
                   "Drizzle the sheet with melted butter and a pinch of semolina, fold the sides in to make a square, and set aside. Repeat with the rest.",
                   "Heat a dry skillet over medium heat. Flatten each square gently with your palms and cook 2 to 3 minutes per side, until blistered with deep golden spots.",
                   "Press the edges down with a spatula as they cook so the layers inside steam and separate.",
                   "Warm equal parts honey and butter until pourable. Serve the msemen hot, torn by hand and dipped, with mint tea if you have it.",
               ],
               note: "The dough must be softer than feels right and the counter well oiled; a stiff dough will never stretch thin enough to give you flaky layers.",
               shortcut: "A stand mixer with a dough hook does the 10-minute knead in 5; hand-stretching is the one step with no substitute."),
        Recipe(dishID: "morocco-sardines", serves: 4, prepMinutes: 25, cookMinutes: 10, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "fresh sardines, butterflied (ask the fish counter)"),
                   RecipeIngredient(amount: "1 cup", item: "cilantro leaves"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic"),
                   RecipeIngredient(amount: "2 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "2 tsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1/2 tsp", item: "cayenne"),
                   RecipeIngredient(amount: "1", item: "lemon, juiced, plus wedges to serve"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/2 cup", item: "vegetable oil, for shallow frying"),
               ],
               steps: [
                   "Blend the cilantro, garlic, cumin, paprika, cayenne, lemon juice, olive oil, and salt into a loose green paste; this is the chermoula.",
                   "Pat the butterflied sardines dry and smear chermoula over the flesh side of each one.",
                   "Sandwich the sardines in pairs, flesh sides together with the paste in the middle, and press gently so they hold.",
                   "Chill the pairs for 15 minutes so the marinade grips and the sandwiches firm up.",
                   "Heat the vegetable oil in a wide skillet over medium-high until a pinch of flour sizzles on contact.",
                   "Dredge each sardine pair lightly in flour, shake off the excess, and fry 2 to 3 minutes per side, until the crust is deep gold and the edges crisp.",
                   "Drain on paper for a minute, shower with salt, and eat hot with bread and lemon wedges, standing up if you want authenticity.",
               ],
               note: "Everything depends on dead-fresh sardines; they should smell of the sea and nothing else, and once floured they must hit hot oil immediately.",
               shortcut: "Frozen butterflied sardines work if thawed slowly in the fridge and pressed very dry; the crust will be slightly less crisp."),
        Recipe(dishID: "morocco-chebakia", serves: 8, prepMinutes: 60, cookMinutes: 40, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 cup", item: "sesame seeds, toasted, plus 3 tbsp for sprinkling"),
                   RecipeIngredient(amount: "1 tsp", item: "ground anise (or fennel seed, ground)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "a pinch", item: "saffron threads, steeped in 2 tbsp warm water"),
                   RecipeIngredient(amount: "3 tbsp", item: "orange blossom water"),
                   RecipeIngredient(amount: "1/2 cup", item: "olive oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "melted butter"),
                   RecipeIngredient(amount: "1/2 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 cups", item: "honey"),
                   RecipeIngredient(amount: "4 cups", item: "vegetable oil, for frying"),
               ],
               steps: [
                   "Grind half the toasted sesame seeds to a coarse powder. Mix them with the flour, anise, cinnamon, yeast, and salt in a wide bowl.",
                   "Add the olive oil, butter, saffron water, 2 tablespoons of orange blossom water, and enough warm water to gather a firm, pliable dough. Knead 8 minutes, then rest 15.",
                   "Roll the dough a scant 1/8 inch thick and cut into 4-inch squares. Cut four slits in each square, leaving the edges attached, like a little ladder.",
                   "Thread your finger through alternating strips and pinch the opposite corners together, turning each square inside out into a loose rose. They tighten as they fry, so keep them airy.",
                   "Warm the honey with the remaining orange blossom water in a wide saucepan until thin and pourable; keep it warm on the lowest heat.",
                   "Heat the frying oil to 350°F. Fry the roses in batches, turning once, 5 to 6 minutes, until they are a deep amber, not pale gold.",
                   "Move them straight from the oil into the warm honey and let them drink it in for 5 minutes, turning once.",
                   "Lift onto a rack, sprinkle with the reserved sesame seeds, and let the glaze set for an hour. They keep for weeks in a tin, which is the point.",
               ],
               note: "Fry darker than instinct says; pale chebakia taste doughy, and only a deep amber cookie can stand up to five minutes in warm honey.",
               shortcut: "Skip shaping roses and fry simple twisted strips; they soak honey the same way and cost you only the wedding-tray look."),
        Recipe(dishID: "morocco-zaalouk", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2", item: "medium eggplants"),
                   RecipeIngredient(amount: "3", item: "ripe tomatoes, grated (skins discarded)"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "2 tsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1/4 cup", item: "olive oil, plus more to finish"),
                   RecipeIngredient(amount: "1/2 cup", item: "chopped cilantro"),
                   RecipeIngredient(amount: "1/2", item: "lemon, juiced"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Prick the eggplants and char them directly over a gas flame or under the broiler, turning, until the skins are blackened all over and the flesh has gone slack, about 15 minutes.",
                   "Let them cool in a covered bowl, then peel off the burnt skin and roughly chop the smoky flesh, keeping any juices.",
                   "Warm the olive oil in a skillet over medium heat and cook the garlic 1 minute, just until fragrant, not colored.",
                   "Add the grated tomatoes, paprika, cumin, and salt and simmer 10 minutes, until the sauce thickens and the oil rises to the edges.",
                   "Fold in the eggplant and cook 10 more minutes, crushing with the back of the spoon until you have a rough, jammy mash with some texture left.",
                   "Take off the heat and stir in the cilantro and lemon juice; taste and sharpen with more salt or lemon.",
                   "Serve warm or at room temperature, pooled with olive oil, with plenty of torn bread for scooping.",
               ],
               note: "The char is not optional; without real smoke on the eggplant, zaalouk is just stewed vegetables. Blacken the skins past the point of politeness.",
               shortcut: "Roasting halved eggplants cut-side down at 450°F works with less mess; brush the skins with oil and expect a milder, less smoky result."),
    ]

    private static let recipes_ethiopia: [Recipe] = [
        Recipe(dishID: "ethiopia-doro-wat", serves: 4, prepMinutes: 25, cookMinutes: 100, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "chicken drumsticks and thighs, skin removed"),
                   RecipeIngredient(amount: "4", item: "large red onions, very finely chopped"),
                   RecipeIngredient(amount: "4 tbsp", item: "berbere (or 3 tbsp paprika plus 1 tbsp cayenne with a pinch each of ginger and allspice)"),
                   RecipeIngredient(amount: "6 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "6 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "fresh ginger, minced"),
                   RecipeIngredient(amount: "4", item: "hard-boiled eggs, peeled"),
                   RecipeIngredient(amount: "1", item: "lemon, juiced"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Toss the skinned chicken with the lemon juice and a pinch of salt and set aside while you start the onions.",
                   "Cook the chopped onions in a dry, heavy pot over medium-low heat, stirring often, for 30 minutes, until they collapse into a dry, bronze paste. Add splashes of water whenever they threaten to scorch.",
                   "Melt the butter with the cardamom into the onions, then add the garlic, ginger, and berbere and fry 5 minutes, stirring, until the paste turns brick red and the oil stains the spoon.",
                   "Add 2 cups of water a little at a time, stirring the paste smooth between additions, and simmer 10 minutes into a thick sauce.",
                   "Nestle in the chicken, cover, and simmer gently for 40 minutes, turning the pieces halfway, until the meat is nearly falling off the bone.",
                   "Score each boiled egg lightly a few times and roll them into the sauce for the last 10 minutes so they soak up color and heat.",
                   "Season with salt, rest 10 minutes off the heat, and serve ladled over injera or flatbread, one egg per person.",
               ],
               note: "Doro wat is an onion dish wearing a chicken costume; the dry, slow onion stage cannot be rushed, and starting them without oil is correct, not a typo.",
               shortcut: "Pulse the onions in a food processor to skip the fine chopping; the sauce turns out slightly lighter in color but the flavor holds."),
        Recipe(dishID: "ethiopia-injera", serves: 4, prepMinutes: 20, cookMinutes: 30, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "teff flour (dark or ivory)"),
                   RecipeIngredient(amount: "1/2 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 tsp", item: "instant yeast (stands in for a wild starter)"),
                   RecipeIngredient(amount: "3 cups", item: "water, room temperature"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "vegetable oil, for the pan"),
               ],
               steps: [
                   "Whisk the teff, all-purpose flour, yeast, and water into a smooth, thin batter. Cover loosely and leave at room temperature for 24 to 48 hours; it should bubble and smell pleasantly sour. This is the honest weeknight version of a multi-day wild ferment.",
                   "Pour off any dark liquid on top. Take 1/2 cup of the batter, whisk it into 1/2 cup of boiling water, and cook 1 minute into a thin porridge; this absit gives the injera its sheen.",
                   "Whisk the warm porridge and the salt back into the batter and rest 30 minutes; the batter should pour like thin pancake batter.",
                   "Heat a 10-inch nonstick skillet over medium heat and wipe it with the barest film of oil.",
                   "Pour in a scant 1/2 cup of batter in a spiral from the outside in, tilting to fill gaps. Do not touch it after it sets.",
                   "Cook uncovered until holes, called eyes, open across the whole surface, then cover with a lid for 1 to 2 minutes until the top is set and glossy. Never flip it.",
                   "Slide onto a clean towel to cool and repeat, stacking the finished rounds only after they are fully cool so they do not stick.",
               ],
               note: "Wait for eyes across the entire surface before covering; an injera without eyes is a crepe, and the sour smell after two days is the flavor, not a fault.",
               shortcut: "A half-and-half teff and all-purpose blend ferments more reliably for beginners than pure teff; you trade some of the deep, dark-earth flavor away."),
        Recipe(dishID: "ethiopia-kitfo", serves: 4, prepMinutes: 20, cookMinutes: 10, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "beef tenderloin or eye of round, trimmed of all fat and sinew"),
                   RecipeIngredient(amount: "6 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "1 tbsp", item: "mitmita (or 2 tsp cayenne mixed with 1 tsp paprika and a pinch of cardamom)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "farmer cheese or dry cottage cheese (stands in for ayib)"),
                   RecipeIngredient(amount: "1 bunch", item: "collard greens, sautéed with a little butter and salt"),
                   RecipeIngredient(amount: "4 pieces", item: "injera or soft flatbread, to serve"),
               ],
               steps: [
                   "Chill the beef in the freezer for 20 minutes, then mince it very finely with a sharp knife, or ask the butcher to grind trimmed tenderloin fresh the same day.",
                   "Melt the butter with the cardamom in a small pan over the lowest heat for 5 minutes so the spice perfumes it; do not let it brown.",
                   "Stir the mitmita and salt into the warm spiced butter.",
                   "Put the minced beef in a warm bowl and pour the butter over it, folding with a spoon until every bit is glossy and evenly red.",
                   "For the traditional leb leb style, warm the dressed beef in the pan over low heat for 1 to 2 minutes, stirring, so it heats through but stays rare inside. Cook it fully through if you prefer; nobody at an American table will object.",
                   "Mound the kitfo in the center of a platter with the farmer cheese and sautéed collards on either side.",
                   "Serve immediately with injera, pinching up a little of all three in each bite.",
               ],
               note: "This dish is only as safe and as good as the meat; buy whole tenderloin from a butcher you trust, ground fresh that day, never pre-ground supermarket beef.",
               shortcut: "A food processor minces the chilled beef in short pulses; stop while it still looks hand-chopped or the texture turns to paste."),
        Recipe(dishID: "ethiopia-shiro", serves: 4, prepMinutes: 10, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "chickpea flour"),
                   RecipeIngredient(amount: "1 tbsp", item: "berbere (or paprika plus a pinch of cayenne)"),
                   RecipeIngredient(amount: "1", item: "red onion, very finely chopped"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, minced"),
                   RecipeIngredient(amount: "1/4 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "1", item: "tomato, grated"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
               ],
               steps: [
                   "Toast the chickpea flour in a dry skillet over medium heat, stirring, for 3 to 4 minutes, until it smells nutty; this stands in for traditional shiro powder.",
                   "Whisk the toasted flour with the berbere and 2 cups of the water until completely smooth, so no lumps survive to haunt the pot.",
                   "Cook the onion in the oil over medium heat until golden, about 8 minutes, then add the garlic, ginger, and grated tomato and fry 3 minutes more.",
                   "Pour in the remaining 2 cups of water and the salt and bring to a boil.",
                   "Whisk in the chickpea slurry in a steady stream and drop the heat to low.",
                   "Simmer 10 to 12 minutes, whisking often, until the shiro thickens to the texture of a loose gravy that ribbons off the spoon; it firms more as it cools.",
                   "Serve bubbling hot, drizzled with a little oil, with injera or flatbread for scooping.",
               ],
               note: "Shiro waits for no one; it is at its silky best in the first ten minutes off the stove, so cook it last and bring it to the table still bubbling.",
               shortcut: "Real shiro powder from an Ethiopian grocery or online replaces the flour, spices, and toasting in one scoop and tastes deeper."),
        Recipe(dishID: "ethiopia-tibs", serves: 4, prepMinutes: 15, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "sirloin or ribeye, cut into thin 1-inch strips"),
                   RecipeIngredient(amount: "2", item: "red onions, cut into thick slivers"),
                   RecipeIngredient(amount: "2", item: "jalapeños, sliced into rings"),
                   RecipeIngredient(amount: "2 sprigs", item: "fresh rosemary"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, sliced"),
                   RecipeIngredient(amount: "1 tsp", item: "berbere (or paprika with a pinch of cayenne)"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
               ],
               steps: [
                   "Melt the butter with the cardamom in a small pan over low heat and set it aside; this quick spiced butter is the flavor spine of the dish.",
                   "Pat the beef very dry and season with the salt; wet meat will steam instead of sear.",
                   "Heat the oil in your widest cast-iron skillet until it smokes. Sear the beef in two batches, undisturbed for the first minute, until deeply browned but still pink inside. Remove to a plate.",
                   "Drop the onions into the same skillet and cook 3 minutes, until charred at the edges but still crunchy.",
                   "Add the garlic, jalapeños, rosemary, and berbere and cook 1 minute, until the pan smells like a campfire in the best way.",
                   "Return the beef and its juices, pour in the spiced butter, and toss everything together over high heat for 1 minute, no longer.",
                   "Serve straight from the skillet, ideally set on a trivet in the middle of the table, with injera or bread to mop the butter.",
               ],
               note: "Tibs is a searing contest, not a stew; if the meat crowds the pan it boils in its own juice, so brown it in batches and keep the heat brutal.",
               shortcut: "Pre-sliced stir-fry beef from the meat counter saves knife work; choose the thickest cut available or it will overcook in seconds."),
        Recipe(dishID: "ethiopia-misir-wot", serves: 4, prepMinutes: 10, cookMinutes: 45, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "red lentils, rinsed"),
                   RecipeIngredient(amount: "3 tbsp", item: "berbere (or 2 tbsp paprika plus 1 tbsp cayenne with a pinch of allspice)"),
                   RecipeIngredient(amount: "2", item: "red onions, finely chopped"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1/3 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
               ],
               steps: [
                   "Cook the onions in a dry pot over medium-low heat, stirring, for 10 minutes, until soft and dry; add small splashes of water if they start to catch.",
                   "Add the oil, garlic, and ginger and cook 3 minutes, until fragrant.",
                   "Stir in the berbere and tomato paste and fry 3 to 4 minutes, stirring constantly, until the paste darkens and the oil turns brick red at the edges.",
                   "Add the lentils and stir 1 minute to coat them in the spice base.",
                   "Pour in the water, bring to a boil, then simmer uncovered over low heat for 30 minutes, stirring now and then so the bottom never scorches.",
                   "The wot is done when the lentils have broken down into a thick, spoonable red porridge that mounds on a spoon; add water if it tightens too much.",
                   "Season with salt and serve hot alongside other stews on injera, or over rice on an ordinary Tuesday.",
               ],
               note: "Frying the berbere in oil until it darkens is the whole game; undercooked spice tastes raw and dusty no matter how long the lentils simmer afterward.",
               shortcut: "A rice cooker on the porridge setting handles the simmer unattended; fry the onion-spice base in a skillet first and scrape it in."),
        Recipe(dishID: "ethiopia-ful", serves: 2, prepMinutes: 10, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 can (15 oz)", item: "fava beans (ful medames), undrained"),
                   RecipeIngredient(amount: "1/2", item: "red onion, finely chopped"),
                   RecipeIngredient(amount: "1", item: "jalapeño, finely chopped"),
                   RecipeIngredient(amount: "1", item: "tomato, chopped"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1/2 tsp", item: "berbere or cayenne"),
                   RecipeIngredient(amount: "1/4 cup", item: "plain yogurt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2", item: "soft bread rolls"),
               ],
               steps: [
                   "Warm the fava beans with their liquid in a saucepan over medium heat until they simmer.",
                   "Mash about half the beans against the side of the pan with a fork, leaving the rest whole, and cook 5 minutes until creamy but not stiff.",
                   "Stir in the cumin, berbere, salt, and 2 tablespoons of the olive oil.",
                   "Simmer 5 more minutes, adding a splash of water if the ful gets thicker than soft oatmeal.",
                   "Tip into two shallow bowls and press a well into the center of each with the back of the spoon.",
                   "Top with the chopped onion, jalapeño, and tomato, spoon the yogurt into the well, and finish with the last of the olive oil.",
                   "Serve with the rolls for tearing and dunking, and sweet black tea if you are doing it properly.",
               ],
               note: "Ful should be creamy enough to scoop with soft bread but never soupy; the toppings go on at the table so every spoonful has crunch, heat, and cool.",
               shortcut: "Canned favas are the accepted standard even in Addis cafes; plain canned ones just need 10 extra minutes of simmering and a firmer mash."),
        Recipe(dishID: "ethiopia-hambasha", serves: 8, prepMinutes: 30, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "4 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1/4 cup", item: "sugar"),
                   RecipeIngredient(amount: "1 tsp", item: "ground fenugreek (or omit)"),
                   RecipeIngredient(amount: "1 tbsp", item: "nigella seeds (or black sesame)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1/4 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "warm water"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter, melted"),
               ],
               steps: [
                   "Whisk the flour, yeast, sugar, fenugreek, coriander, nigella seeds, and salt together in a large bowl.",
                   "Add the oil and warm water and knead 8 to 10 minutes into a soft, supple dough that springs back slowly when poked.",
                   "Cover and rise in a warm spot for about an hour, until doubled.",
                   "Punch down and press the dough into a buttered 12-inch round pan or skillet, flattening it to about an inch thick.",
                   "Score a wheel pattern on top with a knife, a circle in the center with spokes radiating out, cutting only a quarter inch deep. Rest 20 minutes while the oven heats to 350°F.",
                   "Bake 30 to 35 minutes, until the top is golden brown and the loaf sounds hollow when tapped on the base.",
                   "Brush the hot crust with the melted butter, cool at least 20 minutes, and cut along the spokes to serve, ideally with strong coffee.",
               ],
               note: "The shallow wheel scoring is functional as well as beautiful; it lets the thick, dense crumb bake through evenly, so do not skip it or cut too deep.",
               shortcut: "A stand mixer kneads the stiff dough in 5 minutes; baking in a cast-iron skillet gives the traditional thick bottom crust for free."),
    ]

    private static let recipes_nigeria: [Recipe] = [
        Recipe(dishID: "nigeria-jollof", serves: 6, prepMinutes: 20, cookMinutes: 70, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "long grain parboiled rice, rinsed"),
                   RecipeIngredient(amount: "4", item: "ripe tomatoes"),
                   RecipeIngredient(amount: "2", item: "red bell peppers"),
                   RecipeIngredient(amount: "1", item: "scotch bonnet (or habanero)"),
                   RecipeIngredient(amount: "3", item: "yellow onions"),
                   RecipeIngredient(amount: "1/3 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "3 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1 tbsp", item: "curry powder"),
                   RecipeIngredient(amount: "2 tsp", item: "dried thyme"),
                   RecipeIngredient(amount: "3", item: "bay leaves"),
                   RecipeIngredient(amount: "2", item: "chicken bouillon cubes"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Blend the tomatoes, bell peppers, scotch bonnet, and one onion into a smooth red puree, then boil it in a saucepan for 15 minutes to cook off the raw taste and reduce it by a third.",
                   "Slice the remaining onions. Heat the oil in a heavy pot and fry them until golden, then stir in the tomato paste and fry 3 minutes, until it darkens to brick.",
                   "Pour in the reduced pepper puree, add the curry powder, thyme, bay leaves, crumbled bouillon, and salt, and simmer 10 minutes into a thick, glossy stew base.",
                   "Stir in the rinsed rice until every grain is coated red, then add 2 cups of hot water, just level with the rice.",
                   "Cover with foil and then the lid to trap the steam, and cook on the lowest heat for 30 minutes without peeking.",
                   "Check the grains; they should be tender and separate. If not, sprinkle 1/4 cup water, re-cover, and give it 10 more minutes.",
                   "Let the bottom layer toast on medium heat for the final 3 minutes; that faintly smoky scorch is prized, not a mistake. Fold in the butter and rest 10 minutes before serving.",
                   "Serve with fried plantains and whatever protein the party demands.",
               ],
               note: "Reduce the pepper base until thick before the rice goes in; watery base makes mushy jollof, and the foil under the lid is the secret to even steam.",
               shortcut: "A 28 oz can of crushed tomatoes plus one jarred roasted red pepper replaces the fresh blend; you lose a little brightness but keep the color."),
        Recipe(dishID: "nigeria-egusi", serves: 6, prepMinutes: 25, cookMinutes: 75, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "ground egusi (melon seeds; or raw pumpkin seeds, ground fine)"),
                   RecipeIngredient(amount: "1/2 cup", item: "palm oil"),
                   RecipeIngredient(amount: "1 lb", item: "beef stew meat, cubed"),
                   RecipeIngredient(amount: "8 oz", item: "smoked mackerel or whitefish, flaked (stands in for smoked catfish)"),
                   RecipeIngredient(amount: "3 tbsp", item: "ground dried crayfish (or dried shrimp, ground)"),
                   RecipeIngredient(amount: "1 lb", item: "fresh spinach, chopped (stands in for ugu leaves)"),
                   RecipeIngredient(amount: "1", item: "red onion, chopped"),
                   RecipeIngredient(amount: "1", item: "scotch bonnet, blended with 2 tomatoes"),
                   RecipeIngredient(amount: "2", item: "beef bouillon cubes"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Simmer the beef with the onion, one bouillon cube, salt, and water to cover for 40 minutes, until tender. Keep the meat and about 3 cups of the broth.",
                   "Mix the ground egusi with 1/2 cup of water into a thick, crumbly paste.",
                   "Heat the palm oil in a wide pot over medium heat until it loosens and smells nutty, then fry the tomato and scotch bonnet blend for 5 minutes.",
                   "Drop the egusi paste in by rough spoonfuls and fry 10 minutes without breaking them up too much; the curds should set and toast like scrambled eggs.",
                   "Add the reserved broth, beef, smoked fish, crayfish, and second bouillon cube and simmer 15 minutes, until the oil rises to the surface in orange pools.",
                   "Stir in the spinach and cook 5 minutes more, just until wilted but still green.",
                   "Rest 10 minutes off the heat so the soup thickens, then serve with pounded yam, fufu, or steamed rice for the unorthodox.",
               ],
               note: "Fry the egusi paste in lumps and leave them alone; those toasted curds are the dish's whole texture, and stirring too soon dissolves them into wallpaper paste.",
               shortcut: "Ground raw pumpkin seeds from the baking aisle are a faithful stand-in for egusi; the soup comes out slightly greener and a touch sweeter."),
        Recipe(dishID: "nigeria-suya", serves: 4, prepMinutes: 30, cookMinutes: 10, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "sirloin, sliced against the grain into thin wide ribbons"),
                   RecipeIngredient(amount: "1/2 cup", item: "roasted unsalted peanuts"),
                   RecipeIngredient(amount: "1 tbsp", item: "ground ginger"),
                   RecipeIngredient(amount: "1 tbsp", item: "cayenne or hot chili powder"),
                   RecipeIngredient(amount: "1 tbsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1 tsp", item: "garlic powder"),
                   RecipeIngredient(amount: "1 tsp", item: "onion powder"),
                   RecipeIngredient(amount: "1", item: "chicken bouillon cube, crushed"),
                   RecipeIngredient(amount: "3 tbsp", item: "peanut or vegetable oil"),
                   RecipeIngredient(amount: "1", item: "red onion, sliced into rings, to serve"),
                   RecipeIngredient(amount: "2", item: "tomatoes, sliced, to serve"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Pulse the peanuts in a food processor to a fine powder, stopping before they turn to butter, then sift out any big pieces.",
                   "Mix the peanut powder with the ginger, cayenne, paprika, garlic powder, onion powder, crushed bouillon, and salt; this is your yaji.",
                   "Toss the beef ribbons with the oil, then with two-thirds of the yaji, pressing the spice into every surface. Marinate 30 minutes at room temperature, or up to overnight chilled.",
                   "Thread the ribbons onto soaked wooden skewers in loose waves, so heat can reach between the folds.",
                   "Grill over high direct heat or under a maxed-out broiler for 3 to 4 minutes per side, until the edges char and the spice crust darkens.",
                   "Dust the hot skewers with the reserved yaji the moment they come off the fire, so it clings to the juices.",
                   "Pile onto a platter with the onion rings and tomato slices, and eat with your hands off the skewer, extra yaji on the side.",
               ],
               note: "The double hit of yaji, before and after cooking, is what separates suya from ordinary kebabs; the second dusting onto hot meat is non-negotiable.",
               shortcut: "Unsweetened powdered peanut butter from the supplement aisle replaces grinding peanuts and is actually closer to the drier texture street vendors use."),
        Recipe(dishID: "nigeria-puff-puff", serves: 6, prepMinutes: 15, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1/2 cup", item: "sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "freshly grated nutmeg"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "warm water"),
                   RecipeIngredient(amount: "4 cups", item: "vegetable oil, for deep frying"),
               ],
               steps: [
                   "Whisk the flour, yeast, sugar, nutmeg, and salt in a large bowl.",
                   "Stir in the warm water to make a thick, sticky, pourable batter, somewhere between cake batter and bread dough.",
                   "Cover and let it rise in a warm spot for about an hour, until doubled and webbed with bubbles.",
                   "Heat 3 inches of oil in a heavy pot to 350°F; a drop of batter should sizzle and rise at once.",
                   "Scoop batter with a wet hand and squeeze balls off between your thumb and forefinger into the oil, or use two oiled spoons. Do not crowd the pot.",
                   "Fry 4 to 5 minutes, turning them as they bob, until evenly deep golden brown all over; too-hot oil browns the outside and leaves raw dough inside.",
                   "Drain on paper towels and eat warm by the handful, plain or rolled in sugar.",
               ],
               note: "The batter should fight you a little coming off the spoon; too thin and the balls flatten, too thick and they stay doughy at the center.",
               shortcut: "Skip the hand-squeeze and use a small ice cream scoop dipped in oil; the balls come out uniform, if slightly less charmingly lopsided."),
        Recipe(dishID: "nigeria-moi-moi", serves: 6, prepMinutes: 45, cookMinutes: 50, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "dried black-eyed peas"),
                   RecipeIngredient(amount: "1", item: "red bell pepper, chopped"),
                   RecipeIngredient(amount: "1/2", item: "scotch bonnet (or less, to taste)"),
                   RecipeIngredient(amount: "1", item: "red onion, chopped"),
                   RecipeIngredient(amount: "1/3 cup", item: "palm oil or vegetable oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "ground dried crayfish (or omit)"),
                   RecipeIngredient(amount: "2", item: "bouillon cubes"),
                   RecipeIngredient(amount: "3", item: "hard-boiled eggs, quartered"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "about 1 cup", item: "warm water"),
               ],
               steps: [
                   "Soak the black-eyed peas for 30 minutes, then rub them between your palms in batches under water until the skins float free. Pour off the skins and repeat until the beans are mostly white.",
                   "Blend the peeled beans with the bell pepper, scotch bonnet, onion, and about a cup of warm water until completely smooth; the batter should fall in a thick ribbon.",
                   "Whisk in the oil, crayfish, crumbled bouillon, and salt; the mixture should loosen to the texture of pancake batter, so add water a spoonful at a time if needed.",
                   "Grease 6 ramekins or foil cups, drop a quarter of boiled egg into each, and fill three-quarters full with batter. Cover each tightly with foil.",
                   "Set the cups in a wide pot with an inch of simmering water, cover the pot, and steam on medium-low for 45 to 50 minutes, topping up the water if it runs low.",
                   "A skewer pushed into the center should come out clean and the tops should be set and slightly domed.",
                   "Rest 10 minutes, then unmold or serve in the cups, warm, next to jollof or with soft pap for breakfast.",
               ],
               note: "Peeling the beans is tedious and completely mandatory; skins left in make moi moi gritty and dull colored, so budget the full half hour and rub hard.",
               shortcut: "Buy peeled black-eyed pea flour or pre-peeled beans from an African grocery online; blending flour with water skips the entire soak-and-rub ordeal."),
        Recipe(dishID: "nigeria-ofada", serves: 4, prepMinutes: 30, cookMinutes: 100, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "ofada or short-grain brown rice"),
                   RecipeIngredient(amount: "6", item: "green bell peppers"),
                   RecipeIngredient(amount: "2", item: "green scotch bonnets (or serranos for less heat)"),
                   RecipeIngredient(amount: "2/3 cup", item: "palm oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "fermented locust beans (iru; or 1 tbsp red miso)"),
                   RecipeIngredient(amount: "1 lb", item: "assorted beef (stew meat plus tripe or shaki if you can get it)"),
                   RecipeIngredient(amount: "3", item: "hard-boiled eggs, halved"),
                   RecipeIngredient(amount: "2", item: "red onions"),
                   RecipeIngredient(amount: "2", item: "bouillon cubes"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Simmer the assorted beef with one sliced onion, a bouillon cube, and salted water to cover for 45 minutes, until everything is tender. Reserve the stock.",
                   "Blend the green peppers, scotch bonnets, and remaining onion coarsely, then boil the blend in a dry pot, stirring, until the water cooks off and it sits thick, about 15 minutes.",
                   "Heat the palm oil alone in a heavy pot over medium heat for 8 to 10 minutes until it fades from red to pale orange; open a window, this bleaching stage is smoky and it is supposed to be.",
                   "Fry the locust beans in the cooled-slightly oil for 2 minutes, then add the green pepper paste and fry 15 minutes, stirring, until the sauce darkens to olive drab and the oil separates.",
                   "Add the cooked meats, a splash of stock, and the second bouillon cube and simmer 15 minutes so the sauce clings to the meat. Fold in the boiled eggs at the end.",
                   "Meanwhile rinse the rice until the water runs clear and boil it in salted water for 30 to 40 minutes, until the chewy grains are tender but distinct. Drain.",
                   "Serve the rice with the ayamase spooned generously over, traditionally in a washed banana or foil-lined leaf wrap, with a spoon and a cold drink.",
               ],
               note: "Ayamase must be green-black, not bright green; that color comes from properly bleached palm oil and long frying, and there is no polite indoor way around it.",
               shortcut: "Skip bleaching and use half palm oil, half vegetable oil; the sauce tastes brighter and less smoky but dinner arrives without setting off the alarm."),
        Recipe(dishID: "nigeria-akara", serves: 4, prepMinutes: 40, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "dried black-eyed peas"),
                   RecipeIngredient(amount: "1/2", item: "red onion, roughly chopped"),
                   RecipeIngredient(amount: "1", item: "scotch bonnet (or half, for the cautious)"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "vegetable oil, for deep frying"),
               ],
               steps: [
                   "Soak the black-eyed peas for 30 minutes, then rub them between your palms under water until the skins slip off and float. Rinse the skins away and repeat until the beans are clean and pale.",
                   "Blend the beans with the onion, scotch bonnet, and as little water as your blender allows, no more than 1/2 cup; a thick batter is everything here.",
                   "Whisk the batter vigorously with a spoon or hand mixer for 3 to 4 minutes to beat in air; it should lighten in color and fall from the spoon in soft peaks.",
                   "Stir in the salt only now; salting early deflates the batter.",
                   "Heat 3 inches of oil to 350°F in a deep pot.",
                   "Drop rounded spoonfuls into the oil and fry 4 to 5 minutes, turning once, until deep golden brown with crisp ragged edges.",
                   "Drain on paper towels and eat hot, with soft bread, pap, or straight from the plate before anyone else gets there.",
               ],
               note: "Air is the only leavening; the beating stage decides whether you get cloud-light fritters or bean hockey pucks, so whip until the batter visibly lightens.",
               shortcut: "Black-eyed pea flour from an African grocery whisked with water skips soaking and peeling entirely; whip it longer to get the same lift."),
        Recipe(dishID: "nigeria-pepper-soup", serves: 4, prepMinutes: 15, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "catfish steaks (or other firm white fish, thick-cut)"),
                   RecipeIngredient(amount: "1", item: "scotch bonnet, blended or finely minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "pepper soup spice mix (or 2 tsp ground fennel seed plus 1 tsp allspice and a pinch of nutmeg)"),
                   RecipeIngredient(amount: "1", item: "red onion, half blended, half sliced"),
                   RecipeIngredient(amount: "1 handful", item: "fresh basil leaves (stands in for scent leaf)"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, grated"),
                   RecipeIngredient(amount: "2", item: "bouillon cubes"),
                   RecipeIngredient(amount: "1", item: "lime"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "6 cups", item: "water"),
               ],
               steps: [
                   "Rinse the catfish steaks with the juice of half the lime and a little salt to tame any muddiness, then pat dry.",
                   "Bring the water to a boil in a wide pot with the blended onion, ginger, scotch bonnet, pepper soup spice, and crumbled bouillon.",
                   "Simmer the broth for 10 minutes so the spices open up; it should smell sharp, medicinal, and inviting all at once.",
                   "Slide in the fish steaks and the sliced onion in a single layer and drop the heat to a gentle simmer; boiling will break the fish apart.",
                   "Poach 12 to 15 minutes, without stirring, until the flesh flakes at the thickest point when nudged with a spoon.",
                   "Season with salt and the rest of the lime juice, then scatter the basil over and let it wilt in the residual heat for 1 minute.",
                   "Ladle into deep bowls, giving everyone a whole steak, and serve with nothing but a spoon and patience for the bones; boiled yam or white rice on the side is common.",
               ],
               note: "This broth is meant to be thin, hot, and clear, never thickened; resist adding oil or tomato, and let the fish poach gently so it stays intact.",
               shortcut: "Frozen catfish or tilapia fillets work; add them for only the last 8 minutes and accept a soup that is easier to eat but less dramatic."),
    ]

    static let all: [Recipe] = recipes_morocco + recipes_ethiopia + recipes_nigeria
}
