import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesSouthAsia {

    private static let recipes_india: [Recipe] = [
        Recipe(dishID: "india-dosa", serves: 4, prepMinutes: 30, cookMinutes: 45, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "long-grain white rice"),
                   RecipeIngredient(amount: "1/2 cup", item: "urad dal (split black gram, from an Indian grocer or online)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "fenugreek seeds"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 lb", item: "yukon gold potatoes"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil, plus more for the griddle"),
                   RecipeIngredient(amount: "1 tsp", item: "brown mustard seeds"),
                   RecipeIngredient(amount: "10", item: "curry leaves (or leave them out)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "1", item: "small onion, thinly sliced"),
                   RecipeIngredient(amount: "2", item: "serrano chiles, slit lengthwise"),
               ],
               steps: [
                   "Rinse the rice in one bowl and the urad dal with the fenugreek in another, cover both generously with cold water, and soak at least six hours or overnight.",
                   "Drain and blend each separately with just enough fresh water to move, until completely smooth. Combine the two batters with the salt; it should fall off a spoon in a thick ribbon.",
                   "Cover and leave the batter somewhere warm for 8 to 12 hours, until it rises noticeably and smells gently sour, like plain yogurt. Stir it down once before cooking.",
                   "Boil the potatoes whole until a knife slides through, about 15 minutes. Peel while warm and crumble them coarsely with your hands rather than mashing smooth.",
                   "Heat the oil in a skillet, pop the mustard seeds, then add curry leaves, onion, and chiles and cook until the onion softens. Stir in turmeric, the potatoes, and salt to taste.",
                   "Set a wide nonstick skillet over medium-high heat until a drop of water skitters and vanishes. Rub the surface with an oiled paper towel between every dosa.",
                   "Pour a ladleful of batter into the center and immediately spread it outward in widening spirals with the bottom of the ladle, into the thinnest round you can manage.",
                   "Drizzle a teaspoon of oil around the rim and cook without flipping until the underside turns deep gold and the edges lift free, two to three minutes.",
                   "Spoon a line of potato filling down the middle, fold both sides over it, and slide onto a plate. Serve each dosa straight from the pan; they do not wait.",
               ],
               note: "The ferment is the dish. If the batter has not visibly risen and turned faintly sour, wait longer; flat batter makes a pale, leathery dosa no griddle can rescue.",
               shortcut: "Buy ready-made dosa batter from an Indian grocer. You skip two days of soaking and fermenting and lose almost nothing but bragging rights."),
        Recipe(dishID: "india-jhol", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "firm white fish steaks or thick fillets (halibut, cod, or salmon)"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric, divided"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "mustard oil (or vegetable oil plus 1 tsp yellow mustard)"),
                   RecipeIngredient(amount: "1 tsp", item: "panch phoron (or equal parts cumin, fennel, and nigella seeds)"),
                   RecipeIngredient(amount: "2", item: "medium potatoes, cut in thick wedges"),
                   RecipeIngredient(amount: "1 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "1", item: "ripe tomato, chopped"),
                   RecipeIngredient(amount: "3", item: "green chiles, slit lengthwise"),
                   RecipeIngredient(amount: "a handful", item: "cilantro, roughly chopped"),
               ],
               steps: [
                   "Pat the fish dry, rub it all over with half the turmeric and a teaspoon of salt, and let it sit while you prepare everything else, about ten minutes.",
                   "Heat the mustard oil in a wide pan until it just begins to smoke, which mellows its raw bite. Fry the fish two minutes per side until the edges color, then lift it out.",
                   "In the same oil, sizzle the panch phoron for a few seconds until fragrant, then add the potato wedges and turn them until their edges pick up a little gold.",
                   "Add the ginger, tomato, and remaining turmeric and cook, stirring, until the tomato breaks down completely and the oil starts to separate at the edges of the pan.",
                   "Pour in 3 cups of hot water, season with the remaining salt, and simmer uncovered until the potatoes are tender when pierced, about 12 minutes.",
                   "Slide the fish back in along with the green chiles and simmer gently five more minutes, spooning broth over the pieces rather than stirring, so they stay whole.",
                   "Taste the broth; it should be thin, sharp, and clean, not rich. Scatter cilantro over the top and rest five minutes before serving over plain rice.",
               ],
               note: "Keep the broth thin and do not thicken it; jhol means the rice does the absorbing. Stirring after the fish returns will break every piece.",
               shortcut: "Skip frying the fish and poach it straight in the simmering broth. You save a step and the splatter, but lose the toasty mustard-oil edge."),
        Recipe(dishID: "india-litti", serves: 4, prepMinutes: 45, cookMinutes: 50, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "whole wheat flour"),
                   RecipeIngredient(amount: "1 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "5 tbsp", item: "ghee, divided (or melted butter)"),
                   RecipeIngredient(amount: "1 cup", item: "chickpea flour, toasted in a dry pan (stand-in for sattu)"),
                   RecipeIngredient(amount: "1 tsp", item: "ajwain seeds (or dried thyme)"),
                   RecipeIngredient(amount: "2 tbsp", item: "jarred indian lime pickle, finely chopped"),
                   RecipeIngredient(amount: "3 tbsp", item: "mustard oil, divided (or olive oil plus a little yellow mustard)"),
                   RecipeIngredient(amount: "1", item: "large eggplant"),
                   RecipeIngredient(amount: "2", item: "ripe tomatoes"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "2", item: "green chiles, minced"),
                   RecipeIngredient(amount: "1/2", item: "red onion, finely chopped"),
               ],
               steps: [
                   "Knead the wheat flour with half the salt, one tablespoon of ghee, and about 3/4 cup water into a firm, smooth dough. Cover and rest it 20 minutes.",
                   "Mix the toasted chickpea flour with ajwain, chopped lime pickle, one tablespoon of mustard oil, and a few spoonfuls of water until it just clumps when squeezed.",
                   "Divide the dough into eight balls, cup each into a bowl shape, pack in a spoonful of filling, and pinch firmly shut. Roll gently between your palms to seal.",
                   "Bake the littis at 400°F on a rack set over a sheet pan, turning twice, until blistered and deeply browned in patches, 30 to 35 minutes.",
                   "Meanwhile, broil the whole eggplant and tomatoes, turning, until the skins char and the eggplant collapses, about 15 minutes. Rest until cool enough to peel.",
                   "Peel the charred vegetables and mash them roughly with the garlic, chiles, onion, remaining mustard oil, and remaining salt. The chokha should stay coarse, not smooth.",
                   "Crack each litti open, pour the remaining melted ghee into the break, and serve hot with the chokha and raw onion on the side.",
               ],
               note: "The crust should sound hollow when tapped and look scorched in spots; an evenly pale litti has not spent long enough in the heat.",
               shortcut: "Real sattu from an Indian grocer beats home-toasted chickpea flour and saves the toasting step; the flavor is nuttier and drier."),
        Recipe(dishID: "india-dhokla", serves: 6, prepMinutes: 15, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "chickpea flour"),
                   RecipeIngredient(amount: "2 tbsp", item: "plain yogurt"),
                   RecipeIngredient(amount: "3 tbsp", item: "lemon juice, divided"),
                   RecipeIngredient(amount: "3 tbsp", item: "sugar, divided"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "fruit salt (eno, from an Indian grocer) or 3/4 tsp baking soda"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "brown mustard seeds"),
                   RecipeIngredient(amount: "10", item: "curry leaves (or leave them out)"),
                   RecipeIngredient(amount: "3", item: "green chiles, slit lengthwise"),
                   RecipeIngredient(amount: "a handful", item: "cilantro, chopped"),
               ],
               steps: [
                   "Set up a steamer: a large lidded pot with an inch of simmering water and a rack that holds a greased 8-inch round cake pan level.",
                   "Whisk the chickpea flour with the yogurt, one tablespoon lemon juice, one tablespoon sugar, the salt, ginger, and about 3/4 cup water into a thick, pourable, lump-free batter.",
                   "Just before steaming, sprinkle the fruit salt over the batter with a teaspoon of water and whisk briskly for ten seconds; it should froth and lighten visibly.",
                   "Immediately pour the batter into the pan and steam, covered, until a skewer comes out clean and the top springs back, 15 to 18 minutes. Rest ten minutes, then cut into squares in the pan.",
                   "Heat the oil in a small pan, pop the mustard seeds, add curry leaves and chiles for a few seconds, then carefully pour in 2/3 cup water with the remaining sugar and lemon juice. Boil one minute.",
                   "Spoon this hot sweet-sour tempering evenly over the squares, letting it pool in the cuts and soak in. Scatter cilantro on top and serve at room temperature.",
               ],
               note: "The fruit salt dies fast; the pan must be greased, the steamer boiling, and the lid ready before you add it, or the sponge never rises.",
               shortcut: "Boxed instant dhokla mix from an Indian grocer needs only water and the steamer, and the crumb is nearly as good as scratch."),
        Recipe(dishID: "india-roganjosh", serves: 4, prepMinutes: 20, cookMinutes: 120, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "bone-in lamb shoulder, cut in 2-inch pieces"),
                   RecipeIngredient(amount: "1 cup", item: "whole-milk yogurt"),
                   RecipeIngredient(amount: "3 tbsp", item: "kashmiri chili powder (or sweet paprika with a pinch of cayenne)"),
                   RecipeIngredient(amount: "2 tsp", item: "ground fennel seed"),
                   RecipeIngredient(amount: "1 tsp", item: "ground dried ginger"),
                   RecipeIngredient(amount: "4", item: "green cardamom pods, cracked"),
                   RecipeIngredient(amount: "2", item: "black cardamom pods (or 2 more green)"),
                   RecipeIngredient(amount: "1", item: "cinnamon stick"),
                   RecipeIngredient(amount: "4", item: "whole cloves"),
                   RecipeIngredient(amount: "3 tbsp", item: "ghee or vegetable oil"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "a pinch", item: "asafetida (optional, from an Indian grocer)"),
               ],
               steps: [
                   "Heat the ghee in a heavy pot and let the cardamoms, cinnamon, cloves, and asafetida sizzle until fragrant, about thirty seconds; do not let them darken past deep brown.",
                   "Add the lamb in one layer and brown it patiently on all sides, in batches if the pot crowds, about ten minutes total. Salt it as it browns.",
                   "Whisk the yogurt smooth with the chili powder. Off the heat, stir it into the pot one spoonful at a time, letting each disappear before the next, so it cannot split.",
                   "Return the pot to low heat, add a cup of hot water, cover, and braise at a bare simmer until the meat is nearly falling from the bone, about 90 minutes. Stir occasionally.",
                   "Stir in the ground fennel and dried ginger and simmer uncovered fifteen more minutes, until the sauce is glossy and a slick of red fat rises to the surface.",
                   "Taste for salt, rest ten minutes off the heat, and serve with plain basmati rice. The sauce should coat the meat, not drown it.",
               ],
               note: "Temper the yogurt off the heat, spoonful by spoonful, or it curdles into grains nothing will smooth. The red comes from the chili, never from heat.",
               shortcut: "A pressure cooker or Instant Pot takes the braise from 90 minutes to 30; you lose a little of the slow-reduced gloss."),
        Recipe(dishID: "india-puranpoli", serves: 6, prepMinutes: 50, cookMinutes: 60, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "chana dal (or yellow split peas)"),
                   RecipeIngredient(amount: "1 cup", item: "grated jaggery (or packed dark brown sugar)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "a pinch", item: "grated nutmeg"),
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "4 tbsp", item: "ghee, for cooking and serving"),
               ],
               steps: [
                   "Simmer the chana dal in plenty of water until completely soft but not mushy, 35 to 40 minutes, then drain it thoroughly; wet dal makes a filling that leaks.",
                   "Return the dal to the pot with the jaggery and stir over medium heat until the mixture thickens enough that a spoon stood in it stays upright, about ten minutes.",
                   "Mash or process the filling completely smooth, work in the cardamom and nutmeg, and cool it fully. Roll it into eight balls.",
                   "Knead the flour with turmeric, salt, the oil, and enough water to make a dough noticeably softer and slacker than the filling. Rest it 20 minutes under a damp towel.",
                   "Flatten a dough ball into a cup, seat a filling ball inside, and gather the edges shut. There should look like too much filling for the dough; that is correct.",
                   "On a well-floured surface, roll each stuffed ball gently from the center outward into a thin round, until the filling just shows through the dough like a shadow.",
                   "Cook on a dry griddle over medium heat until brown spots bloom on both sides, about two minutes per side, pressing the edges lightly so they cook through.",
                   "Brush generously with ghee only after cooking and stack under a towel. Serve warm, with more ghee or a small cup of warm milk.",
               ],
               note: "The dough must be softer than the filling or it tears when rolled. If the filling feels loose, cook it drier; there is no rescuing it later.",
               shortcut: "A food processor purees the cooked dal and jaggery smooth in seconds; the traditional wooden masher takes ten minutes and better forearms."),
        Recipe(dishID: "india-panipuri", serves: 4, prepMinutes: 35, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "30", item: "ready-made puri shells (boxed, from an Indian grocer)"),
                   RecipeIngredient(amount: "1 cup packed", item: "fresh mint leaves"),
                   RecipeIngredient(amount: "1/2 cup", item: "cilantro"),
                   RecipeIngredient(amount: "2", item: "green chiles"),
                   RecipeIngredient(amount: "1-inch piece", item: "fresh ginger"),
                   RecipeIngredient(amount: "3 tbsp", item: "tamarind paste concentrate, divided"),
                   RecipeIngredient(amount: "2 tsp", item: "ground roasted cumin"),
                   RecipeIngredient(amount: "1 tsp", item: "black salt (kala namak, or flaky sea salt)"),
                   RecipeIngredient(amount: "2", item: "medium potatoes"),
                   RecipeIngredient(amount: "1 cup", item: "cooked chickpeas, rinsed"),
                   RecipeIngredient(amount: "3 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "4 cups", item: "cold water, plus ice"),
               ],
               steps: [
                   "Boil the potatoes until tender, about 15 minutes, then peel and dice them small. Toss with the chickpeas, a pinch of black salt, and a little cumin.",
                   "Blend the mint, cilantro, chiles, and ginger with a cup of the water until completely smooth, scraping down the sides once or twice.",
                   "Stir the green blend into the remaining cold water with one tablespoon tamarind, the rest of the cumin and black salt, and a spoon of sugar. Chill with a handful of ice.",
                   "Warm the remaining tamarind with the remaining sugar and a splash of water until it loosens into a pourable sweet chutney, then cool it.",
                   "Tap a hole in the top of each puri with your thumb, keeping the shell whole. Cracked ones are the cook's snack, which is traditional.",
                   "Fill each shell with a spoonful of potato mixture and a few drops of sweet chutney, working a few at a time so the shells stay crisp.",
                   "Dunk each filled puri fully into the cold pani and eat it immediately, whole, in one bite. Serve standing in the kitchen; this dish does not sit down.",
               ],
               note: "The whole dish lives in the five seconds between the dunk and the bite. Fill and dunk one at a time; a soggy puri is a small tragedy.",
               shortcut: "Boxed pani puri kits include shells and spice mix for the water; add fresh mint and cold water and you are most of the way there."),
        Recipe(dishID: "india-jadoh", serves: 4, prepMinutes: 15, cookMinutes: 45, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "skinless pork belly (or pork shoulder), cut in 3/4-inch cubes"),
                   RecipeIngredient(amount: "2 cups", item: "short grain rice (sushi rice works)"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "1", item: "small onion, finely chopped"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "coarsely ground black pepper"),
                   RecipeIngredient(amount: "3 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2", item: "scallions, sliced, plus chili paste for serving"),
               ],
               steps: [
                   "Rinse the rice in a few changes of water until it runs mostly clear, then drain it well in a sieve while you start the pork.",
                   "Heat the oil in a heavy lidded pot and brown the pork cubes slowly, letting their fat render and the edges crisp, eight to ten minutes.",
                   "Add the onion and ginger and cook in the pork fat until soft and golden, then stir in the turmeric and black pepper for thirty seconds until fragrant.",
                   "Add the drained rice and stir two minutes so every grain is coated in the seasoned fat and stained a rusty yellow.",
                   "Pour in the stock, add the salt, and bring to a boil. Cover, drop the heat to its lowest, and cook undisturbed 18 minutes.",
                   "Rest, still covered, ten minutes off the heat, then fluff gently from the bottom so the pork redistributes through the rice.",
                   "Serve in shallow plates with scallions on top and a fierce chili paste on the side, the way the Shillong stalls do.",
               ],
               note: "The street version includes offal, which deepens the iron-rich flavor; belly alone is the gentle home adaptation, so do not skimp on the black pepper.",
               shortcut: "Leftover cooked rice folded into the browned pork and spices makes a fast fried-rice version; you lose the stock-soaked depth of the real thing."),
    ]

    private static let recipes_srilanka: [Recipe] = [
        Recipe(dishID: "srilanka-ricecurry", serves: 4, prepMinutes: 25, cookMinutes: 40, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "red rice (or long-grain brown rice)"),
                   RecipeIngredient(amount: "1 cup", item: "red lentils"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut milk, divided"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "15", item: "curry leaves, divided (or leave them out)"),
                   RecipeIngredient(amount: "1", item: "small onion, half sliced, half minced"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, sliced"),
                   RecipeIngredient(amount: "1 tsp", item: "brown mustard seeds"),
                   RecipeIngredient(amount: "1 cup", item: "unsweetened shredded coconut"),
                   RecipeIngredient(amount: "2", item: "limes"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "crushed red pepper, divided"),
                   RecipeIngredient(amount: "1 tsp", item: "fish sauce (stand-in for maldive fish, or skip it)"),
                   RecipeIngredient(amount: "2 tbsp", item: "coconut oil or vegetable oil"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt, divided"),
               ],
               steps: [
                   "Start the rice in plenty of salted water and cook until tender; red rice usually wants 30 to 35 minutes. Drain and keep it warm.",
                   "Simmer the lentils with the turmeric and 2 cups water until they collapse into a loose porridge, about 15 minutes, then stir in most of the coconut milk.",
                   "Heat the oil in a small pan, pop the mustard seeds, then fry the sliced onion, garlic, and half the curry leaves until golden. Sizzle in half the crushed pepper.",
                   "Pour the tempering over the dhal, add salt to taste, and let it sit; it should pour like heavy cream, loosened with coconut milk if it stiffens.",
                   "Moisten the shredded coconut with a few spoonfuls of warm water until it feels like fresh snow, then work in the minced onion, remaining crushed pepper, lime juice, salt, and fish sauce.",
                   "Grind the sambol against the bowl with the back of a spoon until it turns faintly pink and clumps; taste it, it should bite back with heat, salt, and sour.",
                   "Plate the rice in the center with dhal poured to one side and sambol heaped on the other, and mix each mouthful by hand or fork as you go.",
               ],
               note: "Each dish keeps its own seasoning until the plate; the mixing happens mouthful by mouthful, so make the sambol sharper than seems polite.",
               shortcut: "Use white basmati instead of red rice and the meal is on the table in half the time; the nutty chew is what you give up."),
        Recipe(dishID: "srilanka-hoppers", serves: 4, prepMinutes: 20, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "rice flour"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut milk"),
                   RecipeIngredient(amount: "1 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "3/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "warm water, more as needed"),
                   RecipeIngredient(amount: "8", item: "eggs"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1/2", item: "red onion, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "crushed red pepper"),
                   RecipeIngredient(amount: "1", item: "lime"),
                   RecipeIngredient(amount: "1/2 tsp", item: "flaky salt"),
               ],
               steps: [
                   "Whisk the yeast and sugar into the warm water and let it foam five minutes, then whisk in the rice flour, coconut milk, and salt into a smooth batter.",
                   "Cover and leave the batter somewhere warm about two hours, until it is visibly bubbly and smells faintly sour and yeasty.",
                   "Make the lunu miris while you wait: pound or grind the onion, crushed pepper, flaky salt, and the juice of the lime into a rough, wet red paste.",
                   "Thin the risen batter with warm water to the consistency of heavy cream; a thick batter makes a pancake, not a bowl, and the swirl will not climb.",
                   "Heat a small nonstick wok or deep 8-inch skillet with a lid over medium heat and wipe it with an oiled paper towel.",
                   "Pour in a third of a cup of batter and immediately lift and roll the pan in a full circle so the batter climbs the sides in a thin coat.",
                   "Crack an egg into the center, cover, and cook two to three minutes until the rim turns lacy gold, the base sets soft, and the white is just firm.",
                   "Loosen the edge with a thin spatula and ease the hopper out whole. Serve hot with lunu miris, and repeat, re-oiling the pan each time.",
               ],
               note: "The swirl decides everything: pour, then roll the pan in one unhurried circle. Batter that will not climb the wall is too thick, so thin it and try again.",
               shortcut: "A boxed hopper mix from a Sri Lankan or Indian grocer skips the ferment; add the egg and the swirl still has to be yours."),
        Recipe(dishID: "srilanka-kottu", serves: 4, prepMinutes: 20, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "frozen paratha (or flour tortillas, less chewy)"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "1", item: "leek, halved and sliced"),
                   RecipeIngredient(amount: "1", item: "carrot, cut in thin matchsticks"),
                   RecipeIngredient(amount: "1", item: "small onion, sliced"),
                   RecipeIngredient(amount: "2", item: "green chiles, sliced"),
                   RecipeIngredient(amount: "1 tbsp", item: "curry powder"),
                   RecipeIngredient(amount: "2 cups", item: "shredded rotisserie chicken"),
                   RecipeIngredient(amount: "3/4 cup", item: "chicken stock"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Cook the parathas in a dry skillet according to the package until browned and flaky, then cool slightly and slice them into short, ragged ribbons.",
                   "Warm the stock with the curry powder and half the salt in a small pan; this stands in for the curry gravy a street kitchen would ladle from its pot.",
                   "Heat the oil in your widest skillet over high heat and stir-fry the onion, leek, carrot, and chiles until they soften but keep a little snap, about three minutes.",
                   "Push the vegetables aside, crack the eggs into the cleared space, and scramble them hard until just set before folding everything back together.",
                   "Add the roti ribbons and chicken and toss, then chop and fold repeatedly with two metal spatulas, channeling the two-cleaver clatter, until everything is a coarse, mixed hash.",
                   "Pour the curry stock over and keep chopping and tossing until it is absorbed and the bottom layer scorches a little in spots, two to three minutes.",
                   "Taste for salt and serve in a hot pile straight from the pan, with extra chili or gravy for anyone who wants it wetter.",
               ],
               note: "Kottu was invented for day-old roti, so drier is better; fresh soft bread turns gummy under the gravy instead of staying chewy with crisp scorched bits.",
               shortcut: "Leftover takeout curry, gravy and all, replaces the stock and chicken in one move and is the most authentic shortcut on this page."),
        Recipe(dishID: "srilanka-lamprais", serves: 4, prepMinutes: 60, cookMinutes: 110, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "short grain rice"),
                   RecipeIngredient(amount: "3 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "4", item: "green cardamom pods and 4 whole cloves"),
                   RecipeIngredient(amount: "1 lb", item: "boneless chicken thighs, cut in chunks"),
                   RecipeIngredient(amount: "2 tbsp", item: "curry powder, toasted dark in a dry pan"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut milk"),
                   RecipeIngredient(amount: "1", item: "yellow plantain, sliced in thick coins"),
                   RecipeIngredient(amount: "1/4 cup", item: "dried shrimp (or 1 tbsp shrimp paste)"),
                   RecipeIngredient(amount: "1/2 lb", item: "ground pork"),
                   RecipeIngredient(amount: "2", item: "onions, one sliced, one minced"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "cayenne pepper"),
                   RecipeIngredient(amount: "4 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "4", item: "banana leaves (frozen, from an Asian market; or parchment plus foil)"),
               ],
               steps: [
                   "Cook the rice in the stock with the cardamom and cloves until just short of done, about 15 minutes; it finishes inside the parcel.",
                   "Brown the chicken in a tablespoon of oil, add the sliced onion, half the garlic, and the dark-toasted curry powder, then simmer in the coconut milk until thick and clinging, about 25 minutes.",
                   "Fry the plantain coins in a little oil until deeply golden on both sides and set them aside on paper towels.",
                   "Grind or mince the dried shrimp, then fry it with the minced onion, remaining garlic, and cayenne until it darkens into a jammy, pungent blachan paste.",
                   "Season the ground pork with salt, roll it into eight small meatballs, and brown them in the same pan until cooked through.",
                   "Pass each banana leaf briefly over a flame or hot burner until it turns glossy and pliable; this is the moment the kitchen starts smelling right.",
                   "Center a mound of rice on each leaf, arrange chicken curry, two meatballs, plantain, and a spoon of blachan around it, and fold into a snug flat parcel, seam down.",
                   "Bake the parcels seam-down on a sheet pan at 350°F for 25 minutes and serve unopened, so each person gets the burst of leaf-scented steam.",
               ],
               note: "The bake inside the banana leaf is not packaging, it is the seasoning; a lamprais assembled and eaten unbaked is just rice with sides.",
               shortcut: "Skip the meatballs and double the chicken curry; the parcel loses one voice from the choir but still sings."),
        Recipe(dishID: "srilanka-ambulthiyal", serves: 4, prepMinutes: 15, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "fresh tuna steaks, cut in large 2-inch cubes"),
                   RecipeIngredient(amount: "6 pieces", item: "goraka (Sri Lankan grocer or online; or 3 tbsp tamarind paste)"),
                   RecipeIngredient(amount: "2 tsp", item: "coarsely ground black pepper"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, crushed"),
                   RecipeIngredient(amount: "1 tsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "10", item: "curry leaves (or leave them out)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "cayenne pepper"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "coconut oil"),
                   RecipeIngredient(amount: "3/4 cup", item: "water"),
               ],
               steps: [
                   "Soak the goraka in half a cup of hot water for ten minutes until soft, then grind it into a dark paste with its liquid; tamarind paste just needs loosening with the water.",
                   "Work the sour paste with the black pepper, garlic, ginger, cayenne, and salt into a thick, almost black marinade.",
                   "Turn the tuna cubes gently in the marinade until every face is coated, and let them sit fifteen minutes while you find your widest shallow pan.",
                   "Arrange the fish in a single layer in the pan with the curry leaves and coconut oil, and pour the water carefully down the side, not over the fish.",
                   "Simmer uncovered on medium-low, turning each piece once with a spoon rather than stirring, until the liquid has nearly vanished, 25 to 30 minutes.",
                   "Keep cooking on the lowest heat until the pieces look dry, dark, and firm and the pan is barely slicked, about ten more minutes.",
                   "Rest at least half an hour before eating, or better, overnight at room temperature covered, as the fishing coast does; serve one or two pieces per person with rice.",
               ],
               note: "This is a dry dish on purpose; if there is sauce left, keep going. The sour and pepper should hit almost too hard next to plain rice.",
               shortcut: "Tamarind paste for goraka is the accepted substitute everywhere outside the island; the sourness is brighter and less resinous, and no one refuses the plate."),
        Recipe(dishID: "srilanka-stringhoppers", serves: 4, prepMinutes: 40, cookMinutes: 35, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "fine rice flour (red rice flour if you can find it)"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "boiling water, more as needed"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "1 cup", item: "red lentils"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut milk, divided"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "10", item: "curry leaves (or leave them out)"),
                   RecipeIngredient(amount: "1 cup", item: "unsweetened shredded coconut"),
                   RecipeIngredient(amount: "1/2", item: "red onion, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "crushed red pepper"),
                   RecipeIngredient(amount: "1", item: "lime"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
               ],
               steps: [
                   "Toast the rice flour in a dry pan two minutes without coloring it, then mix it with half the salt and pour in the boiling water in stages, stirring with a spoon.",
                   "Knead briefly once cool enough to touch; the dough should be smooth, hot, and soft enough to squeeze through a press without cracking.",
                   "Load a string hopper press, or a potato ricer fitted with its finest disc, and pipe small flat spirals of thread, about 4 inches across, onto lightly oiled steamer trays or plates.",
                   "Steam the nests over boiling water until they turn from chalky to translucent-white and spring back when pressed, 8 to 10 minutes.",
                   "Simmer the lentils with turmeric, curry leaves, and 2 cups water until collapsed, then stir in most of the coconut milk and the remaining salt for a loose, pourable dhal.",
                   "Moisten the shredded coconut with the last of the coconut milk and work in the onion, crushed pepper, lime juice, and a pinch of salt for a quick pol sambol.",
                   "Serve five or six nests per plate and let everyone break them up by hand, dousing with dhal and pinching sambol through the threads.",
               ],
               note: "Press the dough while it is still warm; cooled dough clogs the press and cracks. The nests should taste of almost nothing, and that is correct.",
               shortcut: "Thin rice vermicelli, briefly steamed and coiled into nests, gets you nine tenths of the way without buying a press."),
        Recipe(dishID: "srilanka-kiribath", serves: 6, prepMinutes: 5, cookMinutes: 40, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "short grain rice (sushi rice works)"),
                   RecipeIngredient(amount: "3 cups", item: "water"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "full-fat coconut milk"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "1/2", item: "red onion, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "crushed red pepper"),
                   RecipeIngredient(amount: "1", item: "lime"),
                   RecipeIngredient(amount: "2 tbsp", item: "grated jaggery or brown sugar (optional, for the sweet camp)"),
               ],
               steps: [
                   "Rinse the rice once, then simmer it in the water, covered, until the water is absorbed and the grains are just tender, about 15 minutes.",
                   "Pour in the coconut milk and a teaspoon of salt and cook uncovered on low, stirring often, until it thickens to a stiff porridge that holds a spoon trail, 12 to 15 minutes.",
                   "Turn the hot rice onto a plate or into an 8-inch square pan and press it flat and even, about an inch thick, with the back of a wet spoon.",
                   "Rest it 15 to 20 minutes until set firm enough to slice, then cut it into diamonds with a wet knife.",
                   "Pound or grind the onion, crushed pepper, lime juice, and remaining salt into a coarse red lunu miris while the kiribath sets.",
                   "Serve the diamonds barely warm, with lunu miris for heat or a piece of jaggery for the sweet-toothed, and eat with your fingers as a proper new beginning demands.",
               ],
               note: "Cut only when fully set and keep the knife wet, or the diamonds crumble. The rice itself stays bland; the sambol is the flavor.",
               shortcut: "Leftover cooked rice reheated with coconut milk sets nearly as well, turning yesterday's rice pot into a festival breakfast in twenty minutes."),
        Recipe(dishID: "srilanka-watalappan", serves: 6, prepMinutes: 15, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "chopped kithul jaggery (or 1 cup dark brown sugar plus 1 tbsp molasses)"),
                   RecipeIngredient(amount: "3 tbsp", item: "water"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "full-fat coconut milk"),
                   RecipeIngredient(amount: "5", item: "large eggs"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "a pinch", item: "ground cloves"),
                   RecipeIngredient(amount: "a pinch", item: "grated nutmeg"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/3 cup", item: "roasted cashews, roughly chopped"),
               ],
               steps: [
                   "Melt the jaggery with the water over low heat, stirring until it dissolves into a dark syrup, then cool it until just warm to the touch.",
                   "Whisk the eggs gently in a large bowl, stirring rather than beating; froth now means bubbles baked into the custard later.",
                   "Stir in the coconut milk, warm syrup, cardamom, cloves, nutmeg, and salt, then strain the mixture through a sieve into a 1-quart baking dish or six ramekins.",
                   "Set the dish in a roasting pan, pour hot water halfway up its sides, and cover the pan loosely with foil.",
                   "Bake at 325°F until the custard is set at the edges with a slight wobble at the center, 35 to 45 minutes for a single dish, less for ramekins.",
                   "Cool to room temperature, then chill at least two hours; the texture tightens from soft-set to sliceable silk in the refrigerator.",
                   "Scatter the cashews over the top just before serving so they stay crisp against the smooth, dark custard.",
               ],
               note: "The wobble is the whole test: pull it while the center still shivers like set jelly. Overbaked watalappan weeps and turns grainy at the edges.",
               shortcut: "Steaming on the stovetop in a covered pot, 25 minutes over low heat, replaces the oven and water bath entirely."),
    ]

    private static let recipes_nepal: [Recipe] = [
        Recipe(dishID: "nepal-dalbhat", serves: 4, prepMinutes: 20, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "long-grain rice"),
                   RecipeIngredient(amount: "1 cup", item: "split black lentils (urad, or brown lentils)"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric, divided"),
                   RecipeIngredient(amount: "3 tbsp", item: "ghee or vegetable oil, divided"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "cumin seeds, divided"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, sliced"),
                   RecipeIngredient(amount: "1 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "2", item: "medium potatoes, cut in chunks"),
                   RecipeIngredient(amount: "1/2 head", item: "cauliflower, cut in florets"),
                   RecipeIngredient(amount: "1 bunch", item: "mustard greens or spinach, chopped"),
                   RecipeIngredient(amount: "1 3/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "2 tbsp", item: "jarred indian lime or mango pickle, for serving"),
               ],
               steps: [
                   "Cook the rice however you always cook rice; in this meal it is the quiet center, not the performance.",
                   "Simmer the lentils with half the turmeric and 4 cups water until fully soft, 30 to 35 minutes, then whisk briefly so the dal turns loose and pourable, and salt it.",
                   "Heat a tablespoon of ghee until shimmering, sizzle half the cumin seeds and half the garlic to deep gold, and pour the sputtering tempering straight into the dal.",
                   "For the tarkari, fry the potatoes in the remaining ghee five minutes, add cauliflower, ginger, remaining cumin, turmeric, and salt, then cover and cook, stirring now and then, until tender and browned in spots, about 15 minutes.",
                   "Wilt the greens in the same pan with the remaining garlic and a pinch of salt, two to three minutes, just until they collapse but stay bright.",
                   "Build each steel plate, or regular plate, with rice in the center, dal poured generously over it, tarkari and greens beside, and a small fierce spoonful of pickle on the rim.",
                   "Offer seconds before anyone asks; in a Nepali kitchen the refill is not hospitality, it is the baseline.",
               ],
               note: "The dal should pour like heavy cream, never stand like porridge, and the tempering must audibly sizzle when it hits, or it was not hot enough.",
               shortcut: "Red lentils cook in half the time of black ones and make an honest weeknight dal; the flavor is lighter and less earthy."),
        Recipe(dishID: "nepal-momo", serves: 4, prepMinutes: 60, cookMinutes: 25, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "40", item: "round dumpling wrappers (gyoza wrappers work)"),
                   RecipeIngredient(amount: "1 lb", item: "ground beef or bison, 80/20"),
                   RecipeIngredient(amount: "1", item: "small onion, minced"),
                   RecipeIngredient(amount: "1/2 cup", item: "cilantro, finely chopped"),
                   RecipeIngredient(amount: "1 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil, divided"),
                   RecipeIngredient(amount: "3", item: "ripe tomatoes"),
                   RecipeIngredient(amount: "3 tbsp", item: "sesame seeds"),
                   RecipeIngredient(amount: "3", item: "dried red chiles"),
                   RecipeIngredient(amount: "1/2 tsp", item: "sichuan peppercorns (stand-in for timur)"),
               ],
               steps: [
                   "Mix the beef with onion, cilantro, ginger, garlic, a teaspoon of salt, and a tablespoon of oil, stirring in one direction just until combined; overworking makes the filling dense.",
                   "For the achar, char the whole tomatoes under the broiler until blistered and collapsing, about ten minutes, while you toast the sesame seeds and chiles in a dry pan.",
                   "Blend the tomatoes, sesame, chiles, Sichuan peppercorns, remaining salt, and remaining oil into a smooth, pourable orange sauce, and taste; it should tingle and bite.",
                   "Hold a wrapper flat, place a heaped teaspoon of filling in the center, and moisten the rim with a wet finger.",
                   "Pleat around the edge, gathering fold after fold toward the center and twisting the top shut, or simply fold into half-moons and crimp; sealed matters more than pretty.",
                   "Set the momos on an oiled steamer rack without touching, and steam over hard-boiling water 10 to 12 minutes until the skins turn glossy and slightly translucent.",
                   "Serve ten to a plate straight from the steamer, with achar for dunking, and warn people about the hot juice inside the first bite.",
               ],
               note: "Fat is the juice: lean meat steams into sawdust. And in Kathmandu the achar is the real argument, so taste yours until it fights back.",
               shortcut: "Half the filling in gyoza-folded half-moons takes twenty minutes off the pleating; the steamer does not care about your folds."),
        Recipe(dishID: "nepal-sekuwa", serves: 4, prepMinutes: 25, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "lamb or pork shoulder, with some fat left on"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "sichuan peppercorns, toasted and ground (stand-in for timur)"),
                   RecipeIngredient(amount: "2 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "5", item: "garlic cloves, crushed to a paste"),
                   RecipeIngredient(amount: "3 tbsp", item: "mustard oil (or vegetable oil plus 1 tsp yellow mustard)"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "2 tsp", item: "chili powder"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "red onion, cut in thick rings"),
                   RecipeIngredient(amount: "2", item: "limes"),
               ],
               steps: [
                   "Cut the meat into generous 1 1/2-inch cubes, leaving the fat attached; on the Dharan highway the drip and flare is considered part of the recipe.",
                   "Work the ground Sichuan pepper, ginger, garlic, mustard oil, turmeric, chili powder, and salt into the meat with your hands until every piece is stained.",
                   "Marinate covered in the refrigerator at least four hours, and overnight if dinner can wait; the timur-style numbing note needs time to sink in.",
                   "Thread the cubes onto skewers, packed snugly so the meat stays juicy, and let them lose their fridge chill while the fire heats.",
                   "Grill over hot charcoal, or under a broiler set high with the meat close to the element, turning every few minutes, until charred outside and just cooked through, 10 to 12 minutes.",
                   "Rest the skewers five minutes, squeeze lime over everything, and serve with the raw onion rings and, if you can find it, a bowl of beaten rice.",
               ],
               note: "Wood or charcoal is the argument the whole dish makes; a gas grill works, but get real char on the corners or it is just kebab.",
               shortcut: "Chicken thighs take the same marinade, need only two hours, and cook faster; you trade the gamey depth that goat people prize."),
        Recipe(dishID: "nepal-chatamari", serves: 4, prepMinutes: 15, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "rice flour"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "water, more as needed"),
                   RecipeIngredient(amount: "3/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "1/2 lb", item: "ground beef or bison (stand-in for buffalo)"),
                   RecipeIngredient(amount: "1 tbsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "3/4 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "4", item: "eggs"),
                   RecipeIngredient(amount: "4", item: "spring onions, sliced"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1", item: "green chile, minced"),
               ],
               steps: [
                   "Whisk the rice flour with the water and half the salt into a batter the consistency of thin pancake batter; it should coat a spoon and run off in a stream.",
                   "Brown the ground meat in a teaspoon of oil with the ginger, garlic, cumin, chile, and remaining salt, breaking it fine, until cooked through and a little crisp at the edges.",
                   "Heat a lightly oiled nonstick skillet over medium, pour in a small ladle of batter, and swirl the pan at once into a thin 8-inch round.",
                   "Scatter a quarter of the meat and some spring onion over the surface while the top is still wet, then crack an egg into the center.",
                   "Cover and cook on medium-low until the base is set with a lacy browned underside and the egg is barely set, four to five minutes; a chatamari is never flipped.",
                   "Slide it out whole, repeat with the remaining batter and toppings, and cut each into wedges to share, hands only, the way a Newar feast would.",
               ],
               note: "Never flip it and never rush the covered stage; the lid steams the egg and topping while the rice base crisps underneath, which is the whole trick.",
               shortcut: "Call it Nepali pizza and a skeptical table will try it, though in Kathmandu that nickname costs you some goodwill."),
        Recipe(dishID: "nepal-selroti", serves: 6, prepMinutes: 25, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "rice flour"),
                   RecipeIngredient(amount: "1", item: "ripe banana, mashed smooth"),
                   RecipeIngredient(amount: "1/2 cup", item: "sugar"),
                   RecipeIngredient(amount: "2 tbsp", item: "ghee, melted (or butter)"),
                   RecipeIngredient(amount: "1 cup", item: "whole milk, more as needed"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "a pinch", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "vegetable oil, for deep frying"),
               ],
               steps: [
                   "Whisk the rice flour, mashed banana, sugar, melted ghee, cardamom, salt, and milk into a thick but pourable batter, like heavy pancake batter that falls in a slow ribbon.",
                   "Rest the batter at room temperature at least an hour; it loosens slightly and picks up the faint tang that marks a proper sel.",
                   "Heat two inches of oil in a wide pot to 350°F, checked with a thermometer or a drop of batter that rises and sizzles at once.",
                   "Load the batter into a squeeze bottle or a zip-top bag with a corner snipped, the honest home stand-in for the traditional pour from the fist.",
                   "Pipe a steady stream into the oil in one continuous circle, about six inches across, joining the ends; nudge it round with a skewer if it drifts.",
                   "Fry until the ring puffs and turns deep gold, about two minutes per side, turning once with two skewers or tongs.",
                   "Drain on a rack, not paper, so the shell stays crisp, and repeat. Serve with yogurt or potato curry, or stack them for the week; they keep for days.",
               ],
               note: "The batter thickness decides everything: too thin and the ring breaks apart in the oil, too thick and the crumb turns heavy instead of springy.",
               shortcut: "Skip the ring and drop spoonfuls like fritters; children will not complain, but it stops being sel roti and becomes very good doughnut holes."),
        Recipe(dishID: "nepal-gundruk", serves: 4, prepMinutes: 10, cookMinutes: 30, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "gundruk (Nepali grocer or online; or rinsed sauerkraut plus a handful of chopped kale, a rough but workable stand-in)"),
                   RecipeIngredient(amount: "2", item: "medium potatoes, cut in chunks"),
                   RecipeIngredient(amount: "1/2 cup", item: "cooked soybeans or shelled edamame"),
                   RecipeIngredient(amount: "2", item: "ripe tomatoes, chopped"),
                   RecipeIngredient(amount: "3", item: "dried red chiles"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, sliced"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "2 tbsp", item: "mustard oil or vegetable oil"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
               ],
               steps: [
                   "Soak the gundruk in warm water ten minutes to soften, then drain it and chop it roughly; sauerkraut needs only a rinse and a squeeze.",
                   "Heat the oil in a soup pot until shimmering and fry the dried chiles and garlic until the garlic edges turn gold and the chiles darken.",
                   "Add the tomatoes and cook, stirring, until they slump into a rough sauce, three to four minutes.",
                   "Stir in the potatoes and turmeric, then pour in the water and simmer until the potatoes are just tender, about 12 minutes.",
                   "Add the gundruk and soybeans and simmer ten more minutes, so the broth picks up the sour, faintly smoky funk that names the dish.",
                   "Season with salt, taste, and let it sit five minutes; the broth should be thin, sharp, and bracing. Ladle it beside rice or dhindo.",
               ],
               note: "The broth stays thin on purpose; this is a sour winter tonic beside rice, not a stew, and the smell while cooking is the authentic part.",
               shortcut: "The sauerkraut-and-kale version misses the smoky dried-leaf depth but delivers the sour heat of the real jhol on a weeknight."),
        Recipe(dishID: "nepal-dhindo", serves: 4, prepMinutes: 5, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "millet flour (or fine cornmeal as a last resort)"),
                   RecipeIngredient(amount: "1 cup", item: "buckwheat flour"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
                   RecipeIngredient(amount: "1 tbsp", item: "ghee, divided"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Bring the water to a rolling boil in a heavy pot with the salt and half the ghee; the fat keeps the mass from welding itself to the pan.",
                   "Rain in the two flours a handful at a time with one hand while whisking hard with the other, until the mixture thickens past whisking.",
                   "Switch to a strong wooden spoon or paddle and stir vigorously over medium heat, folding from the edges into the center, for eight to ten minutes.",
                   "Keep working it until the dhindo turns glossy, stiff, and elastic and pulls cleanly away from the sides of the pot in one mass.",
                   "Beat in the remaining ghee, cover, and rest two minutes off the heat so it firms enough to hold its shape on a plate.",
                   "Scoop mounds onto plates with a wet spoon and eat by pinching off lumps with your fingers, dipping into gundruk soup or curry, swallowing more than chewing, as the hills do.",
               ],
               note: "The stirring arm is the only real ingredient; stop early and it stays gluey, keep going until it is glossy and leaves the pot clean.",
               shortcut: "All buckwheat flour, sold as farine de sarrasin in many supermarkets, works alone if millet flour proves hard to find."),
        Recipe(dishID: "nepal-jujudhau", serves: 6, prepMinutes: 15, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1/2 gallon", item: "whole milk"),
                   RecipeIngredient(amount: "1 cup", item: "heavy cream (with the milk, the closest stand-in for buffalo milk)"),
                   RecipeIngredient(amount: "1/2 cup", item: "sugar"),
                   RecipeIngredient(amount: "5", item: "green cardamom pods, cracked"),
                   RecipeIngredient(amount: "2", item: "whole cloves"),
                   RecipeIngredient(amount: "3 tbsp", item: "plain yogurt with live active cultures"),
               ],
               steps: [
                   "Simmer the milk and cream with the cardamom and cloves in a wide, heavy pot, stirring often, until reduced by about a quarter, 30 to 40 minutes.",
                   "Stir in the sugar until dissolved, then pull out the whole spices and let the milk cool until a drop on your wrist feels warm but not hot, about 110°F.",
                   "Whisk the yogurt with a ladle of the warm milk until smooth, then stir it back into the pot gently and briefly.",
                   "Pour into an unglazed clay pot if you have one, which wicks out moisture overnight the Bhaktapur way, or a ceramic bowl if you do not.",
                   "Cover with a plate, wrap in a thick towel, and leave undisturbed in a turned-off oven with the light on for six to eight hours, until set.",
                   "Refrigerate at least four hours; the curd tightens into something thick enough to hold a spoon upright, and it is eaten straight from the pot it set in.",
               ],
               note: "Reduction is what separates this from ordinary yogurt: do not skip the simmer, and do not move the pot while it sets or it splits into curds and whey.",
               shortcut: "A new, well-scrubbed unglazed terracotta plant pot with no drainage hole does the clay pot's moisture-wicking work for a few dollars."),
    ]

    static let all: [Recipe] = recipes_india + recipes_srilanka + recipes_nepal
}
