import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesNorthEurope {

    private static let recipes_poland: [Recipe] = [
        Recipe(dishID: "poland-pierogi-ruskie", serves: 4, prepMinutes: 55, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1", item: "large egg"),
                   RecipeIngredient(amount: "3/4 cup", item: "warm water"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "1 lb", item: "russet potatoes"),
                   RecipeIngredient(amount: "8 oz", item: "farmer's cheese (or whole-milk ricotta, drained well)"),
                   RecipeIngredient(amount: "2", item: "yellow onions, diced"),
                   RecipeIngredient(amount: "5 tbsp", item: "butter, divided"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "1/2 cup", item: "sour cream, for serving"),
               ],
               steps: [
                   "Peel and boil the potatoes in salted water until a knife slides through, about 15 minutes. Drain, mash, and let cool while you make the dough.",
                   "Stir the flour and 1 teaspoon salt together, then work in the egg and warm water until a shaggy dough forms. Knead 5 minutes until smooth, cover, and rest 30 minutes.",
                   "Melt 2 tablespoons butter in a skillet and cook half the diced onion slowly until deep gold, about 10 minutes. Stir it into the potatoes with the cheese, pepper, and remaining salt.",
                   "Roll the dough to about 1/8 inch on a floured counter and cut 3-inch rounds with a glass, rerolling scraps once.",
                   "Put a scant tablespoon of filling on each round, fold into a half-moon, and pinch the edge firmly shut, working out any air. A dab of water helps a dry edge seal.",
                   "Boil the pierogi in batches in well-salted water. They are done about 1 minute after they float to the surface; lift them out with a slotted spoon.",
                   "Fry the remaining onion in the last 3 tablespoons of butter until golden, then add the boiled pierogi and cook until the edges catch and brown in spots.",
                   "Serve six to eight per plate with the buttery onions spooned over and sour cream on the side.",
               ],
               note: "Roll the dough thinner than feels safe. Thick edges turn gummy in the pot, and the filling is soft enough that the dough only needs to hold, not chew.",
               shortcut: "Skip the pan-frying and serve them straight from the pot with melted butter; you lose the browned edges but save a skillet and ten minutes."),
        Recipe(dishID: "poland-bigos", serves: 6, prepMinutes: 30, cookMinutes: 180, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "sauerkraut, drained but not rinsed"),
                   RecipeIngredient(amount: "1 lb", item: "white cabbage, shredded"),
                   RecipeIngredient(amount: "1 lb", item: "pork shoulder, cut in 1-inch cubes"),
                   RecipeIngredient(amount: "12 oz", item: "kielbasa, sliced thick"),
                   RecipeIngredient(amount: "1 oz", item: "dried porcini or mixed dried mushrooms"),
                   RecipeIngredient(amount: "8", item: "prunes, halved"),
                   RecipeIngredient(amount: "1", item: "large onion, diced"),
                   RecipeIngredient(amount: "2 tbsp", item: "lard or neutral oil"),
                   RecipeIngredient(amount: "2", item: "bay leaves"),
                   RecipeIngredient(amount: "1 tsp", item: "caraway seeds"),
                   RecipeIngredient(amount: "1 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "2 cups", item: "water, plus more as needed"),
               ],
               steps: [
                   "Cover the dried mushrooms with 1 cup of hot water and let them soak while you brown the meat. Keep the soaking liquid.",
                   "Heat the lard in a heavy pot and brown the pork shoulder hard on two sides, working in batches so it sears instead of steams. Set the meat aside.",
                   "Cook the onion in the same pot until soft and golden, scraping up the browned bits, then add the kielbasa and let it take some color.",
                   "Return the pork with the sauerkraut, fresh cabbage, chopped soaked mushrooms and their liquid (leave any grit behind), prunes, bay leaves, caraway, pepper, and 2 cups water.",
                   "Bring to a bare simmer, cover with the lid ajar, and cook 2 1/2 to 3 hours, stirring every half hour and adding a splash of water if it threatens to stick.",
                   "It is ready when the cabbage has gone soft and khaki-brown and the pork pulls apart with a spoon. Taste and add salt only at the end; the kraut usually carries enough.",
                   "Rest the pot off the heat at least 30 minutes, or better, refrigerate overnight and reheat. Serve hot with dark rye bread.",
               ],
               note: "Bigos made and eaten the same day tastes unfinished. Cook it a day ahead; the overnight rest is when the sour, smoke, and prune sweetness fuse into one flavor.",
               shortcut: "Use all kielbasa and skip the pork shoulder to cut an hour of simmering; you lose the shreddy braised texture but keep the smoky core."),
        Recipe(dishID: "poland-zurek", serves: 4, prepMinutes: 20, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1/2 cup", item: "rye flour"),
                   RecipeIngredient(amount: "6 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "12 oz", item: "fresh white sausage (or mild uncooked bratwurst)"),
                   RecipeIngredient(amount: "4 oz", item: "smoked bacon, diced"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "dried marjoram"),
                   RecipeIngredient(amount: "1/2 cup", item: "brine from a jar of sauerkraut"),
                   RecipeIngredient(amount: "4", item: "eggs"),
                   RecipeIngredient(amount: "1/2 cup", item: "sour cream"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
               ],
               steps: [
                   "Boil the eggs for 9 minutes, cool them under running water, peel, and halve. Set aside for serving.",
                   "Whisk the rye flour with 1 cup of cold water until completely smooth. This stands in for the fermented rye starter; the sourness comes later from the sauerkraut brine.",
                   "Cook the bacon in a soup pot over medium heat until its fat renders and the edges crisp, then add the whole sausages and brown them lightly on all sides.",
                   "Pour in the stock and simmer gently 15 minutes so the sausage cooks through and flavors the broth. Lift out the sausages, slice them thick, and return the slices to the pot.",
                   "Whisk the rye slurry again and stir it into the simmering soup. Cook 10 minutes, stirring often, until the soup thickens to the texture of thin gravy.",
                   "Add the garlic, marjoram, pepper, and sauerkraut brine. Simmer 5 more minutes, then taste; it should be distinctly tart, like buttermilk. Add more brine a spoonful at a time if it is flat.",
                   "Temper the sour cream with a ladle of hot soup, stir it back in, and heat without boiling. Serve each bowl with two egg halves on top.",
               ],
               note: "The real thing sours rye flour and water for four or five days; this weeknight version borrows its tang from sauerkraut brine. Do not skip the brine, or it is just sausage soup.",
               shortcut: "Some Polish groceries and online shops sell bottled zurek starter; a cup of it replaces both the rye slurry and the brine with a truer sourness."),
        Recipe(dishID: "poland-zapiekanka", serves: 2, prepMinutes: 15, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1", item: "baguette"),
                   RecipeIngredient(amount: "8 oz", item: "button mushrooms, sliced thin"),
                   RecipeIngredient(amount: "1", item: "small onion, diced fine"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2 cups", item: "shredded gouda or mozzarella"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/4 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "3 tbsp", item: "ketchup"),
                   RecipeIngredient(amount: "2 tbsp", item: "chopped chives"),
               ],
               steps: [
                   "Heat the oven to 425°F. Split the baguette lengthwise into two long open halves and pull out a little of the soft crumb so the toppings have somewhere to sit.",
                   "Melt the butter in a skillet over medium-high heat and cook the onion 2 minutes, then add the mushrooms, salt, and pepper.",
                   "Cook the mushrooms until their water releases and boils away and they begin to brown, 8 to 10 minutes. A wet topping makes soggy bread, so be patient here.",
                   "Spread the mushroom mixture evenly over the cut sides of the bread, then cover it edge to edge with the shredded cheese.",
                   "Bake directly on the oven rack 10 to 12 minutes, until the cheese is molten and browning in spots and the crust is audibly crisp.",
                   "Stripe each half generously with ketchup, scatter the chives over, and eat hot with both hands over the wrapper.",
               ],
               note: "Cook the mushrooms until genuinely dry and browning. Every failed zapiekanka fails the same way: mushroom water soaking the bread under a raft of cheese.",
               shortcut: "A par-baked supermarket demi-baguette crisps better than a soft sandwich roll; using pre-shredded cheese is fine here since browning hides its coating."),
        Recipe(dishID: "poland-schabowy", serves: 4, prepMinutes: 20, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "boneless pork loin chops, about 6 oz each"),
                   RecipeIngredient(amount: "1/2 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "fine dry breadcrumbs"),
                   RecipeIngredient(amount: "4 tbsp", item: "lard (or neutral oil)"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1", item: "lemon, cut in wedges"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
               ],
               steps: [
                   "Trim the chops of any silverskin, lay them between sheets of plastic wrap, and pound with a pan or mallet to an even 1/4 inch. Thinness matters more than neatness.",
                   "Season both sides with the salt and pepper. Set up three shallow dishes: flour, eggs beaten until uniform, and breadcrumbs.",
                   "Dredge each cutlet in flour and shake off the excess, drag it through the egg, then press it into the crumbs so they stick everywhere. Do not compact the coating.",
                   "Heat the lard with the butter in a wide skillet over medium-high until a pinch of crumbs sizzles instantly. The fat should be a good 1/4 inch deep.",
                   "Fry one or two cutlets at a time, 2 to 3 minutes per side, spooning fat over the top, until the crust is deep gold and puffed slightly away from the meat.",
                   "Drain briefly on a rack or paper towels, salt lightly while hot, and serve at once with lemon wedges, boiled potatoes with dill, and shredded cabbage salad.",
               ],
               note: "Pound thin and fry in fat deep enough to half-float the cutlet. A crust that puffs away from the pork in blisters is the mark you are after.",
               shortcut: "Thin-cut pork chops from the meat case skip the pounding; they are a shade less tender but go from fridge to plate in twenty minutes."),
        Recipe(dishID: "poland-paczki", serves: 8, prepMinutes: 50, cookMinutes: 25, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 1/2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 cup", item: "warm whole milk"),
                   RecipeIngredient(amount: "4", item: "egg yolks"),
                   RecipeIngredient(amount: "1/4 cup", item: "sugar"),
                   RecipeIngredient(amount: "4 tbsp", item: "soft butter"),
                   RecipeIngredient(amount: "1 tsp", item: "vanilla extract"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3/4 cup", item: "rose petal jam (or thick raspberry jam)"),
                   RecipeIngredient(amount: "6 cups", item: "neutral oil, for frying"),
                   RecipeIngredient(amount: "1 cup", item: "powdered sugar"),
                   RecipeIngredient(amount: "2 tbsp", item: "orange juice"),
               ],
               steps: [
                   "Whisk the flour, yeast, sugar, and salt, then add the warm milk, yolks, and vanilla and mix into a soft dough. Knead in the butter a tablespoon at a time until silky, about 10 minutes.",
                   "Cover and let rise in a warm spot until doubled, 1 to 1 1/2 hours. The dough should be pillowy and hold a fingerprint.",
                   "Roll to 1/2 inch thick on a floured counter and cut 3-inch rounds. Reroll scraps once. Cover the rounds and let them puff again, 30 to 40 minutes.",
                   "Heat the oil in a deep pot to 350°F, checking with a thermometer. Too hot and the crust darkens before the middle cooks; too cool and they drink oil.",
                   "Fry two or three at a time, about 2 minutes per side, until deep gold with a pale ring around the equator. That ring means the dough rose properly before it hit the fat.",
                   "Drain on a rack. Once cool enough to handle, fill a piping bag or a squeeze bottle with jam, poke into the pale side of each paczek, and squeeze in a generous spoonful.",
                   "Stir the powdered sugar with the orange juice into a thin glaze and brush or drizzle it over the tops. Let it set 10 minutes before serving with coffee.",
               ],
               note: "Watch for the pale ring around the middle when frying; no ring means the dough was underproofed and the crumb inside will be tight and heavy instead of springy.",
               shortcut: "Fill with jam from a zip-top bag with a corner snipped and a chopstick-poked hole; a proper piping tip is neater but not necessary."),
        Recipe(dishID: "poland-sledz", serves: 4, prepMinutes: 20, cookMinutes: 0, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "8 oz", item: "matjes or pickled herring fillets, drained"),
                   RecipeIngredient(amount: "1 cup", item: "sour cream"),
                   RecipeIngredient(amount: "1", item: "small red onion, sliced paper thin"),
                   RecipeIngredient(amount: "1", item: "tart apple, such as granny smith"),
                   RecipeIngredient(amount: "1 tbsp", item: "lemon juice"),
                   RecipeIngredient(amount: "2 tbsp", item: "chopped fresh dill"),
                   RecipeIngredient(amount: "1/2 tsp", item: "coarsely ground black pepper"),
                   RecipeIngredient(amount: "8 slices", item: "rye bread, for serving"),
               ],
               steps: [
                   "Taste a piece of the herring. If it is aggressively salty, soak the fillets in cold milk or water for 30 minutes, then pat dry; matjes-style usually needs no soak.",
                   "Cut the herring into neat 1-inch pieces and lay them in a shallow dish.",
                   "Put the sliced onion in a small bowl of ice water for 10 minutes to tame its bite, then drain and pat dry.",
                   "Peel and core the apple and cut it into small dice, tossing the pieces with the lemon juice so they stay white.",
                   "Stir the sour cream with the pepper and half the dill, then fold in the onion and apple. Spoon the dressing over the herring and turn gently to coat every piece.",
                   "Cover and refrigerate at least 1 hour so the cream takes on the herring's salt. Scatter the remaining dill on top and serve cold with rye bread.",
               ],
               note: "The hour in the fridge is not optional; the dish comes together when the cream pulls salt from the fish and the onion and apple loosen into the dressing.",
               shortcut: "A jar of herring already in wine sauce works if you rinse off its marinade first; the flavor leans sweeter than the classic salted cure."),
        Recipe(dishID: "poland-oscypek", serves: 4, prepMinutes: 10, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "12 oz", item: "smoked scamorza (or halloumi)"),
                   RecipeIngredient(amount: "1 tbsp", item: "butter"),
                   RecipeIngredient(amount: "3/4 cup", item: "whole-berry cranberry sauce"),
                   RecipeIngredient(amount: "1 tsp", item: "lemon juice"),
                   RecipeIngredient(amount: "1/4 tsp", item: "coarsely ground black pepper"),
                   RecipeIngredient(amount: "1", item: "small loaf crusty bread, sliced"),
               ],
               steps: [
                   "Stir the cranberry sauce with the lemon juice so it tastes tart rather than jammy, and set it aside in a small serving bowl. Real oscypek gets exactly this pairing at the mountain stalls.",
                   "Slice the cheese into rounds or slabs about 1/2 inch thick. Pat them dry; a dry surface browns, a wet one steams.",
                   "Heat a cast-iron skillet or grill pan over medium-high until a drop of water skitters, then film it with the butter.",
                   "Lay in the cheese slices with space between them and leave them alone for 2 to 3 minutes, until the undersides blister and brown and the edges begin to slump.",
                   "Flip once and cook 1 to 2 minutes more, until the second side colors and the centers are warm and pliable but not melted into a puddle.",
                   "Grind pepper over, and serve straight from the pan on a board with the cranberry sauce and bread. Eat while it is hot; the squeak fades as it cools.",
               ],
               note: "True oscypek rarely leaves Poland, so the game is texture: a smoked, salty cheese that browns without collapsing. Serve it hot off the pan or the magic stiffens away.",
               shortcut: "Halloumi is easier to find than smoked scamorza and holds its shape better; you trade the pine-smoke note for a saltier, squeakier bite."),
    ]

    private static let recipes_sweden: [Recipe] = [
        Recipe(dishID: "sweden-kottbullar", serves: 4, prepMinutes: 30, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1/2 lb", item: "ground beef"),
                   RecipeIngredient(amount: "1/2 lb", item: "ground pork"),
                   RecipeIngredient(amount: "1/2 cup", item: "fine breadcrumbs"),
                   RecipeIngredient(amount: "1/2 cup", item: "whole milk"),
                   RecipeIngredient(amount: "1", item: "small yellow onion, grated"),
                   RecipeIngredient(amount: "1", item: "egg"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground allspice"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "white pepper"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter, divided"),
                   RecipeIngredient(amount: "2 tbsp", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "beef stock"),
                   RecipeIngredient(amount: "1/2 cup", item: "heavy cream"),
                   RecipeIngredient(amount: "1/2 cup", item: "lingonberry jam (or whole-berry cranberry sauce)"),
               ],
               steps: [
                   "Soak the breadcrumbs in the milk for 10 minutes until they swell into a paste. This soaked panade is what keeps the meatballs soft instead of rubbery.",
                   "Mix the beef, pork, grated onion, egg, allspice, salt, and white pepper into the panade with your hands, just until even. Overworking makes them dense.",
                   "Roll into balls a little smaller than a golf ball with wet hands, setting them on a tray. You should get 24 to 28.",
                   "Brown the meatballs in 2 tablespoons of butter over medium heat, shaking the pan to turn them, working in two batches. They need color more than they need to cook through here.",
                   "Set the meatballs aside, melt the remaining butter in the same pan, and whisk in the flour. Cook 1 minute, then whisk in the stock gradually until smooth.",
                   "Add the cream, return the meatballs and their juices, and simmer gently 8 to 10 minutes until the sauce coats a spoon and the meatballs are cooked through.",
                   "Taste the gravy for salt and pepper, and serve with boiled potatoes, a spoonful of lingonberry jam on the plate, and pickled cucumber if you have it.",
               ],
               note: "Grate the onion instead of chopping it; the raw juice seasons the meat evenly and disappears, and the lingonberry is structural, not decorative. The plate needs its acid.",
               shortcut: "IKEA sells frozen lingonberry jam and it is the real thing; whole-berry cranberry sauce sharpened with a squeeze of lemon is the everyday substitute."),
        Recipe(dishID: "sweden-gravlax", serves: 8, prepMinutes: 25, cookMinutes: 0, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "center-cut salmon fillet, skin on, pin bones removed"),
                   RecipeIngredient(amount: "1/4 cup", item: "kosher salt"),
                   RecipeIngredient(amount: "1/4 cup", item: "sugar"),
                   RecipeIngredient(amount: "2 tsp", item: "white peppercorns, crushed"),
                   RecipeIngredient(amount: "2 large bunches", item: "fresh dill"),
                   RecipeIngredient(amount: "3 tbsp", item: "dijon mustard"),
                   RecipeIngredient(amount: "1 tbsp", item: "sugar (for the sauce)"),
                   RecipeIngredient(amount: "2 tbsp", item: "white wine vinegar"),
                   RecipeIngredient(amount: "1/2 cup", item: "neutral oil"),
                   RecipeIngredient(amount: "1 loaf", item: "dark rye bread, for serving"),
               ],
               steps: [
                   "Buy the freshest salmon you can and freeze it solid for at least 3 days first if it was not sold as sushi-grade or previously frozen; the cure adds flavor, not safety.",
                   "Mix the salt, sugar, and crushed white pepper. Lay the fillet skin side down on a double sheet of plastic wrap and pack the cure evenly over the flesh.",
                   "Cover the surface completely with roughly chopped dill, stems and all, pressing it into the cure.",
                   "Wrap tightly, set the parcel in a rimmed dish, and put a small cutting board with a couple of cans on top. Refrigerate 48 hours, flipping the parcel once a day.",
                   "For the sauce, whisk the mustard, sugar, and vinegar, then drizzle in the oil while whisking until it thickens. Stir in a handful of chopped dill.",
                   "Unwrap the salmon, scrape off the dill and cure, and pat dry. The flesh should be firm and slightly translucent, like smoked salmon.",
                   "Slice thin on a long diagonal, freeing each slice from the skin, and serve on a board with the mustard sauce and rye bread.",
               ],
               note: "The weight is what firms the flesh; without it the cure seasons but never transforms. Forty-eight hours under cans, flipped daily, and the texture turns silken.",
               shortcut: "Cure a 12 oz piece for 24 hours instead; the flavor is gentler and the slices softer, but it turns a weekend project into an overnight one."),
        Recipe(dishID: "sweden-skagen", serves: 4, prepMinutes: 15, cookMinutes: 5, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "small cooked cold-water shrimp, peeled"),
                   RecipeIngredient(amount: "1/2 cup", item: "mayonnaise"),
                   RecipeIngredient(amount: "1/4 cup", item: "crème fraîche or sour cream"),
                   RecipeIngredient(amount: "3 tbsp", item: "chopped fresh dill"),
                   RecipeIngredient(amount: "1 tbsp", item: "lemon juice, plus wedges for serving"),
                   RecipeIngredient(amount: "1/4 tsp", item: "white pepper"),
                   RecipeIngredient(amount: "4 slices", item: "white sandwich bread"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2 oz", item: "salmon roe (optional but traditional)"),
               ],
               steps: [
                   "Drain the shrimp well and press them gently between paper towels; a watery shrimp salad is the dish's one failure mode.",
                   "Stir the mayonnaise, crème fraîche, dill, lemon juice, and white pepper together in a bowl.",
                   "Fold in the shrimp and taste. It should be creamy but distinctly lemony; add another squeeze if the richness sits too flat. Chill while you fry the bread.",
                   "Cut the crusts off the bread and halve each slice into triangles. Melt the butter in a skillet over medium heat.",
                   "Fry the bread 1 to 2 minutes per side until golden and crisp at the edges, adding a little more butter if the pan goes dry.",
                   "Pile the shrimp mixture high on the warm toast, top each with a small spoonful of roe, and serve immediately with lemon wedges, knife and fork.",
               ],
               note: "Use the small sweet cold-water shrimp, not big warm-water ones; the dish depends on many tender pieces in every bite, not a few bouncy chunks.",
               shortcut: "Frozen cooked bay shrimp, thawed and pressed very dry, work well; skip the roe rather than substitute the neon-red imitation kind."),
        Recipe(dishID: "sweden-artsoppa", serves: 6, prepMinutes: 15, cookMinutes: 120, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "yellow split peas, rinsed"),
                   RecipeIngredient(amount: "1", item: "smoked ham hock (or 3/4 lb salt pork in one piece)"),
                   RecipeIngredient(amount: "1", item: "large yellow onion, diced"),
                   RecipeIngredient(amount: "2 tsp", item: "dried thyme"),
                   RecipeIngredient(amount: "1 tsp", item: "dried marjoram"),
                   RecipeIngredient(amount: "8 cups", item: "water"),
                   RecipeIngredient(amount: "1 tsp", item: "salt, or to taste"),
                   RecipeIngredient(amount: "1/4 cup", item: "spicy brown or hot swedish-style mustard, for serving"),
               ],
               steps: [
                   "Put the rinsed peas, ham hock, onion, thyme, marjoram, and water in a large pot and bring to a boil, skimming any gray foam that rises in the first few minutes.",
                   "Lower to a gentle simmer, cover with the lid ajar, and cook 1 1/2 to 2 hours, stirring now and then so the peas do not catch on the bottom.",
                   "The soup is ready when most of the peas have broken down into a thick, mealy porridge with some whole ones still holding shape, and the hock meat is loose on the bone.",
                   "Lift out the hock, pull the meat from the bone and skin, chop it, and stir it back into the pot.",
                   "Season with salt only now; the hock releases salt as it cooks and early salting also keeps the peas stubborn. Thin with hot water if it has gone stodgy.",
                   "Serve in deep bowls, each with a sharp stripe of mustard stirred in at the table. Thin pancakes with jam afterward if you are doing Thursday properly.",
               ],
               note: "Salt at the end, never the start, and do not fear the porridge texture; artsoppa is supposed to sit halfway between soup and something you could stand a spoon in.",
               shortcut: "Yellow split peas need no overnight soak despite what the bag says; a straight two-hour simmer gets you there, so this is really a one-pot afternoon."),
        Recipe(dishID: "sweden-raggmunk", serves: 4, prepMinutes: 20, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 cups", item: "whole milk"),
                   RecipeIngredient(amount: "1", item: "egg"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "russet potatoes"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/4 tsp", item: "white or black pepper"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter, plus more as needed"),
                   RecipeIngredient(amount: "3/4 lb", item: "thick-cut bacon or salt pork, cut in strips"),
                   RecipeIngredient(amount: "3/4 cup", item: "lingonberry jam (or whole-berry cranberry sauce)"),
               ],
               steps: [
                   "Whisk the flour with half the milk until smooth, then whisk in the rest of the milk, the egg, salt, and pepper. Let the batter rest while you handle the potatoes.",
                   "Fry the bacon strips in a large skillet until browned but still chewy, then set them aside and pour off all but a film of the fat.",
                   "Peel the potatoes and grate them coarsely straight into the batter, stirring them in as you go so they do not brown. Do not rinse the shreds; their starch binds the pancakes.",
                   "Melt a tablespoon of butter in the skillet over medium-high heat. Ladle in batter to make pancakes about 5 inches across, spreading the shreds into a thin, even layer.",
                   "Fry 3 to 4 minutes per side, until the edges turn to deep-brown lace and the center is cooked through. Add butter between batches and keep finished pancakes warm in a low oven.",
                   "Serve straight from the skillet in stacks, with the bacon alongside and a generous spoonful of lingonberry jam on every plate.",
               ],
               note: "Grate the potatoes at the last minute and straight into the batter; once they gray from the air, the pancakes look sad no matter how well they fry.",
               shortcut: "Frozen shredded hash browns, thawed and squeezed, save the grating; the pancakes come out a little drier, so add an extra splash of milk."),
        Recipe(dishID: "sweden-kanelbullar", serves: 8, prepMinutes: 45, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "4 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 cup", item: "whole milk, warmed"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1/3 cup", item: "sugar"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "ground cardamom"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "10 tbsp", item: "butter, softened, divided"),
                   RecipeIngredient(amount: "1/2 cup", item: "packed brown sugar"),
                   RecipeIngredient(amount: "1 1/2 tbsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "1", item: "egg, beaten, for glazing"),
                   RecipeIngredient(amount: "1/3 cup", item: "pearl sugar (or coarsely crushed sugar cubes)"),
               ],
               steps: [
                   "Whisk the flour, yeast, sugar, cardamom, and salt, then add the warm milk and mix into a shaggy dough. Knead in 6 tablespoons of the butter until the dough is smooth and elastic, about 10 minutes.",
                   "Cover and let rise until doubled, about 1 hour. Meanwhile mash the remaining 4 tablespoons butter with the brown sugar and cinnamon into a spreadable paste.",
                   "Roll the dough into a rectangle about 12 by 18 inches and spread the cinnamon butter to the edges.",
                   "Fold the rectangle in thirds like a letter, then cut crosswise into 12 strips. Twist each strip and coil it into a loose knot, tucking the tail underneath.",
                   "Set the buns on lined baking sheets, cover, and let puff 30 to 40 minutes until they wobble slightly when the pan is nudged. Heat the oven to 425°F.",
                   "Brush with beaten egg, scatter pearl sugar over generously, and bake 8 to 10 minutes until deep golden brown.",
                   "Cool on a rack at least 15 minutes. Eat the same day with strong coffee; that is the entire point of them.",
               ],
               note: "Cardamom in the dough is what makes them Swedish rather than American mall buns; buy whole pods and crush the seeds if you can, the aroma difference is enormous.",
               shortcut: "Skip the twist-and-knot and roll the sheet into a log, slicing pinwheels like American cinnamon rolls; less handsome, same flavor, ten minutes saved."),
        Recipe(dishID: "sweden-vasterbottenspaj", serves: 6, prepMinutes: 30, cookMinutes: 50, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/4 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "8 tbsp", item: "cold butter, cubed"),
                   RecipeIngredient(amount: "2-3 tbsp", item: "ice water"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "3", item: "eggs"),
                   RecipeIngredient(amount: "3/4 cup", item: "heavy cream"),
                   RecipeIngredient(amount: "10 oz", item: "vasterbotten cheese, grated (or aged white cheddar plus 1 oz grated parmesan)"),
                   RecipeIngredient(amount: "1/4 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "2 tbsp", item: "chopped fresh dill, for serving"),
               ],
               steps: [
                   "Rub the cold butter into the flour and salt until the mixture looks like damp sand with some pea-size lumps, then add ice water a spoonful at a time until it just holds together.",
                   "Press the dough into a disk, wrap, and chill 30 minutes. Roll it out and line a 9-inch tart or pie pan, pricking the base all over with a fork. Freeze 10 minutes.",
                   "Heat the oven to 400°F. Line the shell with foil and pie weights or dry beans and bake 15 minutes, then remove the foil and bake 5 more until the base looks dry.",
                   "Whisk the eggs with the cream and pepper, then stir in the grated cheese. Go easy on added salt; the cheese brings plenty.",
                   "Pour the filling into the warm shell and turn the oven down to 350°F.",
                   "Bake 25 to 30 minutes, until the filling is set at the edges with the faintest wobble at the center and the top is spotted gold.",
                   "Rest 15 minutes before slicing. Serve warm in wedges with dill scattered over, and cold shrimp alongside if you are pretending it is August in Sweden.",
               ],
               note: "Pull it while the center still trembles slightly; the custard finishes setting as it rests, and an overbaked cheese pie turns grainy and loses its salty cream.",
               shortcut: "A store-bought refrigerated pie crust, blind-baked, cuts half an hour; the filling is the star, so the pastry downgrade is barely noticed."),
        Recipe(dishID: "sweden-pitepalt", serves: 4, prepMinutes: 45, cookMinutes: 50, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 lb", item: "russet potatoes"),
                   RecipeIngredient(amount: "1 cup", item: "barley flour (or 1 1/4 cups all-purpose flour)"),
                   RecipeIngredient(amount: "1/2 cup", item: "all-purpose flour, plus more for shaping"),
                   RecipeIngredient(amount: "2 tsp", item: "salt, plus more for the pot"),
                   RecipeIngredient(amount: "6 oz", item: "salt pork or slab bacon, cut in 1/2-inch cubes"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter, for serving"),
                   RecipeIngredient(amount: "3/4 cup", item: "lingonberry jam (or whole-berry cranberry sauce)"),
               ],
               steps: [
                   "Peel and finely grate the raw potatoes into a clean kitchen towel, then twist and wring hard over the sink until they stop dripping. Dry potato is what holds these together.",
                   "Mix the wrung-out potato with the barley flour, all-purpose flour, and salt into a firm, slightly sticky gray dough. Work in more flour a spoonful at a time if it will not hold a ball.",
                   "Cook the salt pork cubes in a skillet just until the fat starts to render, 3 to 4 minutes; they finish cooking inside the dumplings.",
                   "With floured hands, shape the dough into 8 balls, poke a deep pocket into each, tuck in a few pork cubes, and pinch the dough closed around them.",
                   "Bring a wide pot of generously salted water to a bare simmer, never a rolling boil, and lower in the dumplings. Loosen any that stick to the bottom after a minute.",
                   "Simmer gently, uncovered, 45 to 50 minutes, turning them once, until they float, look glossy, and a skewer meets no raw paste at the center.",
                   "Serve hot, split open, with a knob of butter melting into each and lingonberry jam on the side. Fry leftover slices in butter tomorrow; many prefer them that way.",
               ],
               note: "A rolling boil tears them apart; keep the water at a shiver. And the dense, gluey bite is correct, so do not chase fluffiness that was never intended.",
               shortcut: "All-purpose flour instead of barley flour works fine and is what many Swedish kitchens use now; you lose a little of the nutty gray earthiness."),
    ]

    private static let recipes_hungary: [Recipe] = [
        Recipe(dishID: "hungary-gulyas", serves: 6, prepMinutes: 30, cookMinutes: 150, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "beef chuck or shin, cut in 3/4-inch cubes"),
                   RecipeIngredient(amount: "2", item: "large onions, diced fine"),
                   RecipeIngredient(amount: "2 tbsp", item: "lard or neutral oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1 tsp", item: "caraway seeds, crushed"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1", item: "ripe tomato, chopped"),
                   RecipeIngredient(amount: "1", item: "hungarian wax or cubanelle pepper, sliced"),
                   RecipeIngredient(amount: "2", item: "carrots, cut in thick coins"),
                   RecipeIngredient(amount: "1 lb", item: "potatoes, cut in 3/4-inch chunks"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "egg (for the csipetke noodles)"),
                   RecipeIngredient(amount: "1/2 cup", item: "all-purpose flour (for the csipetke noodles)"),
               ],
               steps: [
                   "Melt the lard in a heavy pot and cook the onions over medium-low heat until soft, golden, and collapsed, 15 to 20 minutes. Do not rush this; the onions are the body of the soup.",
                   "Pull the pot off the heat, stir in the paprika for 30 seconds so it blooms without scorching, then immediately add the beef, caraway, garlic, and salt and stir to coat.",
                   "Return to low heat, cover, and let the beef stew in its own juices 30 minutes, stirring occasionally. This dry-ish start is what separates gulyas from generic beef soup.",
                   "Add the tomato, wax pepper, and 8 cups of water. Simmer gently, partly covered, for 1 1/2 hours, until the beef is nearly tender.",
                   "Meanwhile knead the egg with the flour and a pinch of salt into a stiff dough for the csipetke. Let it rest under a cup.",
                   "Add the carrots and potatoes to the pot and simmer 20 minutes more, until both are tender and the broth has taken on a clear red sheen.",
                   "Pinch fingernail-size bits of the dough directly into the simmering soup and cook 3 to 4 minutes, until they float. Taste for salt.",
                   "Ladle into deep bowls and serve with white bread, and hot paprika paste or a split fresh chile on the side for those who want heat.",
               ],
               note: "Paprika scorches in seconds and turns bitter, so it always goes in off the heat, and this is a drinkable soup; resist the urge to thicken it toward stew.",
               shortcut: "Skip the csipetke and drop in a handful of small egg noodles instead; you lose the rustic pinched texture but save a bowl and twenty minutes."),
        Recipe(dishID: "hungary-porkolt", serves: 4, prepMinutes: 20, cookMinutes: 135, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "beef chuck, cut in 1-inch cubes"),
                   RecipeIngredient(amount: "3", item: "large onions, diced fine"),
                   RecipeIngredient(amount: "3 tbsp", item: "lard (or neutral oil)"),
                   RecipeIngredient(amount: "3 tbsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1", item: "ripe tomato, chopped"),
                   RecipeIngredient(amount: "1", item: "hungarian wax or cubanelle pepper, sliced"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground caraway"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Melt the lard in a heavy pot over medium-low heat and cook the onions with a pinch of salt until they collapse into a soft golden mass, a full 20 minutes. This is the dish's foundation.",
                   "Take the pot off the heat and stir in the paprika until the onions turn brick red, no more than 30 seconds.",
                   "Add the beef, garlic, caraway, and salt and stir until every cube is coated red. Do not add water yet.",
                   "Cover and cook over the lowest heat, stirring every 15 minutes. The beef will release its own liquid; only add a few tablespoons of water when the pot looks in danger of catching.",
                   "After 1 hour, add the tomato and wax pepper and keep going, covered, at the same lazy pace.",
                   "Cook 1 to 1 1/2 hours more, until the beef breaks apart under a spoon and the sauce is thick, glossy, and clinging rather than pooling.",
                   "Taste for salt and serve over small egg dumplings, egg noodles, or with bread, with sour cream on the table for anyone drifting toward paprikas.",
               ],
               note: "The discipline is adding almost no water; porkolt braises in what the meat and onions surrender, and every unnecessary cup you pour in thins the point of the dish away.",
               shortcut: "Boneless pork shoulder cooks tender in about half the beef's time; Hungarians make porkolt from it constantly, so it is a substitution with a passport."),
        Recipe(dishID: "hungary-halaszle", serves: 4, prepMinutes: 30, cookMinutes: 75, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "carp or catfish steaks or thick fillets"),
                   RecipeIngredient(amount: "1 lb", item: "fish heads, bones, and trimmings (ask the fish counter)"),
                   RecipeIngredient(amount: "2", item: "large onions, diced"),
                   RecipeIngredient(amount: "2 tbsp", item: "hot paprika"),
                   RecipeIngredient(amount: "1 tbsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1", item: "ripe tomato, chopped"),
                   RecipeIngredient(amount: "1", item: "hungarian wax or cubanelle pepper, sliced"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "8 cups", item: "water"),
               ],
               steps: [
                   "Salt the fish steaks lightly and refrigerate them while you build the stock; they go in only at the end and need barely any time.",
                   "Put the fish heads, bones, and trimmings in a pot with the onions, tomato, wax pepper, salt, and water. Bring to a boil, then simmer briskly, uncovered, for 1 hour.",
                   "Press the solids through a sieve or food mill into a clean pot, mashing hard to push through the soft onion and every drop of gelatin. Discard what will not pass.",
                   "Bring the strained base back to a boil and whisk in both paprikas. The soup should turn a deep, glowing red and look thin; that thinness is correct.",
                   "Slide in the fish steaks and poach at a gentle simmer 10 to 12 minutes, without stirring, until the flesh flakes at the bone. Shake the pot instead of stirring to keep the pieces whole.",
                   "Taste for salt and heat; Szeged tables would push more hot paprika at you here.",
                   "Ladle carefully into deep bowls, one steak per person, and serve with white bread, or over cooked noodles if you side with Baja in the eternal argument.",
               ],
               note: "The soup is only as good as what you press through the sieve; grind the boiled onion and every scrap of gelatin into the broth, because that is the body.",
               shortcut: "No trimmings at the counter means no stock: use 6 cups bottled clam juice diluted with water; it is a different river, but the paprika still lands."),
        Recipe(dishID: "hungary-langos", serves: 4, prepMinutes: 30, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1", item: "small boiled potato, riced or finely mashed"),
                   RecipeIngredient(amount: "1 cup", item: "warm water"),
                   RecipeIngredient(amount: "4 cups", item: "sunflower or other neutral oil, for frying"),
                   RecipeIngredient(amount: "2", item: "garlic cloves"),
                   RecipeIngredient(amount: "1 cup", item: "sour cream"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "grated cheese, such as gouda or mild cheddar"),
               ],
               steps: [
                   "Mix the flour, yeast, salt, and sugar, then work in the mashed potato and warm water into a soft, sticky dough. Knead 5 minutes; it should barely clear the sides of the bowl.",
                   "Cover and let rise until doubled and bubbly, about 1 hour.",
                   "Crush the garlic into 3 tablespoons of warm water with a pinch of salt to make a rubbing liquid, and set out the sour cream and grated cheese.",
                   "Divide the dough into 4 pieces on an oiled counter. With oiled hands, stretch each into a rough 8-inch disc, leaving it slightly thicker at the rim, like a small pizza.",
                   "Heat 1 1/2 inches of oil in a wide pot to 350°F. Lower in one disc; it should sizzle immediately and balloon in places.",
                   "Fry about 2 minutes per side, until blistered, golden, and crisp at the rim, then drain on a rack. Repeat, letting the oil recover heat between rounds.",
                   "Brush each hot langos with the garlic water, spread thickly with sour cream, and bury it in grated cheese. Fold and eat standing, ideally over a paper plate.",
               ],
               note: "Oiled hands and a wet dough are the trick; flour worked in at shaping stage toughens it, and the garlic water must hit the bread while it is still hissing hot.",
               shortcut: "Store-bought pizza dough, rested to room temperature and stretched thin, fries into a very passable langos; you give up the faint potato softness."),
        Recipe(dishID: "hungary-toltott-kaposzta", serves: 6, prepMinutes: 50, cookMinutes: 120, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1", item: "large head green cabbage"),
                   RecipeIngredient(amount: "2 lb", item: "sauerkraut, drained"),
                   RecipeIngredient(amount: "1 lb", item: "ground pork"),
                   RecipeIngredient(amount: "1/2 cup", item: "long-grain rice, rinsed"),
                   RecipeIngredient(amount: "1", item: "onion, diced fine"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "2 tsp", item: "sweet paprika, plus 1 tsp for the pot"),
                   RecipeIngredient(amount: "1", item: "egg"),
                   RecipeIngredient(amount: "3/4 lb", item: "smoked pork ribs or smoked sausage, cut in pieces"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "1 cup", item: "sour cream, for serving"),
               ],
               steps: [
                   "Core the cabbage and lower it into a big pot of boiling water. As the outer leaves soften, peel them off with tongs; you need 12 good leaves. Shave down the thick center rib of each so it rolls.",
                   "Cook the onion in a little fat until soft, and mix it with the pork, rice, garlic, 2 teaspoons paprika, egg, salt, and pepper. The rice goes in raw; it swells in the pot.",
                   "Put an egg-size portion of filling near the stem end of each leaf, fold in the sides, and roll into a snug parcel. Do not overstuff; the rice needs room.",
                   "Spread half the sauerkraut over the bottom of a heavy pot, nest the rolls on it seam side down in one or two layers, and tuck the smoked ribs between them.",
                   "Cover with the remaining sauerkraut, dust with the last teaspoon of paprika, and add water until it just shows through the kraut.",
                   "Bring to a simmer, then cover and cook at the barest bubble for 2 hours, either on the stove or in a 325°F oven. Shake the pot occasionally; never stir, or the rolls tear.",
                   "Rest 20 minutes off the heat. Serve two rolls per plate with kraut and smoked meat around them and a heavy spoonful of sour cream on top.",
               ],
               note: "This is honestly a weekend pot; the two-hour simmer cannot be rushed or the rice stays hard. Like bigos, it is better on day two, so plan accordingly.",
               shortcut: "Jarred whole sour cabbage leaves from an Eastern European grocery skip the blanch-and-peel entirely and taste more authentic than fresh cabbage does."),
        Recipe(dishID: "hungary-lecso", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "hungarian wax, banana, or cubanelle peppers"),
                   RecipeIngredient(amount: "4", item: "ripe tomatoes, chopped"),
                   RecipeIngredient(amount: "2", item: "onions, sliced"),
                   RecipeIngredient(amount: "3 tbsp", item: "sunflower oil (or lard)"),
                   RecipeIngredient(amount: "2 tsp", item: "sweet paprika"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 pinch", item: "sugar"),
                   RecipeIngredient(amount: "4", item: "eggs"),
               ],
               steps: [
                   "Halve the peppers, strip out seeds and ribs, and slice them into 1/2-inch rings or strips.",
                   "Heat the oil in a wide, deep skillet and cook the onions over medium heat until soft and translucent, about 8 minutes.",
                   "Pull the pan off the heat, stir in the paprika for a few seconds, then add the peppers and salt and return to medium heat.",
                   "Cook 10 minutes, stirring now and then, until the peppers slump and lose their rawness.",
                   "Add the tomatoes and the pinch of sugar and simmer, uncovered, 15 to 20 minutes, until everything collapses into a loose, glistening stew and the liquid turns silky rather than watery.",
                   "Taste; it should be sweet, mildly smoky, and just short of soupy. Reduce a few minutes more if it slides off the spoon like water.",
                   "Beat the eggs and stir them through the hot lecso until just set in soft ribbons, about 1 minute. Serve immediately with fresh white bread for mopping.",
               ],
               note: "The dish stands or falls on the peppers: pale yellow-green wax or banana peppers, not bell peppers, whose thick sweet flesh turns this into a different, duller stew.",
               shortcut: "Out of season, a can of good peeled tomatoes replaces fresh ones seamlessly; there is no substitute worth naming for the pale peppers."),
        Recipe(dishID: "hungary-turos-csusza", serves: 4, prepMinutes: 10, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "12 oz", item: "wide egg noodles"),
                   RecipeIngredient(amount: "12 oz", item: "farmer's cheese (or dry-curd cottage cheese, drained)"),
                   RecipeIngredient(amount: "1 cup", item: "sour cream, plus more for serving"),
                   RecipeIngredient(amount: "6 oz", item: "thick-cut bacon, diced"),
                   RecipeIngredient(amount: "1 tsp", item: "salt, plus more for the pasta water"),
                   RecipeIngredient(amount: "1/4 tsp", item: "black pepper"),
               ],
               steps: [
                   "Fry the diced bacon in a skillet over medium heat until deeply browned and crisp, standing in for the traditional pork cracklings. Keep both the bacon and its rendered fat.",
                   "Boil the noodles in well-salted water until just tender, then drain, saving a splash of the cooking water.",
                   "Toss the hot noodles in the skillet with the bacon fat and a spoonful of the cooking water so every strand is slicked and glossy.",
                   "Crumble the farmer's cheese over the noodles and fold in the sour cream, salt, and pepper off the heat; the cheese should warm and soften but stay in distinct curds, not melt into sauce.",
                   "Heat the oven broiler, spread the noodles in the skillet or a baking dish, and broil 3 to 4 minutes, until the top browns lightly at the edges.",
                   "Scatter the crisp bacon over the top and serve hot, with extra sour cream, and sugar on the table for anyone taking the sweet road.",
               ],
               note: "The curds must stay curds; stir the cheese in off the heat, or it melts into a bland sauce and you lose the cool-grainy-against-hot-noodle contrast that is the dish.",
               shortcut: "Regular cottage cheese works if you drain it in a sieve for twenty minutes and press gently; skip the draining and the dish goes watery."),
        Recipe(dishID: "hungary-dobos", serves: 8, prepMinutes: 60, cookMinutes: 30, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "6", item: "eggs, separated"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "sugar, divided"),
                   RecipeIngredient(amount: "1 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "7 oz", item: "dark chocolate, chopped"),
                   RecipeIngredient(amount: "1 cup", item: "butter, softened"),
                   RecipeIngredient(amount: "3/4 cup", item: "powdered sugar"),
                   RecipeIngredient(amount: "1 tsp", item: "vanilla extract"),
                   RecipeIngredient(amount: "1 tbsp", item: "lemon juice"),
                   RecipeIngredient(amount: "1/2 cup", item: "hazelnuts, toasted and chopped"),
               ],
               steps: [
                   "Heat the oven to 400°F. Trace an 8-inch circle on each of six sheets of parchment, flipping them ink side down on baking sheets. Bake in rounds as your sheets allow.",
                   "Beat the yolks with 1/2 cup sugar until pale and thick, then whip the whites with 1/4 cup sugar and the salt to soft peaks. Fold the whites into the yolks, then sift and fold in the flour.",
                   "Spread the batter thinly and evenly inside each traced circle and bake 6 to 8 minutes per layer, until pale gold and springy. Peel off the parchment while warm and cool flat.",
                   "Melt the chocolate and cool it to lukewarm. Beat the butter with the powdered sugar and vanilla until fluffy, then beat in the chocolate until the buttercream is smooth and holds its shape.",
                   "Pick the flattest layer and set it aside for the caramel top. Stack the other five with a thin, even coat of buttercream between each, then coat the top and sides. Chill 30 minutes.",
                   "Butter a knife and have it ready. Cook the remaining 3/4 cup sugar with the lemon juice in a light-colored pan, swirling, until it turns deep amber.",
                   "Immediately pour the caramel over the reserved layer, spreading fast with an oiled spatula, and score it into 8 wedges with the buttered knife before it hardens.",
                   "Set the caramel wedges on top of the cake, propped at a slight angle on dabs of buttercream if you like the classic look, and press the hazelnuts onto the sides. Chill 1 hour before slicing.",
               ],
               note: "Score the caramel wedges within the first minute or it shatters instead of cutting; everything about the top layer is a race you win by having tools laid out first.",
               shortcut: "Bake three layers and split each horizontally with a serrated knife once cool; less parchment tracing, and the thin-layer effect survives almost intact."),
    ]

    static let all: [Recipe] = recipes_poland + recipes_sweden + recipes_hungary
}
