import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesMiddleEast {

    private static let recipes_turkey: [Recipe] = [
        Recipe(dishID: "turkey-lahmacun", serves: 4, prepMinutes: 40, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 cup", item: "warm water"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "8 oz", item: "ground lamb (or 85 percent lean ground beef)"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1", item: "red bell pepper, minced fine"),
                   RecipeIngredient(amount: "1", item: "small onion, grated"),
                   RecipeIngredient(amount: "1/2 cup", item: "flat-leaf parsley, chopped, plus more to serve"),
                   RecipeIngredient(amount: "1 tsp", item: "red pepper flakes"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1", item: "lemon, in wedges"),
               ],
               steps: [
                   "Stir the flour, yeast, salt and warm water into a shaggy dough, knead 5 minutes until smooth, then cover and let it rest 30 minutes while you make the topping.",
                   "Set a pizza stone or an upside-down sheet pan on the top oven rack and heat the oven to 500 F for at least 30 minutes.",
                   "Mix the lamb, tomato paste, bell pepper, grated onion, parsley, pepper flakes, olive oil and a big pinch of salt into a loose, spreadable paste; add a spoonful of water if it feels stiff.",
                   "Divide the dough into 8 balls. On a floured counter, roll each one paper thin, about 8 inches across; you should almost see the counter through it.",
                   "Smear a thin layer of the lamb paste over each round, all the way to the rim, pressing it in with your fingers so it grips the dough.",
                   "Slide one or two rounds onto the hot stone on parchment and bake 4 to 5 minutes, until the rim browns in spots and the meat looks dry, not shiny.",
                   "Stack the finished rounds under a towel so they stay pliable, then serve with lemon wedges, extra parsley and sliced onion for rolling into tubes.",
               ],
               note: "Roll the dough thinner than feels reasonable and keep the meat layer scant; a thick smear steams the bread and you lose the crisp rim entirely.",
               shortcut: "Use store-bought fresh pizza dough and skip the mixing; it bakes up slightly breadier and less crackly at the edge."),
        Recipe(dishID: "turkey-manti", serves: 4, prepMinutes: 60, cookMinutes: 20, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1", item: "large egg"),
                   RecipeIngredient(amount: "1/2 cup", item: "water"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "8 oz", item: "ground lamb (or ground beef)"),
                   RecipeIngredient(amount: "1", item: "small onion, grated and squeezed dry"),
                   RecipeIngredient(amount: "2 cups", item: "plain whole-milk yogurt"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, grated"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1 tsp", item: "paprika or Aleppo-style pepper flakes"),
                   RecipeIngredient(amount: "1 tsp", item: "dried mint"),
               ],
               steps: [
                   "Knead the flour, egg, water and 1 teaspoon of salt into a firm dough, about 8 minutes; cover and rest it 20 minutes so it rolls without fighting back.",
                   "Mix the lamb, grated onion, remaining salt and a good grind of black pepper. Stir the yogurt with the garlic and a pinch of salt and leave it at room temperature.",
                   "Roll half the dough into a sheet thinner than a nickel and cut it into 1 1/4-inch squares with a knife or pizza cutter. Repeat with the second half.",
                   "Drop a chickpea-sized dab of filling on each square, then pinch opposite corners together into a little four-cornered bundle, sealing the seams firmly so they survive the boil.",
                   "Boil the manti in well-salted water in two batches, 6 to 8 minutes, until the dough is tender and the parcels float and look slightly translucent at the folds.",
                   "While they cook, melt the butter in a small pan until it foams, pull it off the heat and stir in the paprika so it turns brick red without scorching.",
                   "Lift the manti into shallow bowls with a slotted spoon, blanket them with the garlic yogurt, streak the red butter over the top and finish with dried mint crushed between your palms.",
               ],
               note: "Keep the parcels small and the filling scant; oversized manti cook unevenly and the dough-to-meat ratio is the entire point of the dish.",
               shortcut: "Fold them as open-topped squares instead of sealed bundles; it halves the pinching time and only costs you a little broth-tightness in the bite."),
        Recipe(dishID: "turkey-iskender", serves: 4, prepMinutes: 25, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "boneless leg of lamb or ribeye, sliced paper thin"),
                   RecipeIngredient(amount: "2 tbsp", item: "plain yogurt (for the marinade)"),
                   RecipeIngredient(amount: "1 tsp", item: "dried oregano"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2", item: "pide or pocketless pita breads, cut in 1-inch squares"),
                   RecipeIngredient(amount: "1 can (14 oz)", item: "crushed tomatoes"),
                   RecipeIngredient(amount: "1 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "5 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "plain whole-milk yogurt, at room temperature"),
                   RecipeIngredient(amount: "4", item: "small green peppers (Anaheim or cubanelle)"),
                   RecipeIngredient(amount: "1 tbsp", item: "olive oil"),
               ],
               steps: [
                   "Toss the sliced meat with the 2 tablespoons of yogurt, oregano and half the salt; let it sit while you make the sauce, at least 15 minutes.",
                   "Simmer the crushed tomatoes, tomato paste, 1 tablespoon of butter and the remaining salt for 10 minutes, until it thickens enough to coat a spoon. Keep it warm.",
                   "Rub the green peppers with olive oil and blister them in a dry skillet over high heat, turning until soft and charred in patches. Set aside.",
                   "Toast the bread squares in the same skillet with 1 tablespoon of butter until the edges crisp, then divide them among four plates in a single layer.",
                   "Sear the meat in the ripping-hot skillet in two batches, undisturbed for a minute so the edges brown and frizzle, then tossed just until no pink remains.",
                   "Pile the meat over the bread, spoon the tomato sauce generously over everything and add a thick spoonful of yogurt and a charred pepper to each plate.",
                   "Melt the last 3 tablespoons of butter until it foams and smells nutty, and pour it sizzling over each plate at the table.",
               ],
               note: "Serve it the second the butter hits; the dish is engineered around bread that is soaking but not yet soggy, and it waits for no one.",
               shortcut: "Buy shaved beef sold for cheesesteaks instead of slicing your own; it browns fast and fakes doner texture well, just watch it closely or it overcooks."),
        Recipe(dishID: "turkey-menemen", serves: 2, prepMinutes: 10, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "6", item: "large eggs"),
                   RecipeIngredient(amount: "3", item: "small green peppers (cubanelle or Anaheim), diced"),
                   RecipeIngredient(amount: "3", item: "ripe tomatoes, grated on a box grater, skins discarded"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/4 tsp", item: "red pepper flakes"),
                   RecipeIngredient(amount: "2 oz", item: "feta cheese, crumbled"),
                   RecipeIngredient(amount: "1/2 loaf", item: "crusty white bread, for the table"),
               ],
               steps: [
                   "Warm the olive oil in a 10-inch skillet over medium heat and cook the diced peppers with a pinch of salt until fully soft and sweet, 5 to 6 minutes.",
                   "Add the grated tomato, remaining salt and pepper flakes and simmer until the puddle of juice cooks off and the mixture looks jammy, about 5 minutes.",
                   "Crack the eggs straight into the pan and let them sit untouched for 20 seconds so the whites start to set against the hot vegetables.",
                   "Drop the heat to low and stir slowly and constantly with a wooden spoon, folding rather than scrambling, until the eggs form soft, loose curds still shiny on top.",
                   "Pull the pan off the heat while the eggs still look slightly underdone; they finish cooking in the skillet on the way to the table.",
                   "Scatter the feta over the top, set the whole pan down on a trivet and eat straight from it with torn bread, tea alongside if you have it.",
               ],
               note: "Stop cooking earlier than instinct says; menemen should slump off the spoon like custard, and thirty extra seconds turns it into ordinary scrambled eggs.",
               shortcut: "Canned diced tomatoes, drained well, work in winter; you lose the fresh acidity, so add a small squeeze of lemon at the end."),
        Recipe(dishID: "turkey-mercimek", serves: 6, prepMinutes: 10, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "red lentils, rinsed"),
                   RecipeIngredient(amount: "1", item: "onion, chopped"),
                   RecipeIngredient(amount: "1", item: "carrot, chopped"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "7 cups", item: "water or chicken stock"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1 tsp", item: "paprika or Aleppo-style pepper flakes"),
                   RecipeIngredient(amount: "1 tsp", item: "dried mint"),
                   RecipeIngredient(amount: "2", item: "lemons, in wedges"),
               ],
               steps: [
                   "Sweat the onion and carrot in the olive oil in a soup pot over medium heat until soft but not browned, about 6 minutes.",
                   "Stir in the tomato paste and cook 1 minute until it darkens a shade and smells sweet rather than raw.",
                   "Add the lentils, water and salt, bring to a boil, then simmer uncovered about 25 minutes, skimming foam, until the lentils have completely collapsed.",
                   "Blend the soup smooth with an immersion blender, or in batches in a countertop blender, then thin with hot water until it pours like heavy cream.",
                   "Melt the butter in a small pan until foaming, pull it off the heat and stir in the paprika so it stains the butter red without burning.",
                   "Ladle into bowls, spoon a slick of pepper butter over each, crush dried mint on top and serve with lemon wedges; the soup is not finished until each eater squeezes one in.",
               ],
               note: "The lemon at the table is structural, not garnish; without a hard squeeze per bowl the soup tastes flat, however well you seasoned the pot.",
               shortcut: "Skip the blender and whisk hard at the end; red lentils mostly dissolve on their own and you only sacrifice a little silkiness."),
        Recipe(dishID: "turkey-baklava", serves: 8, prepMinutes: 45, cookMinutes: 60, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "frozen filo sheets, thawed overnight in the fridge"),
                   RecipeIngredient(amount: "1 cup", item: "unsalted butter"),
                   RecipeIngredient(amount: "2 1/2 cups", item: "shelled pistachios (or walnuts), finely chopped"),
                   RecipeIngredient(amount: "1 tbsp", item: "fine semolina"),
                   RecipeIngredient(amount: "2 cups", item: "sugar"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "water"),
                   RecipeIngredient(amount: "1 tsp", item: "lemon juice"),
                   RecipeIngredient(amount: "a pinch", item: "salt"),
               ],
               steps: [
                   "Melt the butter gently and let it sit 5 minutes, then spoon the clear yellow fat off the milky solids; this clarified butter is what keeps the layers crisp.",
                   "Toss the chopped pistachios with the semolina and salt. Butter a 9-by-13-inch metal pan and heat the oven to 350 F.",
                   "Lay in half the filo one sheet at a time, brushing every sheet edge to edge with clarified butter and keeping the waiting stack under a barely damp towel.",
                   "Spread the pistachios in an even layer, then continue stacking and buttering the remaining sheets, finishing with a generously buttered top sheet tucked in at the edges.",
                   "Cut all the way to the bottom of the pan in a diamond pattern with a sharp knife before baking; you cannot cut it cleanly afterward.",
                   "Bake 45 to 55 minutes until deep gold to the center layers; if the top browns early, tent it loosely with foil.",
                   "While it bakes, boil the sugar, water and lemon juice for 10 minutes until lightly syrupy, then let it cool to warm; it must not be cold or hot when poured.",
                   "Pour the warm syrup slowly over the baklava the moment it leaves the oven, aiming into the cut lines, and listen for the crackle. Rest at room temperature at least 4 hours, never refrigerated.",
               ],
               note: "Hot pastry, warm syrup is the rule that keeps layers brittle; refrigeration at any point turns forty crisp sheets into one damp one.",
               shortcut: "Skip clarifying and use plain melted butter; the layers brown a little blotchier and crisp slightly less, but the pan still disappears."),
        Recipe(dishID: "turkey-cigkofte", serves: 6, prepMinutes: 50, cookMinutes: 0, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "fine bulgur (labeled no. 1 or fine grind)"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "boiling water"),
                   RecipeIngredient(amount: "3 tbsp", item: "red pepper paste (or tomato paste mixed with 1 tsp hot paprika)"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "2 tbsp", item: "isot pepper (or 1 tbsp smoked paprika plus 1 tsp cayenne)"),
                   RecipeIngredient(amount: "1", item: "small onion, grated to a pulp"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, grated"),
                   RecipeIngredient(amount: "3 tbsp", item: "pomegranate molasses, plus more to serve"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 head", item: "romaine or butter lettuce, leaves separated"),
                   RecipeIngredient(amount: "2", item: "lemons, in wedges"),
               ],
               steps: [
                   "Put the bulgur in a wide bowl, pour the boiling water over, cover with a plate and let it swell 20 minutes until the grains are tender but still distinct.",
                   "Add both pastes, the isot pepper, grated onion, garlic, cumin and salt, and start kneading with your hands, pressing and folding like stiff bread dough.",
                   "Keep kneading 15 to 20 minutes, wetting your hands occasionally, until the mixture darkens to brick red and holds together in a dense, cohesive mass.",
                   "Knead in the pomegranate molasses and olive oil in the last few minutes, then taste; it should hit sour, hot and salty in that order, so adjust each.",
                   "Squeeze handfuls in your fist to shape oval kofte, your finger marks left in each one, and chill them 30 minutes so they firm up.",
                   "Serve cold, wrapped in lettuce leaves with a squeeze of lemon and an extra drip of pomegranate molasses on each bite.",
               ],
               note: "The kneading time is not padding; the mixture only binds and turns silky when the bulgur has been worked long past the point that feels sufficient.",
               shortcut: "A stand mixer with the paddle on low does 15 minutes of kneading in 6, at the cost of the traditional hand-pressed texture."),
        Recipe(dishID: "turkey-hamsi", serves: 4, prepMinutes: 25, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "fresh anchovies or smelts (or the smallest sardines you can find)"),
                   RecipeIngredient(amount: "1 cup", item: "fine corn flour (not cornstarch; corn muffin mix works in a pinch)"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "sunflower or vegetable oil"),
                   RecipeIngredient(amount: "2", item: "lemons, in wedges"),
                   RecipeIngredient(amount: "1", item: "red onion, sliced paper thin"),
                   RecipeIngredient(amount: "1/2 cup", item: "flat-leaf parsley leaves"),
                   RecipeIngredient(amount: "1 tsp", item: "sumac (optional but traditional in the onion salad)"),
               ],
               steps: [
                   "Gut the fish by pulling the head down and back so the innards follow, then rinse quickly and pat very dry; leave the tails and backbones in.",
                   "Toss the sliced onion with a big pinch of salt, squeeze and scrunch it with your hands for a minute, then mix with parsley, sumac and a squeeze of lemon.",
                   "Salt the fish, then dredge each one in corn flour, pressing so it sticks, and shake off the excess; a plastic bag makes this fast.",
                   "Heat the oil in a wide nonstick or cast-iron skillet over medium-high until a pinch of corn flour sizzles on contact.",
                   "Lay the fish in a tight fan or spiral, working in two batches, and fry 3 to 4 minutes untouched until the underside is deep golden and crisp.",
                   "Turn carefully with a spatula, in sections if the fan holds together, and fry 2 to 3 minutes more, then drain on paper towels and salt lightly.",
                   "Serve hot with the onion salad and lemon wedges, and eat them whole with your fingers; the small bones fry soft.",
               ],
               note: "Bone-dry fish and properly hot oil are everything; damp fish sheds its corn crust into the pan and steams instead of crisping.",
               shortcut: "Ask the fish counter to gut them for you; it saves twenty messy minutes, though a Black Sea cook would call it cheating."),
    ]

    private static let recipes_lebanon: [Recipe] = [
        Recipe(dishID: "lebanon-hummus", serves: 6, prepMinutes: 15, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 cans (15 oz each)", item: "chickpeas, drained and rinsed"),
                   RecipeIngredient(amount: "1/2 tsp", item: "baking soda"),
                   RecipeIngredient(amount: "2/3 cup", item: "tahini, stirred well"),
                   RecipeIngredient(amount: "1/3 cup", item: "fresh lemon juice"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, roughly chopped"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "4 tbsp", item: "ice water"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "2", item: "pita or flatbread rounds, warmed"),
               ],
               steps: [
                   "Simmer the chickpeas with the baking soda in fresh water for 20 minutes, until they crush between two fingers with no resistance and skins float free.",
                   "While they cook, blend the lemon juice, garlic and salt in a food processor and let it sit 5 minutes so the garlic mellows, then add the tahini.",
                   "Blend the tahini mixture, streaming in the ice water, until it lightens from tan to nearly white and turns thick and smooth like frosting.",
                   "Drain the chickpeas well, reserve a spoonful of whole ones for the top, and add the rest to the processor with the cumin.",
                   "Run the machine a full 3 to 4 minutes, scraping down twice; stop only when the hummus is completely smooth and loose enough to slump off a spoon.",
                   "Spread it in a shallow bowl with the back of the spoon, making a shallow well and ridge, and let it sit 10 minutes so the flavors settle.",
                   "Spoon the reserved chickpeas into the well, flood generously with olive oil and serve warm or at room temperature with torn flatbread.",
               ],
               note: "Overcooking the chickpeas is the trick everyone resists; they should be one step from mush, or no machine will get you to silky.",
               shortcut: "Skip the simmer and blend straight from the can with an extra minute of processing; the hummus lands stiffer and grainier but still respectable."),
        Recipe(dishID: "lebanon-tabbouleh", serves: 4, prepMinutes: 40, cookMinutes: 0, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "3 large bunches", item: "flat-leaf parsley (about 4 packed cups once chopped)"),
                   RecipeIngredient(amount: "3 tbsp", item: "fine bulgur (labeled no. 1 or fine grind)"),
                   RecipeIngredient(amount: "3", item: "ripe tomatoes, seeded and diced small"),
                   RecipeIngredient(amount: "1/4 cup", item: "fresh mint leaves, chopped"),
                   RecipeIngredient(amount: "3", item: "scallions, sliced thin"),
                   RecipeIngredient(amount: "1/3 cup", item: "fresh lemon juice"),
                   RecipeIngredient(amount: "1/3 cup", item: "olive oil"),
                   RecipeIngredient(amount: "3/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 head", item: "romaine lettuce, inner leaves separated"),
               ],
               steps: [
                   "Dice the tomatoes first and put the bulgur in the bowl underneath them, so the grains soak in tomato juice for 20 minutes while you chop; no other soaking needed.",
                   "Wash the parsley and dry it completely, in a salad spinner and then on towels; wet parsley turns the salad to sludge within minutes.",
                   "Gather the parsley into tight bundles and shave it fine with your sharpest knife, slicing rather than rocking, so the leaves stay in distinct dry ribbons.",
                   "Chop the mint the same way, no finer than the parsley, and slice the scallions thin, including most of the green.",
                   "Combine the parsley, mint, scallions and the tomato-bulgur mixture in a wide bowl, tossing gently with your hands so nothing bruises.",
                   "Just before serving, add the lemon juice, olive oil and salt, toss again and taste; it should be sharp enough to make you blink, then serve with romaine leaves for scooping.",
               ],
               note: "This is a parsley salad with bulgur in it, never the reverse; if grain is visible in every bite you have made a different dish.",
               shortcut: "A food processor can chop the parsley in pulses, but it bruises the leaves; expect a darker, wetter salad that will not keep."),
        Recipe(dishID: "lebanon-kibbeh", serves: 6, prepMinutes: 50, cookMinutes: 45, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "fine bulgur (labeled no. 1 or fine grind)"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "lean ground lamb (or 90 percent lean ground beef), divided"),
                   RecipeIngredient(amount: "2", item: "onions, one grated, one chopped fine"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "ground allspice"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/3 cup", item: "pine nuts"),
                   RecipeIngredient(amount: "4 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1/2 cup", item: "ice water"),
                   RecipeIngredient(amount: "1 cup", item: "plain yogurt, to serve"),
               ],
               steps: [
                   "Rinse the bulgur, squeeze it dry in your fists, and soak it in cold water for 15 minutes while you make the filling.",
                   "Cook the chopped onion in 2 tablespoons of olive oil until golden, add a third of the meat and brown it, breaking it up fine.",
                   "Stir the pine nuts, half the allspice, a pinch of cinnamon and a half teaspoon of salt into the filling, cook 2 more minutes and set it aside to cool.",
                   "Squeeze the bulgur dry again and process it with the remaining raw meat, grated onion, remaining spices and salt, adding ice water a splash at a time, until it becomes a smooth, sticky paste.",
                   "Oil a 9-by-13-inch baking dish and press half the paste into an even layer with wet hands, smoothing it flat with your palm.",
                   "Spread the cooled filling over it, then flatten palm-sized patches of the remaining paste between wet hands and lay them on top, sealing the seams into one sheet.",
                   "Score deeply into diamonds with a wet knife, run the knife around the edge, and drizzle the last 2 tablespoons of oil over the top.",
                   "Bake at 375 F for 40 to 45 minutes until the top is deep brown and the edges pull from the dish, then rest 10 minutes and serve with yogurt.",
               ],
               note: "Ice water in the food processor is the modern stand-in for an hour at the mortar; without a truly cold, smooth paste the kibbeh bakes up crumbly.",
               shortcut: "Ask the butcher to grind the meat twice, extra fine; it shortens processing and gets you closer to the pounded texture."),
        Recipe(dishID: "lebanon-manakish", serves: 4, prepMinutes: 30, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "warm water"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil, for the dough"),
                   RecipeIngredient(amount: "1/2 cup", item: "za'atar blend"),
                   RecipeIngredient(amount: "1/2 cup", item: "olive oil, for the topping"),
                   RecipeIngredient(amount: "1 tsp", item: "sumac (boosts store-bought za'atar; skip if yours is already tart)"),
                   RecipeIngredient(amount: "1 tbsp", item: "sesame seeds"),
                   RecipeIngredient(amount: "1", item: "cucumber, cut in spears, to serve"),
                   RecipeIngredient(amount: "a handful", item: "fresh mint sprigs, to serve"),
               ],
               steps: [
                   "Mix the flour, yeast, sugar and salt, then add the water and 2 tablespoons of oil and knead 8 minutes until the dough is smooth and slightly tacky.",
                   "Cover the dough and let it rise somewhere warm until doubled, about 1 hour; meanwhile set a pizza stone or inverted sheet pan in the oven at 500 F.",
                   "Stir the za'atar with the half cup of olive oil, the sumac and sesame seeds into a loose, pourable paste; add oil if it sits stiff like wet sand.",
                   "Divide the dough into 6 balls, roll each into a 6-inch round on a floured counter, and let them puff 10 minutes under a towel.",
                   "Dimple each round hard with your fingertips, right to the edge, so the topping has somewhere to pool and the bread cannot balloon.",
                   "Spread a generous spoonful of the za'atar paste over each round, leaving a thin bare rim, and slide them onto the hot stone in batches.",
                   "Bake 6 to 8 minutes until the rims are golden and the topping bubbles at the edges, then stack under a towel so they stay foldable, and serve warm with cucumber and mint.",
               ],
               note: "Buy za'atar that smells grassy and tastes tart; a stale, sawdusty jar cannot be rescued by any amount of good olive oil.",
               shortcut: "Store-bought pizza dough works fine here; the crumb is chewier and less tender, but the za'atar carries the whole show anyway."),
        Recipe(dishID: "lebanon-shishbarak", serves: 4, prepMinutes: 60, cookMinutes: 40, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "3/4 cup", item: "warm water"),
                   RecipeIngredient(amount: "1 3/4 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "8 oz", item: "ground lamb (or ground beef)"),
                   RecipeIngredient(amount: "1", item: "small onion, minced"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground allspice"),
                   RecipeIngredient(amount: "4 cups", item: "plain whole-milk yogurt"),
                   RecipeIngredient(amount: "1", item: "large egg"),
                   RecipeIngredient(amount: "2 tbsp", item: "cornstarch"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter or olive oil"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "dried mint"),
                   RecipeIngredient(amount: "1 cup", item: "long-grain or short-grain rice, cooked, to serve"),
               ],
               steps: [
                   "Knead the flour, water and 3/4 teaspoon of salt into a smooth dough, cover and rest 30 minutes. Meanwhile cook the onion, lamb, allspice and 1/2 teaspoon of salt until browned, and cool it.",
                   "Roll the dough thin and cut 2-inch circles. Put a small dab of filling on each, fold into a half-moon, seal the edge, then pull the two corners together and pinch into a little hat.",
                   "Spread the dumplings on a parchment-lined sheet and bake at 375 F for 10 minutes until barely golden; this keeps them from dissolving in the sauce.",
                   "Whisk the yogurt with the egg, cornstarch and remaining salt in a heavy pot until completely smooth; the egg and starch are the insurance against splitting.",
                   "Set the pot over medium heat and stir constantly in one direction until the yogurt loosens, then thickens, and comes to a lazy bubble; never walk away during this stage.",
                   "Slide the dumplings into the yogurt, drop the heat low and simmer gently 15 minutes, stirring now and then, until the dough is tender all the way through.",
                   "Fry the garlic in the butter until it just turns gold, stir in the dried mint off the heat, and swirl this into the pot right before serving over rice.",
               ],
               note: "Stabilized yogurt breaks the moment it boils hard or gets ignored; stir one direction, keep the flame gentle and it stays silk from stove to bowl.",
               shortcut: "Fold small wonton wrappers around the filling instead of making dough; they are thinner than tradition wants but poach beautifully in the yogurt."),
        Recipe(dishID: "lebanon-samkeharra", serves: 4, prepMinutes: 20, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "whole branzino or red snapper, gutted and scaled (or 4 thick cod fillets)"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "2/3 cup", item: "tahini, stirred well"),
                   RecipeIngredient(amount: "1/2 cup", item: "fresh lemon juice"),
                   RecipeIngredient(amount: "1/2 cup", item: "walnuts, chopped"),
                   RecipeIngredient(amount: "1", item: "onion, sliced thin"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1", item: "red chili, minced (or 1 tsp red pepper flakes)"),
                   RecipeIngredient(amount: "1 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1 cup", item: "fresh cilantro, chopped, divided"),
                   RecipeIngredient(amount: "1/2 cup", item: "warm water"),
               ],
               steps: [
                   "Heat the oven to 425 F. Slash the fish twice on each side, rub inside and out with salt and 2 tablespoons of oil, and set it on a lined sheet pan.",
                   "Roast 20 to 25 minutes, until the flesh at the deepest slash flakes when nudged with a fork and pulls from the bone.",
                   "While it roasts, soften the onion in the remaining oil over medium heat, then add the garlic, chili and ground coriander and cook one fragrant minute more.",
                   "Whisk the tahini with the lemon juice; it will seize into paste first, then loosen as you whisk in the warm water until it pours like cream.",
                   "Pour the tahini into the skillet with the onions, add most of the cilantro and the walnuts, and warm gently 3 to 4 minutes, stirring, until it thickens to a coating sauce; never let it boil.",
                   "Move the fish to a platter, spoon the hot sauce generously over the whole thing and scatter the last of the cilantro and a few extra walnuts on top.",
                   "Serve at the table with bread or rice, encouraging people to pull the fish apart and drag every piece through the sauce.",
               ],
               note: "Tahini thickens fast as it heats; keep spare warm water at the stove and loosen the sauce until it pours, not spreads.",
               shortcut: "Cod or halibut fillets skip the whole-fish theater and roast in 12 minutes; you lose the platter drama but none of the sauce."),
        Recipe(dishID: "lebanon-knafeh", serves: 8, prepMinutes: 30, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "frozen kataifi (shredded filo), thawed (look in Middle Eastern or Greek markets)"),
                   RecipeIngredient(amount: "1 cup", item: "unsalted butter, melted"),
                   RecipeIngredient(amount: "12 oz", item: "low-moisture mozzarella, shredded"),
                   RecipeIngredient(amount: "1 cup", item: "whole-milk ricotta"),
                   RecipeIngredient(amount: "2 tbsp", item: "fine semolina"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "sugar"),
                   RecipeIngredient(amount: "3/4 cup", item: "water"),
                   RecipeIngredient(amount: "1 tsp", item: "lemon juice"),
                   RecipeIngredient(amount: "1 tbsp", item: "orange blossom water"),
                   RecipeIngredient(amount: "1/4 cup", item: "pistachios, ground fine"),
                   RecipeIngredient(amount: "8", item: "sesame buns or brioche rolls, split (optional but traditional)"),
               ],
               steps: [
                   "Boil the sugar, water and lemon juice for 10 minutes until lightly syrupy, stir in the orange blossom water off the heat, and let it cool completely.",
                   "Pull the kataifi apart into a bowl and chop it roughly into inch-long pieces, then work the melted butter through with your hands until every strand is coated and glistening.",
                   "Press two-thirds of the buttered pastry firmly into a buttered 10-inch oven-safe skillet or 9-by-13-inch pan, packing the base and a shallow rim with the bottom of a measuring cup.",
                   "Mix the mozzarella, ricotta and semolina, spread it over the base leaving a half-inch border, and scatter the remaining pastry loosely on top.",
                   "Bake at 375 F for 35 to 45 minutes, until the top is deep gold and you can see the edges bubbling and browned when you tilt the pan.",
                   "Pour the cooled syrup evenly over the hot knafeh the moment it comes out; it will hiss and soak in. Rest 5 minutes, no longer.",
                   "Scatter the ground pistachios over the top, cut wedges while the cheese still pulls, and serve hot, tucked into a sesame roll if you want the Beirut breakfast experience.",
               ],
               note: "Serve it hot or not at all; once the cheese sets, no reheating fully brings back the pull, so time it to the table.",
               shortcut: "Mozzarella plus ricotta stands in for hard-to-find akkawi; soak slices of salted halloumi in water and shred them if you want closer to the real salt-edge."),
        Recipe(dishID: "lebanon-mujaddara", serves: 4, prepMinutes: 10, cookMinutes: 50, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "brown or green lentils, rinsed"),
                   RecipeIngredient(amount: "3/4 cup", item: "long-grain rice, rinsed"),
                   RecipeIngredient(amount: "3", item: "large onions, halved and sliced thin"),
                   RecipeIngredient(amount: "1/2 cup", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
                   RecipeIngredient(amount: "1 cup", item: "plain yogurt, to serve"),
                   RecipeIngredient(amount: "a handful", item: "dill pickles or pickled turnips, to serve"),
               ],
               steps: [
                   "Fry the onions in the olive oil in a wide pot over medium-high heat, stirring often, 20 to 25 minutes, until deep mahogany with crisp near-black edges; do not stop at golden.",
                   "Lift out half the onions onto paper towels for the topping; they will crisp as they cool. Leave the rest and the oil in the pot.",
                   "Simmer the lentils in the 4 cups of water in a separate pot for 12 minutes; they should still be firm at the center. Keep the cooking water.",
                   "Add the rice, cumin and salt to the onion pot, stir a minute in the oil, then add the lentils and 2 1/2 cups of their cooking liquid.",
                   "Bring to a boil, then cover, drop the heat to its lowest and cook 18 minutes without lifting the lid.",
                   "Rest off the heat, covered, for 10 minutes, then fluff gently with a fork; the grains should be distinct, the lentils soft but whole.",
                   "Serve warm or at room temperature, piled with the reserved crisp onions, with yogurt and pickles on the side.",
               ],
               note: "The onions must go past golden into true dark brown; that burnt-sweet edge is the flavor of the dish, and timidity here makes it bland.",
               shortcut: "Canned lentils, drained, go in with the rice and skip the pre-simmer; texture goes softer, so cut the liquid by half a cup."),
    ]

    private static let recipes_georgia: [Recipe] = [
        Recipe(dishID: "georgia-khachapuri", serves: 4, prepMinutes: 40, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "warm milk"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "12 oz", item: "low-moisture mozzarella, shredded (stand-in for sulguni)"),
                   RecipeIngredient(amount: "6 oz", item: "feta cheese, crumbled (stand-in for imeruli)"),
                   RecipeIngredient(amount: "4", item: "large egg yolks"),
                   RecipeIngredient(amount: "4 tbsp", item: "butter, in pats"),
               ],
               steps: [
                   "Mix the flour, yeast, sugar and salt, add the warm milk and olive oil, and knead 8 minutes to a soft, supple dough. Cover and rise until doubled, about 1 hour.",
                   "Heat the oven to 475 F with a pizza stone or inverted sheet pan inside. Toss the mozzarella and feta together with your fingers.",
                   "Divide the dough in quarters and roll each piece into an oval about 9 inches long on floured parchment.",
                   "Roll the two long sides inward toward the middle, then pinch and twist the ends hard so each oval becomes an open boat with rolled rims.",
                   "Fill each boat with the cheese mixture, mounding it slightly, and pack some into the rolled rims so the crust bakes up cheese-lined.",
                   "Slide the boats, parchment and all, onto the hot stone and bake 12 to 15 minutes, until the crust is deep gold and the cheese bubbles and browns in spots.",
                   "Pull them out, immediately press a crater in each molten center and drop in a yolk and a pat of butter; the residual heat cooks the yolk to a sauce.",
                   "Serve at once, showing everyone the move: stir yolk and butter into the cheese, tear the crust ends off and dip.",
               ],
               note: "The yolk goes in after baking, never before; it must stay liquid enough to stir into the cheese, or the whole dipping ritual collapses.",
               shortcut: "Store pizza dough makes fine boats; the crumb is less tender, and you save the hour of rising for the part everyone remembers."),
        Recipe(dishID: "georgia-khinkali", serves: 4, prepMinutes: 60, cookMinutes: 20, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 cup", item: "cold water"),
                   RecipeIngredient(amount: "2 tsp", item: "salt, divided"),
                   RecipeIngredient(amount: "8 oz", item: "ground beef"),
                   RecipeIngredient(amount: "8 oz", item: "ground pork"),
                   RecipeIngredient(amount: "1", item: "onion, grated on the fine holes"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "coarsely ground black pepper, plus more to serve"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1 tsp", item: "dried summer savory or thyme (optional but Georgian)"),
                   RecipeIngredient(amount: "3/4 cup", item: "cold beef broth or water, for the filling"),
               ],
               steps: [
                   "Knead the flour, cold water and 1 teaspoon of salt into a stiff, smooth dough, about 8 minutes, then cover and rest it 30 minutes.",
                   "Mix the beef, pork, grated onion, remaining salt, pepper, coriander and savory, then beat in the cold broth a splash at a time until the filling turns loose and sloppy; that liquid becomes the broth inside.",
                   "Roll the dough a scant eighth-inch thick and cut 4-inch circles; reroll scraps once. You should get 20 to 24 rounds.",
                   "Roll each circle a bit thinner at the edges than the center, put a heaping tablespoon of filling in the middle, and gather the rim into small accordion pleats.",
                   "Work around the circle pleating and pinching until closed, then twist the gathered top into a firm topknot; count your pleats if you want bragging rights.",
                   "Boil the khinkali in well-salted water in two batches, stirring once so nothing sticks, 8 to 9 minutes, until the dough is cooked through at the pleats.",
                   "Lift them out with a slotted spoon, dust heavily with black pepper and serve immediately, instructing everyone: hold the knob, bite the side, drink the broth first, leave the knob on the plate.",
               ],
               note: "The filling must be wet enough to alarm you; a firm, tidy filling gives you a dumpling with no broth, which in Georgia is a failed khinkali.",
               shortcut: "A tortilla press flattens the dough rounds fast, though you still need a pin to thin the edges where the pleats stack up."),
        Recipe(dishID: "georgia-satsivi", serves: 6, prepMinutes: 30, cookMinutes: 75, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "bone-in chicken thighs (or half a small turkey breast)"),
                   RecipeIngredient(amount: "1", item: "onion, halved, plus 1 chopped fine"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 cups", item: "walnuts"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1 tsp", item: "ground fenugreek (stand-in for blue fenugreek)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground marigold (or 1/2 tsp turmeric plus a pinch of paprika)"),
                   RecipeIngredient(amount: "1/4 tsp", item: "cayenne"),
                   RecipeIngredient(amount: "2 tbsp", item: "white wine vinegar"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1/2 loaf", item: "crusty bread, to serve"),
               ],
               steps: [
                   "Cover the chicken and halved onion with water, add 1 teaspoon of salt, and poach at a bare simmer 40 minutes, skimming, until the meat pulls easily from the bone.",
                   "Lift out the chicken, strain and reserve the broth, and pull the meat into large shreds, discarding skin and bones.",
                   "Grind the walnuts with the garlic and remaining salt in a food processor until they pass ground and start to look damp and pasty, scraping down twice.",
                   "Soften the chopped onion in the butter over medium-low heat until translucent, about 8 minutes, without letting it brown; brown onion muddies the sauce's pale color.",
                   "Stir the walnut paste, coriander, fenugreek, marigold and cayenne into the onions, then whisk in 3 cups of warm broth until the sauce is smooth and pourable.",
                   "Simmer gently 10 minutes, stirring, until it thickens to heavy-cream consistency and beads of walnut oil appear on the surface, then stir in the vinegar.",
                   "Fold in the chicken, take the pot off the heat and cool to room temperature, then refrigerate at least 4 hours or overnight; it must be served cold.",
                   "Taste after chilling and wake it up with a pinch more salt and a few drops of vinegar, then serve in shallow bowls with bread.",
               ],
               note: "Make it the day before without fail; the walnut sauce only knits together and turns velvet in the cold, and it thickens as it sits.",
               shortcut: "A rotisserie chicken plus boxed stock skips the poaching hour; the broth is thinner-flavored, so simmer the sauce a few minutes longer."),
        Recipe(dishID: "georgia-pkhali", serves: 6, prepMinutes: 30, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "fresh spinach (or 1 lb spinach and 1 lb beet greens for two colors)"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "walnuts"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic"),
                   RecipeIngredient(amount: "1", item: "small onion, roughly chopped"),
                   RecipeIngredient(amount: "1 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground fenugreek (stand-in for blue fenugreek)"),
                   RecipeIngredient(amount: "1/4 tsp", item: "cayenne"),
                   RecipeIngredient(amount: "1 tbsp", item: "white wine vinegar"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "fresh cilantro, chopped"),
                   RecipeIngredient(amount: "1/2 cup", item: "pomegranate seeds"),
               ],
               steps: [
                   "Blanch the spinach in batches in boiling salted water for 90 seconds, until fully wilted but still bright green, then plunge it straight into ice water.",
                   "Squeeze the cooled greens in your fists, hard and repeatedly, until no more liquid comes out; a watery pkhali will not hold its shape.",
                   "Grind the walnuts, garlic, onion, coriander, fenugreek, cayenne and salt in a food processor until the mixture is damp, fine and starting to clump.",
                   "Chop the squeezed greens fine with a knife, then pulse them into the walnut mixture with the vinegar and cilantro until evenly blended but not pureed.",
                   "Taste and adjust; it should land nutty first, then garlicky, with the vinegar arriving late. Chill the mixture 30 minutes so it firms.",
                   "Roll into golf-ball rounds with damp hands, flatten each slightly, press a thumbprint into the top and fill it with pomegranate seeds.",
                   "Arrange on a plate and serve cool or at room temperature with bread, at the start of the meal.",
               ],
               note: "Squeezing the greens dry is the whole game; every tablespoon of water left in the spinach is a pkhali ball that slumps on the plate.",
               shortcut: "Frozen chopped spinach, thawed and squeezed, skips blanching entirely and honestly loses very little; you still must wring it dry."),
        Recipe(dishID: "georgia-mtsvadi", serves: 4, prepMinutes: 20, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "boneless pork shoulder, cut in 1 1/2-inch chunks"),
                   RecipeIngredient(amount: "1 tbsp", item: "kosher salt"),
                   RecipeIngredient(amount: "1 tsp", item: "coarsely ground black pepper"),
                   RecipeIngredient(amount: "2", item: "red onions, one sliced paper thin, one quartered for the skewers"),
                   RecipeIngredient(amount: "1/2 cup", item: "pomegranate seeds"),
                   RecipeIngredient(amount: "1/2 cup", item: "tkemali sauce (or thin plum jam sharpened with lemon juice and a pinch of cayenne)"),
                   RecipeIngredient(amount: "1", item: "flatbread or lavash, to serve"),
                   RecipeIngredient(amount: "1 tbsp", item: "red wine vinegar"),
               ],
               steps: [
                   "Toss the pork with the salt and pepper and let it sit at room temperature for 30 minutes; that dry salting is the entire traditional marinade.",
                   "Light a charcoal fire and let it burn to gray coals with no flame; add a few dry grapevine cuttings or fruit-wood chips if you can get them.",
                   "Toss the sliced onion with the vinegar and a pinch of salt and set it aside to soften while the meat cooks.",
                   "Thread the pork snugly onto long flat skewers, alternating with pieces of the quartered onion, keeping the chunks touching so they baste each other.",
                   "Grill over medium coals, turning a quarter turn every 4 to 5 minutes, about 18 to 22 minutes total, until deeply browned outside and just cooked at the center.",
                   "Rest the skewers 5 minutes on the lavash so the bread catches the juices, then push the meat off the skewers onto it.",
                   "Pile the vinegared onions and pomegranate seeds over the meat and serve with tkemali for dipping, tearing the juice-soaked bread as you go.",
               ],
               note: "Resist the marinade urge; salt, real coals and fruit-wood smoke are the flavor, and anything wet on the meat just steams the crust away.",
               shortcut: "A grill pan indoors gets you the crust in 15 minutes but none of the smoke; add a drop of liquid smoke to the onions, not the meat."),
        Recipe(dishID: "georgia-churchkhela", serves: 8, prepMinutes: 30, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "walnut halves, as unbroken as possible"),
                   RecipeIngredient(amount: "4 cups", item: "100 percent grape juice (dark Concord tastes closest)"),
                   RecipeIngredient(amount: "3/4 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "a pinch", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "lemon juice"),
               ],
               steps: [
                   "Thread the walnut halves onto cotton kitchen twine with a large needle, making four strands about 8 inches long, each with a loop at the top for hanging.",
                   "Whisk 1 cup of the cold grape juice with the flour until completely lump free; this slurry is what thickens the dip.",
                   "Bring the remaining 3 cups of juice to a simmer with the sugar and salt, then whisk in the slurry and cook, stirring constantly, 10 to 12 minutes until it thickens to pudding and loses its raw flour taste.",
                   "Stir in the lemon juice, then let the mixture cool 5 minutes; it should coat a spoon thickly but still flow slowly off it.",
                   "Dip each walnut strand into the warm grape pudding, hold it up until it stops dripping, and hang it over a sheet pan from a cabinet knob or rack.",
                   "After 20 minutes, dip and hang each strand a second time for a thicker coat, using the leftover pudding, rewarmed briefly if it stiffens.",
                   "Hang the strands somewhere airy for 2 to 3 days, until the surface is dry and leathery to the touch, then slice into rounds; traditional versions dry for weeks, and this quick one stays softer and fresher-tasting.",
               ],
               note: "This is the honest fast version; real churchkhela dries for weeks until a matte skin forms, so expect yours chewier, softer and closer to grape pudding on a string.",
               shortcut: "Skip stringing entirely, stir the walnuts into the thickened juice and set it in a loaf pan; slice it like fudge, no hanging or waiting days."),
        Recipe(dishID: "georgia-lobio", serves: 6, prepMinutes: 15, cookMinutes: 110, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "dried red kidney beans, soaked overnight"),
                   RecipeIngredient(amount: "2", item: "onions, chopped fine"),
                   RecipeIngredient(amount: "3 tbsp", item: "sunflower or olive oil"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "ground coriander"),
                   RecipeIngredient(amount: "1 tsp", item: "ground fenugreek (stand-in for blue fenugreek)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "cayenne"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "red wine vinegar"),
                   RecipeIngredient(amount: "1 cup", item: "fresh cilantro, chopped"),
                   RecipeIngredient(amount: "1", item: "box corn muffin mix, baked as directed, or cornbread, to serve"),
                   RecipeIngredient(amount: "a handful", item: "dill pickles, to serve"),
               ],
               steps: [
                   "Drain the soaked beans, cover them with 2 inches of fresh water in a heavy pot and boil hard for 10 minutes, then simmer 60 to 75 minutes until completely tender.",
                   "While the beans cook, fry the onions in the oil over medium heat until deeply golden, about 15 minutes, then add the garlic for the last 2 minutes.",
                   "Season the beans with the salt only once they are soft, and keep about 2 cups of their cooking liquid when you drain them.",
                   "Mash a third of the beans roughly against the pot with a wooden spoon, leaving the rest whole, and stir the onions in with a cup of the reserved liquid.",
                   "Add the coriander, fenugreek and cayenne and simmer 15 minutes, stirring and adding bean liquid as needed, until it is thick, creamy and barely pourable.",
                   "Stir in the vinegar and most of the cilantro off the heat, then taste; it should be savory and faintly bitter from fenugreek, with a sour lift at the end.",
                   "Serve hot in bowls with the rest of the cilantro on top, cornbread for dragging through it and pickles on the side.",
               ],
               note: "Salt the beans only after they soften and do not rush the simmer; underdone kidney beans are unpleasant at best and genuinely unsafe at worst.",
               shortcut: "Three 15-oz cans of kidney beans, drained, cut the cook time to 30 minutes; the stew is a little less creamy without the long-simmered bean liquid."),
        Recipe(dishID: "georgia-chikhirtma", serves: 4, prepMinutes: 15, cookMinutes: 70, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "bone-in chicken thighs and drumsticks"),
                   RecipeIngredient(amount: "8 cups", item: "water"),
                   RecipeIngredient(amount: "2", item: "large onions, chopped fine"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2 tbsp", item: "all-purpose flour"),
                   RecipeIngredient(amount: "4", item: "large egg yolks"),
                   RecipeIngredient(amount: "3 tbsp", item: "white wine vinegar"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "a pinch", item: "saffron threads (or 1/4 tsp turmeric)"),
                   RecipeIngredient(amount: "1/2 cup", item: "fresh cilantro, chopped"),
                   RecipeIngredient(amount: "1/2 loaf", item: "crusty bread, to serve"),
               ],
               steps: [
                   "Simmer the chicken in the water with 1 teaspoon of salt for 45 minutes, skimming the first foam, until the meat is falling off the bone.",
                   "Lift out the chicken, strain the broth, and shred the meat into large pieces, discarding skin and bones.",
                   "Cook the onions in the butter in the rinsed pot over medium-low heat until completely soft and translucent, about 10 minutes, without browning.",
                   "Sprinkle the flour over the onions, stir 2 minutes, then whisk the broth back in gradually and simmer 10 minutes with the saffron and remaining salt.",
                   "Return the chicken to the pot and keep the soup at a bare quiver, not a boil.",
                   "Whisk the egg yolks with the vinegar in a bowl, then whisk in a ladle of hot broth, and another, to warm the yolks gently.",
                   "Take the pot off the heat and pour the yolk mixture in slowly, stirring the whole time; the soup will turn glossy and pale gold and thicken slightly.",
                   "Stir in the cilantro and serve straight away in deep bowls with bread; do not reboil it once the eggs are in, ever.",
               ],
               note: "Everything depends on the last two minutes: temper the yolks patiently and finish off the heat, because one hard bubble turns silk into egg-drop soup.",
               shortcut: "Boxed chicken stock plus a rotisserie chicken skips the 45-minute simmer; the broth is lighter, so be a touch bolder with the vinegar."),
    ]

    static let all: [Recipe] = recipes_turkey + recipes_lebanon + recipes_georgia
}
