import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesAmericas {

    private static let recipes_mexico: [Recipe] = [
        Recipe(dishID: "mexico-pastor", serves: 4, prepMinutes: 30, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "pork shoulder, sliced 1/4 inch thick"),
                   RecipeIngredient(amount: "4", item: "dried guajillo chiles, stemmed and seeded"),
                   RecipeIngredient(amount: "1 tbsp", item: "achiote paste (or 2 tsp paprika plus 1/2 tsp turmeric)"),
                   RecipeIngredient(amount: "1/4 cup", item: "pineapple juice"),
                   RecipeIngredient(amount: "2 tbsp", item: "white vinegar"),
                   RecipeIngredient(amount: "3", item: "garlic cloves"),
                   RecipeIngredient(amount: "1 tsp", item: "dried oregano"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "fresh pineapple, cut in thin wedges"),
                   RecipeIngredient(amount: "12", item: "corn tortillas"),
                   RecipeIngredient(amount: "1/2", item: "white onion, finely chopped"),
                   RecipeIngredient(amount: "1/2 cup", item: "cilantro leaves, chopped"),
               ],
               steps: [
                   "Toast the guajillos in a dry skillet over medium heat for about 30 seconds per side, until fragrant and pliable, then soak them in hot water for 15 minutes.",
                   "Blend the soaked chiles with achiote paste, pineapple juice, vinegar, garlic, oregano and salt until completely smooth, adding a spoonful of soaking water if needed.",
                   "Coat the pork slices in the marinade and let them sit at least 20 minutes at room temperature, or up to overnight in the fridge.",
                   "Heat the broiler with a rack about 4 inches from the element. Spread the pork in a single layer on a foil-lined sheet pan with the pineapple wedges.",
                   "Broil for 6 to 8 minutes per side, until the edges char and crisp in spots. Rest the meat 5 minutes, then chop it into small pieces with the pineapple.",
                   "Warm the tortillas directly over a gas flame or in a dry skillet until soft and lightly speckled, stacking them in a clean towel.",
                   "Pile the chopped pork and pineapple onto doubled tortillas and top with onion and cilantro. Serve with lime wedges and any juices from the pan.",
               ],
               note: "The char is the dish. Get the pork close to the broiler and let the edges genuinely blacken in spots before you pull the pan out.",
               shortcut: "Thin-cut pork chops skip the slicing work, but they dry out faster, so cut the broil time by a couple of minutes."),
        Recipe(dishID: "mexico-mole", serves: 6, prepMinutes: 40, cookMinutes: 75, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "dried ancho chiles, stemmed and seeded"),
                   RecipeIngredient(amount: "3", item: "dried mulato chiles (or 3 more anchos)"),
                   RecipeIngredient(amount: "3 tbsp", item: "sesame seeds"),
                   RecipeIngredient(amount: "1/4 cup", item: "almonds"),
                   RecipeIngredient(amount: "1/4 cup", item: "raisins"),
                   RecipeIngredient(amount: "1", item: "corn tortilla, torn"),
                   RecipeIngredient(amount: "2 oz", item: "dark chocolate, chopped"),
                   RecipeIngredient(amount: "1/2", item: "white onion, quartered"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, unpeeled"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "4 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "3 tbsp", item: "lard (or vegetable oil)"),
                   RecipeIngredient(amount: "2 lb", item: "bone-in chicken thighs"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Toast the chiles in a dry skillet over medium heat until they puff and smell like raisins, about 30 seconds per side, then soak in hot water for 20 minutes.",
                   "In the same skillet, toast the sesame seeds, almonds, raisins and torn tortilla in batches until each is browned and fragrant, moving them constantly so nothing scorches.",
                   "Char the onion quarters and unpeeled garlic in the dry skillet until blackened in spots, about 8 minutes, then peel the garlic.",
                   "Blend the drained chiles, toasted seeds and nuts, raisins, tortilla, onion, garlic, cinnamon and 2 cups of stock until the paste is completely smooth, working in batches.",
                   "Heat the lard in a Dutch oven over medium heat and fry the paste, stirring constantly, until it darkens, thickens and pulls from the pan sides, 10 to 12 minutes.",
                   "Whisk in the remaining stock, the chocolate and the salt, and simmer gently for 20 minutes, stirring often, until the sauce coats a spoon like heavy cream.",
                   "Season the chicken thighs with salt, nestle them into the sauce, cover and simmer over low heat for 30 to 35 minutes, until cooked through and tender.",
                   "Serve the chicken cloaked in sauce, with a scatter of sesame seeds, warm tortillas and rice alongside.",
               ],
               note: "This is the honest weeknight version of a multi-day dish. Frying the paste until it truly darkens is the step nobody should shorten, because that is where mole gets its depth.",
               shortcut: "A cup of jarred mole paste thinned with stock replaces steps one through five, but the sauce tastes flatter and sweeter than one you toasted yourself."),
        Recipe(dishID: "mexico-pozole", serves: 6, prepMinutes: 20, cookMinutes: 120, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "pork shoulder, cut in 2-inch chunks"),
                   RecipeIngredient(amount: "2 cans (25 oz each)", item: "white hominy, drained and rinsed"),
                   RecipeIngredient(amount: "5", item: "dried guajillo chiles, stemmed and seeded"),
                   RecipeIngredient(amount: "1", item: "white onion, halved"),
                   RecipeIngredient(amount: "5", item: "garlic cloves"),
                   RecipeIngredient(amount: "2 tsp", item: "dried oregano (mexican if you can find it)"),
                   RecipeIngredient(amount: "1 tbsp", item: "salt"),
                   RecipeIngredient(amount: "2 cups", item: "green cabbage, finely shredded"),
                   RecipeIngredient(amount: "4", item: "radishes, sliced thin"),
                   RecipeIngredient(amount: "2", item: "limes, cut in wedges"),
                   RecipeIngredient(amount: "6", item: "tostadas or tortilla chips"),
               ],
               steps: [
                   "Put the pork, half the onion, 3 garlic cloves, 1 teaspoon of oregano and the salt in a large pot with 10 cups of water. Bring to a simmer, skimming any foam.",
                   "Cook the pork gently, partly covered, for about 90 minutes, until a fork slides in without resistance. Do not let it boil hard or the broth clouds.",
                   "Meanwhile, toast the guajillos in a dry skillet until fragrant, soak them in hot water for 15 minutes, then blend with the remaining onion and garlic and a cup of soaking water until smooth.",
                   "Pour the chile puree into the pot through a fine strainer, pressing it through with a spoon and discarding the skins left behind.",
                   "Add the hominy and simmer everything together, uncovered, for 30 minutes, until the broth turns brick red and tastes rounded rather than raw.",
                   "Pull the pork pieces out, shred them roughly with two forks, and return them to the pot. Taste and add salt until the broth is properly seasoned.",
                   "Ladle into deep bowls and let everyone add their own cabbage, radish, oregano and lime at the table, with tostadas for crunch.",
               ],
               note: "The garnishes are not optional. Pozole without the cold crunch of cabbage and the lime squeezed in at the table is only half the dish.",
               shortcut: "Boneless country-style pork ribs cook in an hour instead of ninety minutes, though the broth loses a little body without the shoulder's connective tissue."),
        Recipe(dishID: "mexico-cochinita", serves: 6, prepMinutes: 20, cookMinutes: 210, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "pork shoulder, cut in 3-inch chunks"),
                   RecipeIngredient(amount: "3 tbsp", item: "achiote paste"),
                   RecipeIngredient(amount: "1/2 cup", item: "orange juice"),
                   RecipeIngredient(amount: "1/4 cup", item: "lime juice"),
                   RecipeIngredient(amount: "2 tbsp", item: "white vinegar"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 package", item: "banana leaves (frozen, from a latin or asian market; or parchment plus foil)"),
                   RecipeIngredient(amount: "1", item: "red onion, sliced very thin"),
                   RecipeIngredient(amount: "1", item: "habanero chile, sliced thin"),
                   RecipeIngredient(amount: "12", item: "corn tortillas"),
               ],
               steps: [
                   "Whisk the achiote paste with the orange juice, lime juice, half the vinegar, the garlic, cumin and salt until it dissolves into a loose brick-red marinade.",
                   "Toss the pork chunks in the marinade and refrigerate at least 30 minutes, or overnight if you have the time.",
                   "Heat the oven to 300°F. Pass the banana leaves briefly over a stove flame until they turn glossy and pliable, then line a Dutch oven with them, leaving overhang.",
                   "Pile in the pork and all its marinade, fold the leaves over the top, cover with the lid and bake for 3 to 3 1/2 hours, until the meat collapses under a fork.",
                   "While the pork cooks, toss the red onion and habanero with the remaining vinegar and a pinch of salt, and let them pickle at room temperature.",
                   "Shred the pork into its own juices with two forks, discarding any large pieces of fat, and taste for salt.",
                   "Serve piled onto warm tortillas with the pickled onion and habanero on top, spooning extra juice over each taco.",
               ],
               note: "Sour orange is the traditional acid, and the orange-lime mix here is the closest supermarket match. Keep the meat swimming in its juices after shredding or it dries in minutes.",
               shortcut: "Skip the banana leaves and use a covered Dutch oven alone. You lose the faint green tea aroma but keep everything else."),
        Recipe(dishID: "mexico-tamal", serves: 6, prepMinutes: 60, cookMinutes: 75, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "masa harina"),
                   RecipeIngredient(amount: "1 cup", item: "lard (or vegetable shortening), softened"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "baking powder"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 1/2 cups", item: "warm chicken stock"),
                   RecipeIngredient(amount: "3 cups", item: "cooked chicken, shredded"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "mole negro (jarred is fine), warmed"),
                   RecipeIngredient(amount: "1 package", item: "banana leaves (frozen; or corn husks, soaked)"),
               ],
               steps: [
                   "Beat the lard with the baking powder and salt in a stand mixer or with a hand mixer until fluffy and pale, about 3 minutes.",
                   "Add the masa harina and the warm stock in alternating additions, beating until the dough is light and spreadable. A small ball of it should float in a glass of water.",
                   "Toss the shredded chicken with 1 cup of the mole so every strand is darkly coated.",
                   "Pass the banana leaves over a flame until glossy and cut them into rectangles roughly 10 by 8 inches.",
                   "Spread a scant 1/2 cup of dough into a thin square in the center of each leaf, top with a spoonful of chicken and a little extra mole, then fold the leaf into a flat parcel.",
                   "Stack the parcels seam side down in a steamer basket over simmering water, cover with a damp towel and the lid, and steam for 60 to 75 minutes, topping up the water as needed.",
                   "Test one tamal: the dough should peel cleanly from the leaf and feel set. Rest them 10 minutes before serving, since they firm as they stand.",
                   "Serve in the leaf, letting each person unwrap their own, with any remaining mole spooned over.",
               ],
               note: "The float test is the whole game. If the dough ball sinks, keep beating in air and fat, because dense dough steams into a brick no filling can save.",
               shortcut: "Corn husks from any supermarket work in place of banana leaves. The tamales come out rounder and lose the leafy perfume, but steam exactly the same way."),
        Recipe(dishID: "mexico-nogada", serves: 4, prepMinutes: 50, cookMinutes: 35, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "large poblano chiles"),
                   RecipeIngredient(amount: "1 lb", item: "ground pork"),
                   RecipeIngredient(amount: "1/2", item: "white onion, chopped"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1", item: "apple, peeled and diced"),
                   RecipeIngredient(amount: "1", item: "pear, peeled and diced"),
                   RecipeIngredient(amount: "1/3 cup", item: "raisins (or chopped candied fruit)"),
                   RecipeIngredient(amount: "1", item: "tomato, chopped"),
                   RecipeIngredient(amount: "1/4 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "walnuts"),
                   RecipeIngredient(amount: "4 oz", item: "cream cheese (or queso fresco)"),
                   RecipeIngredient(amount: "3/4 cup", item: "milk"),
                   RecipeIngredient(amount: "1/2 cup", item: "pomegranate seeds"),
               ],
               steps: [
                   "Char the poblanos directly over a gas flame or under the broiler, turning, until blackened all over. Steam them in a covered bowl 10 minutes, then rub off the skins.",
                   "Cut a slit down one side of each chile and pull out the seeds carefully, keeping the stem and the chile whole.",
                   "Cook the onion and garlic in a skillet over medium heat until soft, then add the pork and cook, breaking it up, until no longer pink.",
                   "Stir in the apple, pear, raisins, tomato, cinnamon and salt, and simmer until the fruit is tender and the pan is nearly dry, about 12 minutes. Cool slightly.",
                   "Pour boiling water over the walnuts, let them sit 5 minutes, and rub off as much of the papery brown skin as your patience allows, since the skins turn the sauce bitter.",
                   "Blend the walnuts with the cream cheese, milk and a pinch of salt until completely smooth and pourable. Chill the sauce while you stuff the chiles.",
                   "Fill each poblano generously with the warm picadillo and close the slit as best you can.",
                   "Set one stuffed chile on each plate, pour the cold walnut sauce over the middle, and scatter pomegranate seeds across the top just before serving.",
               ],
               note: "The dish depends on the temperature contrast: warm chile, cold sauce, and pomegranate added at the last second so the white stays white.",
               shortcut: "Skip skinning the walnuts and accept a beige, slightly tannic sauce. It saves twenty fiddly minutes and most guests never notice."),
        Recipe(dishID: "mexico-elote", serves: 4, prepMinutes: 10, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "ears of corn, husked"),
                   RecipeIngredient(amount: "1/4 cup", item: "mayonnaise"),
                   RecipeIngredient(amount: "1/4 cup", item: "mexican crema (or sour cream thinned with a little milk)"),
                   RecipeIngredient(amount: "1/2 cup", item: "cotija cheese, crumbled (or grated parmesan)"),
                   RecipeIngredient(amount: "1 tsp", item: "chile powder"),
                   RecipeIngredient(amount: "1", item: "lime, cut in wedges"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
               ],
               steps: [
                   "Heat a grill or a cast iron grill pan over high heat until it smokes faintly.",
                   "Grill the corn, turning every couple of minutes, until the kernels are deep gold with charred spots on every side, 10 to 12 minutes total.",
                   "While the corn cooks, stir the mayonnaise, crema and salt together in a small bowl and spread the cotija on a plate.",
                   "Working while the corn is hot, brush each ear all over with the mayonnaise mixture so it clings in a thin even coat.",
                   "Roll each ear through the crumbled cheese, pressing lightly so it sticks, then dust with chile powder.",
                   "Squeeze lime generously over each ear and serve immediately, with more wedges on the side and napkins nearby.",
               ],
               note: "Dress the corn while it is almost too hot to hold. On cooled corn the coating slides instead of melting into the kernels.",
               shortcut: "Boil the corn 5 minutes instead of grilling when the weather is against you. You lose the char but the salty, cheesy, limey coating still carries it."),
        Recipe(dishID: "mexico-pandemuerto", serves: 8, prepMinutes: 45, cookMinutes: 30, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 1/4 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1/2 cup", item: "sugar, plus 1/3 cup for coating"),
                   RecipeIngredient(amount: "3", item: "eggs"),
                   RecipeIngredient(amount: "1/2 cup", item: "milk, warm"),
                   RecipeIngredient(amount: "1", item: "orange, zested"),
                   RecipeIngredient(amount: "1 tsp", item: "anise seed"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "10 tbsp", item: "butter, softened, plus 2 tbsp melted for finishing"),
               ],
               steps: [
                   "Stir the flour, yeast, 1/2 cup sugar, salt, anise seed and orange zest together, then add the eggs and warm milk and mix into a shaggy dough.",
                   "Knead 5 minutes, then work in the softened butter a spoonful at a time, kneading until the dough is glossy, elastic and pulls cleanly off the counter, about 10 more minutes.",
                   "Cover and let the dough rise in a warm spot until doubled, 1 1/2 to 2 hours.",
                   "Cut off a quarter of the dough and set it aside. Shape the rest into a tight round on a parchment-lined sheet pan.",
                   "Roll the reserved dough into four thin ropes, pressing knuckle bumps into each so they look like bones, plus one small ball. Drape the ropes over the round in a cross and set the ball on top.",
                   "Cover loosely and let rise until puffy, about 45 minutes, while the oven heats to 350°F.",
                   "Bake 25 to 30 minutes, until deep gold and hollow-sounding when tapped on the bottom. Tent with foil if the bones brown too fast.",
                   "While still warm, brush all over with melted butter and shower with the remaining sugar so it sticks in a crunchy coat.",
               ],
               note: "The butter goes in only after the dough has structure. Add it early and you will knead twice as long wondering why the dough stays a sticky puddle.",
               shortcut: "Let the shaped loaf rise overnight in the fridge and bake it in the morning. The flavor deepens and the timeline stops owning your evening."),
    ]

    private static let recipes_peru: [Recipe] = [
        Recipe(dishID: "peru-ceviche", serves: 4, prepMinutes: 25, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "very fresh sea bass or other firm white fish, skinless"),
                   RecipeIngredient(amount: "10", item: "limes, juiced"),
                   RecipeIngredient(amount: "1", item: "habanero chile, seeded and minced (the closest stand-in for ají limo)"),
                   RecipeIngredient(amount: "1", item: "red onion, sliced paper thin"),
                   RecipeIngredient(amount: "1", item: "garlic clove, grated"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/4 cup", item: "cilantro leaves, chopped"),
                   RecipeIngredient(amount: "1", item: "sweet potato"),
                   RecipeIngredient(amount: "1", item: "ear of corn, cut in 4 rounds"),
               ],
               steps: [
                   "Boil the sweet potato whole until a knife slides through, about 20 minutes, adding the corn rounds for the last 8 minutes. Drain, peel the sweet potato and slice it thick. Cool both.",
                   "Rinse the sliced onion in cold water and drain well, which softens its bite without losing the crunch.",
                   "Cut the fish into neat 3/4-inch cubes, trimming away any dark bloodline, and keep it cold until the last minute.",
                   "In a chilled bowl, stir the lime juice with the garlic, half the habanero and the salt.",
                   "Add the fish and fold gently so every piece is submerged. Let it sit just 3 to 5 minutes, until the outside turns opaque but the center stays translucent.",
                   "Fold in the onion, cilantro and the rest of the habanero, then taste the milky juice and add salt until it makes you sit up.",
                   "Serve immediately in shallow bowls with the sweet potato and corn alongside, spooning plenty of the juice over everything.",
               ],
               note: "Buy the fish the day you make it, from a counter you trust, and tell them it is for ceviche. Everything else in the dish is negotiable except that.",
               shortcut: "Frozen-and-thawed fish sold as sushi or sashimi grade is a safe fallback. The texture is a shade softer, but the safety margin is real."),
        Recipe(dishID: "peru-lomo", serves: 4, prepMinutes: 20, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "sirloin steak, cut in thick strips"),
                   RecipeIngredient(amount: "1", item: "red onion, cut in thick wedges"),
                   RecipeIngredient(amount: "2", item: "tomatoes, cut in wedges, seeds shaken out"),
                   RecipeIngredient(amount: "3 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "red wine vinegar"),
                   RecipeIngredient(amount: "1 tbsp", item: "ají amarillo paste (or 1 tsp sriracha with a pinch of turmeric)"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1 lb", item: "frozen french fries"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1/4 cup", item: "cilantro leaves"),
                   RecipeIngredient(amount: "3 cups", item: "cooked white rice, hot"),
               ],
               steps: [
                   "Bake or air-fry the french fries until deeply crisp, timing them to finish when the beef does.",
                   "Pat the beef strips very dry and season with salt, pepper and the cumin. Stir the soy sauce, vinegar and ají amarillo paste together in a cup.",
                   "Heat half the oil in your largest skillet over the highest heat until it smokes. Sear half the beef in a single layer, undisturbed, 1 minute per side, and remove. Repeat with the rest.",
                   "Add the remaining oil, then the onion wedges, and stir-fry 2 minutes, keeping them crisp at the center. Add the garlic and tomatoes for 1 minute more.",
                   "Return the beef and any juices to the pan, pour the soy mixture down the hot sides so it sizzles, and toss everything for 30 seconds.",
                   "Pull the pan off the heat, fold in the hot fries and the cilantro, and toss once so some fries soak and some stay crisp.",
                   "Serve immediately with white rice on the same plate, pushing the rice into the gravy as you eat.",
               ],
               note: "Smoking-hot pan, small batches, meat bone dry. The moment the beef steams instead of sears, you have stew, not saltado.",
               shortcut: "Bagged frozen fries are not cheating, they are what most Lima kitchens use on a weekday. Cutting fresh potatoes buys you little here."),
        Recipe(dishID: "peru-ajigallina", serves: 4, prepMinutes: 20, cookMinutes: 40, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "bone-in chicken breasts"),
                   RecipeIngredient(amount: "3 tbsp", item: "ají amarillo paste"),
                   RecipeIngredient(amount: "1 can (12 oz)", item: "evaporated milk"),
                   RecipeIngredient(amount: "3 slices", item: "white sandwich bread, crusts removed"),
                   RecipeIngredient(amount: "1/3 cup", item: "walnuts"),
                   RecipeIngredient(amount: "1/4 cup", item: "grated parmesan"),
                   RecipeIngredient(amount: "1", item: "white onion, finely chopped"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 cups", item: "cooked white rice, hot"),
                   RecipeIngredient(amount: "2", item: "yukon gold potatoes, boiled and sliced"),
                   RecipeIngredient(amount: "8", item: "black olives"),
                   RecipeIngredient(amount: "2", item: "hard-boiled eggs, quartered"),
               ],
               steps: [
                   "Simmer the chicken in salted water to cover until just cooked through, about 20 minutes. Reserve the broth, cool the chicken, and pull it into fine shreds.",
                   "Soak the bread in half the evaporated milk until collapsed, then blend it with the walnuts and the remaining milk into a smooth cream.",
                   "Cook the onion in the oil over medium heat until soft and translucent, about 6 minutes, then add the garlic and ají amarillo paste and fry 2 minutes more, until the oil turns yellow.",
                   "Pour in the bread cream and a cup of the reserved broth, and simmer gently, stirring, until the sauce thickens enough to hold a trail from the spoon.",
                   "Fold in the shredded chicken and parmesan, and loosen with more broth until the sauce is thick but pourable. Season with the salt.",
                   "Simmer 5 more minutes over low heat so the chicken drinks in the sauce, stirring so the bottom does not catch.",
                   "Serve over rice and sliced boiled potato, topped with olives and hard-boiled egg.",
               ],
               note: "The sauce should be the yellow of egg yolk and thick enough to nap the potato. If it tightens as it sits, loosen it with broth, never water.",
               shortcut: "A rotisserie chicken and store broth cut out the poaching step entirely, trimming half an hour for a slightly less silky sauce."),
        Recipe(dishID: "peru-huancaina", serves: 4, prepMinutes: 15, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "yukon gold potatoes"),
                   RecipeIngredient(amount: "8 oz", item: "queso fresco"),
                   RecipeIngredient(amount: "3 tbsp", item: "ají amarillo paste"),
                   RecipeIngredient(amount: "3/4 cup", item: "evaporated milk"),
                   RecipeIngredient(amount: "4", item: "saltine crackers"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "4", item: "lettuce leaves"),
                   RecipeIngredient(amount: "8", item: "black olives"),
                   RecipeIngredient(amount: "2", item: "hard-boiled eggs, halved"),
               ],
               steps: [
                   "Boil the potatoes whole in well-salted water until a knife meets no resistance, 20 to 25 minutes, then drain and let them cool until just warm.",
                   "Warm the oil and ají amarillo paste together in a small pan for 2 minutes, until fragrant and glossy, which mellows the paste's raw edge.",
                   "Blend the queso fresco, evaporated milk, crackers, the ají oil and the salt until completely smooth and thick enough to coat a spoon heavily.",
                   "Taste the sauce and adjust: more milk if too thick, another cracker if too thin, more paste if you want the heat to announce itself.",
                   "Peel the potatoes and slice them into thick rounds.",
                   "Lay lettuce on a platter, shingle the potato slices over it, and pour the sauce generously across the middle.",
                   "Finish with the olives and halved eggs, and serve at room temperature or lightly chilled.",
               ],
               note: "The crackers are the traditional thickener, not a hack, and they matter. Without them the sauce is a soup that slides straight off the potato.",
               shortcut: "Feta blended with a little extra milk stands in for queso fresco. Cut the added salt in half, since feta brings its own."),
        Recipe(dishID: "peru-anticucho", serves: 4, prepMinutes: 30, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "beef heart, trimmed (or sirloin, the common home substitute)"),
                   RecipeIngredient(amount: "3 tbsp", item: "ají panca paste (or 2 tbsp ancho chile powder mixed with oil)"),
                   RecipeIngredient(amount: "1/4 cup", item: "red wine vinegar"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1 tsp", item: "dried oregano"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 lb", item: "small potatoes, boiled"),
                   RecipeIngredient(amount: "8", item: "wooden or metal skewers"),
               ],
               steps: [
                   "If using wooden skewers, soak them in water for 30 minutes so they survive the fire.",
                   "Trim the beef heart of any silverskin and fat, and cut it into flat pieces roughly 1 1/2 inches square and 1/2 inch thick.",
                   "Whisk the ají panca paste, vinegar, garlic, cumin, oregano, salt and 2 tablespoons of the oil into a loose marinade.",
                   "Toss the meat in the marinade and refrigerate at least 20 minutes, or up to 4 hours for deeper flavor. Reserve a spoonful of marinade for basting.",
                   "Thread the meat flat onto the skewers, three or four pieces each, so every piece can touch the heat.",
                   "Grill over the hottest part of a charcoal or gas grill, or under a scorching broiler, 2 to 3 minutes per side, basting once, until charred outside and just pink within.",
                   "Rest the skewers 2 minutes and serve with the boiled potatoes, which belong under the meat to catch the drippings.",
               ],
               note: "Heart is a muscle that goes from tender to rubber in about a minute, so stand at the grill and pull the skewers while the centers are still rosy.",
               shortcut: "Sirloin cubes take the same marinade and forgive an extra minute of cooking, at the cost of the mineral depth that makes anticuchos themselves."),
        Recipe(dishID: "peru-causa", serves: 6, prepMinutes: 40, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "yukon gold potatoes"),
                   RecipeIngredient(amount: "3 tbsp", item: "ají amarillo paste"),
                   RecipeIngredient(amount: "3", item: "limes, juiced"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 cups", item: "cooked chicken, finely shredded"),
                   RecipeIngredient(amount: "1/2 cup", item: "mayonnaise"),
                   RecipeIngredient(amount: "2", item: "ripe avocados, sliced thin"),
                   RecipeIngredient(amount: "1/4", item: "red onion, minced"),
                   RecipeIngredient(amount: "2", item: "hard-boiled eggs, sliced, for the top"),
               ],
               steps: [
                   "Boil the potatoes whole in salted water until completely tender, about 25 minutes, then drain and peel while still hot.",
                   "Rice or mash the potatoes until absolutely smooth, with no lumps, and let them cool to warm.",
                   "Work the ají amarillo paste, lime juice, oil and salt into the potatoes with your hands until the mash is yellow, tangy and holds together like soft dough. Cool fully.",
                   "Mix the shredded chicken with the mayonnaise and minced onion, and season it with salt and a squeeze of lime.",
                   "Press half the potato dough into an even layer in a loaf pan or springform lined with plastic wrap.",
                   "Cover with the chicken salad, then a layer of avocado slices, then press the remaining potato dough evenly over the top.",
                   "Chill at least 1 hour, then unmold, top with sliced egg, and cut into thick slices with a wet knife.",
               ],
               note: "Season the potato until it tastes slightly too sharp on its own. Cold dulls everything, and a timid causa is just mashed potato in a mold.",
               shortcut: "Skip the mold and layer it in individual glasses like a parfait. It sets faster, unmolds never, and looks intentional."),
        Recipe(dishID: "peru-pachamanca", serves: 6, prepMinutes: 30, cookMinutes: 150, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "lamb shoulder, cut in large chunks"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "pork shoulder, cut in large chunks"),
                   RecipeIngredient(amount: "1/2 cup", item: "huacatay paste (jarred, from a latin market; or blended mint, cilantro and basil)"),
                   RecipeIngredient(amount: "6", item: "garlic cloves"),
                   RecipeIngredient(amount: "1 tbsp", item: "ground cumin"),
                   RecipeIngredient(amount: "1/4 cup", item: "red wine vinegar"),
                   RecipeIngredient(amount: "1 tbsp", item: "salt"),
                   RecipeIngredient(amount: "2 lb", item: "small potatoes, scrubbed"),
                   RecipeIngredient(amount: "1 lb", item: "frozen fava beans (or lima beans), thawed"),
                   RecipeIngredient(amount: "2", item: "ears of corn, cut in thirds"),
                   RecipeIngredient(amount: "1 package", item: "banana leaves (or parchment and foil)"),
               ],
               steps: [
                   "Blend the huacatay paste, garlic, cumin, vinegar, salt and a splash of water into a thick green marinade.",
                   "Toss the lamb and pork in two-thirds of the marinade and refrigerate at least 30 minutes, or overnight.",
                   "Heat the oven to 325°F and line a deep roasting pan or large Dutch oven with banana leaves, letting them hang over the sides.",
                   "Lay the potatoes on the bottom, since they take the longest, then the marinated meats, then the corn and favas, spooning the reserved marinade over the vegetables.",
                   "Fold the leaves over everything, cover tightly with a lid or a double layer of foil, and bake for 2 1/2 hours without peeking.",
                   "Check the meat: it should pull apart at a touch, and the potatoes should be floury right through. Give it 20 more covered minutes if not.",
                   "Open the leaves at the table so everyone gets the burst of green steam, and serve straight from the pot with the juices spooned over.",
               ],
               note: "This is the oven translation of an earth pit, and it says so proudly. The sealed leaves and the long unopened bake are what keep the highland character.",
               shortcut: "Use only pork shoulder instead of two meats. One less package, no flavor argument at the table, and the leftovers are less confusing."),
        Recipe(dishID: "peru-picarones", serves: 6, prepMinutes: 45, cookMinutes: 40, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "butternut squash, peeled and cubed"),
                   RecipeIngredient(amount: "1 cup", item: "sweet potato, peeled and cubed"),
                   RecipeIngredient(amount: "2 1/2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 1/4 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "anise seed"),
                   RecipeIngredient(amount: "8 oz", item: "piloncillo or dark brown sugar (the chancaca substitute)"),
                   RecipeIngredient(amount: "2 strips", item: "orange peel"),
                   RecipeIngredient(amount: "1", item: "cinnamon stick"),
                   RecipeIngredient(amount: "2", item: "whole cloves"),
                   RecipeIngredient(amount: "6 cups", item: "vegetable oil, for frying"),
               ],
               steps: [
                   "Boil the squash and sweet potato until completely soft, about 15 minutes, then drain, reserving a cup of the cooking water, and mash until smooth. Cool to warm.",
                   "Mix the mash with the flour, yeast, sugar, salt, anise seed and enough reserved cooking water to make a very soft, sticky, stretchy dough. Beat it by hand for 5 minutes.",
                   "Cover and let the dough rise until doubled and bubbly, about 1 hour.",
                   "Meanwhile, simmer the piloncillo with 1 cup water, the orange peel, cinnamon and cloves until it turns into a syrup that coats a spoon, about 15 minutes. Keep warm.",
                   "Heat the oil in a deep pot to 360°F. Set a bowl of salted water beside it for your hands.",
                   "With wet fingers, scoop a handful of dough, poke a hole through the center, and stretch it into a rough ring as you lower it into the oil.",
                   "Fry two or three rings at a time, turning once, until puffed and deep gold, about 2 minutes per side. Drain on a rack.",
                   "Stack the hot rings in shallow bowls and pour the warm spiced syrup generously over them. Eat immediately, with fingers.",
               ],
               note: "The dough should feel too wet to shape, which is exactly right. Wet hands and a fast drop into the oil are the entire technique.",
               shortcut: "Canned pumpkin replaces the boiled squash and skips a pot. The rings taste slightly earthier and nobody in the room will object."),
    ]

    private static let recipes_brazil: [Recipe] = [
        Recipe(dishID: "brazil-feijoada", serves: 6, prepMinutes: 25, cookMinutes: 165, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "dried black beans"),
                   RecipeIngredient(amount: "1 lb", item: "smoked pork ribs, cut apart"),
                   RecipeIngredient(amount: "12 oz", item: "linguiça (or kielbasa), thickly sliced"),
                   RecipeIngredient(amount: "4 oz", item: "slab bacon, cubed"),
                   RecipeIngredient(amount: "1", item: "white onion, chopped"),
                   RecipeIngredient(amount: "4", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "2", item: "bay leaves"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "2", item: "oranges, peeled and sliced"),
                   RecipeIngredient(amount: "1 bunch", item: "collard greens, sliced in thin ribbons"),
                   RecipeIngredient(amount: "1 cup", item: "cassava flour (or coarse dry breadcrumbs), for farofa"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter"),
                   RecipeIngredient(amount: "4 cups", item: "cooked white rice, hot"),
               ],
               steps: [
                   "Cover the beans with cold water and soak overnight, or use the quick method: boil 2 minutes, then rest covered for 1 hour. Drain.",
                   "In a large Dutch oven, brown the bacon in its own fat, then the linguiça, and set the sausage aside. Cook the onion in the fat until golden, adding the garlic at the end.",
                   "Add the beans, smoked ribs, bay leaves and 8 cups of water. Simmer, partly covered, for about 2 hours, until the beans are fully soft and the ribs give way.",
                   "Return the linguiça for the last 30 minutes. Mash a ladle of beans against the pot wall and stir it back in, so the broth thickens to a dark gravy. Season with the salt.",
                   "While the pot finishes, toast the cassava flour in the butter over medium heat, stirring constantly, until golden and nutty, about 5 minutes. This is the farofa.",
                   "Wilt the collard ribbons in a hot oiled skillet with a pinch of salt for 2 minutes, keeping them bright and slightly crisp.",
                   "Serve the feijoada over rice, with the collards, orange slices and a generous spoonful of farofa on every plate. Do not skip the orange.",
               ],
               note: "The orange is not a garnish, it is relief. This is the weeknight-scale version of a Saturday pot, and it still wants nothing scheduled afterward.",
               shortcut: "Canned black beans collapse the simmer to 45 minutes. You give up some body in the broth, so mash in an extra ladleful."),
        Recipe(dishID: "brazil-moqueca", serves: 4, prepMinutes: 20, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "firm white fish fillets, cut in large pieces"),
                   RecipeIngredient(amount: "2", item: "limes, juiced"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, minced"),
                   RecipeIngredient(amount: "1", item: "white onion, sliced in rings"),
                   RecipeIngredient(amount: "2", item: "bell peppers (one red, one yellow), sliced in rings"),
                   RecipeIngredient(amount: "3", item: "tomatoes, sliced in rounds"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut milk"),
                   RecipeIngredient(amount: "2 tbsp", item: "dendê palm oil (or olive oil plus 1 tsp sweet paprika)"),
                   RecipeIngredient(amount: "1/2 cup", item: "cilantro, roughly chopped"),
                   RecipeIngredient(amount: "3 cups", item: "cooked white rice, hot"),
               ],
               steps: [
                   "Toss the fish with the lime juice, garlic and salt, and let it sit while you slice the vegetables, about 15 minutes.",
                   "In a wide heavy pot or clay casserole, lay down half the onion, pepper and tomato rings in an even bed.",
                   "Arrange the fish pieces on the vegetables in a single layer, then cover with the remaining onion, pepper and tomato.",
                   "Pour the coconut milk over everything and drizzle the dendê oil across the top. Do not stir, now or later.",
                   "Cover and bring to a gentle simmer over medium-low heat, then cook 20 to 25 minutes, until the fish flakes and the vegetables slump into the broth.",
                   "Tilt the pot and spoon the orange broth back over the fish a few times, then scatter the cilantro thickly across the surface.",
                   "Bring the pot straight to the table and serve over rice, with hot sauce on the side for those who want it.",
               ],
               note: "No browning, no stirring, no shortcuts on the dendê if you can find it, because that waxy orange fruitiness is the entire signature of Bahia.",
               shortcut: "Shrimp instead of fish cuts the simmer to 8 minutes. Add them raw for the final stretch so they stay plump."),
        Recipe(dishID: "brazil-paodequeijo", serves: 6, prepMinutes: 20, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "tapioca flour (the US shelf name for cassava starch)"),
                   RecipeIngredient(amount: "1/2 cup", item: "milk"),
                   RecipeIngredient(amount: "1/4 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "3/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "egg"),
                   RecipeIngredient(amount: "3/4 cup", item: "grated parmesan"),
                   RecipeIngredient(amount: "3/4 cup", item: "shredded mozzarella"),
               ],
               steps: [
                   "Heat the oven to 375°F and line a sheet pan with parchment.",
                   "Bring the milk, oil and salt just to a boil in a small saucepan, watching it, since it foams up the moment it turns.",
                   "Pour the hot liquid over the tapioca flour in a bowl and stir hard. It will look like lumpy glue, which is correct.",
                   "Let the mixture cool 10 minutes, then beat in the egg until the dough turns smooth, glossy and stretchy.",
                   "Work in both cheeses until evenly distributed. The dough should be sticky but hold a shape; add a spoonful more tapioca flour if it pools.",
                   "With oiled hands, roll the dough into balls the size of a golf ball and space them on the pan.",
                   "Bake 20 to 25 minutes, until puffed, pale gold and hollow-feeling when lifted. Eat warm, when the centers still pull like taffy.",
               ],
               note: "The hot milk poured over the starch is what makes them chew instead of crumble. Cold-mixed versions bake up as sad little biscuits.",
               shortcut: "Freeze the raw balls on a tray and bag them. They bake from frozen in 30 minutes, which is how Brazilian households actually operate."),
        Recipe(dishID: "brazil-acaraje", serves: 4, prepMinutes: 50, cookMinutes: 30, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "dried black-eyed peas"),
                   RecipeIngredient(amount: "1", item: "white onion, half chopped rough, half minced"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "4 cups", item: "red palm oil for frying (or vegetable oil plus 1 tbsp paprika)"),
                   RecipeIngredient(amount: "1/2 cup", item: "dried shrimp (or 1/2 lb cooked shrimp, chopped)"),
                   RecipeIngredient(amount: "2 slices", item: "white bread, torn"),
                   RecipeIngredient(amount: "1/2 cup", item: "coconut milk"),
                   RecipeIngredient(amount: "1/4 cup", item: "roasted peanuts"),
                   RecipeIngredient(amount: "1 tsp", item: "grated fresh ginger"),
                   RecipeIngredient(amount: "1 tbsp", item: "malagueta pepper sauce (or any hot sauce)"),
                   RecipeIngredient(amount: "1", item: "tomato, diced"),
                   RecipeIngredient(amount: "1/4 cup", item: "cilantro, chopped"),
               ],
               steps: [
                   "Soak the black-eyed peas in cold water overnight. Then rub them hard between your palms under water so the skins float free, and pour the skins off. Patience here pays.",
                   "Blend the skinned peas with the rough-chopped onion and half the salt into a thick, fluffy batter, adding water a spoonful at a time only if the blender stalls.",
                   "Beat the batter with a spoon for 2 minutes to work in air, which keeps the fritters light.",
                   "For the filling, blend the bread, coconut milk, half the dried shrimp, the peanuts, ginger and remaining salt into a soft paste, and warm it in a pan until it thickens. This is a quick vatapá.",
                   "Stir the tomato, minced onion and cilantro together for a fresh salad topping.",
                   "Heat 2 inches of palm oil in a deep pot to 350°F. Drop in large spoonfuls of batter, shaping each between two spoons, and fry until deep orange-brown, about 3 minutes per side.",
                   "Drain the fritters, split each one open like a pocket while hot, and load it with vatapá, the remaining shrimp, the tomato salad and hot sauce.",
                   "Serve immediately, standing up if you want the full Salvador effect.",
               ],
               note: "Skinning the peas is the step that separates acarajé from a bean pancake. The skins weigh the batter down and the fritters will not puff with them in.",
               shortcut: "A food processor pulse before soaking cracks the peas so the skins slip off in half the time, at the cost of a few lost pea halves."),
        Recipe(dishID: "brazil-picanha", serves: 6, prepMinutes: 10, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "picanha (ask the butcher for top sirloin cap with the fat left on)"),
                   RecipeIngredient(amount: "2 tbsp", item: "coarse salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 cup", item: "cassava flour (or coarse dry breadcrumbs)"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2", item: "garlic cloves, minced"),
               ],
               steps: [
                   "Cut the picanha with the grain into 3 thick strips, each with its cap of fat, and bend each strip into a C shape onto a long skewer, fat side out. Season heavily with the coarse salt.",
                   "Let the skewers sit at room temperature for 30 minutes while you light a charcoal grill or heat a gas grill to high.",
                   "Grill fat side toward the heat first, lid open, until the fat crackles, renders and chars at the edges, 8 to 10 minutes, managing flare-ups by shifting the skewers.",
                   "Turn and grill the meat sides until a thermometer reads 125°F in the thickest part for medium-rare, another 10 to 12 minutes.",
                   "Rest the skewers 10 minutes on a board, uncovered, so the crust stays crisp.",
                   "While the meat rests, melt the butter in a skillet, cook the garlic 30 seconds, then toast the cassava flour in it, stirring, until golden. This is the farofa.",
                   "Slice the picanha thin against the grain, straight off the skewer at the board, and serve with the farofa and any board juices.",
               ],
               note: "Salt and fire are the recipe. The fat cap must render and crackle before the meat side ever touches the heat, or it stays waxy.",
               shortcut: "No grill: sear the fat side in a cold cast iron pan set over medium heat, then finish in a 400°F oven to temperature."),
        Recipe(dishID: "brazil-tacaca", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "4 cups", item: "jarred tucupi (from a brazilian market; or shrimp stock sharpened with 3 tbsp lime juice)"),
                   RecipeIngredient(amount: "3", item: "garlic cloves, smashed"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "tapioca starch"),
                   RecipeIngredient(amount: "1 cup", item: "dried shrimp, soaked 10 minutes (or small cooked shrimp)"),
                   RecipeIngredient(amount: "2 cups", item: "watercress (the stand-in for jambu)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground sichuan peppercorn (for jambu's tingle)"),
                   RecipeIngredient(amount: "1 tbsp", item: "malagueta pepper sauce (or any hot sauce)"),
                   RecipeIngredient(amount: "1", item: "lime, cut in wedges"),
               ],
               steps: [
                   "Simmer the tucupi with the garlic and salt, partly covered, for 20 minutes, so the broth mellows and takes the garlic in.",
                   "Whisk the tapioca starch with 1 1/2 cups cold water until smooth, then pour it into a small saucepan over medium heat, stirring constantly until it turns into a thick translucent gel, about 4 minutes. This is the goma.",
                   "Blanch the watercress in the simmering broth for 30 seconds, then lift it out and set it aside.",
                   "Add the soaked shrimp to the broth and simmer 5 minutes, until plump and tender.",
                   "Dust the watercress with the ground sichuan peppercorn and toss, which borrows jambu's electric tingle honestly, if imperfectly.",
                   "To serve, spoon a ribbon of the tapioca gel into each deep bowl or mug, add a tangle of watercress and a share of shrimp, and ladle the hot broth over.",
                   "Finish each bowl with hot sauce and a squeeze of lime, and drink it rather than spoon it, tipping the bowl to catch the slippery strands.",
               ],
               note: "This is an honest adaptation: real tucupi and jambu rarely leave the Amazon. Chase the sour-hot-numbing balance rather than the exact ingredients and the bowl still transports.",
               shortcut: "Skip the sichuan peppercorn and accept a tacacá without the numbness. It becomes a sour shrimp soup, still worth making on a cold night."),
        Recipe(dishID: "brazil-tapioca", serves: 2, prepMinutes: 10, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "tapioca starch"),
                   RecipeIngredient(amount: "3 tbsp", item: "water"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1/2 cup", item: "shredded low-moisture mozzarella (or sliced halloumi, closer to queijo coalho)"),
                   RecipeIngredient(amount: "1/4 cup", item: "sweetened shredded coconut"),
                   RecipeIngredient(amount: "2 tbsp", item: "condensed milk"),
               ],
               steps: [
                   "Sprinkle the water over the tapioca starch with the salt and rub it between your fingers until the whole bowl feels like damp sand with no wet clumps.",
                   "Push the mixture through a sieve into a second bowl, so it becomes a fine, loose, snowy powder. This step is what makes the disc knit together.",
                   "Heat a small nonstick skillet over medium heat until a pinch of the powder sticks lightly when scattered.",
                   "Sift half the powder into the pan in an even layer covering the base, and cook without touching it for about 1 minute, until it fuses into a single flexible disc.",
                   "Flip the disc, lay half the cheese on one side, and cook 1 minute more, until the underside is set but still pale.",
                   "Drizzle with condensed milk, scatter with coconut, dot with butter and fold in half. Slide onto a plate.",
                   "Repeat with the remaining powder and fillings, and eat each one hot, with your hands, while the next cooks.",
               ],
               note: "The sieve is non-negotiable. Unsifted starch cooks into gravel instead of a crepe, and the pan must be dry, never oiled.",
               shortcut: "Pre-hydrated tapioca flour sold as massa pronta skips the water and sieve steps entirely, if a Brazilian market is within reach."),
        Recipe(dishID: "brazil-brigadeiro", serves: 8, prepMinutes: 15, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 can (14 oz)", item: "sweetened condensed milk"),
                   RecipeIngredient(amount: "3 tbsp", item: "unsweetened cocoa powder"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter, plus more for your hands"),
                   RecipeIngredient(amount: "1 pinch", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "chocolate sprinkles"),
               ],
               steps: [
                   "Sift the cocoa into a nonstick saucepan, then stir in the condensed milk, butter and salt until no dry streaks remain.",
                   "Cook over medium-low heat, stirring constantly with a silicone spatula, scraping the bottom and corners the whole time.",
                   "Keep stirring for 10 to 15 minutes, until the mixture thickens and pulls away from the bottom of the pan in a single sluggish mass when you drag the spatula through.",
                   "Scrape onto a buttered plate, spread it out, and let it cool to room temperature, then chill for 30 minutes so it firms enough to roll.",
                   "Butter your palms, scoop teaspoons of the fudge, and roll them into balls the size of a large marble.",
                   "Roll each ball through the chocolate sprinkles until fully coated, pressing gently so they embed.",
                   "Set each brigadeiro in a small paper cup and serve at room temperature, or keep covered up to 3 days.",
               ],
               note: "The drag test decides everything: the spatula should leave a trail that shows the pan bottom for a full second before closing. Underdone brigadeiro never rolls.",
               shortcut: "Cook it slightly less and serve it as a spoon fudge straight from the pan, which is how many Brazilians prefer it anyway."),
    ]

    static let all: [Recipe] = recipes_mexico + recipes_peru + recipes_brazil
}
