import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesMedEurope {

    private static let recipes_italy: [Recipe] = [
        Recipe(dishID: "italy-cacioepepe", serves: 2, prepMinutes: 10, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "8 oz", item: "thick spaghetti or tonnarelli"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "finely grated pecorino romano"),
                   RecipeIngredient(amount: "2 tsp", item: "whole black peppercorns"),
                   RecipeIngredient(amount: "1 tsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tbsp", item: "kosher salt, for the pasta water"),
               ],
               steps: [
                   "Crush the peppercorns coarsely with the bottom of a heavy pan or a mortar. You want cracked shards, not powder, so the pepper perfumes the sauce instead of muddying it.",
                   "Boil the pasta in about 6 cups of well-salted water, less than usual, so the water gets extra starchy. Stir now and then to keep the strands loose.",
                   "While the pasta cooks, toast the cracked pepper in the olive oil in a wide skillet over medium heat until fragrant, about 1 minute, then pull it off the heat.",
                   "Put the grated pecorino in a bowl and beat in 3 to 4 tbsp of the hot pasta water, a spoonful at a time, until you have a smooth, thick paste.",
                   "Drain the pasta 1 minute early, saving 1 cup of cooking water, and toss it in the skillet with the pepper and a splash of that water for 30 seconds.",
                   "Off the heat, wait 30 seconds so the pan cools slightly, then add the cheese paste and toss hard, loosening with pasta water until every strand is glossy. Serve immediately.",
               ],
               note: "Heat is the enemy. If the cheese hits a pan that is too hot it seizes into clumps, so always combine off the heat and trust the pasta water.",
               shortcut: "Blitz the cheese, pepper, and hot pasta water in a mini food processor for a nearly break-proof paste. You lose a little of the pepper's rough bite."),
        Recipe(dishID: "italy-tortellini", serves: 4, prepMinutes: 15, cookMinutes: 75, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "fresh tortellini with meat filling, from the refrigerated case"),
                   RecipeIngredient(amount: "8 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "1 lb", item: "bone-in chicken thighs"),
                   RecipeIngredient(amount: "1", item: "carrot, halved"),
                   RecipeIngredient(amount: "1", item: "celery stalk"),
                   RecipeIngredient(amount: "1/2", item: "yellow onion, unpeeled"),
                   RecipeIngredient(amount: "1", item: "parmesan rind (or a 1-inch chunk of parmesan)"),
                   RecipeIngredient(amount: "1/2 cup", item: "grated parmigiano reggiano, for the table"),
                   RecipeIngredient(amount: "1 tsp", item: "salt, plus more to taste"),
               ],
               steps: [
                   "This is the honest weeknight version: hand-folded tortellini and capon broth take two days, so you buy good tortellini and make the store-bought stock taste homemade.",
                   "Combine the stock, chicken thighs, carrot, celery, onion, and parmesan rind in a pot. Bring just to a simmer, then lower the heat so it barely bubbles.",
                   "Simmer uncovered for 45 minutes to 1 hour, skimming any foam off the surface, until the broth tastes rich and rounded rather than like the carton it came from.",
                   "Strain the broth through a fine sieve into a clean pot and discard the solids, or save the chicken for another meal. Season with salt until it tastes complete on its own.",
                   "Bring the strained broth back to a gentle simmer and drop in the tortellini. Cook until they float and the pasta at the folded seam is tender, 3 to 5 minutes.",
                   "Ladle into warm, deep bowls, counting the tortellini out fairly, and pass the grated parmesan at the table so each person can snow their own bowl.",
               ],
               note: "The broth is the dish. Taste it before the pasta goes in; if it would not be worth drinking from a mug on its own, keep simmering.",
               shortcut: "Skip the enrichment and use boxed stock straight, simmered with just the parmesan rind for 20 minutes. Faster, but the broth stays one-dimensional."),
        Recipe(dishID: "italy-bistecca", serves: 4, prepMinutes: 10, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 lb", item: "porterhouse steak, cut at least 2 inches thick"),
                   RecipeIngredient(amount: "2 tbsp", item: "coarse sea salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil, the best you have"),
                   RecipeIngredient(amount: "2 sprigs", item: "fresh rosemary"),
                   RecipeIngredient(amount: "1 can (15 oz)", item: "cannellini beans, drained and rinsed"),
                   RecipeIngredient(amount: "1/2 tsp", item: "coarsely ground black pepper"),
               ],
               steps: [
                   "Take the steak out of the refrigerator a full hour before cooking and pat it bone dry. A cold or wet steak will steam instead of crust. Do not salt it yet.",
                   "Build a hot charcoal fire or heat a heavy cast-iron pan over high heat until it just begins to smoke. There is no medium setting in this recipe.",
                   "Lay the steak down and leave it completely alone for 5 minutes, until the underside is deeply browned with charred edges. Moving it early tears the crust off.",
                   "Flip once and cook 5 minutes more, then stand the steak upright on its bone for 3 to 4 minutes so heat travels toward the center. It should stay rare, 115 to 120°F at the bone.",
                   "Move the steak to a cutting board, shower both sides with the coarse salt, lay the rosemary on top, and rest it for 10 full minutes without cutting.",
                   "While it rests, warm the beans with 1 tbsp of the olive oil and a pinch of salt. Carve the two muscles off the bone, slice thickly, and serve drizzled with the remaining oil and the pepper.",
               ],
               note: "Rare is the recipe, not a preference. If your table insists on medium, make a different steak; past medium-rare the Fiorentina turns gray, dry, and pointless.",
               shortcut: "A thick ribeye works if the butcher has no 2-inch porterhouse. You lose the tenderloin side and the bone drama, but the char-and-salt method is identical."),
        Recipe(dishID: "italy-pizzamargherita", serves: 2, prepMinutes: 40, cookMinutes: 10, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 1/2 cups", item: "bread flour"),
                   RecipeIngredient(amount: "1 cup", item: "warm water"),
                   RecipeIngredient(amount: "1/2 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "fine salt"),
                   RecipeIngredient(amount: "1 can (14 oz)", item: "whole san marzano tomatoes"),
                   RecipeIngredient(amount: "8 oz", item: "fresh mozzarella"),
                   RecipeIngredient(amount: "12 leaves", item: "fresh basil"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil"),
               ],
               steps: [
                   "The day before, stir the flour, water, yeast, and salt into a shaggy, sticky dough. Knead 5 minutes, cover, and refrigerate overnight; the slow rise builds the flavor and blister.",
                   "Two hours before baking, divide the dough into two balls, set them on a floured tray, cover, and let them come to room temperature until puffy and relaxed.",
                   "Set a pizza steel or upside-down baking sheet on the top oven rack and heat at 550°F, or as high as your oven goes, for a full 45 minutes.",
                   "Crush the tomatoes by hand with a pinch of salt; do not cook or blend them. Tear the mozzarella into chunks and let it drain on paper towels while the oven heats.",
                   "Stretch one ball on a floured counter, pressing from the center outward with flat fingers and leaving a fat rim. Pull to about 10 inches; if it fights back, rest it 5 minutes.",
                   "Slide the round onto floured parchment, spread a thin layer of tomato to the rim, and scatter half the mozzarella. Less topping than looks right is exactly right.",
                   "Slide it onto the hot steel and switch to broil. Bake 4 to 6 minutes, until the rim blisters with dark spots. Finish with torn basil and a thread of olive oil, then repeat.",
               ],
               note: "A home oven cannot hit 900°F, so the steel plus broiler trick is the whole game. Skip the overnight rest and you get bread with toppings, not pizza.",
               shortcut: "A 1-lb ball of store-bought dough, rested at room temperature for 2 hours, saves a day. The crumb will be tighter and less blistered."),
        Recipe(dishID: "italy-arancine", serves: 4, prepMinutes: 60, cookMinutes: 90, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "arborio rice"),
                   RecipeIngredient(amount: "1 pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter"),
                   RecipeIngredient(amount: "1/2 cup", item: "grated parmesan"),
                   RecipeIngredient(amount: "1/2 lb", item: "ground beef"),
                   RecipeIngredient(amount: "1/2", item: "yellow onion, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1/2 cup", item: "frozen peas"),
                   RecipeIngredient(amount: "4 oz", item: "caciocavallo or low-moisture mozzarella, diced"),
                   RecipeIngredient(amount: "3/4 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "2 cups", item: "plain dry breadcrumbs"),
                   RecipeIngredient(amount: "6 cups", item: "neutral frying oil"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
               ],
               steps: [
                   "Cook the rice like a plain risotto: simmer it in 4 cups of salted water with the saffron, stirring, until the water is absorbed and the rice is just tender, about 18 minutes.",
                   "Stir the butter and parmesan into the hot rice, then spread it on a sheet pan and refrigerate until completely cold and stiff, at least 1 hour. Warm rice will not shape.",
                   "Make the ragu: brown the ground beef with the onion, stir in the tomato paste and 1/2 cup water, and simmer 15 minutes until thick and jammy. Fold in the peas and cool.",
                   "With wet hands, press a scant 1/2 cup of cold rice into a cup shape in your palm. Spoon in a tablespoon of ragu and a cube of cheese, then cap with more rice and seal into a tight ball.",
                   "Whisk the eggs with the flour and 1/2 cup water into a smooth batter about the thickness of pancake batter. Roll each ball through the batter, then coat thoroughly in breadcrumbs.",
                   "Heat the oil in a deep pot to 340°F. Fry the arancine two or three at a time, turning them, until deep amber all over, about 5 minutes per batch.",
                   "Drain on a rack, not paper, and rest 5 minutes so the center cheese settles from lava to molten. Eat standing, out of hand, like a Palermo bar counter intended.",
               ],
               note: "Cold, stiff rice is everything. If the balls crack while shaping, the rice is too warm or too dry; wet your hands more and press firmly like packing a snowball.",
               shortcut: "Use 3 cups of day-old risotto or leftover cooked short-grain rice mixed with saffron water. The balls hold slightly less well but skip the first hour."),
        Recipe(dishID: "italy-bagnacauda", serves: 4, prepMinutes: 20, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "12", item: "oil-packed anchovy fillets"),
                   RecipeIngredient(amount: "2 heads", item: "garlic, cloves peeled"),
                   RecipeIngredient(amount: "1 cup", item: "whole milk"),
                   RecipeIngredient(amount: "3/4 cup", item: "olive oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2", item: "bell peppers, cut into wide strips"),
                   RecipeIngredient(amount: "1 bulb", item: "fennel, cut into wedges"),
                   RecipeIngredient(amount: "1 lb", item: "small potatoes, boiled"),
                   RecipeIngredient(amount: "1 loaf", item: "crusty bread, torn"),
               ],
               steps: [
                   "Simmer the peeled garlic cloves in the milk over the lowest heat for 20 minutes, until they are completely soft and the raw punch has mellowed. Drain, discarding the milk.",
                   "Mash the softened garlic to a paste with a fork, right in the saucepan, then add the anchovies and mash again until no whole fillets remain.",
                   "Add the olive oil and butter and cook over very low heat, whisking now and then, for 10 to 15 minutes. The sauce should tremble, never fry; anchovies turn bitter if browned.",
                   "While the sauce mellows, arrange the peppers, fennel, potatoes, and bread on a board. Anything crisp, sweet, or starchy that can carry a heavy sauce belongs here.",
                   "Bring the pot to the table and set it over a candle warmer, fondue burner, or trivet, whisking once more so the oil and garlic come together into a murky, fragrant bath.",
                   "Everyone dips for themselves, holding bread underneath to catch the drips. When only oil is left, tradition says to scramble an egg into the pot, which is worth honoring.",
               ],
               note: "Low heat from start to finish. The sauce should never bubble hard; the moment the garlic or anchovy browns, the whole pot turns acrid and there is no rescue.",
               shortcut: "Skip the milk step and use jarred roasted garlic mashed straight into the oil. Faster by 20 minutes, but the sauce loses its sweet, rounded edge."),
        Recipe(dishID: "italy-culurgiones", serves: 4, prepMinutes: 60, cookMinutes: 40, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "semolina flour, plus more for dusting"),
                   RecipeIngredient(amount: "3/4 cup", item: "warm water"),
                   RecipeIngredient(amount: "1 lb", item: "russet potatoes"),
                   RecipeIngredient(amount: "1 cup", item: "grated pecorino romano"),
                   RecipeIngredient(amount: "1/4 cup", item: "chopped fresh mint"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, smashed"),
                   RecipeIngredient(amount: "1/4 cup", item: "olive oil"),
                   RecipeIngredient(amount: "1 can (14 oz)", item: "crushed tomatoes"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Knead the semolina, warm water, and 1/2 tsp salt into a firm, smooth dough, about 8 minutes. Wrap it and rest at room temperature while you make the filling.",
                   "Boil the potatoes whole in their skins until a knife slides through, about 25 minutes. Peel while warm and mash until completely smooth; lumps will tear the pasta.",
                   "Warm the olive oil with the smashed garlic until fragrant, then discard the garlic. Beat the oil, pecorino, and mint into the potatoes and season with salt. Cool completely.",
                   "Roll the dough thin, about 1/16 inch, and cut 3-inch circles. Set a walnut-sized ball of filling in the center of each.",
                   "Close each one: cup the circle in one hand and pinch the edges together in small alternating folds from one end to the other, so the seam ridges like an ear of wheat. If the pleat defeats you, seal them flat like a half-moon dumpling; they will still be delicious.",
                   "Simmer the crushed tomatoes with a pinch of salt and a spoonful of the pasta water for 10 minutes into a loose, simple sauce.",
                   "Boil the culurgiones in gently simmering salted water, a few at a time, until they float and the seam is tender, about 5 minutes. A hard boil will burst them.",
                   "Plate on a spoonful of tomato sauce, seam side up so the pleat shows, and finish with more grated pecorino.",
               ],
               note: "The filling must be cold and the dough rolled truly thin. Warm filling steams the seam open in the pot and you will fish out potato soup.",
               shortcut: "Round dumpling or potsticker wrappers stand in for the semolina dough. You lose the chew and the wheat-ear pleat, but the filling still sings."),
        Recipe(dishID: "italy-tiramisu", serves: 8, prepMinutes: 35, cookMinutes: 0, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "24", item: "savoiardi ladyfingers, the crisp kind"),
                   RecipeIngredient(amount: "16 oz", item: "mascarpone, at room temperature"),
                   RecipeIngredient(amount: "4", item: "eggs, separated (use pasteurized if that worries you)"),
                   RecipeIngredient(amount: "1/2 cup", item: "sugar"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "strong brewed espresso or moka coffee, cooled"),
                   RecipeIngredient(amount: "2 tbsp", item: "unsweetened cocoa powder"),
                   RecipeIngredient(amount: "1 pinch", item: "salt"),
               ],
               steps: [
                   "Whisk the egg yolks with the sugar until pale, thick, and ribbony, a good 3 minutes by hand. The sugar should be fully dissolved, not grainy.",
                   "Beat the mascarpone into the yolks a third at a time until smooth. Do not overbeat; mascarpone splits into grainy butter if you bully it.",
                   "In a clean bowl, whip the egg whites with the pinch of salt to soft peaks, then fold them into the mascarpone mixture in two additions, keeping as much air as you can.",
                   "Pour the cooled coffee into a shallow dish. Dip each ladyfinger for one second per side, a quick baptism, not a soak, and lay them in a single layer in an 8-by-8-inch dish.",
                   "Spread half the mascarpone cream over the biscuits, then repeat with a second layer of dipped ladyfingers and the remaining cream, smoothing the top.",
                   "Refrigerate at least 6 hours, ideally overnight, so the layers fuse and the biscuits turn to sponge. Dust generously with cocoa only just before serving.",
               ],
               note: "The one-second dip is sacred. Soaked ladyfingers collapse into coffee sludge, and the whole structure depends on them starting crisp and finishing like cake.",
               shortcut: "Fold 3/4 cup of whipped heavy cream into the mascarpone instead of raw whipped whites. Safer and quicker, slightly denser and less airy."),
    ]

    private static let recipes_france: [Recipe] = [
        Recipe(dishID: "france-bouillabaisse", serves: 4, prepMinutes: 30, cookMinutes: 50, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "firm white fish fillets (snapper, cod, or halibut), cut in large chunks"),
                   RecipeIngredient(amount: "1/2 lb", item: "shell-on shrimp"),
                   RecipeIngredient(amount: "4 cups", item: "seafood stock or 2 cups clam juice plus 2 cups water"),
                   RecipeIngredient(amount: "1 bulb", item: "fennel, sliced"),
                   RecipeIngredient(amount: "1", item: "leek, white part, sliced"),
                   RecipeIngredient(amount: "6 cloves", item: "garlic, 4 sliced and 2 whole"),
                   RecipeIngredient(amount: "1 can (14 oz)", item: "crushed tomatoes"),
                   RecipeIngredient(amount: "1 big pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "2 strips", item: "orange peel"),
                   RecipeIngredient(amount: "1/4 cup", item: "olive oil"),
                   RecipeIngredient(amount: "1/2 cup", item: "mayonnaise"),
                   RecipeIngredient(amount: "1/4 tsp", item: "cayenne"),
                   RecipeIngredient(amount: "1", item: "baguette, sliced and toasted"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Peel the shrimp and simmer the shells in the stock for 15 minutes, then strain. This is the honest home stand-in for a Marseille rockfish broth.",
                   "Meanwhile, soften the fennel, leek, and sliced garlic in the olive oil over medium heat until sweet and translucent, about 8 minutes, without browning.",
                   "Add the tomatoes, saffron, orange peel, salt, and the strained stock. Boil hard, not gently, for 15 minutes; the rolling boil is what forces the oil and broth into one silky body.",
                   "Make the quick rouille: grate the 2 whole garlic cloves into the mayonnaise with the cayenne and a spoonful of the hot broth, and stir until it turns a pale sunset orange.",
                   "Lower the broth to a simmer, slide in the fish chunks, and cook 5 minutes. Add the shrimp for the final 3 minutes, until both are just opaque.",
                   "Fish out the orange peel. Serve the Marseille way in two acts: broth first, ladled over rouille-slathered toasts, then the fish and shrimp on a warm platter with more broth spooned over.",
               ],
               note: "The hard boil in step three is counterintuitive and non-negotiable; a timid simmer leaves the olive oil floating instead of emulsified, and the broth eats thin.",
               shortcut: "Skip the shrimp-shell step and use good boxed seafood stock straight. Costs some depth; a pinch more saffron papers over most of it."),
        Recipe(dishID: "france-choucroute", serves: 6, prepMinutes: 20, cookMinutes: 100, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "refrigerated sauerkraut, drained"),
                   RecipeIngredient(amount: "4 slices", item: "thick-cut bacon, chopped"),
                   RecipeIngredient(amount: "1", item: "yellow onion, sliced"),
                   RecipeIngredient(amount: "1 cup", item: "dry riesling"),
                   RecipeIngredient(amount: "1 cup", item: "chicken stock"),
                   RecipeIngredient(amount: "8", item: "juniper berries (or 2 bay leaves plus 1 tsp caraway seeds)"),
                   RecipeIngredient(amount: "4", item: "smoked pork chops"),
                   RecipeIngredient(amount: "1 lb", item: "kielbasa, cut in chunks"),
                   RecipeIngredient(amount: "4", item: "bratwurst"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "small yellow potatoes"),
                   RecipeIngredient(amount: "1 jar", item: "dijon mustard, for the table"),
               ],
               steps: [
                   "Rinse the sauerkraut briefly in a colander and squeeze it dry by the handful. You want it pleasantly sour, not aggressive; taste a strand and rinse again if it makes you wince.",
                   "In a wide Dutch oven, cook the bacon until its fat runs, then soften the onion in that fat until golden at the edges, about 8 minutes.",
                   "Stir in the sauerkraut and juniper, pour in the riesling and stock, and bring to a simmer. The wine is doing traditional work here; it cooks down completely.",
                   "Nestle the smoked chops, kielbasa, and bratwurst into the kraut, cover, and cook in a 325°F oven for 1 1/4 hours, until the cabbage is silky and stained gold with pork fat.",
                   "In the last half hour, boil the potatoes in salted water until a knife slides in easily, then drain and keep warm.",
                   "Mound the kraut on one enormous platter, arrange the meats on top and the potatoes around the edge, and put the mustard jar on the table. Small portions are against the spirit of the thing.",
               ],
               note: "Buy refrigerated sauerkraut in a bag or jar, never canned; canned kraut has been cooked dead and no amount of riesling and juniper will wake it up.",
               shortcut: "One meat works: double the kielbasa and skip the chops and bratwurst. The platter loses its variety show but the kraut underneath tastes the same."),
        Recipe(dishID: "france-bourguignon", serves: 6, prepMinutes: 30, cookMinutes: 210, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "beef chuck, cut in 2-inch cubes"),
                   RecipeIngredient(amount: "1 bottle (750 ml)", item: "dry red wine, like pinot noir"),
                   RecipeIngredient(amount: "6 oz", item: "thick-cut smoked bacon, cut in batons"),
                   RecipeIngredient(amount: "2 cups", item: "frozen pearl onions"),
                   RecipeIngredient(amount: "1 lb", item: "button mushrooms, halved"),
                   RecipeIngredient(amount: "3", item: "carrots, cut in thick coins"),
                   RecipeIngredient(amount: "2 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "3 tbsp", item: "all-purpose flour"),
                   RecipeIngredient(amount: "2 cups", item: "beef stock"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, smashed"),
                   RecipeIngredient(amount: "4 sprigs", item: "fresh thyme"),
                   RecipeIngredient(amount: "2", item: "bay leaves"),
                   RecipeIngredient(amount: "2 tbsp", item: "butter"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
               ],
               steps: [
                   "Pat the beef very dry and season with the salt. Render the bacon in a Dutch oven over medium heat until crisp, then lift it out, leaving the fat.",
                   "Brown the beef in the bacon fat in three batches, hard and unhurried, 3 to 4 minutes per side. A crowded pot steams gray; the dark crust here is most of the final flavor.",
                   "Return all the beef and bacon to the pot, stir in the flour and tomato paste, and cook 2 minutes until the flour smells toasty and coats everything.",
                   "Pour in the wine and stock, scraping the browned crust off the bottom, and add the carrots, garlic, thyme, and bay. The liquid should barely cover the meat.",
                   "Cover and slide into a 300°F oven for 2 1/2 to 3 hours. Leave it alone; it is done when a cube of beef breaks apart under a fork with no resistance.",
                   "In the last 20 minutes, brown the mushrooms and pearl onions in the butter in a skillet until golden, then stir them into the pot to finish.",
                   "Skim the fat off the surface, fish out the herb stems and bay leaves, and taste for salt. If the sauce is thin, boil it hard on the stovetop for 5 minutes until it coats a spoon.",
               ],
               note: "Everything depends on the sear and the patience after it. Brown in small batches, then keep the oven low; boiling the braise makes stringy beef.",
               shortcut: "Skip browning the pearl onions and mushrooms separately and add them raw at the start. Saves a skillet, but they braise pale and a little waterlogged."),
        Recipe(dishID: "france-galette", serves: 4, prepMinutes: 10, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/4 cups", item: "buckwheat flour"),
                   RecipeIngredient(amount: "1 3/4 cups", item: "cold water"),
                   RecipeIngredient(amount: "3/4 tsp", item: "fine salt"),
                   RecipeIngredient(amount: "4", item: "eggs"),
                   RecipeIngredient(amount: "4 slices", item: "good deli ham"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "grated gruyere"),
                   RecipeIngredient(amount: "4 tbsp", item: "salted butter"),
               ],
               steps: [
                   "Whisk the buckwheat flour, water, and salt into a thin, pourable batter, like heavy cream. Rest it at least 2 hours, or overnight in the refrigerator; unrested batter fries brittle.",
                   "Heat a 10-inch nonstick or crepe pan over medium-high until a drop of water skitters. Swirl in a teaspoon of butter and wipe most of it out with a paper towel.",
                   "Pour in a scant 1/2 cup of batter and immediately tilt and swirl the pan to coat it thinly to the edges. Cook untouched until the edges lift and lace, about 2 minutes.",
                   "Lower the heat slightly. Crack an egg onto the center of the galette and spread the white gently outward with the back of a spoon, leaving the yolk whole.",
                   "Ring the egg with a slice of ham torn in pieces and a handful of gruyere. Cook until the white is just set but the yolk still trembles, 2 to 3 minutes.",
                   "Fold the four sides in to frame the yolk in an open square, slide onto a plate, and top with a knob of salted butter. Repeat for the rest, serving each one immediately.",
               ],
               note: "The batter is only flour, water, and salt, so the pan must be properly hot before the first pour; a timid pan gives you a pale, gummy galette.",
               shortcut: "Swap half the buckwheat for all-purpose flour and skip the rest time. The galette handles more easily but loses its dark, earthy edge."),
        Recipe(dishID: "france-piperade", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "green bell or cubanelle peppers, sliced in strips"),
                   RecipeIngredient(amount: "4", item: "ripe tomatoes, roughly chopped"),
                   RecipeIngredient(amount: "1 large", item: "yellow onion, sliced"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, sliced"),
                   RecipeIngredient(amount: "6", item: "eggs, beaten"),
                   RecipeIngredient(amount: "1 tsp", item: "espelette pepper (or sweet paprika plus a pinch of cayenne)"),
                   RecipeIngredient(amount: "3 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "crusty baguette, for the table"),
               ],
               steps: [
                   "Warm the olive oil in a wide skillet over medium heat and cook the onion and peppers with a pinch of salt until completely limp and sweet, a full 15 minutes. No browning, no shortcuts.",
                   "Add the garlic and cook 2 minutes more, until fragrant, then stir in the tomatoes, espelette, and remaining salt.",
                   "Simmer uncovered, stirring now and then, until the tomatoes collapse and the mixture thickens from watery to spoonably soft, 12 to 15 minutes.",
                   "Taste the stew before the eggs go in. It should already be delicious on its own, sweet and gently warm; fix the salt now, because you cannot stir hard later.",
                   "Lower the heat, pour the beaten eggs over the vegetables, and fold slowly with a spatula just until the eggs form soft, creamy curds threaded through the peppers, about 2 minutes.",
                   "Pull the pan off the heat while the eggs still look slightly underdone; they finish in the pan. Serve straight from the skillet with torn baguette.",
               ],
               note: "The eggs are a binder, not an omelet. Fold them in barely and stop early; one minute too long turns silk into cafeteria scramble.",
               shortcut: "A drained 14-oz can of diced tomatoes replaces fresh out of season. The stew is a shade less bright, so add a pinch of sugar."),
        Recipe(dishID: "france-quenelles", serves: 4, prepMinutes: 45, cookMinutes: 50, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "skinless pike or cod fillets, very cold"),
                   RecipeIngredient(amount: "3/4 cup", item: "whole milk"),
                   RecipeIngredient(amount: "5 tbsp", item: "butter"),
                   RecipeIngredient(amount: "3/4 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "3", item: "eggs"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "heavy cream"),
                   RecipeIngredient(amount: "1/2 lb", item: "shell-on shrimp"),
                   RecipeIngredient(amount: "1 tbsp", item: "tomato paste"),
                   RecipeIngredient(amount: "1/4 tsp", item: "ground nutmeg"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/4 tsp", item: "white pepper"),
               ],
               steps: [
                   "Make the panade: boil the milk with 3 tbsp of the butter, dump in the flour, and stir hard over the heat until it forms a ball that films the pan. Cool completely.",
                   "Peel the shrimp, saving every shell. Blitz the cold fish in a food processor to a fine paste, then add the cooled panade, eggs, nutmeg, salt, and white pepper and blend until smooth.",
                   "With the machine running, stream in 1/2 cup of the cream. Chill the mixture at least 30 minutes; a cold paste holds its shape, a warm one dissolves in the poaching water.",
                   "Make the sauce, the Nantua stand-in: sizzle the shrimp shells in the remaining butter until pink and toasty, add the tomato paste and remaining cream, simmer 10 minutes, and strain, pressing hard on the shells.",
                   "Shape the paste into fat ovals using two large spoons dipped in hot water, passing each scoop between the spoons until smooth.",
                   "Poach the quenelles in barely simmering salted water, never boiling, until they roll over and feel set, 8 to 10 minutes. Drain on a towel.",
                   "Lay the quenelles in a buttered baking dish, pour the sauce over, and add the peeled shrimp. Bake at 400°F for 15 minutes, until puffed and blistering at the edges.",
                   "Serve straight from the oven, before they deflate, with rice or bread for the sauce. The collapse starts within minutes; in Lyon they run these to the table.",
               ],
               note: "Cold ingredients and a lazy poach are the two hinges. If the water boils the quenelles shred, and if the paste is warm they never hold at all.",
               shortcut: "Skip the shell sauce and stir the tomato paste into cream with a splash of bottled clam juice. Five minutes instead of twenty; shallower, still pink and plush."),
        Recipe(dishID: "france-tartiflette", serves: 4, prepMinutes: 20, cookMinutes: 50, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "yukon gold potatoes"),
                   RecipeIngredient(amount: "1 lb", item: "reblochon-style washed-rind cheese (or ripe camembert)"),
                   RecipeIngredient(amount: "6 oz", item: "thick-cut bacon, cut in batons"),
                   RecipeIngredient(amount: "1 large", item: "yellow onion, sliced"),
                   RecipeIngredient(amount: "1/3 cup", item: "dry white wine"),
                   RecipeIngredient(amount: "1/2 cup", item: "crème fraîche or heavy cream"),
                   RecipeIngredient(amount: "1 clove", item: "garlic, halved"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 tsp", item: "black pepper"),
               ],
               steps: [
                   "Boil the potatoes whole in well-salted water until just tender, about 20 minutes. Drain, cool enough to handle, and slice into thick coins; leave the skins on.",
                   "Cook the bacon in a skillet until its fat runs and the edges crisp, then add the onion and cook until soft and golden, about 10 minutes.",
                   "Splash in the wine and let it bubble away almost completely, scraping the pan. This is the traditional deglaze and it cooks off entirely.",
                   "Rub a baking dish all over with the cut garlic clove, then layer in the potatoes, bacon-onion mixture, salt, pepper, and dollops of crème fraîche, folding gently.",
                   "Halve the cheese horizontally through its equator and lay both halves on top, rind side up, like two shields covering the dish.",
                   "Bake at 400°F for 25 to 30 minutes, until the rind blisters brown and molten cheese runs into every gap. Rest 5 minutes, then scoop at the table with green salad alongside.",
               ],
               note: "Rind side up is the trick; the rind roasts into a savory lid while the underside melts downward. True raw-milk reblochon is unavailable in the US, so buy the closest washed-rind wheel.",
               shortcut: "Use leftover boiled or roasted potatoes and the dish comes together in 10 minutes of assembly. Slightly drier, easily fixed with an extra spoon of cream."),
        Recipe(dishID: "france-canele", serves: 6, prepMinutes: 25, cookMinutes: 65, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "whole milk"),
                   RecipeIngredient(amount: "3 tbsp", item: "butter, plus more for the molds"),
                   RecipeIngredient(amount: "1", item: "vanilla bean, split (or 1 tbsp vanilla extract)"),
                   RecipeIngredient(amount: "2", item: "egg yolks"),
                   RecipeIngredient(amount: "1", item: "whole egg"),
                   RecipeIngredient(amount: "1 cup", item: "sugar"),
                   RecipeIngredient(amount: "3/4 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
               ],
               steps: [
                   "Heat the milk with the butter and vanilla bean until steaming, then let it cool until just warm. Hot milk would scramble the eggs and toughen the batter.",
                   "Whisk the yolks, whole egg, and sugar together, then whisk in the flour and salt, and finally the warm milk in a slow stream. The batter should be thin, like crepe batter.",
                   "Strain the batter, cover, and refrigerate at least 24 hours and up to 48. This rest is not optional; it relaxes the flour so the centers set to custard instead of cake.",
                   "Heat the oven to 475°F. Butter canele molds or a dark metal muffin tin generously and put the empty tin in the oven for 5 minutes until the butter sizzles.",
                   "Stir the cold batter gently, without whipping in air, and pour it into the hot molds, stopping 1/2 inch from the rim.",
                   "Bake 15 minutes at 475°F, then drop the oven to 375°F and bake 40 to 50 minutes more. Hold your nerve: they are done when nearly black-brown, not merely golden.",
                   "Turn them out of the molds onto a rack within a minute of leaving the oven and cool at least 30 minutes. The shell crisps as it cools; eat them the same day.",
               ],
               note: "Every failed canele is an underbaked canele. The mahogany-going-on-black crust looks burnt to first-timers and is exactly the bitter caramel shell the custard needs.",
               shortcut: "A dark nonstick muffin tin replaces copper molds and beeswax. You lose the deep flutes and some crust snap, but the custard interior is untouched."),
    ]

    private static let recipes_spain: [Recipe] = [
        Recipe(dishID: "spain-paella", serves: 4, prepMinutes: 20, cookMinutes: 60, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "bomba or calasparra rice (or another short-grain rice, not risotto rice)"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "bone-in chicken thighs, cut in half"),
                   RecipeIngredient(amount: "3/4 lb", item: "rabbit pieces (or more chicken thighs)"),
                   RecipeIngredient(amount: "1/2 lb", item: "flat romano or green beans, cut in 2-inch lengths"),
                   RecipeIngredient(amount: "1 cup", item: "frozen butter beans or lima beans"),
                   RecipeIngredient(amount: "1", item: "ripe tomato, grated on a box grater"),
                   RecipeIngredient(amount: "1 big pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "1 tsp", item: "sweet smoked paprika"),
                   RecipeIngredient(amount: "1/4 cup", item: "olive oil"),
                   RecipeIngredient(amount: "5 cups", item: "chicken stock, hot"),
                   RecipeIngredient(amount: "1 sprig", item: "fresh rosemary"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
               ],
               steps: [
                   "Heat the oil in your widest shallow pan, 13 inches or more, over medium-high. Salt the chicken and rabbit and brown them slowly and thoroughly, a full 15 minutes; this browning is the flavor base.",
                   "Push the meat to the edges, add the green beans and butter beans to the center, and cook 3 minutes. Then add the grated tomato and paprika and fry until it darkens to brick and smells sweet.",
                   "Pour in the hot stock, crumble in the saffron, and season the liquid until it tastes slightly too salty on its own; the rice will absorb the excess.",
                   "Simmer the broth with the meat for 10 minutes so it takes on the pan's flavor, then scatter in the rice as evenly as you can. From this moment on, never stir again.",
                   "Cook hard for 10 minutes, then lower the heat and cook 8 more, rotating the pan for even heat. Lay the rosemary sprig on top in the final minutes.",
                   "Listen at the end: a faint crackle means the socarrat, the prized toasted crust, is forming underneath. Raise the heat 60 to 90 seconds, sniffing for toast, not burn.",
                   "Pull the pan off, cover loosely with a kitchen towel, and rest 5 minutes. Set the pan in the middle of the table and eat straight from it, working from the edge inward.",
               ],
               note: "The no-stirring rule is absolute. Stirring releases starch and makes risotto; paella rice must sit still, drink the broth, and toast against the pan floor.",
               shortcut: "All chicken, no rabbit, changes little for a US kitchen. Skipping bomba rice for long-grain, though, costs you the whole texture; use any short-grain first."),
        Recipe(dishID: "spain-gazpacho", serves: 4, prepMinutes: 20, cookMinutes: 0, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "ripe tomatoes, cored and chopped"),
                   RecipeIngredient(amount: "1/2", item: "cucumber, peeled"),
                   RecipeIngredient(amount: "1", item: "green bell pepper, seeded"),
                   RecipeIngredient(amount: "2 slices", item: "day-old white bread, crusts removed"),
                   RecipeIngredient(amount: "1 clove", item: "garlic"),
                   RecipeIngredient(amount: "3 tbsp", item: "sherry vinegar"),
                   RecipeIngredient(amount: "1/2 cup", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "cold water"),
               ],
               steps: [
                   "Tear the bread into a bowl with the chopped tomatoes and let it soak in their juice for 10 minutes while you prep everything else. The bread is the ancient thickener here.",
                   "Blend the soaked bread and tomatoes with the cucumber, green pepper, garlic, vinegar, salt, and cold water on high until completely smooth, a full 2 minutes.",
                   "With the blender running, stream in the olive oil slowly. The soup will lighten from red to a pale salmon-orange and turn noticeably creamy; that is the emulsion you want.",
                   "Push the soup through a fine sieve, pressing with a ladle, and discard the skins and seeds. This step separates gazpacho from salsa; do not skip it.",
                   "Chill at least 2 hours, until properly cold. Taste after chilling and correct the salt and vinegar; cold blunts both, so it will need more than you think.",
                   "Serve in glasses to drink or bowls with a thread of olive oil, and pass small dishes of diced cucumber, pepper, and onion for topping.",
               ],
               note: "Everything depends on the tomatoes. Out of season, ripen them on the counter for days or walk away; refrigerated or mealy tomatoes make cold pink disappointment.",
               shortcut: "Skip the sieve if your blender is powerful and you like rustic texture. You save 5 minutes and lose the silky restaurant finish."),
        Recipe(dishID: "spain-pulpo", serves: 4, prepMinutes: 10, cookMinutes: 70, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2-3 lb", item: "frozen octopus, thawed in the refrigerator"),
                   RecipeIngredient(amount: "1", item: "yellow onion, halved"),
                   RecipeIngredient(amount: "2", item: "bay leaves"),
                   RecipeIngredient(amount: "1 1/2 lb", item: "yellow potatoes"),
                   RecipeIngredient(amount: "2 tsp", item: "sweet smoked paprika"),
                   RecipeIngredient(amount: "2 tsp", item: "coarse sea salt"),
                   RecipeIngredient(amount: "1/3 cup", item: "olive oil, the best you have"),
               ],
               steps: [
                   "Bring a large pot of unsalted water to a rolling boil with the onion and bay leaves. Freezing has already tenderized the octopus, which is why frozen beats fresh here.",
                   "Perform the traditional dip: holding the octopus by the head with tongs, lower it into the boiling water for 3 seconds and lift it out. Repeat three times; this sets the skin so it does not slough off.",
                   "Lower the octopus in for good and simmer gently, uncovered, for 40 to 50 minutes. It is done when a knife slides easily into the thickest part of a tentacle.",
                   "Turn off the heat and let the octopus rest in its cooking water for 15 minutes; this rest finishes the tenderizing that no amount of extra boiling can.",
                   "Meanwhile, boil the potatoes in some of the octopus water until tender, then slice into thick coins and lay them on a wooden board or warm platter.",
                   "Snip the tentacles into 1/2-inch coins with kitchen scissors, right over the potatoes. Shower everything with the coarse salt and paprika, flood with olive oil, and serve with toothpicks.",
               ],
               note: "Buy frozen without apology; Galician pulpeiras freeze theirs too. The knife-tender check and the 15-minute rest in the pot matter more than any clock time.",
               shortcut: "Spanish groceries and some supermarkets sell cooked octopus tentacles vacuum-packed. Warm them 2 minutes in simmering water and jump to the final step."),
        Recipe(dishID: "spain-tortilla", serves: 4, prepMinutes: 15, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "yukon gold potatoes, peeled and sliced 1/8 inch thick"),
                   RecipeIngredient(amount: "6", item: "eggs"),
                   RecipeIngredient(amount: "1", item: "yellow onion, thinly sliced"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "olive oil"),
                   RecipeIngredient(amount: "1 1/4 tsp", item: "salt"),
               ],
               steps: [
                   "Warm the olive oil in a 9- or 10-inch nonstick skillet over medium-low and slide in the potatoes and onion. They should poach lazily in the oil, never fry or brown.",
                   "Cook 20 to 25 minutes, turning gently now and then, until a potato slice breaks in half under a spoon with no resistance. Drain everything in a colander set over a bowl, saving the oil.",
                   "Beat the eggs with the salt in a large bowl, fold in the warm drained potatoes, and let the mixture sit for 10 minutes; this soak is where potato and egg become one thing.",
                   "Heat 2 tbsp of the saved oil in the same skillet over medium-high until shimmering, pour in the mixture, and immediately drop the heat to medium-low, shaking the pan so nothing grabs.",
                   "Cook 4 to 5 minutes, tucking the edges under with a spatula to build the tortilla's rounded shoulder, until the bottom is set but the top is still loose.",
                   "The flip: put a flat plate over the skillet, grip both with conviction, and invert in one motion over the sink. Slide the tortilla back in, raw side down, and cook 2 to 3 minutes more.",
                   "Turn it onto a plate while the center is still barely set; it firms as it rests. Serve warm or at room temperature, in wedges, never refrigerated the first day.",
               ],
               note: "A jiggly center is correct in most of Spain; carryover heat finishes it on the plate. The only real failure is overcooked, bouncy egg.",
               shortcut: "Poach the potatoes in the microwave with 3 tbsp oil, covered, 8 minutes. Saves a cup of oil and half the time; you lose the deep olive oil savor."),
        Recipe(dishID: "spain-fabada", serves: 6, prepMinutes: 15, cookMinutes: 180, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "dried large white beans (fabes, or large lima or butter beans)"),
                   RecipeIngredient(amount: "1/2 lb", item: "spanish chorizo (the cured kind, not mexican)"),
                   RecipeIngredient(amount: "1/2 lb", item: "morcilla (or double the chorizo)"),
                   RecipeIngredient(amount: "3/4 lb", item: "slab bacon or salt pork, in one piece"),
                   RecipeIngredient(amount: "1", item: "yellow onion, halved"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, peeled"),
                   RecipeIngredient(amount: "1 1/2 tsp", item: "sweet smoked paprika"),
                   RecipeIngredient(amount: "1 pinch", item: "saffron threads"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
               ],
               steps: [
                   "The night before, cover the beans generously with cold water and leave them on the counter. They should double in size; skip this and no amount of simmering saves them.",
                   "Drain the beans into a wide pot with the onion, garlic, olive oil, and the bacon in one piece. Cover with fresh cold water by 1 inch and bring just to a boil.",
                   "Skim the foam, then 'scare' the beans the Asturian way: pour in a splash of cold water to knock the boil back. Do this twice more during cooking; it keeps the skins from splitting.",
                   "Lower the heat until the surface barely shivers, add the paprika and saffron, and cook uncovered 2 hours, shaking the pot occasionally instead of stirring so the beans stay whole.",
                   "Add the chorizo and morcilla, tucking them under the surface, and cook 45 minutes to 1 hour more, until the beans are butter-soft and the broth has thickened on its own.",
                   "Season with the salt only near the end, then rest off the heat for 20 minutes. Slice the meats, return them to the pot, and serve in deep bowls with bread and no plans afterward.",
               ],
               note: "Never stir, only swirl. The beans must arrive at the bowl whole and creamy, and one enthusiastic spoon can turn three hours of patience into bean puree.",
               shortcut: "Two 15-oz cans of butter beans, added in the final 45 minutes with all the meats, cut the time to one hour. The broth stays thinner."),
        Recipe(dishID: "spain-calcots", serves: 4, prepMinutes: 25, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3 bunches", item: "fat scallions or spring onions, the thickest you can find"),
                   RecipeIngredient(amount: "1/2 cup", item: "roasted almonds"),
                   RecipeIngredient(amount: "1/4 cup", item: "roasted hazelnuts"),
                   RecipeIngredient(amount: "1 jar (12 oz)", item: "roasted red peppers, drained"),
                   RecipeIngredient(amount: "1", item: "ripe tomato"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic"),
                   RecipeIngredient(amount: "1 slice", item: "stale bread, toasted"),
                   RecipeIngredient(amount: "2 tbsp", item: "sherry vinegar"),
                   RecipeIngredient(amount: "1/2 cup", item: "olive oil"),
                   RecipeIngredient(amount: "1 tsp", item: "sweet smoked paprika"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
               ],
               steps: [
                   "Make the romesco first: blitz the almonds, hazelnuts, and toasted bread in a food processor to coarse crumbs, the texture of wet sand.",
                   "Add the roasted peppers, tomato, garlic, vinegar, paprika, and salt and blend, streaming in the olive oil, until you have a thick, rusty, spoonable sauce. It should cling, not pour.",
                   "Trim the roots off the onions but leave them otherwise whole, greens and all. Get a grill screaming hot, or set your broiler to high with a rack close to the element.",
                   "Char the onions in a single layer until the outer skin is genuinely blackened on all sides, 8 to 12 minutes, turning once. Burnt is the technique, not a mistake.",
                   "Stack the charred onions on a sheet of newspaper or foil and wrap them tightly. Let them steam in their own heat for 15 minutes; this finishes cooking the sweet interior.",
                   "Show everyone the move: pinch the charred base, pull, and the blackened skin slides off leaving the silky white core. Dip deep into the romesco and lower it in from above.",
                   "Serve outdoors if you can, with plenty of napkins and the romesco bowl in the middle. Blackened fingers are part of the meal.",
               ],
               note: "The wrap-and-steam rest does half the cooking; unwrap early and the centers stay squeaky. And char harder than feels reasonable, since the burnt layer is discarded.",
               shortcut: "Good jarred romesco exists at many supermarkets and saves 20 minutes. Most are smoother and sweeter than homemade, so sharpen with a splash of vinegar."),
        Recipe(dishID: "spain-gilda", serves: 4, prepMinutes: 10, cookMinutes: 0, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "12", item: "oil-packed anchovy fillets, the best jar in the store"),
                   RecipeIngredient(amount: "24", item: "pickled guindilla peppers (or mild pepperoncini)"),
                   RecipeIngredient(amount: "12", item: "pitted manzanilla olives"),
                   RecipeIngredient(amount: "2 tbsp", item: "olive oil"),
                   RecipeIngredient(amount: "1 splash", item: "brine from the pepper jar"),
               ],
               steps: [
                   "Drain the anchovies and lay them on a paper towel. Handle them like the precious things they are; a torn anchovy still tastes fine but loses the drape.",
                   "Trim the stems from the guindillas. If using pepperoncini, slice them in half lengthwise so their vinegar bite spreads through the bite instead of arriving all at once.",
                   "Build each skewer on a toothpick in the classic order: one pepper, an anchovy folded in an S-curve around an olive, then a second pepper to close.",
                   "Line the gildas up on a plate, drizzle with the olive oil, and add a small splash of pepper brine over the top. They should glisten.",
                   "Let them sit 10 minutes so the brine, oil, and anchovy salt start trading places, then serve standing up, before dinner, with something cold to drink. One bite per skewer, no nibbling.",
               ],
               note: "This is shopping, not cooking, so the anchovy decides everything. Cheap tinned fillets taste of salt and regret; spend up on Cantabrian-style anchovies if you can.",
               shortcut: "Green pimento-stuffed olives from any supermarket work for manzanillas. Skip anything labeled black or ripe olive, which turns the bite soft and flat."),
        Recipe(dishID: "spain-churros", serves: 4, prepMinutes: 15, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1 cup", item: "water"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar, plus more for dusting"),
                   RecipeIngredient(amount: "4 cups", item: "neutral frying oil"),
                   RecipeIngredient(amount: "6 oz", item: "dark chocolate, chopped"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "whole milk"),
                   RecipeIngredient(amount: "2 tsp", item: "cornstarch"),
               ],
               steps: [
                   "Boil the water with the salt and 1 tsp sugar, pull it off the heat, and dump in the flour all at once. Stir hard with a wooden spoon until it forms a smooth, stiff ball.",
                   "Let the dough cool 10 minutes, then load it into a sturdy piping bag fitted with a large closed star tip. The star ridges are structural; a plain tube can burst in the oil.",
                   "Make the chocolate: whisk the cornstarch into the cold milk, heat until steaming, then add the chocolate and whisk over low heat until thick enough to coat a spoon heavily.",
                   "Heat the oil in a deep, wide pot to 350°F. Test with a scrap of dough; it should sizzle at once and brown in about 2 minutes.",
                   "Pipe 6-inch lengths directly into the oil, cutting each free with scissors, three or four at a time. Stand back as you pipe; the dough can spit.",
                   "Fry, turning once, until deep golden and rigid, 4 to 5 minutes; pale churros collapse as they cool. Drain on a rack and dust lightly with sugar.",
                   "Pour the thick chocolate into small cups and serve immediately, churros standing in a glass, the way a churreria does at dawn. Dip deep; the chocolate is a sauce, not a drink.",
               ],
               note: "The dough must be stiff and the oil truly at temperature. Wet dough or cool oil gives greasy, hollow-less churros, and dough piped from too high splashes.",
               shortcut: "A cookie press or a zip-top bag with a star tip replaces the piping bag. Squeeze carefully; thin bags can split under this stiff dough."),
    ]

    static let all: [Recipe] = recipes_italy + recipes_france + recipes_spain
}
