import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentMiddleEast {

    private static let cuisine_turkey = Cuisine(
        id: "turkey",
        regionID: "middle-east",
        country: "Turkey",
        adjective: "Turkish",
        tagline: "Palace patience and village fire, sharing one table.",
        summary: "Turkish cooking sits where nomad herders, Ottoman palace cooks and Aegean farmers all left instructions. It is built on lamb, yogurt, wheat in every form and vegetables cooked in olive oil until they collapse. The palace side loves layers and precision; the village side trusts fire, bread and a long afternoon over a low flame.",
        staples: ["wheat", "lamb", "yogurt", "olive oil", "peppers", "eggplant"],
        techniques: ["slow-cooking in olive oil", "baking on a stone oven floor", "grilling over charcoal"],
        flavourBase: "Pepper paste, lemon and yogurt over lamb fat and olive oil.",
        stampInk: "crimson",
        stampShape: "arch",
        stampMotif: "crescent")

    private static let cuisine_lebanon = Cuisine(
        id: "lebanon",
        regionID: "middle-east",
        country: "Lebanon",
        adjective: "Lebanese",
        tagline: "Lemon, oil and a table that never stops arriving.",
        summary: "Lebanese cooking is a mountain and a coast arguing politely. Lemon, olive oil and parsley cut through everything, and the table is designed for sharing rather than courses. Grain, pulses and yogurt carry the everyday; the grill and the pastry oven handle the occasions. Nothing arrives alone, and bread does the work of a fork.",
        staples: ["olive oil", "lemon", "bulgur", "chickpeas", "yogurt", "parsley"],
        techniques: ["pounding to a paste", "charcoal grilling", "pickling in brine"],
        flavourBase: "Lemon, olive oil and garlic, with allspice and cinnamon behind the meat.",
        stampInk: "olive",
        stampShape: "shield",
        stampMotif: "leaf")

    private static let cuisine_georgia = Cuisine(
        id: "georgia",
        regionID: "middle-east",
        country: "Georgia",
        adjective: "Georgian",
        tagline: "Walnut, herb and sour fruit, served all at once.",
        summary: "Georgian food runs on walnuts, herbs and sour fruit, which is why it tastes like nowhere else on either side of the Caucasus. Ground walnut thickens sauces where other kitchens would use cream, and marigold, coriander and fenugreek do the perfuming. Meals are structured around the supra, a long table where dishes arrive all at once.",
        staples: ["walnuts", "cheese", "coriander", "cornmeal", "sour plum", "wheat bread"],
        techniques: ["grinding walnuts to sauce", "grilling over vine cuttings", "baking in a clay oven"],
        flavourBase: "Walnut and blue fenugreek, kept sharp by sour plum and coriander.",
        stampInk: "plum",
        stampShape: "scallop",
        stampMotif: "knot")

    static let cuisines: [Cuisine] = [cuisine_turkey, cuisine_lebanon, cuisine_georgia]

    private static let dishes_turkey: [Dish] = [
        Dish(id: "turkey-lahmacun", cuisineID: "turkey",
             name: "Lahmacun", nativeName: "Lahmacun",
             summary: "Bakers in Gaziantep and Sanliurfa press a paper-thin round of dough, smear it with minced lamb worked into tomato, pepper and parsley, then slide it onto the oven floor for barely two minutes. It is cheap by design, sold by bakeries that also handle the neighborhood bread, and eaten within minutes of leaving the fire.",
             tasteNote: "Crisp at the rim, soft and slightly chewy at the center, with a warm pepper heat and a bright parsley finish.",
             eaten: "Squeezed with lemon, piled with parsley and onion, rolled into a tube and eaten standing at lunch.",
             ingredients: ["thin flatbread dough", "minced lamb", "tomato paste", "red pepper", "parsley", "onion"],
             tags: ["street", "bread", "snack"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 1),
             palette: "rust"),
        Dish(id: "turkey-manti", cuisineID: "turkey",
             name: "Manti", nativeName: "Mantı",
             summary: "Thumbnail-sized parcels of dough, each holding a pinch of spiced lamb, folded by hand in numbers that make sense only when a family works together. Kayseri claims the smallest ones. Boiled, then drowned in garlic yogurt and a spoonful of butter reddened with pepper, it turns very little meat into a full meal.",
             tasteNote: "Slippery dough giving way to a small salty bite of lamb, cooled by sour garlic yogurt, then warmed by peppery butter.",
             eaten: "Spooned from a wide bowl at home, usually a weekend lunch with dried mint scattered over.",
             ingredients: ["flour dough", "minced lamb", "onion", "garlic yogurt", "butter", "dried mint"],
             tags: ["home", "dumpling", "dairy"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "cream"),
        Dish(id: "turkey-iskender", cuisineID: "turkey",
             name: "Iskender Kebap", nativeName: "İskender Kebap",
             summary: "Named for the Bursa cook who, in the 1860s, turned the lamb spit upright so the fat ran down instead of dripping into coals. Shaved slices are laid over cubes of pide bread, flooded with tomato sauce, then finished tableside with foaming butter poured from a small pan.",
             tasteNote: "Bread goes soft under sauce while the lamb edges stay crisp; tomato acidity, then butter coating everything, with cool yogurt against it.",
             eaten: "Knife and fork, a proper sit-down lunch, with yogurt on the plate and grilled peppers alongside.",
             ingredients: ["doner lamb", "pide bread", "tomato sauce", "browned butter", "yogurt", "green peppers"],
             tags: ["grilled", "feast", "bread"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 3, herbal: 0, rich: 3),
             palette: "crimson"),
        Dish(id: "turkey-menemen", cuisineID: "turkey",
             name: "Menemen", nativeName: "Menemen",
             summary: "A skillet of eggs stirred loosely into peppers and tomato that have been softened first, so the vegetables give up their water before the eggs go in. Cooks argue endlessly about onion. It belongs to the late breakfast, the kind that runs into the afternoon and needs nothing more than bread.",
             tasteNote: "Loose and custardy rather than set, sweet from cooked pepper, faintly tart from tomato, with a soft green chili warmth underneath.",
             eaten: "Eaten straight from the pan with torn bread, shared, mid-morning, tea always on the table.",
             ingredients: ["eggs", "green peppers", "tomato", "olive oil", "white cheese"],
             tags: ["breakfast", "vegetarian", "home"],
             profile: Taste(heat: 1, sour: 1, sweet: 2, savour: 2, herbal: 0, rich: 2),
             palette: "saffron"),
        Dish(id: "turkey-mercimek", cuisineID: "turkey",
             name: "Mercimek Corbasi", nativeName: "Mercimek çorbası",
             summary: "Red lentils cooked down with onion and carrot until nothing holds its shape, then blended smooth. Every lokanta in the country has a pot of it going from morning onward, and it costs almost nothing. The transformation happens at the table, when hot pepper butter and lemon are added by the person eating.",
             tasteNote: "Velvety and thick without cream, mild and earthy on its own, sharpened completely by lemon and a slick of pepper butter.",
             eaten: "Bowl and spoon, any hour, with lemon wedges, dried mint and bread on the side.",
             ingredients: ["red lentils", "onion", "carrot", "pepper butter", "lemon", "dried mint"],
             tags: ["soup", "vegetarian", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 2, herbal: 1, rich: 1),
             palette: "ochre"),
        Dish(id: "turkey-baklava", cuisineID: "turkey",
             name: "Baklava", nativeName: "Baklava",
             summary: "Gaziantep pastry cooks stretch dough until a newspaper can be read through it, stack forty or so sheets with clarified butter and green pistachio, bake it, then pour on sugar syrup while the trays are still hot. The syrup is never honey and never chilled, which is why the layers stay brittle.",
             tasteNote: "Shatters at first bite, then turns buttery and dense; sweetness is heavy but short, and pistachio leaves a green, almost grassy finish.",
             eaten: "Two or three pieces with unsweetened tea or coffee, after a meal or at a celebration.",
             ingredients: ["filo sheets", "clarified butter", "pistachios", "sugar syrup", "semolina"],
             tags: ["sweet", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 3),
             palette: "amber"),
        Dish(id: "turkey-cigkofte", cuisineID: "turkey",
             name: "Cig Kofte", nativeName: "Çiğ köfte",
             summary: "Once raw meat kneaded with bulgur for an hour or more, this Sanliurfa specialty is now sold across Turkey in a meatless version that keeps the method and drops the lamb. Fine bulgur, pepper paste and a long list of spices are worked by hand until the mixture turns dark and cohesive.",
             tasteNote: "Dense and slightly grainy, cool from the fridge, with a slow-building chili burn and sharp pomegranate sourness cutting the spice.",
             eaten: "Rolled in lettuce with lemon and pomegranate syrup, handed over a counter as an evening snack.",
             ingredients: ["fine bulgur", "red pepper paste", "isot pepper", "onion", "pomegranate molasses", "lettuce"],
             tags: ["street", "vegetarian", "chili", "snack"],
             profile: Taste(heat: 3, sour: 2, sweet: 1, savour: 2, herbal: 1, rich: 0),
             palette: "crimson"),
        Dish(id: "turkey-hamsi", cuisineID: "turkey",
             name: "Hamsi Tava", nativeName: "Hamsi tava",
             summary: "The Black Sea coast runs on anchovies from November to February, and this is the plainest thing done with them: fish laid in a fan, dredged in corn flour, fried in a shallow pan and turned once. Coastal towns build winter festivals around the catch, and cooks there measure a year by it.",
             tasteNote: "Crunchy corn crust over soft oily flesh, salty and briny, with lemon needed to keep the richness in check.",
             eaten: "Eaten with fingers, bones and all, at a harbor table in winter with raw onion salad.",
             ingredients: ["fresh anchovies", "corn flour", "salt", "sunflower oil", "lemon", "onion salad"],
             tags: ["seafood", "fried", "street"],
             profile: Taste(heat: 0, sour: 1, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
    ]

    private static let dishes_lebanon: [Dish] = [
        Dish(id: "lebanon-hummus", cuisineID: "lebanon",
             name: "Hummus bi Tahini", nativeName: "حمص بطحينة",
             summary: "Chickpeas cooked until they surrender, then ground with sesame paste, lemon and garlic into something closer to a sauce than a dip. The proportion of tahini is the whole argument. In Beirut it belongs to breakfast as much as to the meze table, served warm with whole chickpeas kept back and spooned into the well.",
             tasteNote: "Silky and loose rather than stiff, nutty from sesame, lifted by raw garlic and enough lemon to keep it from feeling heavy.",
             eaten: "Scooped with torn flatbread from a shared shallow bowl, at breakfast or as the first meze.",
             ingredients: ["chickpeas", "tahini", "lemon juice", "garlic", "olive oil", "cumin"],
             tags: ["vegetarian", "breakfast", "home"],
             profile: Taste(heat: 0, sour: 2, sweet: 0, savour: 2, herbal: 0, rich: 2),
             palette: "cream"),
        Dish(id: "lebanon-tabbouleh", cuisineID: "lebanon",
             name: "Tabbouleh", nativeName: "تبولة",
             summary: "Mostly parsley, which surprises people who have met the grain-heavy versions abroad. Bulgur is a seasoning here, a handful swollen in tomato juice, not a base. Everything is chopped fine with a sharp knife rather than a machine, and the dressing goes on at the last second so the leaves stay upright.",
             tasteNote: "Crisp and wet, almost drinkable, dominated by green parsley bitterness with sharp lemon, sweet tomato and a cool mint lift at the end.",
             eaten: "Lifted with romaine leaves instead of a fork, part of any mezze spread, year round.",
             ingredients: ["flat-leaf parsley", "fine bulgur", "tomato", "mint", "lemon juice", "olive oil"],
             tags: ["vegetarian", "home", "snack"],
             profile: Taste(heat: 0, sour: 3, sweet: 1, savour: 1, herbal: 3, rich: 1),
             palette: "herb"),
        Dish(id: "lebanon-kibbeh", cuisineID: "lebanon",
             name: "Kibbeh bil Sanieh", nativeName: "كبة بالصينية",
             summary: "Lamb and fine bulgur pounded into a smooth paste, spread in a tray, layered with a filling of onion, pine nuts and more meat, then scored into diamonds before baking. The tray version is the household one; a village cook once did the pounding in a stone mortar for the better part of a morning.",
             tasteNote: "Firm and slightly sandy from bulgur, deeply meaty, with warm allspice and cinnamon and small buttery pine nuts breaking the texture.",
             eaten: "Cut in diamonds and served hot at a family gathering, with yogurt and cabbage salad.",
             ingredients: ["minced lamb", "fine bulgur", "onion", "pine nuts", "allspice", "cinnamon"],
             tags: ["feast", "home"],
             profile: Taste(heat: 0, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "lebanon-manakish", cuisineID: "lebanon",
             name: "Manakish Za'atar", nativeName: "مناقيش زعتر",
             summary: "Dough rounds spread with za'atar slaked in olive oil and pushed into a communal oven before most people are properly awake. Neighborhood bakeries once baked whatever dough the households brought them, and the habit survives in the queue that forms early. The green paste stains fingers and is meant to.",
             tasteNote: "Chewy warm bread under an oily herb crust, tart from sumac, grassy from thyme, finishing with toasted sesame.",
             eaten: "Folded in half around cucumber and mint, eaten walking, straight from the bakery paper at dawn.",
             ingredients: ["bread dough", "za'atar", "sumac", "olive oil", "sesame seeds"],
             tags: ["breakfast", "street", "bread", "vegetarian"],
             profile: Taste(heat: 0, sour: 2, sweet: 0, savour: 2, herbal: 3, rich: 1),
             palette: "herb"),
        Dish(id: "lebanon-shishbarak", cuisineID: "lebanon",
             name: "Shish Barak", nativeName: "شيش برك",
             summary: "Small meat dumplings poached in cooked yogurt, a dish that takes patience because the yogurt has to be stabilized with starch and stirred one direction until it stops threatening to split. Mountain households made it in winter from preserved yogurt. Garlic fried with dried mint goes in right before serving.",
             tasteNote: "Soft parcels in a tangy, faintly grainy white sauce, sour and savory at once, with garlic and dried mint sharpening every spoonful.",
             eaten: "A deep bowl with rice, spooned hot on a cold evening, usually cooked at home.",
             ingredients: ["dough parcels", "minced lamb", "yogurt", "garlic", "dried mint", "short-grain rice"],
             tags: ["dumpling", "dairy", "home", "soup"],
             profile: Taste(heat: 0, sour: 3, sweet: 0, savour: 2, herbal: 2, rich: 2),
             palette: "cream"),
        Dish(id: "lebanon-samkeharra", cuisineID: "lebanon",
             name: "Samke Harra", nativeName: "سمكة حرة",
             summary: "Tripoli's contribution: a whole white fish baked and then covered in a sauce of tahini, chili, coriander and walnuts, thinned with lemon until it pours. The sauce does the seasoning that the fish cannot, and the northern coast makes it far hotter than the rest of the country expects.",
             tasteNote: "Flaky mild fish under a thick, nutty sauce that is sour first, then slowly hot, with fresh coriander running through it.",
             eaten: "Brought out whole on a platter for guests, shared with bread and rice, coast side.",
             ingredients: ["whole white fish", "tahini", "walnuts", "red chili", "coriander", "lemon juice"],
             tags: ["seafood", "feast", "chili"],
             profile: Taste(heat: 2, sour: 3, sweet: 0, savour: 2, herbal: 2, rich: 2),
             palette: "ochre"),
        Dish(id: "lebanon-knafeh", cuisineID: "lebanon",
             name: "Knafeh bil Jibn", nativeName: "كنافة بالجبن",
             summary: "Shredded pastry or fine semolina over a layer of soft unsalted cheese, baked until the base browns, flipped, then soaked in orange blossom syrup. It is served for breakfast, which visitors find hard to accept. Bakers slide a wedge into a sesame bread roll and hand it across the counter.",
             tasteNote: "Crisp crumbly top, then hot cheese that pulls into strings, sweet and floral, with a mild salty edge underneath the syrup.",
             eaten: "Eaten hot in the morning, inside a sesame roll, from a bakery counter with tea.",
             ingredients: ["kataifi pastry", "akkawi cheese", "semolina", "sugar syrup", "orange blossom water", "pistachios"],
             tags: ["sweet", "breakfast", "dairy", "street"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 1, herbal: 0, rich: 3),
             palette: "blush"),
        Dish(id: "lebanon-mujaddara", cuisineID: "lebanon",
             name: "Mujaddara", nativeName: "مجدرة",
             summary: "Lentils and rice cooked together under a heavy blanket of onions fried until they are nearly black, which is where all the sweetness and most of the flavor comes from. It is old, cheap and meatless, the food of lean weeks and of ordinary Tuesdays, and it is better the next day.",
             tasteNote: "Soft, earthy and plain in the middle, saved by burnt-sweet onion on top and a cool sour bite of yogurt alongside.",
             eaten: "Served warm or at room temperature with yogurt and pickles, an everyday lunch at home.",
             ingredients: ["brown lentils", "rice", "onions", "olive oil", "cumin", "yogurt"],
             tags: ["vegetarian", "home", "rice"],
             profile: Taste(heat: 0, sour: 1, sweet: 2, savour: 2, herbal: 0, rich: 1),
             palette: "umber"),
    ]

    private static let dishes_georgia: [Dish] = [
        Dish(id: "georgia-khachapuri", cuisineID: "georgia",
             name: "Adjaruli Khachapuri", nativeName: "აჭარული ხაჭაპური",
             summary: "The Adjaran version is shaped like a boat, filled with brined sulguni cheese and baked until the edges blister; an egg yolk and a knob of butter go into the middle at the last moment. The shape is said to echo the Black Sea fishing boats of Batumi, where it belongs.",
             tasteNote: "Stretchy salty cheese pulled into a rich yolk sauce, with crusty chewy bread that soaks it up and turns almost custardy.",
             eaten: "Tear the crust, stir the yolk in, dip; eaten with hands, late and shared.",
             ingredients: ["yeast dough", "sulguni cheese", "imeruli cheese", "egg yolk", "butter"],
             tags: ["bread", "dairy", "street"],
             profile: Taste(heat: 0, sour: 1, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "cream"),
        Dish(id: "georgia-khinkali", cuisineID: "georgia",
             name: "Khinkali", nativeName: "ხინკალი",
             summary: "Twisted dumplings from the mountain provinces, pleated at the top into a knob that is not eaten. Inside, coarsely chopped meat and a lot of broth that forms as it cooks. The count of pleats is a matter of pride, and the discarded knobs at the end of a meal are how the table keeps score.",
             tasteNote: "Thick chewy dough, a mouthful of hot peppery broth first, then loose meat; black pepper dominates and lingers.",
             eaten: "Held by the knob, bitten at the side, broth drunk first; fingers only, never a fork.",
             ingredients: ["wheat dough", "minced beef and pork", "onion", "black pepper", "coriander", "broth"],
             tags: ["dumpling", "home", "street"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "ochre"),
        Dish(id: "georgia-satsivi", cuisineID: "georgia",
             name: "Satsivi", nativeName: "საცივი",
             summary: "Poached turkey or chicken cooled in a walnut sauce loosened with its own broth and colored with marigold. The name comes from the word for cold, and it is deliberately served that way, made a day ahead. It appears on almost every table at New Year, where it is the first thing gone.",
             tasteNote: "Cool and thick, the sauce grainy with ground walnut, mildly sour from vinegar, warmly spiced, coating tender shreds of bird.",
             eaten: "Served cold in a shallow bowl at the winter table, scooped up with bread.",
             ingredients: ["turkey", "walnuts", "marigold", "coriander", "garlic", "wine vinegar"],
             tags: ["feast", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 3, herbal: 2, rich: 3),
             palette: "umber"),
        Dish(id: "georgia-pkhali", cuisineID: "georgia",
             name: "Pkhali", nativeName: "ფხალი",
             summary: "Any vegetable that can be boiled and squeezed dry gets turned into pkhali: spinach, beet leaves, beans, nettle. The greens are chopped and bound with pounded walnut, garlic and vinegar, then rolled into small balls. Three colors usually arrive together on one plate, which is half the point.",
             tasteNote: "Dense and cool, earthy from the greens, sweet-nutty from walnut, with garlic heat and vinegar sharpness arriving at the back.",
             eaten: "Small cold balls at the start of a meal, eaten with bread and pomegranate seeds.",
             ingredients: ["spinach or beet leaves", "walnuts", "garlic", "coriander", "wine vinegar", "pomegranate seeds"],
             tags: ["vegetarian", "snack", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 2, herbal: 3, rich: 2),
             palette: "jade"),
        Dish(id: "georgia-mtsvadi", cuisineID: "georgia",
             name: "Mtsvadi", nativeName: "მწვადი",
             summary: "Pork or lamb cut in large pieces, salted, and grilled over grapevine cuttings rather than charcoal, which is the part Georgians insist on. No marinade in the traditional version; the meat is turned by hand on a long skewer and pulled off with raw onion and pomegranate. Cooked outdoors, usually slowly.",
             tasteNote: "Charred outside, juicy and plainly salty inside, with vine smoke in the fat and sour pomegranate cutting straight through it.",
             eaten: "Pulled off the skewer onto bread outdoors, with sliced onion and a sour plum sauce.",
             ingredients: ["pork shoulder", "salt", "onion", "pomegranate seeds", "tkemali sauce"],
             tags: ["grilled", "feast", "street"],
             profile: Taste(heat: 0, sour: 2, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "char"),
        Dish(id: "georgia-churchkhela", cuisineID: "georgia",
             name: "Churchkhela", nativeName: "ჩურჩხელა",
             summary: "Walnuts threaded on string and dipped over and over into grape juice thickened with flour, then hung to dry for weeks until a firm skin forms. It travels well and keeps for months, which is why it followed soldiers and shepherds. Roadside stalls sell it in ropes that look like candles.",
             tasteNote: "Chewy and slightly tacky outside, crunchy walnut inside, moderately sweet with a tannic grape edge that stops it cloying.",
             eaten: "Sliced into rounds or bitten off the string, a snack for the road or with tea.",
             ingredients: ["walnuts", "grape juice", "wheat flour", "sugar"],
             tags: ["sweet", "snack", "street"],
             profile: Taste(heat: 0, sour: 1, sweet: 3, savour: 0, herbal: 0, rich: 1),
             palette: "plum"),
        Dish(id: "georgia-lobio", cuisineID: "georgia",
             name: "Lobio", nativeName: "ლობიო",
             summary: "Red beans stewed with onion, coriander and blue fenugreek until they break down at the edges, often finished in a clay pot and served in it. Every region tweaks it and some versions stay soupy while others are mashed almost dry. The cornbread served alongside is not optional.",
             tasteNote: "Thick and starchy with whole beans still intact, savory and herbal, with fenugreek giving a faint bitterness and vinegar a sour lift.",
             eaten: "Eaten hot from the clay pot with mchadi cornbread and pickles, an everyday winter meal.",
             ingredients: ["red kidney beans", "onion", "coriander", "blue fenugreek", "wine vinegar", "cornmeal bread"],
             tags: ["vegetarian", "home", "braised"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 2, herbal: 3, rich: 1),
             palette: "rust"),
        Dish(id: "georgia-chikhirtma", cuisineID: "georgia",
             name: "Chikhirtma", nativeName: "ჩიხირთმა",
             summary: "A chicken broth thickened at the end with egg yolks beaten into vinegar, off the heat, so it turns silky instead of curdling. There are no vegetables in it at all, which is unusual for a soup. It has a long reputation as the first thing you eat the morning after a supra.",
             tasteNote: "Smooth and glossy rather than clear, gently sour from vinegar, rich with yolk, warmed through by coriander and a lot of onion.",
             eaten: "A deep bowl with a spoon, late morning, bread on the side and nothing else.",
             ingredients: ["chicken", "egg yolks", "onion", "wine vinegar", "coriander", "saffron"],
             tags: ["soup", "home"],
             profile: Taste(heat: 0, sour: 2, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "saffron"),
    ]

    static let dishes: [Dish] = dishes_turkey + dishes_lebanon + dishes_georgia
}
