import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentAfrica {

    private static let cuisine_morocco = Cuisine(
        id: "morocco",
        regionID: "africa",
        country: "Morocco",
        adjective: "Moroccan",
        tagline: "Spice, slow clay and the long patience of the souk.",
        summary: "Moroccan cooking sits where Berber mountain food met Andalusian courts, Arab traders and the caravan routes south. The result is a kitchen that treats sweetness as a savory tool, putting fruit into meat and cinnamon onto pastry that hides pigeon. Direct heat is gentle, but the layering of cumin, saffron and preserved lemon is anything but shy.",
        staples: ["semolina", "olive oil", "preserved lemon", "saffron", "almonds", "mint"],
        techniques: ["slow braising in clay", "steaming over broth", "charcoal grilling"],
        flavourBase: "Cumin, saffron and preserved lemon, rounded out with dried fruit and honey.",
        stampInk: "ochre",
        stampShape: "arch",
        stampMotif: "star")

    private static let cuisine_ethiopia = Cuisine(
        id: "ethiopia",
        regionID: "africa",
        country: "Ethiopia",
        adjective: "Ethiopian",
        tagline: "Sour bread, red spice and one plate shared by many hands.",
        summary: "Ethiopian food is built around injera, a wide sour pancake of fermented teff that works as plate, bread and utensil at once. Stews are ladled straight onto it and eaten by hand from a shared tray. Berbere and spiced butter carry the heat and depth, while long fasting seasons have made the vegetarian half of this kitchen unusually deep.",
        staples: ["teff", "berbere", "spiced butter", "lentils", "collard greens"],
        techniques: ["fermenting teff batter", "griddling on a clay mitad", "stewing in spiced butter"],
        flavourBase: "Berbere chili, spiced clarified butter and the sourness of fermented teff.",
        stampInk: "crimson",
        stampShape: "circle",
        stampMotif: "grain")

    private static let cuisine_nigeria = Cuisine(
        id: "nigeria",
        regionID: "africa",
        country: "Nigeria",
        adjective: "Nigerian",
        tagline: "Pepper first, and enough of it to make a room go quiet.",
        summary: "Nigerian cooking runs on heat, palm oil and starch you can tear with your fingers. Scotch bonnet is not a garnish here, it is the base note, balanced by the deep sweetness of fried tomato and onion. Yam, cassava and rice do the heavy lifting, and almost every soup expects a swallow of pounded starch beside it.",
        staples: ["yam", "palm oil", "scotch bonnet", "cassava", "dried crayfish", "rice"],
        techniques: ["frying a tomato and pepper base", "pounding starch into a swallow", "grilling over open coals"],
        flavourBase: "Scotch bonnet, palm oil and dried crayfish over a long-fried pepper base.",
        stampInk: "forest",
        stampShape: "shield",
        stampMotif: "pot")

    static let cuisines: [Cuisine] = [cuisine_morocco, cuisine_ethiopia, cuisine_nigeria]

    private static let dishes_morocco: [Dish] = [
        Dish(id: "morocco-lamb-tagine", cuisineID: "morocco",
             name: "Lamb Tagine with Prunes", nativeName: "طاجين اللحم بالبرقوق",
             summary: "The conical lid is the whole idea. Steam climbs, cools, and falls back onto the meat, so a tough shoulder turns tender on very little liquid, which mattered where water and fuel were scarce. Prunes and honey arrived from the Andalusian side of the family, cutting the fat with fruit.",
             tasteNote: "Meat collapses at the edge of a spoon; the sauce is dark and honeyed, with cinnamon warmth and a sticky, fatty finish.",
             eaten: "Eaten communally straight from the dish with bread and no forks, usually as the main Friday meal.",
             ingredients: ["lamb shoulder", "prunes", "onions", "cinnamon", "honey", "toasted almonds"],
             tags: ["feast", "braised", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 3, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "morocco-couscous", cuisineID: "morocco",
             name: "Seven Vegetable Couscous", nativeName: "كسكس بالخضر",
             summary: "Friday food, steamed three separate times over the broth it will be served with so that every grain stays loose and dry. The seven vegetables are less a fixed list than a principle of abundance, whatever the season offers piled into a dome. Rolling the semolina by hand was once a weekly household ritual.",
             tasteNote: "Grains are light and dry on the tongue, soaked with mild saffron broth; sweet carrot and pumpkin play against soft chickpeas.",
             eaten: "Served at midday after Friday prayers, from one wide dish, with a ladle of broth poured over.",
             ingredients: ["semolina couscous", "chickpeas", "pumpkin", "carrots", "turnips", "saffron broth"],
             tags: ["home", "vegetarian", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 2, herbal: 1, rich: 1),
             palette: "saffron"),
        Dish(id: "morocco-harira", cuisineID: "morocco",
             name: "Harira", nativeName: "حريرة",
             summary: "A thickened lentil and tomato soup that shows up every evening of Ramadan to break the fast, though people eat it all year. Its body comes from a flour and water slurry stirred in at the very end, called tedouira, which gives the bowl a velvety weight that no cream could match.",
             tasteNote: "Thick and silky rather than brothy, tangy with tomato and lemon, warm with ginger, finishing on soft lentils and coriander.",
             eaten: "Sipped from a bowl at sunset alongside dates and sticky chebakia, most often before anything else.",
             ingredients: ["brown lentils", "chickpeas", "tomatoes", "celery", "coriander", "flour slurry"],
             tags: ["soup", "home", "feast"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 3, herbal: 2, rich: 1),
             palette: "rust"),
        Dish(id: "morocco-bastilla", cuisineID: "morocco",
             name: "Bastilla", nativeName: "بسطيلة",
             summary: "A pie that argues with itself. Shredded pigeon or chicken is cooked with onions and eggs, layered with ground almond under sheets of warqa pastry, then finished on top with sugar and cinnamon. It came to Fez with the Andalusian exiles and stayed as the opening course of any serious celebration.",
             tasteNote: "Shatters into paper flakes, then gives way to soft spiced meat and sweet almond; sugar dust up front, deep savor underneath.",
             eaten: "Cut at the table at weddings and taken by hand as the first course, well before the tagines.",
             ingredients: ["warqa pastry", "chicken", "eggs", "almonds", "cinnamon", "powdered sugar"],
             tags: ["feast", "sweet"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 3, herbal: 0, rich: 3),
             palette: "ochre"),
        Dish(id: "morocco-msemen", cuisineID: "morocco",
             name: "Msemen", nativeName: "مسمن",
             summary: "Dough is stretched until it is nearly transparent, oiled, folded into a square and griddled flat, so it comes off the pan in fine sheets rather than a single crumb. Street cooks turn them out in stacks all morning. The technique is closer to pastry lamination than to any kind of bread baking.",
             tasteNote: "Chewy and slightly greasy in the best way, with crisp edges and buttery layers that pull apart; mild, faintly salty.",
             eaten: "Breakfast food, torn warm and dipped into honey and melted butter with sweet mint tea.",
             ingredients: ["semolina", "flour", "butter", "honey", "salt"],
             tags: ["breakfast", "street", "bread"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 1, herbal: 0, rich: 2),
             palette: "cream"),
        Dish(id: "morocco-sardines", cuisineID: "morocco",
             name: "Chermoula Sardines", nativeName: "سردين بالشرمولة",
             summary: "Atlantic sardines are butterflied and pressed together in pairs around a green paste of coriander, garlic, cumin and paprika, then floured and fried. Morocco lands more sardines than almost anywhere on earth, and this is what the fishing ports do with the cheapest, freshest box on the quay.",
             tasteNote: "Crisp outside, oily and soft within, with herb-heavy chermoula cutting through the fat; salty, garlicky, a clean lemon finish.",
             eaten: "Bought hot in newsprint at port stalls and eaten standing up with bread and lemon.",
             ingredients: ["fresh sardines", "coriander", "garlic", "cumin", "paprika", "lemon"],
             tags: ["street", "seafood", "fried"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 3, herbal: 3, rich: 2),
             palette: "herb"),
        Dish(id: "morocco-chebakia", cuisineID: "morocco",
             name: "Chebakia", nativeName: "شباكية",
             summary: "Strips of sesame dough are pinched and turned into a rosette, fried until dark, then dropped straight into warm honey scented with orange blossom. Households make them in enormous batches before Ramadan and store them in tins, since they only improve as the honey sets around the folds.",
             tasteNote: "Sticky and crunchy at once, heavy with honey and toasted sesame, with orange blossom lifting the last of it.",
             eaten: "Eaten with harira at sunset, or with mint tea in the afternoon, two or three at a time.",
             ingredients: ["flour", "sesame seeds", "orange blossom water", "honey", "anise", "saffron"],
             tags: ["sweet", "fried", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "morocco-zaalouk", cuisineID: "morocco",
             name: "Zaalouk", nativeName: "زعلوك",
             summary: "Eggplant and tomato are cooked down with garlic and paprika until the whole thing gives up its shape and lands somewhere between a salad and a spread. It belongs to the row of small cooked salads that open a Moroccan meal, each one a different vegetable handled a different way.",
             tasteNote: "Soft and jammy, smoky from charred eggplant, tart with tomato, rounded out by olive oil and a low cumin hum.",
             eaten: "Scooped up with torn bread as one of several small dishes set out before the main course.",
             ingredients: ["eggplant", "tomatoes", "garlic", "paprika", "olive oil", "coriander"],
             tags: ["vegetarian", "home"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 2, herbal: 2, rich: 2),
             palette: "umber"),
    ]

    private static let dishes_ethiopia: [Dish] = [
        Dish(id: "ethiopia-doro-wat", cuisineID: "ethiopia",
             name: "Doro Wat", nativeName: "ዶሮ ወጥ",
             summary: "The stew that measures a cook. Onions are dry-cooked without any fat for a long time before spiced butter and berbere go in, which is why the sauce reads dark and deep rather than sharp. Chicken and a whole boiled egg for each guest make it the dish for holidays and for welcoming someone properly.",
             tasteNote: "Dense and glossy, building slow chili heat, sweet cooked onion underneath, and a rich buttery coat that stays on the lips.",
             eaten: "Ladled onto injera on a shared platter and torn up by hand, usually at holidays.",
             ingredients: ["chicken", "red onions", "berbere", "spiced butter", "boiled eggs", "garlic"],
             tags: ["feast", "braised", "chili"],
             profile: Taste(heat: 3, sour: 1, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "crimson"),
        Dish(id: "ethiopia-injera", cuisineID: "ethiopia",
             name: "Injera", nativeName: "እንጀራ",
             summary: "Teff batter is left to ferment for days, then poured in a spiral onto a hot clay griddle and covered so it steams rather than browns. The bubbles that burst on the surface leave the honeycomb face that soaks up stew. It is plate, bread and spoon in one object.",
             tasteNote: "Spongy and cool to the touch, distinctly sour like yogurt, with a faint grassy teff note and no crust to speak of.",
             eaten: "Torn with the right hand at every meal and used to pinch stews off the common tray.",
             ingredients: ["teff flour", "water", "starter culture", "salt"],
             tags: ["bread", "fermented", "vegetarian", "home"],
             profile: Taste(heat: 0, sour: 3, sweet: 0, savour: 1, herbal: 0, rich: 0),
             palette: "cream"),
        Dish(id: "ethiopia-kitfo", cuisineID: "ethiopia",
             name: "Kitfo", nativeName: "ክትፎ",
             summary: "Beef is minced very fine and warmed only to blood temperature in spiced clarified butter, seasoned with mitmita rather than berbere. Gurage country claims it, and there it is a dish of honor rather than everyday eating. Ask for it leb leb if you want it barely cooked, or tere for fully raw.",
             tasteNote: "Soft and almost creamy, warm rather than hot, with a fierce dry chili burn arriving late over clean iron-sweet beef.",
             eaten: "Served with crumbly ayib cheese and greens, taken by hand with injera or kocho.",
             ingredients: ["lean beef", "spiced butter", "mitmita", "ayib cheese", "cardamom"],
             tags: ["raw", "feast", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "rust"),
        Dish(id: "ethiopia-shiro", cuisineID: "ethiopia",
             name: "Shiro", nativeName: "ሽሮ",
             summary: "Chickpea or broad bean flour, already milled together with garlic, ginger and chili, is stirred into simmering water until it thickens. It costs almost nothing, keeps well as a dry powder, and becomes a meal in ten minutes, which is why it feeds more people here than anything else on this list.",
             tasteNote: "Smooth and nutty, thick as a loose puree, gently spiced with a warm garlic edge and a long savory finish.",
             eaten: "Everyday lunch, brought to the table still bubbling in its clay dish with injera.",
             ingredients: ["chickpea flour", "garlic", "ginger", "berbere", "onions", "oil"],
             tags: ["vegetarian", "home", "braised"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 1),
             palette: "ochre"),
        Dish(id: "ethiopia-tibs", cuisineID: "ethiopia",
             name: "Tibs", nativeName: "ጥብስ",
             summary: "Cubed beef or lamb goes into a very hot pan with onion, rosemary and green chili, cooks fast, and arrives at the table still spitting on its own small brazier of coals. It is the celebratory counterweight to the slow stews, ordered when there is something worth marking.",
             tasteNote: "Chewy seared edges, juicy centers, smoke from the hot pan, with rosemary and green chili cutting the butter.",
             eaten: "Shared straight from the sizzling dish in the evening and scooped up with injera.",
             ingredients: ["beef", "onions", "green chilies", "rosemary", "spiced butter", "garlic"],
             tags: ["grilled", "feast", "chili"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 2, rich: 3),
             palette: "char"),
        Dish(id: "ethiopia-misir-wot", cuisineID: "ethiopia",
             name: "Misir Wot", nativeName: "ምስር ወጥ",
             summary: "Red lentils are cooked down with berbere until they lose their edges entirely. On the many fasting days of the Orthodox calendar, when animal products are set aside, this is the anchor of the tray, and part of why Ethiopian vegetable cooking developed such range instead of feeling like a substitute.",
             tasteNote: "Velvety and loose on the tray, sweet from long-cooked onion, then a steady chili heat that builds across several bites.",
             eaten: "Set alongside other vegetable stews on a single injera tray and eaten with the hands.",
             ingredients: ["red lentils", "berbere", "onions", "garlic", "tomato", "oil"],
             tags: ["vegetarian", "home", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 1, savour: 2, herbal: 0, rich: 1),
             palette: "crimson"),
        Dish(id: "ethiopia-ful", cuisineID: "ethiopia",
             name: "Ful", nativeName: "ፉል",
             summary: "Fava beans are simmered soft and then mashed at the table with the back of a spoon, a habit that came up through the Red Sea ports and settled into the Ethiopian and Eritrean morning. Cafes serve it in a metal dish with a swirl of oil, chopped onion and whatever chili you can take.",
             tasteNote: "Warm, thick and mealy, mildly savory on its own, then sharpened by raw onion and green chili stirred in as you go.",
             eaten: "Breakfast in a busy cafe, mashed together with bread rolls and taken with sweet tea.",
             ingredients: ["fava beans", "onions", "green chilies", "tomato", "olive oil", "yogurt"],
             tags: ["breakfast", "street", "vegetarian"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 2, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "ethiopia-hambasha", cuisineID: "ethiopia",
             name: "Hambasha", nativeName: "ሓምባሻ",
             summary: "A round celebration bread, scored across the top in a sun pattern before baking, lightly sweet and scented with fenugreek and black cumin. It appears at weddings, baptisms and holidays, carried in whole and broken by hand rather than sliced, so that everyone takes a piece from the same loaf.",
             tasteNote: "Dense and slightly springy, faintly sweet, warm with fenugreek, under a chewy browned crust dotted with toasted seeds.",
             eaten: "Broken and passed around at celebrations, often with coffee poured from a clay jebena.",
             ingredients: ["wheat flour", "fenugreek", "black cumin", "sugar", "yeast", "butter"],
             tags: ["bread", "feast", "sweet"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 1, herbal: 2, rich: 2),
             palette: "amber"),
    ]

    private static let dishes_nigeria: [Dish] = [
        Dish(id: "nigeria-jollof", cuisineID: "nigeria",
             name: "Jollof Rice", nativeName: "Ìrẹsì Jollof",
             summary: "Long grain rice is cooked in a reduced stew of tomato, pepper and onion until the color goes all the way through the grain. The argument over whose version wins runs across half of West Africa. What marks the Nigerian one is the deliberate scorch at the bottom of the pot, prized rather than apologized for.",
             tasteNote: "Grains stay separate and slightly firm, carrying smoky tomato sweetness and a steady pepper heat, finishing on burnt-pot depth.",
             eaten: "Party food above all, served with fried plantain and chicken from a foil tray.",
             ingredients: ["long grain rice", "tomatoes", "red bell pepper", "scotch bonnet", "onions", "thyme"],
             tags: ["rice", "feast", "home"],
             profile: Taste(heat: 2, sour: 1, sweet: 2, savour: 3, herbal: 1, rich: 2),
             palette: "rust"),
        Dish(id: "nigeria-egusi", cuisineID: "nigeria",
             name: "Egusi Soup", nativeName: "Ẹ̀gúsí",
             summary: "Ground melon seed is the whole point. Fried in palm oil it seizes into soft curds that thicken the pot and lend it a nutty body, then bitterleaf or ugu goes in green and late. Meat, stockfish and smoked fish stack up the savory side. It is soup only in the loosest sense.",
             tasteNote: "Grainy and thick, nutty from the seeds, oily and deeply savory, with bitter greens and a slow scotch bonnet burn.",
             eaten: "Eaten with a ball of pounded yam, pinched and dipped by hand, no spoon involved.",
             ingredients: ["ground melon seeds", "palm oil", "ugu leaves", "smoked fish", "beef", "dried crayfish"],
             tags: ["home", "feast", "braised"],
             profile: Taste(heat: 2, sour: 0, sweet: 0, savour: 3, herbal: 2, rich: 3),
             palette: "herb"),
        Dish(id: "nigeria-suya", cuisineID: "nigeria",
             name: "Suya", nativeName: "Tsire",
             summary: "Thin sheets of beef are pressed onto sticks, coated in yaji, a rub of ground peanut, chili and ginger, then held close over coals by a mallam working a low grill. Northern Hausa in origin, it now runs every Nigerian night market and is sold from dusk onward.",
             tasteNote: "Dry-edged and chewy, peanut dust clinging to charred meat, hot and gingery, with raw onion sharpening every bite.",
             eaten: "Bought after dark wrapped in newspaper with sliced onion, tomato and extra yaji.",
             ingredients: ["beef", "ground peanut", "ginger", "chili powder", "onions", "groundnut oil"],
             tags: ["street", "grilled", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 2),
             palette: "rust"),
        Dish(id: "nigeria-puff-puff", cuisineID: "nigeria",
             name: "Puff-Puff", nativeName: "Bọ̀flọ́t",
             summary: "Yeasted batter, loose and sticky, is squeezed through a fist and dropped into hot oil so that it puffs into an uneven ball with a pale band around the middle. Sold from wide pans on street corners in the late afternoon, counted into a paper bag by the handful.",
             tasteNote: "A crisp thin shell over a stretchy, airy crumb, sweet without being cloying, with a clean fried-dough warmth.",
             eaten: "Bought hot by the bagful in the afternoon and eaten with the fingers straight away.",
             ingredients: ["flour", "yeast", "sugar", "nutmeg", "water", "vegetable oil"],
             tags: ["street", "sweet", "fried"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "amber"),
        Dish(id: "nigeria-moi-moi", cuisineID: "nigeria",
             name: "Moi Moi", nativeName: "Mọ́í mọ́í",
             summary: "Peeled black-eyed peas are blended with pepper and onion, then steamed inside leaves until they set into something between a pudding and a cake. The leaf is not just a wrapper, it perfumes the whole thing while it cooks. Cooks often bury a boiled egg or a piece of fish in the middle.",
             tasteNote: "Soft and slightly grainy, holding its shape on the spoon, savory and gently peppery, with a green leaf aroma throughout.",
             eaten: "Served warm in its parcel beside jollof at parties, or alone with pap at breakfast.",
             ingredients: ["black-eyed peas", "red bell pepper", "onions", "palm oil", "boiled egg", "dried crayfish"],
             tags: ["home", "breakfast"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 0, rich: 2),
             palette: "ochre"),
        Dish(id: "nigeria-ofada", cuisineID: "nigeria",
             name: "Ofada Rice and Ayamase", nativeName: "Ìrẹsì Ofada",
             summary: "Unpolished local rice with a strong earthy smell, steamed and served in leaves next to ayamase, a green pepper sauce built on bleached palm oil and assorted cuts of beef. Ofada is farmed around the town it is named for, and the pairing is a Lagos and Ogun State signature.",
             tasteNote: "Nutty chewy grains against a heavy oily sauce, fiercely hot, savory with fermented locust bean funk running underneath.",
             eaten: "Unwrapped from its leaf at a roadside canteen for lunch and eaten with a spoon.",
             ingredients: ["ofada rice", "green scotch bonnet", "palm oil", "locust beans", "assorted beef", "boiled eggs"],
             tags: ["rice", "chili", "home"],
             profile: Taste(heat: 3, sour: 1, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "char"),
        Dish(id: "nigeria-akara", cuisineID: "nigeria",
             name: "Akara", nativeName: "Àkàrà",
             summary: "Black-eyed peas are soaked, rubbed to shed their skins, then ground and whipped with a wooden spoon until the batter holds air. That beating is what makes the fritter light instead of dense. It crossed the Atlantic with enslaved West Africans and survives in Brazil as acaraje.",
             tasteNote: "Crunchy brown crust giving way to a fluffy, almost cakey inside, savory and peppery with a warm onion sweetness.",
             eaten: "Morning street food, scooped from the oil into paper and eaten with pap or bread.",
             ingredients: ["black-eyed peas", "onions", "scotch bonnet", "salt", "vegetable oil"],
             tags: ["breakfast", "street", "fried", "vegetarian"],
             profile: Taste(heat: 2, sour: 0, sweet: 1, savour: 2, herbal: 0, rich: 2),
             palette: "saffron"),
        Dish(id: "nigeria-pepper-soup", cuisineID: "nigeria",
             name: "Catfish Pepper Soup", nativeName: "Ọbẹ̀ Ata",
             summary: "A thin, almost clear broth carrying a great deal of chili and a specific set of West African aromatics, uziza seed and calabash nutmeg among them, with fresh catfish dropped in near the end. People order it as much for the steam and the sweat as for the fish itself.",
             tasteNote: "Thin and clean rather than heavy, scaldingly hot, aromatic and faintly bitter, with soft flaking fish and a lingering burn.",
             eaten: "Served in a bowl in the evening, spooned up with the fish eaten off the bone.",
             ingredients: ["catfish", "scotch bonnet", "uziza seeds", "calabash nutmeg", "scent leaf", "onions"],
             tags: ["soup", "seafood", "chili"],
             profile: Taste(heat: 3, sour: 0, sweet: 0, savour: 3, herbal: 3, rich: 1),
             palette: "crimson"),
    ]

    static let dishes: [Dish] = dishes_morocco + dishes_ethiopia + dishes_nigeria
}
