import Foundation

// Generated from the authored dish database. Do not edit by hand.

enum ContentAmericas {

    private static let cuisine_mexico = Cuisine(
        id: "mexico",
        regionID: "americas",
        country: "Mexico",
        adjective: "Mexican",
        tagline: "Corn, chile and the patience of the grinding stone.",
        summary: "Mexican cooking runs on three old pillars: corn softened in lime water, chiles dried and toasted for depth rather than heat alone, and long grinding on stone. Layer after layer is built before anything reaches the plate, which is why a sauce can hold thirty ingredients and still taste of one thing. Regional pride is fierce, and every state argues for its own version.",
        staples: ["corn", "chiles", "beans", "tomatillo", "lard", "epazote"],
        techniques: ["nixtamalizing corn", "toasting chiles on a comal", "pit roasting in banana leaf"],
        flavourBase: "Toasted dried chile, charred tomato and onion, ground smooth and fried back into fat.",
        stampInk: "crimson",
        stampShape: "arch",
        stampMotif: "sun")

    private static let cuisine_peru = Cuisine(
        id: "peru",
        regionID: "americas",
        country: "Peru",
        adjective: "Peruvian",
        tagline: "Cold coast, high sierra and four hundred kinds of potato.",
        summary: "Peru cooks vertically. The Pacific gives it cold clean fish, the Andes give it tubers and corn in sizes and colors found nowhere else, and the Amazon gives it river fish and strange fruit. Onto that landscape arrived Spanish, African, Chinese and Japanese cooks, and the country absorbed all of them without losing its own accent, which is sharp, acidic and built on ají.",
        staples: ["potato", "ají amarillo", "lime", "corn", "fish", "coriander"],
        techniques: ["curing raw fish in lime", "stir frying in a hot wok", "roasting in an earth oven"],
        flavourBase: "Ají amarillo, garlic and red onion, brightened hard with lime.",
        stampInk: "ochre",
        stampShape: "shield",
        stampMotif: "mountain")

    private static let cuisine_brazil = Cuisine(
        id: "brazil",
        regionID: "americas",
        country: "Brazil",
        adjective: "Brazilian",
        tagline: "Cassava, dendê and a table that keeps getting longer.",
        summary: "Brazil is too large to have one kitchen. The northeast cooks with palm oil, coconut and West African technique, the Amazon uses river fish and cassava in forms outsiders have never seen, and the south turns almost everything into meat over fire. What holds it together is cassava in every guise, a taste for slow beans, and the assumption that food is shared.",
        staples: ["cassava", "black beans", "rice", "dendê oil", "coconut", "dried shrimp"],
        techniques: ["slow simmering beans", "grilling over wood embers", "toasting cassava flour"],
        flavourBase: "Garlic, onion and coriander in fat, with dendê or coconut milk behind it.",
        stampInk: "forest",
        stampShape: "banner",
        stampMotif: "leaf")

    static let cuisines: [Cuisine] = [cuisine_mexico, cuisine_peru, cuisine_brazil]

    private static let dishes_mexico: [Dish] = [
        Dish(id: "mexico-pastor", cuisineID: "mexico",
             name: "Tacos al Pastor", nativeName: "Tacos al Pastor",
             summary: "Lebanese immigrants brought the vertical spit to Puebla in the early twentieth century, and Mexican cooks swapped the lamb for pork marinated in dried chiles and achiote. The meat turns for hours against a flame, and the taquero shaves it straight onto small corn tortillas, catching a sliver of pineapple from the top on the way down.",
             tasteNote: "Soft warm tortilla first, then charred pork edges with a smoky chile depth, cut by sharp pineapple and a green cilantro finish.",
             eaten: "Standing at a street stall after dark, two or three at a time, folded in one hand.",
             ingredients: ["pork shoulder", "guajillo chiles", "achiote", "corn tortillas", "pineapple", "white onion"],
             tags: ["street", "grilled", "chili"],
             profile: Taste(heat: 2, sour: 1, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "rust"),
        Dish(id: "mexico-mole", cuisineID: "mexico",
             name: "Mole Poblano", nativeName: "Mole Poblano",
             summary: "The great argument of Puebla, claimed by convent kitchens and older indigenous cooks alike. Two or three dozen ingredients are toasted separately, ground, then fried in lard until the paste darkens and turns glossy. Chocolate is present but is a seasoning, not a sweetener. It is a dish measured in days, kept for the occasions that deserve it.",
             tasteNote: "Thick and velvet on the tongue, bitter chocolate and toasted seed up front, a slow warm chile heat arriving last.",
             eaten: "Ladled over turkey or chicken at weddings and birthdays, with rice and warm tortillas to wipe the plate.",
             ingredients: ["ancho chiles", "mulato chiles", "sesame seeds", "almonds", "dark chocolate", "turkey"],
             tags: ["feast", "braised", "chili"],
             profile: Taste(heat: 2, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "mexico-pozole", cuisineID: "mexico",
             name: "Pozole Rojo", nativeName: "Pozole Rojo",
             summary: "Hominy is corn that has been cooked in lime until the kernels burst open like flowers, and pozole exists to show it off. The broth simmers with pork and a red chile puree until both go soft. What arrives at the table is only half the dish, since the crunch is added by whoever is eating it.",
             tasteNote: "Chewy popped corn in a thin red broth, deeply porky and salty, finished with the cold snap of raw cabbage and lime.",
             eaten: "A Saturday night or holiday supper at home, with dishes of shredded cabbage, radish and oregano passed around.",
             ingredients: ["hominy", "pork shoulder", "guajillo chiles", "cabbage", "radish", "mexican oregano"],
             tags: ["soup", "home", "feast"],
             profile: Taste(heat: 2, sour: 1, sweet: 0, savour: 3, herbal: 2, rich: 2),
             palette: "crimson"),
        Dish(id: "mexico-cochinita", cuisineID: "mexico",
             name: "Cochinita Pibil", nativeName: "Cochinita Pibil",
             summary: "Yucatecan cooking has its own logic, closer to the Maya world than to central Mexico. Pork is rubbed with achiote paste and sour orange, wrapped in banana leaves and buried in a stone lined pit with embers, where it cooks overnight until it collapses. The pit is called a pib, and it gives the dish its name.",
             tasteNote: "Meat that falls apart at a touch, earthy and faintly peppery from achiote, sharpened by sour orange and hot pickled onion.",
             eaten: "Sunday morning food, piled onto tortillas or soft bread rolls with habanero salsa on the side.",
             ingredients: ["suckling pig", "achiote paste", "sour orange", "banana leaf", "red onion", "habanero"],
             tags: ["braised", "feast", "home"],
             profile: Taste(heat: 2, sour: 3, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "rust"),
        Dish(id: "mexico-tamal", cuisineID: "mexico",
             name: "Tamales Oaxaqueños", nativeName: "Tamales Oaxaqueños",
             summary: "Corn dough beaten with fat until it floats in water, spread on a banana leaf, filled and steamed in a stack. Oaxaca wraps in leaf rather than husk, which keeps the dough flatter and lends a faint green smell. Tamales are made in batches by several pairs of hands at once, which is half the point of them.",
             tasteNote: "Dense soft dough with a clean corn sweetness, a dark savory pocket of mole inside, and a leafy perfume around it.",
             eaten: "Bought hot for breakfast from a corner cart, unwrapped in the hand, sometimes stuffed into a bread roll.",
             ingredients: ["masa", "lard", "banana leaf", "chicken", "mole negro"],
             tags: ["breakfast", "street", "home"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 3, herbal: 1, rich: 3),
             palette: "ochre"),
        Dish(id: "mexico-nogada", cuisineID: "mexico",
             name: "Chiles en Nogada", nativeName: "Chiles en Nogada",
             summary: "A poblano chile stuffed with a sweet and savory picadillo of pork, apple, pear and candied fruit, then draped in a cold sauce of fresh walnuts and cheese. It appears only in late summer, when the walnuts and pomegranates come in together. The green, white and red on the plate are the reason it is served around Independence Day.",
             tasteNote: "Cool creamy sauce over a warm chile, sweet fruit against savory meat, walnut richness, and pomegranate popping bright at the end.",
             eaten: "A September lunch dish, served whole on a plate with a fork, one chile per person.",
             ingredients: ["poblano chiles", "ground pork", "walnuts", "candied fruit", "pomegranate", "fresh cheese"],
             tags: ["feast", "home"],
             profile: Taste(heat: 1, sour: 1, sweet: 2, savour: 2, herbal: 1, rich: 3),
             palette: "cream"),
        Dish(id: "mexico-elote", cuisineID: "mexico",
             name: "Elote", nativeName: "Elote",
             summary: "Corn on the cob boiled or held over coals, then dressed while it is still too hot to hold. Mayonnaise or crema goes on first so the crumbled cheese and chile powder have something to stick to, and lime is squeezed over the whole thing. The cart that sells it is usually announced by a steam whistle.",
             tasteNote: "Juicy bursting kernels, a salty creamy coating, dry cheese and mild chile dust, then a sharp lime lift at the finish.",
             eaten: "Eaten off a wooden stick in the street or a park, in the late afternoon, walking.",
             ingredients: ["white corn", "crema", "cotija cheese", "chile powder", "lime"],
             tags: ["street", "snack", "vegetarian"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 2, herbal: 0, rich: 2),
             palette: "saffron"),
        Dish(id: "mexico-pandemuerto", cuisineID: "mexico",
             name: "Pan de Muerto", nativeName: "Pan de Muerto",
             summary: "An enriched round loaf baked through late October, scented with orange zest and sometimes anise, and decorated with strips of dough that read as bones across the top. It is placed on family altars and then eaten by the living, which is entirely the intention. Bakeries sell nothing else in that season.",
             tasteNote: "Light and feathery crumb with a buttery pull, orange perfume through it, and a crunch of coarse sugar on the crust.",
             eaten: "Torn apart at the table with hot chocolate or coffee, early evening, shared among the whole family.",
             ingredients: ["wheat flour", "butter", "eggs", "orange zest", "anise seed", "sugar"],
             tags: ["sweet", "bread", "feast"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 1, herbal: 1, rich: 2),
             palette: "amber"),
    ]

    private static let dishes_peru: [Dish] = [
        Dish(id: "peru-ceviche", cuisineID: "peru",
             name: "Ceviche", nativeName: "Cebiche",
             summary: "Fish cut into cubes and dressed with lime, ají, salt and red onion, then eaten within minutes. The older coastal versions marinated for hours, but modern Lima treats the acid as a seasoning rather than a cure, so the center of each piece stays soft. The cloudy juice left behind is the best part of the plate.",
             tasteNote: "Firm cool fish with a silky center, a fierce clean lime hit, salt, and a slow ají burn that builds after swallowing.",
             eaten: "A lunchtime dish only, never at night, with boiled corn, sweet potato and toasted corn kernels.",
             ingredients: ["sea bass", "lime", "ají limo", "red onion", "choclo corn", "sweet potato"],
             tags: ["raw", "seafood", "chili"],
             profile: Taste(heat: 2, sour: 3, sweet: 1, savour: 2, herbal: 2, rich: 0),
             palette: "cream"),
        Dish(id: "peru-lomo", cuisineID: "peru",
             name: "Lomo Saltado", nativeName: "Lomo Saltado",
             summary: "The clearest evidence of chifa, the Cantonese cooking that took root in Lima after Chinese laborers arrived in the nineteenth century. Beef strips, onion and tomato are thrown into a scorching wok with soy and vinegar, then tipped over fries. Rice comes alongside anyway, because a Peruvian plate with two starches is not a mistake.",
             tasteNote: "Charred juicy beef and softened onion in a tangy soy gravy, with fries going half crisp and half soaked underneath.",
             eaten: "The standard weekday lunch in any cheap restaurant, eaten with a fork, rice pushed in for the sauce.",
             ingredients: ["beef sirloin", "red onion", "tomato", "soy sauce", "potatoes", "white rice"],
             tags: ["home", "fried", "rice"],
             profile: Taste(heat: 1, sour: 2, sweet: 1, savour: 3, herbal: 1, rich: 2),
             palette: "umber"),
        Dish(id: "peru-ajigallina", cuisineID: "peru",
             name: "Ají de Gallina", nativeName: "Ají de Gallina",
             summary: "Poached hen pulled into threads and folded into a thick yellow sauce of ají amarillo, milk, ground walnuts and bread. It descends from a medieval Spanish dish of pounded almonds and chicken, remade with a Peruvian chile that carries color and fragrance more than heat. Comfort food in the strictest sense, eaten by everyone.",
             tasteNote: "Silky and thick with a nutty body, gentle chile warmth, mild savoriness, and a soft sweetness from the milk behind it.",
             eaten: "A weekday home dinner, spooned over rice and boiled potato, with olives and egg on top.",
             ingredients: ["hen", "ají amarillo", "evaporated milk", "walnuts", "white bread", "black olives"],
             tags: ["home", "rice", "dairy"],
             profile: Taste(heat: 1, sour: 0, sweet: 1, savour: 2, herbal: 0, rich: 3),
             palette: "saffron"),
        Dish(id: "peru-huancaina", cuisineID: "peru",
             name: "Papa a la Huancaína", nativeName: "Papa a la Huancaína",
             summary: "Boiled yellow potatoes, sliced thick, cold, and covered in a blended sauce of fresh cheese, ají amarillo and milk. It is named for Huancayo in the central highlands, and it exists because Peru has more potato varieties than anywhere on earth and needed a way to celebrate the plainest of them.",
             tasteNote: "Cool waxy potato under a smooth, slightly grainy cheese sauce, mildly hot, salty, with a briny olive edge.",
             eaten: "A cold starter before lunch, or picnic food, served on lettuce and eaten with a fork.",
             ingredients: ["yellow potatoes", "queso fresco", "ají amarillo", "evaporated milk", "black olives", "lettuce"],
             tags: ["vegetarian", "home", "dairy"],
             profile: Taste(heat: 1, sour: 0, sweet: 0, savour: 2, herbal: 0, rich: 2),
             palette: "ochre"),
        Dish(id: "peru-anticucho", cuisineID: "peru",
             name: "Anticuchos", nativeName: "Anticuchos de Corazón",
             summary: "Beef heart, marinated in vinegar, garlic and dried panca chile, then threaded onto skewers and grilled hard over coals. The dish came out of the colonial period, when enslaved African cooks in Lima were given the offcuts and made the best thing on the street out of them. It is still cooked outdoors, at night, on a drum grill.",
             tasteNote: "Firm springy meat with a mineral iron depth, smoky crust, garlic and vinegar sharpness, and a lingering dry chile heat.",
             eaten: "Evening street food, eaten straight off the skewer with a boiled potato and hot green sauce.",
             ingredients: ["beef heart", "ají panca", "garlic", "red wine vinegar", "cumin", "potato"],
             tags: ["street", "grilled", "chili"],
             profile: Taste(heat: 2, sour: 2, sweet: 0, savour: 3, herbal: 1, rich: 1),
             palette: "char"),
        Dish(id: "peru-causa", cuisineID: "peru",
             name: "Causa Limeña", nativeName: "Causa Limeña",
             summary: "Yellow potato mashed with lime, oil and ají amarillo until it holds like a dough, then layered in a mold with a filling and chilled. Wartime legend says it was sold to fund soldiers, hence the name, which means cause. Whatever the origin, the result is a cold terrine that behaves like a savory cake.",
             tasteNote: "Dense cool potato with a lemony chile tang, a soft creamy layer through the middle, and a smooth mayonnaise finish.",
             eaten: "Served cold in slices as a first course or a buffet dish, at family lunches and parties.",
             ingredients: ["yellow potatoes", "ají amarillo", "lime", "mayonnaise", "chicken", "avocado"],
             tags: ["home", "feast"],
             profile: Taste(heat: 1, sour: 2, sweet: 0, savour: 2, herbal: 0, rich: 2),
             palette: "saffron"),
        Dish(id: "peru-pachamanca", cuisineID: "peru",
             name: "Pachamanca", nativeName: "Pachamanca",
             summary: "A whole meal cooked underground in the Andean highlands. Stones are heated in a fire, dropped into a pit, and layered with marinated meats, potatoes, fava beans and corn parcels, then sealed with leaves and earth for several hours. The name means earth pot in Quechua, and it takes a village afternoon to do properly.",
             tasteNote: "Meat gone smoky and tender to the bone, potatoes dry and floury, everything carrying a green herbal scent from huacatay.",
             eaten: "A village or family celebration, dug open in the afternoon and eaten outdoors on shared leaves.",
             ingredients: ["lamb", "pork", "huacatay", "andean potatoes", "fava beans", "choclo corn"],
             tags: ["feast", "grilled", "home"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 3, herbal: 3, rich: 2),
             palette: "herb"),
        Dish(id: "peru-picarones", cuisineID: "peru",
             name: "Picarones", nativeName: "Picarones",
             summary: "Rings of leavened dough made from squash and sweet potato, pulled into shape by hand and dropped into hot oil, then drenched in chancaca syrup boiled with orange peel, fig leaf and spice. They replaced Spanish bunuelos in colonial Lima because the local tubers were cheaper and, most cooks agree, better.",
             tasteNote: "Crisp lacy outside giving way to a light airy middle, faintly earthy from squash, then a dark molasses sweetness over it.",
             eaten: "Made to order at night markets and fairs, handed over hot in a paper dish with syrup.",
             ingredients: ["squash", "sweet potato", "flour", "chancaca", "orange peel", "anise"],
             tags: ["sweet", "street", "fried"],
             profile: Taste(heat: 0, sour: 1, sweet: 3, savour: 0, herbal: 1, rich: 2),
             palette: "amber"),
    ]

    private static let dishes_brazil: [Dish] = [
        Dish(id: "brazil-feijoada", cuisineID: "brazil",
             name: "Feijoada", nativeName: "Feijoada Completa",
             summary: "Black beans simmered for hours with salted and smoked cuts of pork until the pot turns almost black and thickens on its own. It belongs to the Portuguese tradition of bean and meat stews, remade in Brazil with everything a household had. Nobody makes a small one, and nobody works properly in the afternoon afterward.",
             tasteNote: "Heavy and dark, beans collapsed to a thick gravy, deeply salty and smoky, lifted only by orange and the crunch of farofa.",
             eaten: "A Saturday lunch stretching for hours, served with rice, greens, orange slices and toasted cassava flour.",
             ingredients: ["black beans", "smoked pork ribs", "linguiça", "dried beef", "bay leaf", "cassava flour"],
             tags: ["feast", "braised", "home"],
             profile: Taste(heat: 1, sour: 1, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "umber"),
        Dish(id: "brazil-moqueca", cuisineID: "brazil",
             name: "Moqueca Baiana", nativeName: "Moqueca Baiana",
             summary: "A Bahian fish stew built without any browning at all. Fish, peppers, onion and tomato are layered raw into a clay pot, covered in coconut milk and orange red dendê palm oil, and left to steam gently until the fish is just set. The African and indigenous lines of Brazilian cooking meet in this pot more clearly than anywhere else.",
             tasteNote: "Flaking soft fish in a sweet coconut broth, palm oil giving a distinct waxy fruitiness, coriander green and bright over it.",
             eaten: "Brought to the table in its clay pot to share, with white rice and a spoonful of hot pepper sauce.",
             ingredients: ["white fish", "coconut milk", "dendê oil", "bell peppers", "coriander", "lime"],
             tags: ["seafood", "braised", "feast"],
             profile: Taste(heat: 1, sour: 2, sweet: 2, savour: 2, herbal: 3, rich: 3),
             palette: "rust"),
        Dish(id: "brazil-paodequeijo", cuisineID: "brazil",
             name: "Pão de Queijo", nativeName: "Pão de Queijo",
             summary: "Small cheese rolls from Minas Gerais made with sour cassava starch instead of wheat, which is why they puff into hollow spheres and go chewy rather than crumbly. They predate the country's wheat supply and were originally made without cheese at all. Every bakery counter in Brazil keeps a warm tray of them.",
             tasteNote: "Thin crisp shell, then a stretchy hollow inside that pulls, salty aged cheese, and a faint sourness from the starch.",
             eaten: "Breakfast or a mid morning break with strong coffee, eaten warm from the bag in two bites.",
             ingredients: ["sour cassava starch", "queijo minas", "eggs", "milk", "oil"],
             tags: ["breakfast", "snack", "vegetarian", "dairy"],
             profile: Taste(heat: 0, sour: 1, sweet: 0, savour: 2, herbal: 0, rich: 2),
             palette: "cream"),
        Dish(id: "brazil-acaraje", cuisineID: "brazil",
             name: "Acarajé", nativeName: "Acarajé",
             summary: "Black eyed peas soaked, skinned and beaten into a pale batter, then fried in dendê oil until the outside sets deep orange. It crossed from West Africa to Bahia with enslaved Yoruba women, and it is still sold almost entirely by women in white lace who split it open and load it with shrimp and pepper paste.",
             tasteNote: "Crackling greasy crust around a soft savory bean interior, dried shrimp saltiness, and a hot pepper burn that stays.",
             eaten: "Bought late afternoon from a street tray in Salvador and eaten upright, split and stuffed to order.",
             ingredients: ["black eyed peas", "dendê oil", "dried shrimp", "onion", "vatapá paste", "malagueta pepper"],
             tags: ["street", "fried", "chili", "snack"],
             profile: Taste(heat: 3, sour: 0, sweet: 0, savour: 3, herbal: 1, rich: 3),
             palette: "ochre"),
        Dish(id: "brazil-picanha", cuisineID: "brazil",
             name: "Picanha", nativeName: "Picanha na Churrasqueira",
             summary: "The rump cap, cut with its thick fat layer left on, bent into a horseshoe over a long skewer and set above wood embers. Salt is the only seasoning anyone will defend. The cut is barely known by that name outside Brazil, and southern gaucho cooking treats getting it right as a matter of personal standing.",
             tasteNote: "A salty crackling fat cap, then beef that is soft and juicy with an open woodsmoke flavor running through every slice.",
             eaten: "Carved at the grill on a weekend, slices taken straight to the plate with cassava flour and bread.",
             ingredients: ["rump cap", "coarse salt", "cassava flour", "garlic"],
             tags: ["grilled", "feast", "street"],
             profile: Taste(heat: 0, sour: 0, sweet: 0, savour: 3, herbal: 0, rich: 3),
             palette: "char"),
        Dish(id: "brazil-tacaca", cuisineID: "brazil",
             name: "Tacacá", nativeName: "Tacacá",
             summary: "An Amazonian soup poured into a hollow gourd and drunk standing up. The base is tucupi, the yellow liquid pressed from wild cassava, which is poisonous until boiled for hours. Into it go tapioca gum, dried shrimp and jambu, a leaf that makes the mouth tingle and go numb. Nothing else in Brazil tastes remotely like it.",
             tasteNote: "Sour hot broth with slippery tapioca strands, chewy salty shrimp, and a strange electric numbness spreading across the tongue.",
             eaten: "Drunk from a gourd bowl in the late afternoon at a street stall in Belém, no spoon.",
             ingredients: ["tucupi", "tapioca gum", "dried shrimp", "jambu leaves", "chicory root", "malagueta pepper"],
             tags: ["soup", "street", "fermented"],
             profile: Taste(heat: 3, sour: 3, sweet: 0, savour: 3, herbal: 2, rich: 0),
             palette: "amber"),
        Dish(id: "brazil-tapioca", cuisineID: "brazil",
             name: "Tapioca", nativeName: "Tapioca Recheada",
             summary: "Damp cassava starch sifted onto a hot dry pan, where it fuses within a minute into a pale flexible disc with no flour, fat or egg involved. It is northeastern in origin and indigenous in method, and it has spread nationwide as the thing people eat when they want something quick that is not bread.",
             tasteNote: "Chewy and slightly rubbery with a clean neutral starch flavor, warm melted filling inside, coconut sweetness at the edges.",
             eaten: "Made to order for breakfast at a market stall, folded in half, eaten with the hands.",
             ingredients: ["cassava starch", "grated coconut", "condensed milk", "queijo coalho", "butter"],
             tags: ["breakfast", "vegetarian", "street"],
             profile: Taste(heat: 0, sour: 0, sweet: 2, savour: 1, herbal: 0, rich: 1),
             palette: "cream"),
        Dish(id: "brazil-brigadeiro", cuisineID: "brazil",
             name: "Brigadeiro", nativeName: "Brigadeiro",
             summary: "Condensed milk, cocoa and butter stirred over heat until the mixture pulls away from the pan, then cooled, rolled and covered in chocolate sprinkles. It was invented in the 1940s around a political campaign and named for the candidate. It is now the fixed requirement of every Brazilian birthday party, adult ones included.",
             tasteNote: "Dense fudgy chew that clings to the teeth, heavy milk sweetness, mild cocoa bitterness, and a crunch of sprinkles outside.",
             eaten: "Picked off a party tray in a paper cup, one bite each, at birthdays and celebrations.",
             ingredients: ["condensed milk", "cocoa powder", "butter", "chocolate sprinkles"],
             tags: ["sweet", "snack", "feast", "dairy"],
             profile: Taste(heat: 0, sour: 0, sweet: 3, savour: 0, herbal: 0, rich: 3),
             palette: "plum"),
    ]

    static let dishes: [Dish] = dishes_mexico + dishes_peru + dishes_brazil
}
