import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesSoutheastAsia {

    private static let recipes_thailand: [Recipe] = [
        Recipe(dishID: "thailand-padthai", serves: 2, prepMinutes: 25, cookMinutes: 10, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "6 oz", item: "dried flat rice noodles"),
                   RecipeIngredient(amount: "3 tbsp", item: "tamarind paste (or 2 tbsp lime juice plus 1 tsp brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "palm sugar (or light brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "8", item: "medium shrimp, peeled (or diced firm tofu)"),
                   RecipeIngredient(amount: "1 tbsp", item: "dried shrimp, chopped (optional)"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 cup", item: "bean sprouts"),
                   RecipeIngredient(amount: "3", item: "scallions, cut in 2-inch lengths"),
                   RecipeIngredient(amount: "1/4 cup", item: "roasted peanuts, crushed"),
                   RecipeIngredient(amount: "1", item: "lime, in wedges"),
               ],
               steps: [
                   "Soak the rice noodles in warm tap water for 20 to 30 minutes until pliable but still firm at the center, then drain them well and set them next to the stove.",
                   "Stir the tamarind paste, palm sugar, and fish sauce together in a small bowl until the sugar dissolves, mashing any lumps against the side with a spoon.",
                   "Heat 2 tablespoons of oil in your widest skillet over high heat until shimmering, then sear the shrimp and dried shrimp for about a minute per side and push them to the edge.",
                   "Add the remaining oil, crack in the eggs, and scramble them roughly for 30 seconds, breaking them into ragged pieces before they set completely.",
                   "Add the drained noodles and the sauce and toss constantly with tongs for 2 to 3 minutes, letting the noodles sizzle, absorb, and soften without going mushy.",
                   "Throw in the bean sprouts and scallions, toss for 30 seconds more so they barely wilt, and pull the pan off the heat while they still crunch.",
                   "Divide between two plates, shower with crushed peanuts, and serve with lime wedges and chili flakes so each eater adjusts the balance at the table.",
               ],
               note: "Crowding the pan steams the noodles instead of frying them. Cook one portion at a time in a truly hot skillet, or the dish turns gluey.",
               shortcut: "Bottled pad thai sauce saves mixing tamarind and palm sugar, but it runs sweeter and flatter, so add extra lime at the end."),
        Recipe(dishID: "thailand-tomyum", serves: 4, prepMinutes: 15, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "large shrimp, shell-on"),
                   RecipeIngredient(amount: "6 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "3 stalks", item: "lemongrass"),
                   RecipeIngredient(amount: "2-inch piece", item: "galangal (or fresh ginger)"),
                   RecipeIngredient(amount: "6", item: "kaffir lime leaves (or strips of lime zest)"),
                   RecipeIngredient(amount: "4", item: "bird's eye chilies (or 2 serranos)"),
                   RecipeIngredient(amount: "8 oz", item: "white mushrooms, halved"),
                   RecipeIngredient(amount: "3 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "1/4 cup", item: "lime juice"),
                   RecipeIngredient(amount: "1 tbsp", item: "thai chili paste in oil (nam prik pao), optional"),
                   RecipeIngredient(amount: "a handful", item: "cilantro leaves"),
               ],
               steps: [
                   "Peel the shrimp and keep the shells. Simmer the shells in the stock for 10 minutes, then scoop them out; the broth should smell distinctly sweet and briny.",
                   "Smash the lemongrass stalks with the back of a knife, slice the galangal into thin coins, and tear the lime leaves once so they release their oil.",
                   "Drop the lemongrass, galangal, lime leaves, and lightly crushed chilies into the broth and simmer for 5 minutes. These stay in the bowl but are not eaten.",
                   "Add the mushrooms and cook for 3 minutes, until they have darkened slightly and taken on the broth's aroma.",
                   "Add the shrimp and simmer gently for about 2 minutes, just until they curl and turn opaque; pull the pot off the heat immediately.",
                   "Stir in the fish sauce and chili paste, then the lime juice last, off the heat, tasting until sour and hot arrive at the same instant.",
                   "Ladle into small bowls, top with cilantro, and warn everyone about the aromatics floating in the broth.",
               ],
               note: "Lime juice added over heat turns dull and bitter. Season the finished soup off the stove, and it should taste slightly too intense on its own; it is meant for rice.",
               shortcut: "Tom yum paste from a jar replaces the aromatics in one spoonful, but the broth loses its fresh citrus edge; a squeeze of extra lime helps."),
        Recipe(dishID: "thailand-somtam", serves: 2, prepMinutes: 25, cookMinutes: 0, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "green papaya, shredded (or shredded unripe mango or kohlrabi)"),
                   RecipeIngredient(amount: "1/2 cup", item: "long beans or green beans, in 1-inch pieces"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic"),
                   RecipeIngredient(amount: "2", item: "bird's eye chilies (or 1 serrano)"),
                   RecipeIngredient(amount: "1 tbsp", item: "dried shrimp"),
                   RecipeIngredient(amount: "1 tbsp", item: "palm sugar (or brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "3 tbsp", item: "lime juice"),
                   RecipeIngredient(amount: "8", item: "cherry tomatoes, halved"),
                   RecipeIngredient(amount: "2 tbsp", item: "roasted peanuts"),
               ],
               steps: [
                   "Peel the papaya, then shred it into long thin threads with a julienne peeler or the large holes of a box grater. Soak the threads in ice water while you work.",
                   "In a large mortar (or a sturdy bowl with the end of a rolling pin), pound the garlic, chilies, and dried shrimp into a rough, wet paste.",
                   "Add the palm sugar and pound until it dissolves, then work in the fish sauce and lime juice, scraping the paste up from the bottom.",
                   "Add the green beans and bruise them with a few firm strikes so they crack but stay crunchy.",
                   "Drain the papaya well, add it with the tomatoes, and alternate light pounding with lifting and folding using a spoon, about 2 minutes, so every thread gets coated and lightly bruised.",
                   "Taste a full strand; it should hit sour, salty, sweet, then heat, in roughly that order. Adjust with lime, fish sauce, or sugar and pound briefly again.",
                   "Pile onto plates, scatter the peanuts over, and serve immediately with sticky rice or grilled chicken while everything still crunches.",
               ],
               note: "The pounding matters more than the recipe. Bruised threads drink the dressing; cut ones just sit in it. Fold and strike, taste often, and serve within minutes.",
               shortcut: "Shredded green cabbage or carrot stands in for papaya at most supermarkets; the salad turns sweeter and softer but keeps its point."),
        Recipe(dishID: "thailand-massaman", serves: 6, prepMinutes: 25, cookMinutes: 150, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "beef chuck or shin, in 2-inch chunks"),
                   RecipeIngredient(amount: "4 tbsp", item: "massaman curry paste"),
                   RecipeIngredient(amount: "2 cans (13.5 oz each)", item: "coconut milk"),
                   RecipeIngredient(amount: "1 lb", item: "yukon gold potatoes, in large chunks"),
                   RecipeIngredient(amount: "1", item: "yellow onion, in wedges"),
                   RecipeIngredient(amount: "1/2 cup", item: "roasted peanuts"),
                   RecipeIngredient(amount: "2 tbsp", item: "tamarind paste (or 1 tbsp lime juice plus 1 tsp brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "palm sugar (or brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "1", item: "cinnamon stick"),
                   RecipeIngredient(amount: "3", item: "cardamom pods, lightly crushed"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
               ],
               steps: [
                   "Open one can of coconut milk without shaking it and spoon the thick cream from the top into a heavy pot with the oil over medium heat.",
                   "Fry the curry paste in the coconut cream for 3 to 5 minutes, stirring, until it darkens, smells toasty, and the oil starts to separate at the edges.",
                   "Add the beef and turn it in the paste until every piece is coated and beginning to brown at the edges, about 5 minutes.",
                   "Pour in the rest of the coconut milk, add the cinnamon and cardamom, and bring to a bare simmer. Cover partially and cook low for 90 minutes, stirring occasionally.",
                   "Add the potatoes, onion, and peanuts and simmer uncovered for 40 to 50 minutes more, until the beef yields to a spoon and the potatoes are collapsing at their corners.",
                   "Stir in the tamarind, palm sugar, and fish sauce. Simmer 10 minutes, then taste: it should land gently sweet first, salty behind, sour just at the edge.",
                   "Rest off the heat for 15 minutes before serving over jasmine rice; the sauce thickens and the spices settle into the fat.",
               ],
               note: "The paste must fry until the oil splits out before any liquid goes in. Skip that and the curry tastes raw and flat no matter how long it simmers.",
               shortcut: "A slow cooker handles steps four and five overnight on low, though the sauce comes out thinner; reduce it uncovered on the stove before seasoning."),
        Recipe(dishID: "thailand-khaosoi", serves: 4, prepMinutes: 25, cookMinutes: 35, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "fresh chinese egg noodles (or dried, cooked separately)"),
                   RecipeIngredient(amount: "1.5 lb", item: "bone-in chicken thighs"),
                   RecipeIngredient(amount: "3 tbsp", item: "red curry paste"),
                   RecipeIngredient(amount: "1 tbsp", item: "curry powder"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "2 cans (13.5 oz each)", item: "coconut milk"),
                   RecipeIngredient(amount: "2 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "2 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "palm sugar (or brown sugar)"),
                   RecipeIngredient(amount: "2 cups", item: "vegetable oil, for frying"),
                   RecipeIngredient(amount: "1/2 cup", item: "pickled mustard greens, chopped (or chopped dill pickles)"),
                   RecipeIngredient(amount: "2", item: "shallots, thinly sliced"),
                   RecipeIngredient(amount: "1", item: "lime, in wedges"),
               ],
               steps: [
                   "Set aside a quarter of the noodles. Heat the frying oil in a small saucepan to 350°F and fry that handful in two batches until golden and rigid, about 30 seconds. Drain on paper towels.",
                   "Spoon the thick cream from the top of one coconut milk can into a pot and fry the curry paste, curry powder, and turmeric in it over medium heat until fragrant and split, about 4 minutes.",
                   "Add the chicken thighs and turn them in the paste for 2 to 3 minutes so the skin picks up color and spice.",
                   "Pour in the remaining coconut milk and the stock, bring to a gentle simmer, and cook uncovered for 25 minutes, until the chicken pulls easily from the bone.",
                   "Lift out the chicken, pull the meat into large pieces, discard bones and skin, and return the meat to the broth with the fish sauce and palm sugar. Taste for salt.",
                   "Boil the remaining noodles in a separate pot of water until just tender, drain, and divide among four deep bowls.",
                   "Ladle the curry and chicken over the noodles, crown each bowl with fried noodles, and serve with pickled mustard greens, shallots, and lime on a plate alongside.",
               ],
               note: "The bowl only works if the fried noodles go on at the last second and the pickles stay on the side; sog and sweetness are the two ways khao soi dies.",
               shortcut: "Store-bought chow mein crisps stand in for the fried noodle crown and skip the hot oil, at the cost of the fresh-fried crackle."),
        Recipe(dishID: "thailand-mooping", serves: 4, prepMinutes: 20, cookMinutes: 15, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1.5 lb", item: "pork shoulder, in thin 2-inch strips"),
                   RecipeIngredient(amount: "1/2 cup", item: "coconut milk"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "cilantro stems, finely chopped"),
                   RecipeIngredient(amount: "1 tsp", item: "ground white pepper"),
                   RecipeIngredient(amount: "2 tbsp", item: "palm sugar (or brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "light soy sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "12", item: "bamboo skewers, soaked in water"),
               ],
               steps: [
                   "Pound or mince the garlic, cilantro stems, and white pepper into a rough paste; this stands in for the garlic root Thai vendors use.",
                   "Whisk the paste with the coconut milk, palm sugar, soy sauce, fish sauce, and oil until the sugar dissolves into a thin marinade.",
                   "Toss the pork strips in the marinade, cover, and refrigerate at least 4 hours, ideally overnight; the coconut milk needs time to soften and season the meat.",
                   "Thread the strips onto soaked skewers in a flat ribbon, folding each piece once or twice so it hugs the stick without bunching.",
                   "Grill over medium charcoal or a grill pan on medium-high, turning every 2 minutes, until the edges char in spots and the fat glistens, 8 to 10 minutes total.",
                   "Brush with leftover marinade during the first half of grilling only, then let the final turns dry the glaze into a lacquer.",
                   "Rest the skewers 2 minutes and serve with sticky rice, eaten straight from the stick.",
               ],
               note: "The sugar chars fast, so keep the heat moderate and the skewers moving; blackened outside with chewy raw center is the standard beginner failure.",
               shortcut: "Pork loin cooks faster and slices thinner than shoulder, but it dries out on the grill; if you swap it, pull the skewers a minute early."),
        Recipe(dishID: "thailand-hormok", serves: 4, prepMinutes: 30, cookMinutes: 20, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "white fish fillets (cod or tilapia), in small pieces"),
                   RecipeIngredient(amount: "3 tbsp", item: "red curry paste"),
                   RecipeIngredient(amount: "1 cup", item: "coconut cream"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "1 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "2 tsp", item: "palm sugar (or brown sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "rice flour (or cornstarch)"),
                   RecipeIngredient(amount: "4", item: "kaffir lime leaves, sliced hair-thin (or lime zest)"),
                   RecipeIngredient(amount: "1 cup", item: "thai basil leaves (or regular basil)"),
                   RecipeIngredient(amount: "1 cup", item: "napa cabbage, shredded"),
                   RecipeIngredient(amount: "8", item: "foil muffin cups or ramekins (in place of banana leaf cups)"),
               ],
               steps: [
                   "Whisk the curry paste into 3/4 cup of the coconut cream in a large bowl until smooth, then whisk in the eggs, fish sauce, palm sugar, and rice flour.",
                   "Fold in the fish pieces and stir slowly in one direction for 3 to 4 minutes; the mixture should thicken noticeably and turn glossy as the fish releases protein.",
                   "Stir in half the sliced lime leaves. Line each ramekin with a few basil leaves and a pinch of shredded cabbage; they steam into a soft bed under the custard.",
                   "Divide the fish mixture among the cups, filling them three-quarters full, and rap each one once on the counter to settle air pockets.",
                   "Set the cups in a steamer over simmering water, cover, and steam 15 to 18 minutes, until the tops are set but the centers still tremble when nudged.",
                   "Warm the remaining coconut cream with a pinch of salt and spoon a little over each cup, then finish with the rest of the lime leaf threads.",
                   "Rest 5 minutes before serving with rice; the custard firms just enough to spoon cleanly while keeping its wobble.",
               ],
               note: "The stir in one direction is not superstition; it builds the bind that lets the custard set soft. Rushing it gives you curry scrambled with fish.",
               shortcut: "Skipping the steamer for a 300°F water bath in the oven works fine, about 25 minutes, though you lose the faint aroma the steam carries."),
        Recipe(dishID: "thailand-mangosticky", serves: 4, prepMinutes: 10, cookMinutes: 35, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "glutinous rice (labeled sweet or sticky rice)"),
                   RecipeIngredient(amount: "1 can (13.5 oz)", item: "coconut cream"),
                   RecipeIngredient(amount: "1/3 cup", item: "palm sugar (or granulated sugar)"),
                   RecipeIngredient(amount: "3/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 tsp", item: "cornstarch"),
                   RecipeIngredient(amount: "2", item: "ripe mangoes (ataulfo or champagne, soft to the thumb)"),
                   RecipeIngredient(amount: "1 tbsp", item: "toasted sesame seeds or crisp mung beans"),
               ],
               steps: [
                   "Rinse the rice until the water runs nearly clear, then soak it in cold water at least 4 hours or overnight; unsoaked grains never soften properly in steam.",
                   "Drain the rice and steam it in a cheesecloth-lined steamer basket over simmering water for 25 to 30 minutes, until the grains are translucent and chewy with no chalky core.",
                   "While the rice steams, warm 1 cup of coconut cream with the sugar and 1/2 teaspoon of salt until just dissolved; do not let it boil.",
                   "Scrape the hot rice into a bowl, pour the sweetened coconut cream over, stir once, and cover. Let it sit 20 minutes; the rice drinks the cream and turns glossy.",
                   "Simmer the remaining coconut cream with the last of the salt and the cornstarch, whisking until it thickens into a pourable salted sauce.",
                   "Peel the mangoes and slice the cheeks off the pit, then cut into thick slices. Cold fruit against warm rice is part of the dish.",
                   "Mound the rice beside the mango, pour the salted sauce over the rice, and finish with sesame seeds or crisp mung beans.",
               ],
               note: "The rice must still be hot when the sweet cream goes on, and the salt is not optional; it is what keeps the dish from tasting like plain dessert rice.",
               shortcut: "Microwaving the soaked rice covered with a splash of water in three 3-minute bursts replaces the steamer, with slightly less even chew."),
    ]

    private static let recipes_vietnam: [Recipe] = [
        Recipe(dishID: "vietnam-pho", serves: 4, prepMinutes: 30, cookMinutes: 240, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "4 lb", item: "beef bones (knuckle and marrow)"),
                   RecipeIngredient(amount: "1 lb", item: "beef chuck, in one piece"),
                   RecipeIngredient(amount: "8 oz", item: "beef sirloin, sliced paper thin"),
                   RecipeIngredient(amount: "1", item: "large yellow onion, halved"),
                   RecipeIngredient(amount: "4-inch piece", item: "fresh ginger, halved lengthwise"),
                   RecipeIngredient(amount: "3", item: "star anise"),
                   RecipeIngredient(amount: "1", item: "cinnamon stick (for cassia bark)"),
                   RecipeIngredient(amount: "4", item: "whole cloves"),
                   RecipeIngredient(amount: "1 tbsp", item: "coriander seeds"),
                   RecipeIngredient(amount: "3 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "rock sugar (or granulated sugar)"),
                   RecipeIngredient(amount: "1 lb", item: "dried flat rice noodles (banh pho)"),
                   RecipeIngredient(amount: "4", item: "scallions, thinly sliced"),
                   RecipeIngredient(amount: "1 plate", item: "thai basil, bean sprouts, lime wedges, and sliced jalapeño"),
               ],
               steps: [
                   "Cover the bones with cold water, boil hard for 5 minutes, then drain, rinse the bones, and scrub out the pot. This parboil is why the final broth stays clear.",
                   "Char the onion and ginger cut-side down in a dry skillet (or under the broiler) until blackened in patches, about 8 minutes, then scrape off the loosest burnt skin.",
                   "Return the bones to the pot with the chuck and 5 quarts of cold water. Bring to a bare simmer and skim the gray foam for the first 20 minutes.",
                   "Toast the star anise, cinnamon, cloves, and coriander in a dry pan for 2 minutes until fragrant, then add them to the pot with the charred onion and ginger.",
                   "Simmer uncovered at a lazy bubble for 3 hours, skimming occasionally and never boiling. Pull the chuck out after 90 minutes, when tender, and slice it thin once cool.",
                   "Strain the broth through a fine sieve, season with fish sauce and rock sugar, and taste; it should be clean, faintly sweet, and just short of salty enough alone.",
                   "Soak the noodles per the package, then blanch 10 seconds in boiling water and divide among bowls with both meats, the raw sirloin on top.",
                   "Bring the broth to a rolling boil and ladle it directly over the raw beef so it cooks in the bowl. Top with scallions and serve with the herb plate.",
               ],
               note: "Clarity is the whole exam. Parboil the bones, keep the simmer barely moving, and skim early; a boiled broth turns cloudy and greasy and nothing later fixes it.",
               shortcut: "Quality boxed beef broth plus the charred aromatics and toasted spices, simmered 30 minutes, makes an honest weeknight bowl that lacks only the body of real bones."),
        Recipe(dishID: "vietnam-banhmi", serves: 2, prepMinutes: 25, cookMinutes: 5, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2", item: "light, thin-crusted baguette rolls (french rolls work)"),
                   RecipeIngredient(amount: "1 cup", item: "carrot, cut in matchsticks"),
                   RecipeIngredient(amount: "1 cup", item: "daikon radish, cut in matchsticks (or more carrot)"),
                   RecipeIngredient(amount: "1/4 cup", item: "rice vinegar"),
                   RecipeIngredient(amount: "2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "3 tbsp", item: "pork or chicken liver pate"),
                   RecipeIngredient(amount: "3 tbsp", item: "mayonnaise"),
                   RecipeIngredient(amount: "6 oz", item: "cold cuts (ham, roast pork, or vietnamese cha lua)"),
                   RecipeIngredient(amount: "1/2", item: "cucumber, in long thin planks"),
                   RecipeIngredient(amount: "1 handful", item: "cilantro sprigs"),
                   RecipeIngredient(amount: "1", item: "jalapeño, sliced in thin rounds"),
                   RecipeIngredient(amount: "1 tbsp", item: "maggi seasoning (or soy sauce)"),
               ],
               steps: [
                   "Toss the carrot and daikon with the vinegar, sugar, and salt in a bowl and let them sit at least 20 minutes, squeezing once, until floppy and sharp-sweet.",
                   "Warm the rolls in a 350°F oven for 4 to 5 minutes until the crust crackles when squeezed; a soft roll ruins the whole architecture.",
                   "Split each roll along the side without cutting through, and pull out a little of the crumb to make room for the filling.",
                   "Spread pate on one face and mayonnaise on the other, all the way to the ends so no bite goes dry.",
                   "Layer in the cold cuts, then the cucumber planks, then a generous tangle of the drained pickles.",
                   "Tuck in whole cilantro sprigs stems and all, add jalapeño rounds to taste, and shake a few drops of maggi over the filling.",
                   "Press the sandwich gently closed for a few seconds so the layers hold together, and eat within the hour while the crust still shatters.",
               ],
               note: "Everything negotiable but the bread. It must be light and crisp enough to compress in one hand; a dense chewy baguette makes a different, worse sandwich.",
               shortcut: "Deli ham and store-bought pickled jalapeño carrots get you 80 percent of the way with zero prep, losing mainly the daikon funk and fresh crunch."),
        Recipe(dishID: "vietnam-buncha", serves: 4, prepMinutes: 30, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "ground pork"),
                   RecipeIngredient(amount: "8 oz", item: "pork belly, sliced thin (or thick-cut bacon, unsmoked if you can find it)"),
                   RecipeIngredient(amount: "4", item: "shallots, minced"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "5 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "4 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "3 tbsp", item: "rice vinegar"),
                   RecipeIngredient(amount: "2 tbsp", item: "lime juice"),
                   RecipeIngredient(amount: "1 cup", item: "green papaya or kohlrabi, in thin bite-size squares"),
                   RecipeIngredient(amount: "12 oz", item: "rice vermicelli"),
                   RecipeIngredient(amount: "1 large plate", item: "lettuce, mint, cilantro, and perilla if you can find it"),
               ],
               steps: [
                   "Mix the ground pork with half the shallots, half the garlic, 2 tablespoons fish sauce, 1 tablespoon sugar, and the pepper. Form into flat patties the size of a half-dollar.",
                   "Toss the pork belly slices with the remaining shallots, garlic, 1 tablespoon fish sauce, and 1 tablespoon sugar. Let both meats sit 20 minutes.",
                   "Make the bowl sauce: warm 1 cup water with the remaining fish sauce and sugar until dissolved, then add the vinegar and lime juice. It should taste like mild, drinkable seasoning, not dip-strength.",
                   "Drop the papaya or kohlrabi squares into the sauce and let them float and pickle while you cook.",
                   "Cook the vermicelli per the package, rinse under cold water until fully cool, and drain into loose nests on a platter.",
                   "Grill or broil the patties and belly slices on high, turning once, until both carry real char at the edges, 8 to 12 minutes; the smoke is a main ingredient.",
                   "Divide the warm sauce among four bowls, drop the hot meats straight in, and serve with the noodles and herb platter alongside, letting each eater dip as they go.",
               ],
               note: "The sauce is a warm bath, not a dressing; if it tastes strong on its own it will be brutal by the last bite. Dilute until it seems almost too gentle.",
               shortcut: "A broiler on high with the rack close mimics the charcoal char in one pan, though you lose the smoke that drifts through the real thing."),
        Recipe(dishID: "vietnam-goicuon", serves: 4, prepMinutes: 40, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "12 sheets", item: "rice paper (8-inch rounds)"),
                   RecipeIngredient(amount: "12", item: "medium shrimp"),
                   RecipeIngredient(amount: "8 oz", item: "pork belly or pork shoulder, in one piece"),
                   RecipeIngredient(amount: "4 oz", item: "rice vermicelli"),
                   RecipeIngredient(amount: "12 leaves", item: "soft lettuce (butter or red leaf)"),
                   RecipeIngredient(amount: "1 bunch", item: "mint"),
                   RecipeIngredient(amount: "1 bunch", item: "cilantro (plus perilla if your store has it)"),
                   RecipeIngredient(amount: "1/3 cup", item: "hoisin sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "creamy peanut butter"),
                   RecipeIngredient(amount: "1 tsp", item: "chili garlic sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "roasted peanuts, chopped"),
               ],
               steps: [
                   "Simmer the pork in salted water for 25 to 30 minutes until just cooked through, then cool it in the liquid and slice it into thin, wide pieces.",
                   "Poach the shrimp in the same water for 2 minutes until pink, then peel them and slice each one in half lengthwise along the back.",
                   "Cook the vermicelli per the package, rinse cold, and drain very well; wet noodles make rolls that slide apart.",
                   "Whisk the hoisin, peanut butter, chili garlic sauce, and 3 tablespoons warm water into a thick dipping sauce, and top it with chopped peanuts.",
                   "Dip one rice paper sheet in warm water for 2 to 3 seconds only, until barely flexible, and lay it on a damp cutting board; it keeps softening as you build.",
                   "Lay a lettuce leaf on the lower third, then noodles, pork, and herbs. Place three shrimp halves cut-side up above the pile so they show through the finished roll.",
                   "Fold the bottom edge over the filling, fold in the sides, and roll upward firmly, tucking as you go. Repeat, keeping finished rolls apart so they do not stick.",
                   "Serve within an hour at room temperature with the peanut sauce; refrigeration turns the wrappers stiff and chewy.",
               ],
               note: "Under-soak the paper. It should still feel slightly stiff off the water; by the time you finish arranging the filling it will be perfectly soft and tacky.",
               shortcut: "Rotisserie chicken replaces the poached pork and shrimp entirely; the rolls lose their cool sweetness but come together in fifteen minutes."),
        Recipe(dishID: "vietnam-comtam", serves: 2, prepMinutes: 25, cookMinutes: 25, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "broken rice (or jasmine rice pulsed twice in a blender)"),
                   RecipeIngredient(amount: "2", item: "bone-in pork chops, pounded 1/2 inch thin"),
                   RecipeIngredient(amount: "2 tbsp", item: "fish sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1 tbsp", item: "honey"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 stalk", item: "lemongrass, tender core minced (or 1 tsp lemongrass paste)"),
                   RecipeIngredient(amount: "3", item: "scallions, sliced"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "lime juice"),
                   RecipeIngredient(amount: "1", item: "bird's eye chili or half a jalapeño, minced"),
                   RecipeIngredient(amount: "1 cup", item: "cucumber slices and pickled carrot, to serve"),
               ],
               steps: [
                   "Marinate the chops in 1 tablespoon fish sauce, 1 tablespoon sugar, the honey, garlic, and lemongrass for at least 20 minutes while you cook the rice.",
                   "Rinse the broken rice once and cook it with 1 1/4 cups water, covered, on the lowest heat for 15 minutes, then rest it 10 minutes off the heat.",
                   "Make nuoc cham: dissolve the remaining sugar in 1/4 cup warm water, then add the remaining fish sauce, the lime juice, and the chili. It should taste bright, salty, and light.",
                   "Warm the oil in a small pan until it just shimmers, pour it over the sliced scallions in a heatproof bowl, and add a pinch of salt; this is the scallion oil.",
                   "Grill the chops over high heat or sear in a heavy skillet, 3 to 4 minutes per side, until the marinade caramelizes into dark, sticky edges without burning outright.",
                   "Rest the meat for 5 minutes while you fluff the rice with a fork; the grains should be small, dry, and separate.",
                   "Plate a mound of rice with a chop leaning on it, spoon scallion oil over the rice, add cucumber and pickles, and pour nuoc cham over everything at the table.",
               ],
               note: "The chop should be thin enough to cook through in the time the sugar takes to char; a thick chop forces you to choose between burnt and raw.",
               shortcut: "Plain jasmine rice is fine if you skip the blender pulse; you lose the distinct small-grain texture but nothing about the flavor."),
        Recipe(dishID: "vietnam-banhxeo", serves: 4, prepMinutes: 20, cookMinutes: 40, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "rice flour"),
                   RecipeIngredient(amount: "1/2 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "1 cup", item: "coconut milk"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "cold water (or club soda for a lighter shell)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "8 oz", item: "pork belly or shoulder, sliced very thin"),
                   RecipeIngredient(amount: "8 oz", item: "small shrimp, peeled"),
                   RecipeIngredient(amount: "3 cups", item: "bean sprouts"),
                   RecipeIngredient(amount: "1/2", item: "yellow onion, thinly sliced"),
                   RecipeIngredient(amount: "5 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 head", item: "soft lettuce plus mint and cilantro, to wrap"),
                   RecipeIngredient(amount: "1 cup", item: "nuoc cham (fish sauce, lime, sugar, water, chili)"),
               ],
               steps: [
                   "Whisk the rice flour, turmeric, salt, coconut milk, and water into a thin batter the texture of heavy cream, and rest it 15 minutes while you prep the fillings.",
                   "Heat 1 tablespoon of oil in a 10-inch nonstick skillet over medium-high until it shimmers; the pan must hiss loudly when batter hits or the shell will be pale and soft.",
                   "Sear a quarter of the pork and shrimp in the pan for about a minute, spreading them across one half.",
                   "Stir the batter, then pour in a thin ladleful while tilting and swirling the pan so it coats the whole surface in a thin, lacy sheet; you should hear the xeo hiss.",
                   "Scatter a handful of bean sprouts and onion over one side, cover for 1 minute to steam them, then uncover and cook 2 to 3 minutes more until the edges brown and lift.",
                   "Drizzle a little oil around the rim, slide a spatula under the empty half, and fold the crepe over the filling. Cook another minute until the underside is deeply golden and brittle.",
                   "Slide onto a plate and repeat, adjusting heat and oil as you go; the first one is a rehearsal, like the first pancake.",
                   "Serve immediately, torn into pieces, wrapped in lettuce with herbs, and dipped in nuoc cham.",
               ],
               note: "Thin batter, hot pan, enough oil: all three or the shell bends instead of shattering. Pour off extra batter rather than let a thick crepe steam itself soft.",
               shortcut: "Boxed banh xeo flour from an asian aisle already has the turmeric and rice flour balanced; just add water and coconut milk per the bag."),
        Recipe(dishID: "vietnam-dauhu", serves: 4, prepMinutes: 10, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "14 oz", item: "firm tofu"),
                   RecipeIngredient(amount: "4", item: "ripe tomatoes, in wedges (or one 14 oz can of whole tomatoes)"),
                   RecipeIngredient(amount: "3", item: "scallions, whites and greens separated, sliced"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "fish sauce (or soy sauce for a vegetarian pot)"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1/4 tsp", item: "ground white pepper"),
                   RecipeIngredient(amount: "4 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Press the tofu between paper towels under a plate for 10 minutes, then cut it into 1-inch cubes and pat them dry again; wet tofu spits and never crisps.",
                   "Heat the oil in a nonstick skillet over medium-high and fry the tofu in a single layer, turning every few minutes, until most sides are golden and puffed, 10 to 12 minutes. Set aside.",
                   "Pour off all but a tablespoon of oil, drop in the garlic and scallion whites, and stir for 30 seconds until fragrant but not browned.",
                   "Add the tomatoes and salt and cook over medium heat, mashing gently with the spoon, until they collapse into a loose, glossy sauce, 6 to 8 minutes.",
                   "Stir in the fish sauce, sugar, and 1/4 cup water, then return the tofu and simmer for 4 to 5 minutes so the fried skin drinks up the tomato.",
                   "Taste and adjust; it should be gently salty and faintly sweet, with the tomato reading brighter than rich.",
                   "Finish with the scallion greens and white pepper and serve hot over rice, spooning extra sauce over the grains.",
               ],
               note: "Let the tomatoes truly collapse before the tofu goes back in; a watery, chunky sauce slides off the cubes instead of soaking into them.",
               shortcut: "Pre-fried tofu puffs from an asian grocery skip the frying entirely and soak up even more sauce, though the insides are airier than fresh-fried."),
        Recipe(dishID: "vietnam-chetroinuoc", serves: 6, prepMinutes: 50, cookMinutes: 30, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1/2 cup", item: "dried split mung beans (yellow, skinless)"),
                   RecipeIngredient(amount: "5 tbsp", item: "sugar, divided"),
                   RecipeIngredient(amount: "a pinch", item: "salt"),
                   RecipeIngredient(amount: "2 cups", item: "glutinous rice flour"),
                   RecipeIngredient(amount: "1 cup", item: "warm water, plus more as needed"),
                   RecipeIngredient(amount: "1/2 cup", item: "palm sugar (or dark brown sugar)"),
                   RecipeIngredient(amount: "3-inch piece", item: "fresh ginger, sliced into coins"),
                   RecipeIngredient(amount: "3/4 cup", item: "coconut cream"),
                   RecipeIngredient(amount: "1 tsp", item: "cornstarch"),
                   RecipeIngredient(amount: "1 tbsp", item: "toasted sesame seeds"),
               ],
               steps: [
                   "Soak the mung beans 1 hour, then simmer in water to cover until completely soft, about 20 minutes. Drain and mash with 2 tablespoons sugar and the salt into a thick paste.",
                   "Roll the mung bean paste into 12 balls the size of a large marble and set them aside; chill them briefly if they feel sticky.",
                   "Knead the glutinous rice flour with warm water, adding it gradually, until you have a smooth dough like soft playdough that does not crack when pressed. Rest 15 minutes under a towel.",
                   "Simmer the palm sugar, remaining sugar, ginger coins, and 4 cups water for 10 minutes into a thin amber syrup, and keep it hot on the back burner.",
                   "Flatten a golf-ball piece of dough into a disc, cup it in your palm, seal it around a mung bean ball with no air trapped, and roll smooth. Repeat for all twelve.",
                   "Boil the balls in a wide pot of water; they are done about a minute after they float, when the skin turns from chalky to translucent. Lift them straight into the ginger syrup.",
                   "Warm the coconut cream with the cornstarch and a pinch of salt, whisking until it barely thickens.",
                   "Serve three balls per glass, warm, with syrup ladled over, a spoonful of coconut cream, and a scatter of sesame seeds.",
               ],
               note: "Seal with no trapped air and no cracks; a pinhole lets syrup in and the ball splits in the pot. The dough should feel like an earlobe, soft but springy.",
               shortcut: "Canned sweetened red bean paste replaces the mung bean filling outright, trading the traditional flavor for zero soaking and mashing."),
    ]

    private static let recipes_indonesia: [Recipe] = [
        Recipe(dishID: "indonesia-nasigoreng", serves: 2, prepMinutes: 15, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "3 cups", item: "cold day-old cooked rice"),
                   RecipeIngredient(amount: "3 tbsp", item: "kecap manis (or 2 tbsp soy sauce mixed with 1 tbsp molasses)"),
                   RecipeIngredient(amount: "3", item: "shallots, roughly chopped"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic"),
                   RecipeIngredient(amount: "2", item: "bird's eye chilies (or 1 tsp sambal oelek)"),
                   RecipeIngredient(amount: "1 tsp", item: "shrimp paste (or 2 minced anchovy fillets)"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "cucumber, sliced, plus prawn crackers to serve"),
               ],
               steps: [
                   "Break the cold rice apart with wet fingers until no clumps remain; clumped rice steams while loose rice fries, and the difference is the whole dish.",
                   "Pound or blitz the shallots, garlic, chilies, and shrimp paste into a rough paste.",
                   "Heat 2 tablespoons of oil in a wok or large skillet over high heat and fry the paste, stirring, for about 2 minutes until it darkens and smells toasted rather than raw.",
                   "Add the rice and toss hard, scraping the pan bottom, for 2 to 3 minutes; let it sit untouched in 20-second stretches so patches of it catch and crisp.",
                   "Drizzle the kecap manis around the edge of the pan so it sizzles and caramelizes on contact, then toss until every grain is stained mahogany. Season with salt.",
                   "Push the rice aside, add the last of the oil, and fry the eggs sunny side up until the edges frill and brown but the yolks stay loose.",
                   "Plate the rice with an egg on top, cucumber slices leaning on the side, and prawn crackers for scooping.",
               ],
               note: "Cold, dry, day-old rice is non-negotiable. Fresh rice turns to porridge in the pan; even a few hours uncovered in the fridge makes the difference.",
               shortcut: "Sambal oelek from a jar replaces the pounded paste in one spoonful; you lose the shallot sweetness, so fry a little extra sliced shallot first."),
        Recipe(dishID: "indonesia-rendang", serves: 6, prepMinutes: 30, cookMinutes: 240, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "3 lb", item: "beef chuck, in 2-inch cubes"),
                   RecipeIngredient(amount: "2 cans (13.5 oz each)", item: "coconut milk"),
                   RecipeIngredient(amount: "8", item: "shallots"),
                   RecipeIngredient(amount: "6 cloves", item: "garlic"),
                   RecipeIngredient(amount: "6", item: "dried red chilies, soaked (plus more for real minang heat)"),
                   RecipeIngredient(amount: "2-inch piece", item: "galangal (or ginger)"),
                   RecipeIngredient(amount: "2-inch piece", item: "fresh ginger"),
                   RecipeIngredient(amount: "1 tsp", item: "ground turmeric (standing in for turmeric leaf)"),
                   RecipeIngredient(amount: "3 stalks", item: "lemongrass, bruised"),
                   RecipeIngredient(amount: "4", item: "kaffir lime leaves (or strips of lime zest)"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "brown sugar"),
               ],
               steps: [
                   "Blend the shallots, garlic, soaked chilies, galangal, ginger, and turmeric with a splash of water into a smooth paste; this is your bumbu.",
                   "Combine the beef, bumbu, coconut milk, lemongrass, lime leaves, salt, and sugar in a wide heavy pot; wide matters, because the liquid has to evaporate.",
                   "Bring to a boil, then drop to an active simmer, uncovered, stirring every 15 minutes or so as the liquid slowly reduces, about 2 hours.",
                   "When the sauce thickens to a heavy gravy, lower the heat and stir every 5 to 10 minutes; the coconut milk will visibly split and the oil will pool at the edges.",
                   "Keep cooking in the released oil, scraping the bottom constantly now, as the paste darkens from rust to deep brown and coats the beef in a dry crust, 45 to 60 minutes more.",
                   "Stop at the color of dark chocolate, when almost no free liquid remains and the beef shreds under a spoon. Fish out the lemongrass and lime leaves.",
                   "Rest at least 30 minutes, or overnight in the fridge; rendang is better the next day, reheated gently in its own oil, and served with plain rice.",
               ],
               note: "The dish happens in the last hour, after the coconut milk splits; walking away then means scorched paste. Before the split you barely need to watch it.",
               shortcut: "Stopping at the wet gravy stage, around hour two, gives you kalio, the saucier cousin, and it is legitimately good; just do not call it dry rendang."),
        Recipe(dishID: "indonesia-sateayam", serves: 4, prepMinutes: 30, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1.5 lb", item: "boneless chicken thighs, in 3/4-inch pieces"),
                   RecipeIngredient(amount: "5 tbsp", item: "kecap manis (or soy sauce mixed with molasses), divided"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "3/4 cup", item: "roasted unsalted peanuts (or 1/2 cup natural peanut butter)"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic"),
                   RecipeIngredient(amount: "2", item: "candlenuts (or macadamias or 3 cashews)"),
                   RecipeIngredient(amount: "1 tsp", item: "sambal oelek or chili garlic sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "brown sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1", item: "lime"),
                   RecipeIngredient(amount: "2", item: "shallots, sliced paper thin"),
                   RecipeIngredient(amount: "16", item: "bamboo skewers, soaked"),
               ],
               steps: [
                   "Toss the chicken with 2 tablespoons of kecap manis and the oil and let it sit while you make the sauce.",
                   "Grind the peanuts, garlic, and candlenuts in a food processor until mostly smooth with a little grit remaining.",
                   "Simmer the ground peanuts with 1 cup water, the sambal, brown sugar, salt, and 2 tablespoons kecap manis, stirring, until thick enough to coat a spoon, 5 to 8 minutes. Add water if it tightens.",
                   "Thread the chicken snugly onto the soaked skewers, five or six pieces each, leaving a bare handle at the blunt end.",
                   "Grill over hot charcoal or a grill pan on high, turning every 2 minutes, until charred at the corners and just cooked through, 8 to 10 minutes.",
                   "Brush the skewers with the last tablespoon of kecap manis during the final turn so it blisters into a sweet lacquer.",
                   "Pile the skewers on a platter, pour the warm peanut sauce generously over the middle, and finish with raw shallot slices and a hard squeeze of lime.",
               ],
               note: "Thigh, not breast, and real char; the sweet soy needs bitter charred edges to push against, or the whole plate collapses into candy.",
               shortcut: "Natural peanut butter replaces the ground peanuts and cuts the sauce to five minutes; it comes out smoother and slightly less toasty."),
        Recipe(dishID: "indonesia-gadogado", serves: 4, prepMinutes: 30, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "8 oz", item: "tempeh (or extra-firm tofu), in slabs"),
                   RecipeIngredient(amount: "4", item: "eggs"),
                   RecipeIngredient(amount: "8 oz", item: "green beans or long beans, trimmed"),
                   RecipeIngredient(amount: "1/4 head", item: "green cabbage, in wide ribbons"),
                   RecipeIngredient(amount: "2 cups", item: "bean sprouts"),
                   RecipeIngredient(amount: "2", item: "medium potatoes, in thick slices"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "3/4 cup", item: "natural peanut butter"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, grated"),
                   RecipeIngredient(amount: "1 tbsp", item: "kecap manis (or soy sauce plus 1 tsp brown sugar)"),
                   RecipeIngredient(amount: "1 tbsp", item: "lime juice"),
                   RecipeIngredient(amount: "1 tsp", item: "sambal oelek"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 handful", item: "shrimp crackers or fried shallots, to top"),
               ],
               steps: [
                   "Boil the potato slices in salted water until just tender, about 10 minutes, and lift them out. Boil the eggs 9 minutes in the same pot, then peel and halve them.",
                   "Blanch the green beans 2 minutes, the cabbage 1 minute, and the bean sprouts 20 seconds in the same water, scooping each into a colander; everything should stay bright and slightly firm.",
                   "Pan-fry the tempeh slabs in the oil over medium-high until deep golden on both sides, about 6 minutes, then cut into bite-size pieces and salt lightly.",
                   "Whisk the peanut butter with 3/4 cup hot water until smooth, then whisk in the garlic, kecap manis, lime juice, sambal, and salt.",
                   "Warm the sauce briefly in a small pan, adding water spoonful by spoonful until it pours thickly but slides off the spoon; taste for salt-sweet balance.",
                   "Arrange the warm vegetables, potatoes, tempeh, and eggs in loose piles on a platter or four plates, nothing mixed yet.",
                   "Pour the warm sauce over everything just before serving and top with crushed shrimp crackers or fried shallots.",
               ],
               note: "Serve it warm, not cold; the sauce seizes on chilled vegetables. And the sauce should arrive at the last second, or the crackers and sprouts go soft.",
               shortcut: "A rotisserie-counter salad bar supplies boiled eggs and blanched vegetables; you only have to fry the tempeh and whisk the sauce."),
        Recipe(dishID: "indonesia-sotoayam", serves: 4, prepMinutes: 20, cookMinutes: 50, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "bone-in chicken thighs"),
                   RecipeIngredient(amount: "8 cups", item: "water"),
                   RecipeIngredient(amount: "4", item: "shallots"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic"),
                   RecipeIngredient(amount: "2 tsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "1-inch piece", item: "fresh ginger"),
                   RecipeIngredient(amount: "2", item: "candlenuts (or macadamias), optional"),
                   RecipeIngredient(amount: "2 stalks", item: "lemongrass, bruised"),
                   RecipeIngredient(amount: "3", item: "kaffir lime leaves (or bay leaves)"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tbsp", item: "salt"),
                   RecipeIngredient(amount: "4 oz", item: "glass noodles (bean thread)"),
                   RecipeIngredient(amount: "2", item: "hard-boiled eggs, halved"),
                   RecipeIngredient(amount: "1/2 cup", item: "fried shallots (store-bought is standard), plus lime wedges"),
               ],
               steps: [
                   "Simmer the chicken in the water with a teaspoon of salt, skimming the foam, for 30 minutes, until cooked through. Lift out the chicken and keep the broth at a low simmer.",
                   "Blend the shallots, garlic, turmeric, ginger, and candlenuts with a splash of water into a smooth yellow paste.",
                   "Fry the paste in the oil over medium heat for 4 to 5 minutes, stirring, until it thickens, darkens slightly, and loses its raw shallot smell.",
                   "Scrape the fried paste into the broth with the lemongrass and lime leaves and simmer 15 minutes; the broth should turn a clear, deep yellow, not muddy.",
                   "Shred the chicken off the bones into bite-size pieces, discarding skin and bones, and season the broth with the remaining salt to taste.",
                   "Soak the glass noodles in hot water for 5 minutes until clear and slippery, then drain and snip once or twice with scissors.",
                   "Build each bowl: a nest of noodles, shredded chicken, half an egg, then hot broth ladled over, finished with a landslide of fried shallots and a lime wedge squeezed at the table.",
               ],
               note: "Fry the paste properly before it meets the broth; raw shallot paste dumped into stock gives you a harsh, cloudy soup instead of a clear golden one.",
               shortcut: "Rotisserie chicken plus boxed stock collapses this to twenty minutes; simmer the fried paste in the stock so the turmeric still blooms."),
        Recipe(dishID: "indonesia-tumpeng", serves: 8, prepMinutes: 30, cookMinutes: 45, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "4 cups", item: "jasmine rice"),
                   RecipeIngredient(amount: "2 cans (13.5 oz each)", item: "coconut milk"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "water"),
                   RecipeIngredient(amount: "1 tbsp", item: "ground turmeric"),
                   RecipeIngredient(amount: "2 stalks", item: "lemongrass, bruised and knotted"),
                   RecipeIngredient(amount: "3", item: "pandan leaves, knotted (or 2 bay leaves)"),
                   RecipeIngredient(amount: "4", item: "kaffir lime leaves (or strips of lime zest)"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1/2 cup", item: "fried shallots"),
                   RecipeIngredient(amount: "1", item: "cucumber, sliced, plus tomato wedges and cilantro for the tray"),
                   RecipeIngredient(amount: "1 batch", item: "fried chicken pieces and fried tempeh, to ring the cone (store-bought fried chicken is accepted practice abroad)"),
               ],
               steps: [
                   "Rinse the rice until the water runs mostly clear and drain it well.",
                   "Stir the coconut milk, water, turmeric, and salt together in a heavy pot until the turmeric dissolves with no streaks.",
                   "Add the rice, lemongrass, pandan, and lime leaves, bring to a simmer, and stir once so nothing sticks.",
                   "Cover and cook on the lowest possible heat for 18 to 20 minutes, then rest, still covered, for 15 minutes; the coconut fat makes this rice quick to scorch, so trust low heat.",
                   "Fish out the leaves and lemongrass and fold the rice gently with a paddle; it should be an even gold, rich but not wet.",
                   "Pack the hot rice firmly into a large funnel, a cone of parchment, or a tall bowl, pressing in layers, then unmold it point-up in the center of a platter.",
                   "Ring the cone with fried chicken, fried tempeh, cucumber, tomato, and cilantro, and shower the rice with fried shallots.",
                   "Present it whole before anyone eats; the honoree slices the tip off the top and hands it to the person they most respect, then everyone shares the rest.",
               ],
               note: "Pack the cone hot and firmly, layer by layer, or it slumps when unmolded. The sides can be patched with a wet paddle before the garnishes go on.",
               shortcut: "A rice cooker handles the coconut rice on the plain white setting; add the aromatics on top of the rice before starting it."),
        Recipe(dishID: "indonesia-klepon", serves: 6, prepMinutes: 35, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "glutinous rice flour"),
                   RecipeIngredient(amount: "2 tbsp", item: "tapioca starch (or cornstarch)"),
                   RecipeIngredient(amount: "1 tsp", item: "pandan paste (or 1/2 cup blended pandan leaves and water, or a drop of green food coloring plus 1/2 tsp vanilla)"),
                   RecipeIngredient(amount: "3/4 cup", item: "warm water, plus more as needed"),
                   RecipeIngredient(amount: "1/2 cup", item: "palm sugar (gula jawa), finely chopped (or dark brown sugar)"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "unsweetened shredded coconut"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
               ],
               steps: [
                   "Steam the shredded coconut with the salt for 5 minutes (or microwave it damp for 1 minute) so it turns tender and clings, then spread it on a plate to cool.",
                   "Knead the rice flour, tapioca starch, pandan paste, and warm water into a smooth green dough that holds a thumbprint without cracking; add water a teaspoon at a time if crumbly.",
                   "Pinch off a piece the size of a walnut, roll it, and press a deep well into the center with your thumb.",
                   "Pack the well with about half a teaspoon of chopped palm sugar, then pinch the dough closed over it and roll the ball smooth between your palms. Repeat with the rest.",
                   "Boil a wide pot of water and drop in the balls in batches of eight; stir once so nothing sits on the bottom.",
                   "Cook until they float, then give them 2 more minutes so the sugar inside fully melts; the skin should look glossy and slightly translucent.",
                   "Lift them out with a slotted spoon, let them drain 10 seconds, and roll them immediately in the salted coconut.",
                   "Cool to room temperature before serving, and tell everyone to eat each one whole; that is not etiquette, it is damage control.",
               ],
               note: "Chop the palm sugar fine and seal well; big chunks pierce the skin as they melt and bleed out into the water, leaving hollow, sad spheres.",
               shortcut: "Dark brown sugar mixed with a drop of maple syrup mimics the smoke of real gula jawa closely enough for anyone who has not grown up on it."),
        Recipe(dishID: "indonesia-pempek", serves: 4, prepMinutes: 40, cookMinutes: 40, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "spanish mackerel fillets, skinned (or cod, or a mix with a few anchovies for depth)"),
                   RecipeIngredient(amount: "1 cup", item: "ice-cold water"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "tapioca starch (for the sago flour)"),
                   RecipeIngredient(amount: "3/4 cup", item: "dark brown sugar or palm sugar (for the cuko)"),
                   RecipeIngredient(amount: "3 tbsp", item: "tamarind paste"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "3", item: "bird's eye chilies, minced (or 2 tsp sambal oelek)"),
                   RecipeIngredient(amount: "2 tbsp", item: "rice vinegar"),
                   RecipeIngredient(amount: "2 cups", item: "vegetable oil, for frying"),
                   RecipeIngredient(amount: "1/2", item: "cucumber, finely diced, to serve"),
               ],
               steps: [
                   "Make the cuko first: simmer the brown sugar, tamarind, garlic, chilies, and vinegar with 1 1/2 cups water for 15 minutes, then strain or leave rustic. It should sting sour before it turns sweet.",
                   "Blend the fish with the ice water, salt, and sugar in a food processor until it becomes a smooth, sticky paste; the cold keeps the texture springy.",
                   "Turn the paste into a bowl and fold in the tapioca starch with a spatula in a few strokes, stopping the moment it comes together; overworking makes the cakes tough instead of bouncy.",
                   "With oiled hands, shape the dough into logs the size of a small cucumber, or golf balls if that is easier.",
                   "Slide the cakes into a wide pot of gently boiling salted water and cook until they float plus 5 minutes more, about 15 minutes total. Drain and let them dry 10 minutes.",
                   "Heat the oil to 350°F in a deep saucepan and fry the boiled cakes in batches, turning, until the shells are golden and blistered, 3 to 4 minutes per batch.",
                   "Slice the cakes into thick coins, pile them in bowls, pour the room-temperature cuko over, and scatter diced cucumber on top.",
               ],
               note: "The cuko should genuinely pucker your mouth; timid sauce is the most common failure outside Palembang. The fish cake is mild on purpose and needs the assault.",
               shortcut: "Boil the cakes a day ahead and refrigerate; frying straight from the fridge takes a minute longer and the shell blisters even better."),
    ]

    static let all: [Recipe] = recipes_thailand + recipes_vietnam + recipes_indonesia
}
