import Foundation

// Generated from the authored recipe files. Do not edit by hand.

enum RecipesEastAsia {

    private static let recipes_japan: [Recipe] = [
        Recipe(dishID: "japan-shoyu-ramen", serves: 2, prepMinutes: 20, cookMinutes: 60, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "10 oz", item: "fresh ramen noodles (or 2 packs dried, seasoning discarded)"),
                   RecipeIngredient(amount: "4 cups", item: "chicken stock"),
                   RecipeIngredient(amount: "1/2 lb", item: "pork belly or shoulder, in one piece"),
                   RecipeIngredient(amount: "1/4 cup", item: "soy sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "mirin"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, smashed"),
                   RecipeIngredient(amount: "1 inch", item: "fresh ginger, sliced"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "2", item: "scallions, thinly sliced"),
                   RecipeIngredient(amount: "1 sheet", item: "nori, cut into quarters"),
                   RecipeIngredient(amount: "1/2 cup", item: "menma (or canned bamboo shoots, drained)"),
               ],
               steps: [
                   "Put the pork, stock, garlic and ginger in a pot, bring to a bare simmer, cover, and cook 50 minutes until a chopstick slides into the meat easily.",
                   "Meanwhile lower the eggs into boiling water for 6 and a half minutes, then move them straight to ice water and peel once cool.",
                   "Stir the soy sauce and mirin together in a small pan and warm for one minute. This tare is the seasoning; keep it separate from the broth.",
                   "Lift out the pork, rest it 5 minutes, and slice it into thin rounds. Sear the slices in a dry skillet until the edges brown, about 2 minutes.",
                   "Strain the broth, return it to the pot, and keep it just below a boil. Taste it plain; it should be rich but unsalted.",
                   "Boil the noodles in a separate pot of water until springy, usually 1 to 2 minutes for fresh, then drain hard, shaking out every drop.",
                   "Put 2 tablespoons of tare in each warmed bowl, ladle in the hot broth, then lower in the noodles and lift once with chopsticks to loosen.",
                   "Top with pork, halved eggs, menma, scallions and a piece of nori. Serve immediately and eat fast, before the noodles soften.",
               ],
               note: "The broth must be nearly boiling and the bowls warmed before assembly. Lukewarm ramen is dead ramen, and noodles keep cooking in the bowl.",
               shortcut: "Good instant noodles with store-bought stock and this tare still work; you lose the pork-enriched body of the broth."),
        Recipe(dishID: "japan-nigiri", serves: 2, prepMinutes: 40, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 cups", item: "sushi rice"),
                   RecipeIngredient(amount: "3 tbsp", item: "rice vinegar"),
                   RecipeIngredient(amount: "1 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1 tsp", item: "salt"),
                   RecipeIngredient(amount: "6 oz", item: "sushi-grade tuna, from a fish counter you trust"),
                   RecipeIngredient(amount: "6 oz", item: "sushi-grade sea bream or snapper (or more tuna)"),
                   RecipeIngredient(amount: "1 tsp", item: "wasabi paste"),
                   RecipeIngredient(amount: "2 tbsp", item: "soy sauce, for dipping"),
               ],
               steps: [
                   "Rinse the rice in cold water until it runs nearly clear, then cook it with 1 3/4 cups water in a rice cooker or covered pot on low.",
                   "Warm the vinegar, sugar and salt until dissolved. Turn the hot rice out into a wide bowl, pour the vinegar over, and fold gently with a slicing motion.",
                   "Fan the rice while folding until it drops to warm body temperature and takes on a glossy sheen. Cover with a damp towel.",
                   "Slice the fish against the grain into pieces about 3 inches long, 1 inch wide and 1/4 inch thick, wiping the knife between cuts.",
                   "Wet your hands with vinegared water. Pick up a walnut-sized ball of rice and squeeze it lightly into an oblong pillow; it should hold shape but not compact.",
                   "Smear a trace of wasabi on the underside of a fish slice, lay it over the rice, and press gently with two fingers to cup the fish around it.",
                   "Serve right away, fish side down into a shallow dish of soy. The rice should still be faintly warm when eaten.",
               ],
               note: "Buy the fish the day you make this, tell the fishmonger it is for sushi, and never refrigerate the finished rice or it turns hard and dull.",
               shortcut: "Skip the shaping and scatter the same fish over the same rice as a bowl; you lose the hand-warmed rice pillow that defines nigiri."),
        Recipe(dishID: "japan-okonomiyaki", serves: 2, prepMinutes: 20, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "3/4 cup", item: "dashi (or water with 1/2 tsp dashi powder)"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "4 cups", item: "green cabbage, finely shredded"),
                   RecipeIngredient(amount: "4 oz", item: "thin-sliced pork belly (or bacon)"),
                   RecipeIngredient(amount: "3", item: "scallions, sliced"),
                   RecipeIngredient(amount: "3 tbsp", item: "okonomiyaki sauce (or 2 tbsp Worcestershire mixed with 1 tbsp ketchup)"),
                   RecipeIngredient(amount: "2 tbsp", item: "mayonnaise"),
                   RecipeIngredient(amount: "1/2 cup", item: "bonito flakes"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
               ],
               steps: [
                   "Whisk the flour and dashi into a thin batter, then whisk in the eggs. It should pour like heavy cream, not pancake batter.",
                   "Fold in the cabbage and scallions just before cooking, tossing until every shred is coated but the mix still looks mostly like cabbage.",
                   "Heat the oil in a nonstick skillet over medium. Pile in half the mixture and pat it into a round about 1 inch thick; do not press it flat.",
                   "Lay half the pork slices over the top. Cook 5 minutes until the underside is deeply browned and the edges look set.",
                   "Flip with two spatulas in one confident motion so the pork side is down, and cook another 5 minutes until the pork is crisp.",
                   "Flip once more, cover, and give it 2 final minutes so the center steams through. A skewer should come out without wet batter.",
                   "Slide onto a plate pork side up. Paint with sauce, zigzag the mayonnaise, and shower with bonito flakes while hot so they wave.",
                   "Repeat with the remaining mixture. Cut into wedges at the table and eat straight off the plate.",
               ],
               note: "Mix the cabbage in at the last second and keep it barely bound. If the batter pools, the pancake turns to dumpling instead of staying light.",
               shortcut: "Bagged coleslaw mix replaces the shredded cabbage with zero knife work; the pieces are coarser so the middle steams a bit less evenly."),
        Recipe(dishID: "japan-chawanmushi", serves: 2, prepMinutes: 15, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "1 1/4 cups", item: "dashi, cooled (or water with 3/4 tsp dashi powder)"),
                   RecipeIngredient(amount: "1 tsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1/2 tsp", item: "mirin"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
                   RecipeIngredient(amount: "4", item: "raw shrimp, peeled"),
                   RecipeIngredient(amount: "2", item: "shiitake mushrooms, thinly sliced"),
                   RecipeIngredient(amount: "6", item: "canned gingko nuts (or shelled edamame)"),
                   RecipeIngredient(amount: "a few sprigs", item: "mitsuba (or flat-leaf parsley)"),
               ],
               steps: [
                   "Whisk the eggs gently, trying not to raise foam, then whisk in the cooled dashi, soy, mirin and salt until even.",
                   "Pour the mixture through a fine strainer into a measuring cup. This single step is what makes the custard silk instead of scrambled egg.",
                   "Divide the shrimp, shiitake and gingko nuts between two heatproof teacups or ramekins, then pour the strained custard over to fill.",
                   "Set up a steamer with an inch of water at a bare simmer. Cover each cup with foil so condensation cannot drip in.",
                   "Steam over the lowest heat that keeps wisps of steam rising, about 15 minutes. Hard steam will fill the custard with holes.",
                   "Check by tilting a cup: the surface should tremble as one piece, with no liquid egg running. Give it 3 more minutes if it slides.",
                   "Rest 2 minutes, top with mitsuba leaves, and serve warm in the cup with a small spoon, digging down for the treasures.",
               ],
               note: "Heat is the whole game. The water must barely simmer; at a rolling boil the custard curdles into sponge in under two minutes.",
               shortcut: "No steamer needed: set the cups in a covered skillet with an inch of barely simmering water; the texture comes out identical."),
        Recipe(dishID: "japan-ozoni", serves: 2, prepMinutes: 15, cookMinutes: 25, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "kirimochi rice cakes (shelf-stable, from an asian market)"),
                   RecipeIngredient(amount: "3 cups", item: "dashi (or water with 1 1/2 tsp dashi powder)"),
                   RecipeIngredient(amount: "1", item: "boneless chicken thigh, cut into bite-size pieces"),
                   RecipeIngredient(amount: "2 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2 cups", item: "komatsuna or spinach leaves"),
                   RecipeIngredient(amount: "a few strips", item: "yuzu peel (or a strip of lemon zest)"),
               ],
               steps: [
                   "Bring the dashi to a gentle simmer, add the chicken pieces, and skim any gray foam so the broth stays clear.",
                   "Simmer 8 minutes until the chicken is cooked through, then season the broth with the soy sauce and salt. It should taste clean, not salty.",
                   "Blanch the greens in boiling water for 30 seconds, rinse in cold water, squeeze dry, and cut into 2 inch lengths.",
                   "Toast the mochi in a toaster oven or dry skillet, turning once, until it puffs, blisters and browns in spots, about 6 to 8 minutes.",
                   "Set a piece of toasted mochi in each bowl while it is still puffed, before it can deflate and harden.",
                   "Ladle the hot broth and chicken over the mochi, tuck in the greens, and float a strip of yuzu peel on the surface.",
                   "Serve at once with chopsticks, eating slowly. The mochi stretches as you lift it, which is the whole pleasure.",
               ],
               note: "Toast the mochi until it truly puffs and add it last. Dropped in raw, it dissolves into paste and clouds the careful broth.",
               shortcut: "Rotisserie chicken and instant dashi cut this to fifteen minutes; the broth will be lighter without the thigh simmering in it."),
        Recipe(dishID: "japan-nasu-dengaku", serves: 2, prepMinutes: 10, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2", item: "japanese or chinese eggplants (or 1 small globe eggplant)"),
                   RecipeIngredient(amount: "3 tbsp", item: "red or awase miso"),
                   RecipeIngredient(amount: "2 tbsp", item: "mirin"),
                   RecipeIngredient(amount: "1 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1 tbsp", item: "water"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "toasted sesame seeds"),
               ],
               steps: [
                   "Halve the eggplants lengthwise and score the cut faces in a tight crosshatch, cutting deep but not through the skin.",
                   "Brush the cut faces generously with oil. Lay them cut side down in a skillet over medium heat and cook 4 minutes until golden.",
                   "Flip skin side down, add a splash of water, cover, and steam 6 to 8 minutes until the flesh is completely tender to a fork.",
                   "While the eggplant cooks, stir the miso, mirin, sugar and water in a small saucepan over low heat until glossy and just pourable, about 2 minutes.",
                   "Move the eggplant cut side up to a foil-lined pan and spread the miso glaze thickly over the scored faces, right to the edges.",
                   "Broil 2 to 3 minutes, watching constantly, until the glaze bubbles and catches dark brown spots. It goes from blistered to burnt fast.",
                   "Scatter with sesame seeds and serve hot with rice, one half per person, scooping the flesh out with chopsticks or a spoon.",
               ],
               note: "The eggplant must be fully creamy before the glaze goes on. The broiler only colors the miso; it cannot rescue undercooked flesh.",
               shortcut: "White miso works if that is what you have; add an extra teaspoon of it and cut the sugar in half."),
        Recipe(dishID: "japan-oyakodon", serves: 2, prepMinutes: 10, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "cooked short grain rice, hot"),
                   RecipeIngredient(amount: "2", item: "boneless chicken thighs, cut into bite-size pieces"),
                   RecipeIngredient(amount: "4", item: "eggs"),
                   RecipeIngredient(amount: "1/2", item: "yellow onion, thinly sliced"),
                   RecipeIngredient(amount: "3/4 cup", item: "dashi (or water with 1/2 tsp dashi powder)"),
                   RecipeIngredient(amount: "2 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "2 tbsp", item: "mirin"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1", item: "scallion, sliced"),
               ],
               steps: [
                   "Stir the dashi, soy sauce, mirin and sugar together in a small skillet, about 8 inches wide, and bring to a simmer.",
                   "Scatter in the onion and cook 3 minutes until it turns translucent and starts to soften into the broth.",
                   "Add the chicken in one layer and simmer 6 to 8 minutes, turning once, until no pink remains at the thickest piece.",
                   "Beat the eggs only five or six strokes, so ribbons of white remain visible. Overbeaten eggs set into a flat sheet.",
                   "Pour two thirds of the egg in a spiral over the simmering chicken, cover, and cook 1 minute until mostly set but still glossy.",
                   "Add the rest of the egg, cover again, and count 30 seconds. Pull the pan off the heat while the surface is still loose.",
                   "Divide the hot rice between two bowls and slide half the chicken and egg over each, letting the sauce soak down. Top with scallion and eat immediately.",
               ],
               note: "Take it off the heat when the egg still looks slightly underdone. It finishes setting on the rice, and that loose top layer is the dish.",
               shortcut: "Water plus a splash more soy stands in for dashi in a pinch; you trade the smoky depth for pure soy sweetness."),
        Recipe(dishID: "japan-warabimochi", serves: 4, prepMinutes: 25, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "3/4 cup", item: "bracken starch (or tapioca starch)"),
                   RecipeIngredient(amount: "1/4 cup", item: "sugar"),
                   RecipeIngredient(amount: "2 1/2 cups", item: "water"),
                   RecipeIngredient(amount: "1/2 cup", item: "kinako roasted soybean flour"),
                   RecipeIngredient(amount: "1/2 cup", item: "dark brown sugar, for the syrup"),
                   RecipeIngredient(amount: "1/4 cup", item: "water, for the syrup"),
               ],
               steps: [
                   "Make the kuromitsu first: simmer the brown sugar with 1/4 cup water for 3 minutes until syrupy, then set aside to cool.",
                   "Whisk the starch, sugar and 2 1/2 cups water in a saucepan until completely smooth before it ever touches heat.",
                   "Cook over medium heat, stirring constantly with a wooden spoon. It will suddenly seize into lumps; keep stirring hard through this stage.",
                   "Keep stirring 3 to 4 more minutes until the mass turns from cloudy white to translucent and pulls away from the pan in one stretchy piece.",
                   "Scrape it into a bowl of ice water and let it chill 15 minutes until cold and set through.",
                   "Spread half the kinako on a cutting board, turn the chilled jelly onto it, and cut into 1 inch cubes with a wet knife.",
                   "Roll the cubes in kinako until every face is coated, pile into small bowls, and pour the cooled syrup over just before eating.",
               ],
               note: "Translucence is the doneness cue. Stop while any milky white remains and the centers stay chalky instead of turning to that cold wobble.",
               shortcut: "Tapioca starch is the standard substitute even in Japan; true bracken starch is grayer, earthier and roughly ten times the price."),
    ]

    private static let recipes_korea: [Recipe] = [
        Recipe(dishID: "korea-kimchi", serves: 8, prepMinutes: 45, cookMinutes: 0, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 head", item: "napa cabbage, about 2 lb"),
                   RecipeIngredient(amount: "1/4 cup", item: "coarse salt"),
                   RecipeIngredient(amount: "1/3 cup", item: "gochugaru korean chili flakes"),
                   RecipeIngredient(amount: "6 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, grated"),
                   RecipeIngredient(amount: "2 tbsp", item: "salted shrimp, minced (or fish sauce)"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1 cup", item: "korean radish or daikon, cut into matchsticks"),
                   RecipeIngredient(amount: "4", item: "scallions, cut into 1 inch lengths"),
               ],
               steps: [
                   "Quarter the cabbage lengthwise, then cut crosswise into 2 inch pieces. Toss thoroughly with the salt in a large bowl.",
                   "Let the cabbage sit 2 hours, turning it every 30 minutes, until the thick stem pieces bend without snapping.",
                   "Rinse the cabbage three times in cold water to wash off the surface salt, then squeeze it firmly and drain in a colander 15 minutes.",
                   "Stir the gochugaru, garlic, ginger, salted shrimp, sugar and 2 tablespoons of water into a loose red paste.",
                   "Wearing gloves, massage the paste into the cabbage with the radish and scallions until every piece is coated red inside the folds.",
                   "Pack the kimchi into a clean quart jar, pressing down hard after each handful so brine rises above the vegetables. Leave an inch of headspace.",
                   "Close the lid loosely and leave at room temperature 2 to 3 days, pressing down daily, until it smells pleasantly sour and fizzes faintly.",
                   "Refrigerate. It is good immediately, better in a week, and ready for stews when it turns properly sour after a month.",
               ],
               note: "Keep the vegetables submerged under brine at every stage. Anything poking above the surface is where off flavors and white film start.",
               shortcut: "Fish sauce replaces salted shrimp one for one and is easier to find; the kimchi comes out slightly less round and funky."),
        Recipe(dishID: "korea-bibimbap", serves: 2, prepMinutes: 30, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "cooked short grain rice, hot"),
                   RecipeIngredient(amount: "4 cups", item: "spinach"),
                   RecipeIngredient(amount: "2 cups", item: "bean sprouts"),
                   RecipeIngredient(amount: "1", item: "carrot, cut into matchsticks"),
                   RecipeIngredient(amount: "1", item: "zucchini, cut into matchsticks"),
                   RecipeIngredient(amount: "2 tbsp", item: "gochujang (or miso mixed with hot sauce)"),
                   RecipeIngredient(amount: "2", item: "eggs"),
                   RecipeIngredient(amount: "3 tbsp", item: "toasted sesame oil"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "2 tsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 tsp", item: "toasted sesame seeds"),
               ],
               steps: [
                   "Blanch the spinach 30 seconds, squeeze it dry, and toss with a third of the garlic, 2 teaspoons sesame oil and a pinch of salt.",
                   "Blanch the bean sprouts 2 minutes, drain well, and dress the same way with garlic, a teaspoon of sesame oil and salt.",
                   "Saute the carrot in a little vegetable oil with a pinch of salt for 2 minutes until just bendable, then remove. Repeat with the zucchini.",
                   "Stir the gochujang with the soy sauce, sugar, remaining garlic and 2 teaspoons of sesame oil into a spoonable sauce.",
                   "Fry the eggs in the remaining oil over medium heat until the whites are crisp at the edges but the yolks still run.",
                   "Pack the hot rice into two wide bowls and arrange the vegetables over it in separate wedges, keeping each pile distinct.",
                   "Set a fried egg in the center of each bowl, spoon the sauce beside it, and scatter sesame seeds over everything.",
                   "Bring to the table looking composed, then stir everything together violently with a spoon until uniform before the first bite.",
               ],
               note: "Season each vegetable separately and taste each one. The bowl is only as good as its blandest pile, since everything gets stirred together.",
               shortcut: "One skillet, one vegetable at a time, no washing between; the piles pick up traces of each other but dinner arrives twice as fast."),
        Recipe(dishID: "korea-bulgogi", serves: 4, prepMinutes: 25, cookMinutes: 10, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 1/2 lb", item: "ribeye or sirloin, sliced paper thin (ask the butcher, or freeze 1 hour and slice)"),
                   RecipeIngredient(amount: "1/4 cup", item: "soy sauce"),
                   RecipeIngredient(amount: "1/2", item: "asian pear, grated (or 2 tbsp grated apple)"),
                   RecipeIngredient(amount: "4 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "2 tbsp", item: "toasted sesame oil"),
                   RecipeIngredient(amount: "4", item: "scallions, sliced"),
                   RecipeIngredient(amount: "1/4 tsp", item: "black pepper"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "1 head", item: "butter or red leaf lettuce, leaves separated"),
                   RecipeIngredient(amount: "3 cups", item: "cooked short grain rice"),
               ],
               steps: [
                   "Whisk the soy sauce, grated pear, garlic, sugar, sesame oil, half the scallions and the pepper into a marinade.",
                   "Toss the beef slices in the marinade, separating them so every surface is coated, and let sit 30 minutes at room temperature.",
                   "Heat a large cast iron skillet over the highest heat until it smokes faintly, then add the vegetable oil.",
                   "Lay in a third of the beef in a single layer and leave it untouched 1 minute so the sugars caramelize and the edges char.",
                   "Toss and cook 1 more minute until just done, then transfer to a platter. Repeat in two more batches; crowding makes it stew.",
                   "Pour any pan juices over the meat and scatter with the remaining scallions.",
                   "Serve with the lettuce and rice. Each person wraps a leaf around rice and beef, folds it closed, and eats it in one bite.",
               ],
               note: "The pear is not optional garnish; its enzymes tenderize the beef. But past two hours in the marinade the meat turns mushy.",
               shortcut: "Pre-shaved beef sold for hot pot or cheesesteaks skips all knife work; the slices are thinner, so cook each batch in under a minute."),
        Recipe(dishID: "korea-samgyetang", serves: 2, prepMinutes: 20, cookMinutes: 90, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2", item: "cornish game hens (about 1 1/4 lb each)"),
                   RecipeIngredient(amount: "1/2 cup", item: "glutinous rice, soaked 1 hour"),
                   RecipeIngredient(amount: "2", item: "small fresh or dried ginseng roots (or a 2 inch piece of ginger, sliced)"),
                   RecipeIngredient(amount: "6", item: "dried jujubes (or pitted dates)"),
                   RecipeIngredient(amount: "8 cloves", item: "garlic, peeled"),
                   RecipeIngredient(amount: "3", item: "scallions, sliced"),
                   RecipeIngredient(amount: "8 cups", item: "water"),
                   RecipeIngredient(amount: "to serve", item: "coarse salt and black pepper"),
               ],
               steps: [
                   "Rinse the hens inside and out and trim any loose fat from the cavity openings.",
                   "Stuff each bird with half the soaked rice, one ginseng root, two jujubes and three garlic cloves, filling the cavity only two-thirds full.",
                   "Cross the legs and tie them with kitchen twine, or cut a slit in one leg's skin and tuck the other leg through it.",
                   "Set the hens breast up in a pot that holds them snugly, add the remaining garlic and jujubes, and pour in water to just cover.",
                   "Bring to a boil, skim the foam, then cover and simmer gently 75 minutes until a leg wiggles loosely in its joint.",
                   "Uncover and simmer 10 more minutes so the escaped rice thickens the broth to a milky, faintly cloudy body.",
                   "Serve each person a whole bird in a deep bowl of broth, topped with scallions, with a small dish of salt and pepper for dipping the meat.",
               ],
               note: "The broth is served nearly unseasoned on purpose. Salt at the table, bite by bite, or you flatten the mild ginseng bitterness that defines it.",
               shortcut: "Ginger stands in for ginseng if the asian market is far; the soup loses its bitter medicinal edge and becomes purely comforting."),
        Recipe(dishID: "korea-kongguksu", serves: 2, prepMinutes: 20, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "dried soybeans, soaked overnight"),
                   RecipeIngredient(amount: "3 cups", item: "cold water, plus more for soaking"),
                   RecipeIngredient(amount: "2 tbsp", item: "toasted sesame seeds"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt, plus more at the table"),
                   RecipeIngredient(amount: "8 oz", item: "somyeon thin wheat noodles (or somen)"),
                   RecipeIngredient(amount: "1/2", item: "cucumber, cut into fine matchsticks"),
                   RecipeIngredient(amount: "1 cup", item: "ice cubes"),
               ],
               steps: [
                   "Drain the soaked soybeans, cover with fresh water, and boil 20 minutes until a bean crushes easily between your fingers but is not mushy.",
                   "Drain and rinse the beans under cold water, rubbing handfuls between your palms so the papery skins float free. Pour off the skins.",
                   "Blend the skinned beans with 3 cups cold water, the sesame seeds and the salt for a full 2 minutes until thick and completely smooth.",
                   "Chill the soy milk in the refrigerator or set the blender jar in ice water while you cook the noodles.",
                   "Boil the noodles per the package, usually 3 minutes, then rinse them under cold running water, rubbing them until they squeak and fully cool.",
                   "Coil a nest of noodles in the center of each shallow bowl and pour the cold soy milk around until they nearly float.",
                   "Top with cucumber and a few ice cubes. Serve with salt on the table; each eater seasons their own bowl, a pinch at a time.",
               ],
               note: "Rubbing off the bean skins is tedious and worth it. Skins left in make the milk gritty and slightly bitter instead of nutty and smooth.",
               shortcut: "Blend unsweetened soy milk with sesame seeds and skip the beans entirely; thinner body, but the dish appears in ten minutes."),
        Recipe(dishID: "korea-hotteok", serves: 4, prepMinutes: 30, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 cup", item: "glutinous rice flour (or more all-purpose flour)"),
                   RecipeIngredient(amount: "1 tsp", item: "instant yeast"),
                   RecipeIngredient(amount: "1 tbsp", item: "sugar, for the dough"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 cup", item: "warm milk"),
                   RecipeIngredient(amount: "1/2 cup", item: "dark brown sugar"),
                   RecipeIngredient(amount: "1 tsp", item: "ground cinnamon"),
                   RecipeIngredient(amount: "1/4 cup", item: "roasted peanuts, chopped"),
                   RecipeIngredient(amount: "3 tbsp", item: "vegetable oil"),
               ],
               steps: [
                   "Stir both flours, the yeast, sugar and salt together, then mix in the warm milk to a sticky, shaggy dough with no dry patches.",
                   "Cover and let rise in a warm spot about 1 hour until doubled and webbed with bubbles when you pull it aside.",
                   "Mix the brown sugar, cinnamon and peanuts for the filling. Punch the dough down and divide into 8 pieces with oiled hands.",
                   "Flatten a piece into a 4 inch round on an oiled palm, mound 1 tablespoon of filling in the center, and pinch the edges shut like a purse.",
                   "Heat a thin film of oil in a skillet over medium. Place two dough balls seam side down and cook 1 minute until the bottoms set.",
                   "Flip, then press each one flat to a 4 inch disc with an oiled spatula, holding firm pressure for a few seconds.",
                   "Cook 2 minutes per side, flipping once more, until deep golden and crisp. The sugar inside should be fully molten. Repeat with the rest.",
                   "Cool 2 minutes before eating; the filling is lava straight from the pan. Eat warm, folded in a paper towel, over a plate.",
               ],
               note: "Seal the seams completely and press only after the first flip. Any gap lets the molten sugar escape and burn black in the oil.",
               shortcut: "Thawed frozen dinner-roll dough skips the mixing and rise; the bread is fluffier and less chewy without the rice flour."),
        Recipe(dishID: "korea-pajeon", serves: 2, prepMinutes: 15, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "3/4 cup", item: "all-purpose flour"),
                   RecipeIngredient(amount: "1/4 cup", item: "cornstarch"),
                   RecipeIngredient(amount: "1 cup", item: "ice water"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 bunch", item: "scallions, trimmed to fit the skillet"),
                   RecipeIngredient(amount: "1/2 cup", item: "squid rings and chopped clams (or shrimp), patted very dry"),
                   RecipeIngredient(amount: "1", item: "egg, beaten"),
                   RecipeIngredient(amount: "4 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "2 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "rice vinegar"),
               ],
               steps: [
                   "Stir the soy sauce and vinegar together for the dipping sauce and set it aside.",
                   "Whisk the flour, cornstarch, salt and ice water into a thin batter just before cooking. Lumps are fine; cold and thin matter more than smooth.",
                   "Heat 2 tablespoons of oil in a 10 inch skillet over medium-high until it shimmers hard.",
                   "Lay the scallions in a tight parallel raft covering the pan, then pour two-thirds of the batter slowly over them, filling the gaps.",
                   "Scatter the seafood over the top, drizzle on the remaining batter to anchor it, then pour the beaten egg unevenly across everything.",
                   "Cook 4 minutes until the underside is deeply browned and the edges look lacy and crisp when you lift one with a spatula.",
                   "Add the remaining oil around the rim, flip the pancake in one motion, and press down. Cook 3 to 4 minutes until the seafood side crisps.",
                   "Slide onto a board, cut into rough squares, and serve hot with the dipping sauce, tearing at it while the edges still crackle.",
               ],
               note: "Ice water and a batter that looks too thin are what make the crisp lace. A thick pancake-style batter turns it to bread.",
               shortcut: "Frozen mixed seafood works straight from the bag if you thaw and squeeze it dry; wet seafood steams the middle soggy."),
        Recipe(dishID: "korea-tteokbokki", serves: 2, prepMinutes: 10, cookMinutes: 20, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "garaetteok rice cake cylinders (refrigerated or frozen)"),
                   RecipeIngredient(amount: "3 tbsp", item: "gochujang"),
                   RecipeIngredient(amount: "1 tbsp", item: "gochugaru chili flakes (or 1 tsp red pepper flakes)"),
                   RecipeIngredient(amount: "1 1/2 tbsp", item: "sugar"),
                   RecipeIngredient(amount: "1 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "2 1/2 cups", item: "anchovy stock (or chicken broth)"),
                   RecipeIngredient(amount: "4 oz", item: "korean fish cakes, cut into triangles (or imitation crab)"),
                   RecipeIngredient(amount: "2", item: "scallions, cut into 2 inch lengths"),
               ],
               steps: [
                   "If the rice cakes are refrigerated or frozen, soak them in warm water 15 minutes so they separate and soften slightly.",
                   "Whisk the gochujang, gochugaru, sugar and soy sauce into the stock in a wide, deep skillet and bring to a boil.",
                   "Add the drained rice cakes and boil 8 minutes, stirring often and scraping the bottom so they do not stick and scorch.",
                   "Add the fish cakes and keep it at a lively simmer 5 more minutes while the sauce reduces.",
                   "Stir constantly near the end; the sauce is done when it coats the back of a spoon and clings to each cylinder in a thick red gloss.",
                   "Bite a rice cake to check: it should be dense and chewy through the middle with no hard core.",
                   "Stir in the scallions, cook 1 final minute, and serve hot in shallow bowls with toothpicks or forks.",
               ],
               note: "The sauce thickens from the rice cakes' own starch, so keep stirring. Walk away and the bottom scorches into bitterness in a minute.",
               shortcut: "Chicken broth for anchovy stock loses the faint sea depth under the chili; add a splash of fish sauce to claw some back."),
    ]

    private static let recipes_china: [Recipe] = [
        Recipe(dishID: "china-xiaolongbao", serves: 4, prepMinutes: 60, cookMinutes: 45, difficulty: 3,
               ingredients: [
                   RecipeIngredient(amount: "2 cups", item: "all-purpose flour"),
                   RecipeIngredient(amount: "3/4 cup", item: "hot water"),
                   RecipeIngredient(amount: "1 cup", item: "chicken stock"),
                   RecipeIngredient(amount: "1 tsp", item: "unflavored powdered gelatin"),
                   RecipeIngredient(amount: "3/4 lb", item: "ground pork, at least 20 percent fat"),
                   RecipeIngredient(amount: "1 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, grated, plus more cut into fine threads for serving"),
                   RecipeIngredient(amount: "2", item: "scallions, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tsp", item: "toasted sesame oil"),
                   RecipeIngredient(amount: "1/4 cup", item: "chinese black vinegar (or balsamic mixed with rice vinegar)"),
                   RecipeIngredient(amount: "1 head", item: "napa cabbage, leaves separated, for lining the steamer"),
               ],
               steps: [
                   "Sprinkle the gelatin over the cold stock, let it bloom 5 minutes, then warm until dissolved. Chill in a shallow dish 2 hours until firmly set.",
                   "Stir the hot water into the flour, knead 8 minutes to a smooth, supple dough, cover, and rest it 30 minutes.",
                   "Mix the pork with soy sauce, grated ginger, scallions, sugar, salt and sesame oil, stirring in one direction until sticky and cohesive.",
                   "Dice the set aspic into small cubes and fold it gently through the pork. Keep this filling cold until the moment you wrap.",
                   "Roll the dough into a log, cut into 24 pieces, and roll each into a 3 inch circle, thinner at the rim than in the center.",
                   "Put a scant tablespoon of filling on a wrapper and pleat the edge around it, 12 or more folds, twisting closed at the top. Repeat, keeping finished buns covered.",
                   "Line a steamer with cabbage leaves, space the buns an inch apart, and steam over boiling water 8 minutes until the skins turn translucent.",
                   "Serve straight from the steamer with vinegar and ginger threads. Bite a hole, drink the soup, then eat the rest.",
               ],
               note: "Cold filling and a thick wrapper center are your insurance. Warm aspic leaks through pinholes, and a thin base bursts in the steamer.",
               shortcut: "Round dumpling wrappers from the store save an hour of rolling; the skin steams up slightly gummy and will not stretch as far."),
        Recipe(dishID: "china-mapo-doufu", serves: 3, prepMinutes: 15, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "silken or soft tofu, cut into 3/4 inch cubes"),
                   RecipeIngredient(amount: "1/4 lb", item: "ground pork"),
                   RecipeIngredient(amount: "2 1/2 tbsp", item: "doubanjiang chili bean paste (or miso mixed with chili flakes)"),
                   RecipeIngredient(amount: "1 tsp", item: "sichuan peppercorns"),
                   RecipeIngredient(amount: "2 tbsp", item: "chili oil (or vegetable oil plus 1 tsp red pepper flakes)"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "fresh ginger, minced"),
                   RecipeIngredient(amount: "1 cup", item: "chicken stock"),
                   RecipeIngredient(amount: "1 tbsp", item: "cornstarch mixed with 2 tbsp water"),
                   RecipeIngredient(amount: "2", item: "scallions, sliced"),
                   RecipeIngredient(amount: "3 cups", item: "cooked white rice, to serve"),
               ],
               steps: [
                   "Slide the tofu cubes into a pot of barely simmering salted water and hold them there while you cook; this firms them so they survive the sauce.",
                   "Toast the sichuan peppercorns in a dry wok 1 minute until fragrant, then grind them to a coarse powder and set aside.",
                   "Heat the chili oil over medium-high and fry the pork, breaking it into small crumbles, until the bits brown and crisp at the edges.",
                   "Push the pork aside, drop the doubanjiang into the oil, and fry 1 minute until the oil stains deep red. Add garlic and ginger for 30 seconds.",
                   "Pour in the stock, stir everything together, and bring to a simmer.",
                   "Lift the tofu from its water with a slotted spoon into the sauce. From now on, push it gently with the back of the spoon; never stir.",
                   "Simmer 3 minutes, then drizzle in the cornstarch slurry in stages, nudging the tofu, until the sauce turns glossy and clings.",
                   "Slide into a shallow bowl, dust generously with the ground peppercorns, and top with scallions. Serve over rice while it still bubbles.",
               ],
               note: "Fry the doubanjiang until the oil runs red before any liquid goes in. Skip that bloom and the whole dish tastes flat and raw.",
               shortcut: "Firm tofu will not break and needs no pre-simmer, but you trade away the custardy slip that makes the dish."),
        Recipe(dishID: "china-peking-duck", serves: 4, prepMinutes: 20, cookMinutes: 30, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "4", item: "duck breasts, skin on"),
                   RecipeIngredient(amount: "2 tsp", item: "salt"),
                   RecipeIngredient(amount: "1 tbsp", item: "honey (standing in for maltose)"),
                   RecipeIngredient(amount: "1 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1/2 tsp", item: "five-spice powder"),
                   RecipeIngredient(amount: "16", item: "thin store-bought mandarin pancakes (or small flour tortillas, warmed)"),
                   RecipeIngredient(amount: "1/3 cup", item: "sweet bean sauce (or hoisin)"),
                   RecipeIngredient(amount: "6", item: "scallions, cut into thin 3 inch strips"),
                   RecipeIngredient(amount: "1/2", item: "cucumber, cut into thin 3 inch strips"),
               ],
               steps: [
                   "Score the duck skin in a tight diamond pattern, cutting through the fat but not the meat. Salt all over and refrigerate uncovered overnight to dry the skin.",
                   "Stir the honey, soy sauce and five-spice together for the glaze. Take the duck out 30 minutes before cooking.",
                   "Lay the breasts skin side down in a cold, dry skillet, then set it over medium-low. Starting cold renders the fat instead of burning the skin.",
                   "Cook 12 to 15 minutes without moving them, pouring off the fat as it collects, until the skin is deep amber and audibly crisp when tapped.",
                   "Flip, brush the crisp skin with the glaze, and cook the flesh side 3 to 4 minutes for rosy meat.",
                   "Slide under a hot broiler skin side up for 1 minute, watching closely, until the glaze bubbles and lacquers. Rest 8 minutes on a rack.",
                   "Slice thinly across the grain, keeping a cap of crisp skin on every slice, and arrange on a platter with the scallions and cucumber.",
                   "Let everyone build their own: sauce painted on the pancake, two slices of duck, a few strips of each vegetable, rolled and eaten by hand.",
               ],
               note: "This is the honest home version of a dish that hangs a whole bird over fruitwood for a day. The overnight uncovered fridge dry is non-negotiable for crackling skin.",
               shortcut: "A store-bought whole roast duck from a Chinese barbecue shop turns this into pure assembly; crisp its skin under the broiler first."),
        Recipe(dishID: "china-zhou", serves: 4, prepMinutes: 10, cookMinutes: 90, difficulty: 1,
               ingredients: [
                   RecipeIngredient(amount: "1 cup", item: "short grain rice"),
                   RecipeIngredient(amount: "5 cups", item: "pork or chicken stock"),
                   RecipeIngredient(amount: "4 cups", item: "water"),
                   RecipeIngredient(amount: "1 inch", item: "fresh ginger, cut into fine threads"),
                   RecipeIngredient(amount: "1/2 tsp", item: "salt"),
                   RecipeIngredient(amount: "2", item: "scallions, thinly sliced"),
                   RecipeIngredient(amount: "1 tbsp", item: "soy sauce, plus more at the table"),
                   RecipeIngredient(amount: "a pinch", item: "white pepper"),
                   RecipeIngredient(amount: "2", item: "fried dough sticks from an asian bakery (or thick toast), to serve"),
               ],
               steps: [
                   "Rinse the rice once, then freeze it in a bag for 30 minutes if you have time; the ice crystals fracture the grains so they break down faster.",
                   "Combine the rice, stock and water in a heavy pot and bring to a rolling boil, stirring once so nothing sticks.",
                   "Drop to the lowest simmer, set the lid ajar, and cook 60 to 75 minutes, stirring every 15 minutes and scraping the bottom.",
                   "Add half the ginger and the salt in the last 20 minutes of cooking.",
                   "The zhou is ready when the grains have burst into their own starch and a spoon drawn through leaves a trail that closes slowly.",
                   "Thin with hot water if it tightens past pourable; it should slide off a spoon in a ribbon, not plop.",
                   "Ladle into bowls and finish with the remaining ginger, scallions, a thread of soy sauce and a pinch of white pepper.",
                   "Serve with fried dough sticks for dunking, and let everyone adjust their own bowl with more soy at the table.",
               ],
               note: "The difference between rice soup and zhou is the last half hour, when the grains finally surrender. Do not stop while they still look like rice.",
               shortcut: "The freezer trick plus a boil cuts cooking nearly in half; skipping the stock for all water is fine, just season more at the end."),
        Recipe(dishID: "china-hongshaorou", serves: 4, prepMinutes: 15, cookMinutes: 110, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "2 lb", item: "pork belly, skin on if possible, cut into 1 1/2 inch cubes"),
                   RecipeIngredient(amount: "3 tbsp", item: "rock sugar, crushed (or granulated sugar)"),
                   RecipeIngredient(amount: "2 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "3 tbsp", item: "shaoxing wine (or dry sherry)"),
                   RecipeIngredient(amount: "2 tbsp", item: "dark soy sauce"),
                   RecipeIngredient(amount: "1 tbsp", item: "regular soy sauce"),
                   RecipeIngredient(amount: "2", item: "star anise"),
                   RecipeIngredient(amount: "4 slices", item: "fresh ginger"),
                   RecipeIngredient(amount: "2", item: "scallions, cut in half"),
                   RecipeIngredient(amount: "2 cups", item: "hot water"),
               ],
               steps: [
                   "Cover the pork cubes with cold water, bring to a boil for 3 minutes, then drain and rinse off the scum. Pat completely dry.",
                   "Heat the oil and sugar together in a heavy pot over medium, swirling, until the sugar melts and turns the color of dark tea.",
                   "Add the pork immediately and turn the cubes in the caramel 3 to 4 minutes until every face is stained amber. Stand back; it spits.",
                   "Splash in the shaoxing wine and scrape up the caramel stuck to the pot, then add both soy sauces, star anise, ginger and scallions.",
                   "Pour in hot water to almost cover, bring to a simmer, then cover and cook on the lowest heat 90 minutes, turning the cubes twice.",
                   "Check a cube: the fat layers should quiver like set custard and the lean should pull apart with a spoon. Give it 15 more minutes if firm.",
                   "Uncover, raise the heat, and boil the liquid down 8 to 10 minutes, rolling the cubes constantly, until the sauce reduces to a sticky lacquer.",
                   "Fish out the aromatics and serve in a small bowl with plain white rice, which exists to catch the glaze.",
               ],
               note: "Take the caramel truly dark, to the edge of bitter, before the pork goes in. Pale caramel gives sweet pork; dark caramel gives red pork.",
               shortcut: "Boneless country ribs stand in for belly and feel leaner; you give up the translucent, trembling fat that is the dish's whole argument."),
        Recipe(dishID: "china-dandanmian", serves: 2, prepMinutes: 15, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "8 oz", item: "thin wheat noodles"),
                   RecipeIngredient(amount: "3 tbsp", item: "chili oil with sediment"),
                   RecipeIngredient(amount: "2 tbsp", item: "chinese sesame paste (or tahini)"),
                   RecipeIngredient(amount: "3 tbsp", item: "ya cai preserved mustard greens (or finely chopped sauerkraut, squeezed dry)"),
                   RecipeIngredient(amount: "1/4 lb", item: "ground pork"),
                   RecipeIngredient(amount: "1/2 tsp", item: "sichuan peppercorns, toasted and ground"),
                   RecipeIngredient(amount: "2 tbsp", item: "soy sauce"),
                   RecipeIngredient(amount: "1 tsp", item: "sugar"),
                   RecipeIngredient(amount: "2 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tbsp", item: "vegetable oil"),
                   RecipeIngredient(amount: "2", item: "scallions, thinly sliced"),
                   RecipeIngredient(amount: "1/2 cup", item: "hot noodle cooking water"),
               ],
               steps: [
                   "Heat the vegetable oil in a skillet over high and fry the pork, pressing and breaking it, until the crumbles are browned and audibly crisp, about 5 minutes.",
                   "Add half the ya cai and 1 teaspoon of the soy sauce to the pork, toss 1 minute, and set aside off the heat.",
                   "Loosen the sesame paste with a spoonful of warm water until it stirs like heavy cream instead of clay.",
                   "Divide the sesame paste, chili oil, remaining soy sauce, sugar, garlic, ground peppercorns and remaining ya cai between two serving bowls.",
                   "Boil the noodles until just cooked through with a slight core, then scoop out a half cup of the starchy cooking water before draining.",
                   "Stir 2 to 3 tablespoons of the hot noodle water into each bowl, dissolving the sauce into a loose slurry at the bottom.",
                   "Drop the hot drained noodles on top, pile on the crispy pork, and finish with scallions.",
                   "Serve with instructions: stir hard from the bottom for a full fifteen seconds before tasting, until every strand turns red.",
               ],
               note: "The sauce waits at the bottom and looks like too little. It is not. Stirred through hot noodles it coats everything; extra broth would drown it.",
               shortcut: "Tahini for chinese sesame paste is the accepted swap; it is made from raw seeds, so toast a few sesame seeds on top to recover the roast."),
        Recipe(dishID: "china-ganbian-sijidou", serves: 4, prepMinutes: 15, cookMinutes: 15, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1 lb", item: "green beans, trimmed and completely dry"),
                   RecipeIngredient(amount: "1/3 cup", item: "vegetable oil"),
                   RecipeIngredient(amount: "6", item: "dried red chilies, snipped in half, seeds shaken out"),
                   RecipeIngredient(amount: "1 tsp", item: "sichuan peppercorns"),
                   RecipeIngredient(amount: "3 cloves", item: "garlic, minced"),
                   RecipeIngredient(amount: "1 tsp", item: "fresh ginger, minced"),
                   RecipeIngredient(amount: "3 tbsp", item: "ya cai preserved mustard greens (or chopped pickled mustard greens)"),
                   RecipeIngredient(amount: "1/2 tsp", item: "sugar"),
                   RecipeIngredient(amount: "1/4 tsp", item: "salt"),
               ],
               steps: [
                   "Dry the beans obsessively with a towel; a single wet bean makes the oil erupt.",
                   "Heat the oil in a wok or deep skillet over high until it shimmers and a bean dropped in sizzles instantly.",
                   "Fry the beans in two batches, moving them occasionally, 4 to 6 minutes per batch, until the skins blister, wrinkle and patch with brown.",
                   "Lift the beans out with a slotted spoon onto paper towels, and pour off all but 1 tablespoon of the oil.",
                   "Over medium heat, sizzle the dried chilies and peppercorns 30 seconds until the chilies darken a shade and smell toasty, not burnt.",
                   "Add the garlic, ginger and ya cai and stir-fry 1 minute until the preserved greens smell savory and slightly funky.",
                   "Return the beans, add the sugar and salt, and toss hard for 1 minute so every wrinkle picks up the seasoning. There should be no sauce at all.",
                   "Serve hot or warm with rice, as one shared plate among others.",
               ],
               note: "The beans are done when they wrinkle like a deflating balloon, not just brown. Underblistered beans taste raw and squeak against the teeth.",
               shortcut: "A 425°F oven roast, 20 minutes on a sheet pan, blisters the beans with far less oil; the wrinkles come out drier and less silky."),
        Recipe(dishID: "china-tangyuan", serves: 4, prepMinutes: 40, cookMinutes: 20, difficulty: 2,
               ingredients: [
                   RecipeIngredient(amount: "1/3 cup", item: "black sesame seeds (or 1/2 cup store-bought black sesame paste)"),
                   RecipeIngredient(amount: "1/4 cup", item: "powdered sugar"),
                   RecipeIngredient(amount: "3 tbsp", item: "unsalted butter, softened (standing in for lard)"),
                   RecipeIngredient(amount: "1 1/2 cups", item: "glutinous rice flour"),
                   RecipeIngredient(amount: "3/4 cup", item: "warm water, plus more as needed"),
                   RecipeIngredient(amount: "1/3 cup", item: "brown sugar, for the soup"),
                   RecipeIngredient(amount: "4 slices", item: "fresh ginger"),
                   RecipeIngredient(amount: "5 cups", item: "water, for the soup"),
               ],
               steps: [
                   "Toast the sesame seeds in a dry skillet over medium, shaking constantly, until they smell nutty and a few begin to pop, about 3 minutes.",
                   "Grind the seeds to a coarse powder, then mix with the powdered sugar and butter into a thick paste. Freeze 20 minutes until scoopable.",
                   "Roll the chilled filling into 16 small balls, about a teaspoon each, and return them to the freezer.",
                   "Mix the rice flour with warm water into a dough with the texture of playdough: smooth, pliable, cracking only slightly at the edges.",
                   "Divide the dough into 16 pieces. Flatten one into a cup in your palm, seat a filling ball inside, and pinch the dough closed around it, rolling smooth.",
                   "Simmer the brown sugar and ginger in 5 cups of water for 10 minutes to make a thin, fragrant soup.",
                   "Boil the tangyuan in a separate pot of water; they are done 2 minutes after they float to the surface, translucent and swollen.",
                   "Transfer them with a slotted spoon into bowls of the warm ginger soup, two or three per person, and eat with a spoon while the centers are still molten.",
               ],
               note: "If the dough cracks while wrapping, knead in water a half teaspoon at a time. Dry dough splits in the pot and bleeds sesame everywhere.",
               shortcut: "Frozen tangyuan from an asian market boil up in five minutes and are genuinely good; making the dough is what you do for the ritual."),
    ]

    static let all: [Recipe] = recipes_japan + recipes_korea + recipes_china
}
